### ISSUE TITLE
Browsersupport?

### ISSUE THREAD

**Issue by ctaepper** [anseki/leader-line#1]
Which browsers does this lib support? I can't find anything in the readme?

**Comment by anseki** [comment]
Hi @ctaepper, thank you for the comment.

Modern browsers and IE 11 are supported.
If you find something wrong, please report that.

**Comment by anseki** [comment]
No reply came, and I close this issue.

**Comment by ctaepper** [comment]
thanks, will let you know, if something browser related comes up.

**Comment by anseki** [comment]
😄
