### ISSUE TITLE
How to add mouse events listener of the line？

### ISSUE THREAD

**Issue by 426-330** [anseki/leader-line#10]
Which APIs can listen the mouse events (enter,click...)，thks.

**Comment by anseki** [comment]
Hi @426-330, thank you for the comment.

The [`mouseHoverAnchor`](https://github.com/anseki/leader-line#mousehoveranchor) attachment API can listen to the mouse events.
This handles `mouseenter` and `mouseleave` (or `mouseover` and `mouseout`) internally.

Of course you can add all unsupported event types (e.g. `mousemove`, `click`, `dblclick`, `mouseup`, `mousedown`, `wheel`, etc.) by `addEventListener` method of DOM.

**Comment by 426-330** [comment]
Thank you for the answer.
But I want to handle the mouse events of the line.
e.g. I click the leader-line to show a layer.
How to get the SVG line's object or add a event listener?

**Comment by anseki** [comment]
You can get the element by:
```js
document.querySelector('.leader-line')
```
Note that this is not supported by the library.

**Comment by 426-330** [comment]
OK,Thank you.

**Comment by anseki** [comment]
I am glad that I could help you. :smile: 
So, was this issue solved? then, can you close this issue?

**Comment by AhmedAyachi** [comment]
> You can get the element by:
> 
> ```js
> document.querySelector('.leader-line')
> ```
> 
> Note that this is not supported by the library.

hello when i get the line element , element.onclick is not working do you have a solution how to trigger click events thanks

**Comment by anseki** [comment]
Hi @AhmedAyachi, thank you for the comment.
Could you explain the "not working"? An error occurred?
Or could you show me an example by using e.g. https://jsfiddle.net/ to reproduce that?

**Comment by AhmedAyachi** [comment]
@anseki ty for your response
there is no error juste when i click the line nothin happens i just want to know if i'm doin it right (the event trigger)

**Comment by anseki** [comment]
Could you show an example by using e.g. https://jsfiddle.net/ ?

**Comment by Norlandz** [comment]
For anyone who wants to add things like `onHover` `onClick` to the `line path` (`<svg> <path>` of the `leaderline`), 
You may need to **enable the `pointer-events`**, 

Its disabled by default, as follow shows:
```css
.leader-line {
  position: absolute;
  overflow: visible!important;
  pointer-events: none!important;
  font-size: 16px;
}
```
