### ISSUE TITLE
Placing `<svg>` to specified element, not to `<body>`

### ISSUE THREAD

**Issue by byaka** [anseki/leader-line#101]
Is it possible to force lib to placing her `<svg>` elements not to `<body>`?

Abyway this lib awesome, ty m8!

**Comment by anseki** [comment]
Hi @byaka, thank you for the comment.
This may help you.
https://github.com/anseki/leader-line/issues/54

**Comment by byaka** [comment]
> Hi @byaka, thank you for the comment.
> This may help you.
> #54

Thx for info!

**Comment by anseki** [comment]
:smile:
