### ISSUE TITLE
Draw line to connect by mouse

### ISSUE THREAD

**Issue by user007-u** [anseki/leader-line#102]
Hi,
I have the following question: it is possible to draw a line by select with click the start point and the line following the mouse until you select the end? Also 
I saw this #19  Thank you! Here is an example(http://sebastien.drouyer.com/jquery.flowchart-demo/) 
![f](https://user-images.githubusercontent.com/33081921/73645299-b59d5780-467f-11ea-83dd-0354f73a0f43.png)

**Comment by anseki** [comment]
Hi @user007-u, thank you for the comment.
Sorry, my English is poor, then your words are difficult for me.
Do you mean that this example is not what you want?
https://jsfiddle.net/8pn7fqmg/

**Comment by anseki** [comment]
Could you explain about the image that you attached?

**Comment by user007-u** [comment]
This example(https://jsfiddle.net/8pn7fqmg/)  is not what I want, I want something like in Two Operators view (http://sebastien.drouyer.com/jquery.flowchart-demo/#) but with the possibility to draw two line from output to input1 and input2. The point is when I click on pe black point from image the line star drawing and follow the

**Comment by anseki** [comment]
Do you mean that you want clicking instead of dragging?
Like this?
https://jsfiddle.net/zmha68c0/

**Comment by user007-u** [comment]
Something like this, but the line need to follow the mouse cursor up to the end. Like in Two Operators view (http://sebastien.drouyer.com/jquery.flowchart-demo/#)

**Comment by anseki** [comment]
Those are almost the same.
You can do that easily by using `mousemove` event instead of mouse dragging.

**Comment by anseki** [comment]
For example:
https://jsfiddle.net/6Lybe0jm/
Note that this example may not work in old browsers.

**Comment by user007-u** [comment]
Thank you! It is possible to delete a line when I click one and press delete key?

**Comment by anseki** [comment]
Do you mean that the `mousemove` event example is not what you want?
Could you explain about the difference?

**Comment by user007-u** [comment]
The mouse event exemple is good. But it is possible to delete a line when I click one and then press delete key x button?

**Comment by anseki** [comment]
Of course you can do that.
https://anseki.github.io/leader-line/#remove

**Comment by user007-u** [comment]
I saw this, but it is possible to delete a line when I click one and then press delete key x button?

**Comment by anseki** [comment]
Of course you can do that.
Do you mean that you want to know how to bind the deleting a line to those events?

**Comment by anseki** [comment]
For example:
https://jsfiddle.net/nedaybfq/

Note that this is unrelated to LeaderLine, and it is unrelated to this issue.

**Comment by user007-u** [comment]
Thank you! But it is possible to select the line that I want to be deleted, for example if I have multiple line and I want to delete only one(the one that I select)

**Comment by anseki** [comment]
I don't know your app. You should design the UI that allow to delete specific line.
For example, each line has own delete button, and the line is deleted when you click that button.
Or, a line is deleted by clicking the line itself (but this is not good idea for users).

**Comment by user007-u** [comment]
For example it is possibbe to select a line when you click the line?

**Comment by anseki** [comment]
I think that the UI that allows user to select a line by clicking the line is good because it is typical UX.
Or, it is possible to select a line by clicking a marker of the line.
Or, it is possible to delete a line by selecting a "delete command" in a context menu that is shown by right-clicking the line.
Or, it is possible to delete a line by clicking an element that is connected via the line.
Or, it is possible to delete a line by clicking a button that is attached to the line.
And others.

**Comment by user007-u** [comment]
Thank you, all ideas is good. But how can I select a specific line when I click the line? Or how show the context menu when you press right click on a specific line?

**Comment by anseki** [comment]
Do you mean that you want to know how to bind the functions to those events?

**Comment by anseki** [comment]
For example:
https://jsfiddle.net/jq0hw9tx/
This is very simple case.
Note that this is unrelated to LeaderLine, and it is unrelated to this issue.

**Comment by anseki** [comment]
No reply came.
Didn't the example help you?
