### ISSUE TITLE
Line not scrolling with element

### ISSUE THREAD

**Issue by smartified** [anseki/leader-line#103]
I am creating a tournament bracket and i am using your lines but whenever i scroll, the line does not scroll with the match

Before scrolling
![image](https://user-images.githubusercontent.com/16135819/74330802-02c5ab80-4d9b-11ea-8ed4-2eb31330d03a.png)

After Scrolling
![image](https://user-images.githubusercontent.com/16135819/74330845-196c0280-4d9b-11ea-8f05-a18187c2f966.png)

Please help

**Comment by anseki** [comment]
Hi @smartified, thank you for the comment.
Do you mean that you want to use LeaderLine with elements that are in a parent element that has `overflow: scroll`?
If so, this example may help you.
https://github.com/anseki/leader-line/issues/54#issuecomment-500712640
If not so, could you explain that?

**Comment by frumbert** [comment]
Hi @smartified , comment #54 didn't initially help me. I couldn't find a perfect solution for overflowing objects (read from https://github.com/anseki/leader-line/issues/13#issuecomment-586155955 etc) and ended up letting the body scroll like normal and fixed other objects positions in a different way.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
