### ISSUE TITLE
Position of leader lines getting distorted

### ISSUE THREAD

**Issue by kd2801** [anseki/leader-line#105]
Hi. I have a usecase where I am removing and adding lines on route change. On reload, I am getting lines at correct position. Once I switch view, I remove the earlier lines from the dom and then append new lines inside the wrapper. List of svgs get reflected inside the wrapper div but their position is incorrect. If I reload the page, I get the position alright. Possibly there is some issue in removing lines. Attaching code snippet for your reference. 

` removeMapping() {
        this.svgArr.forEach(svg => {
            document.body.appendChild(svg);
        });
        this.mappingArr.forEach(arrow => {
            arrow.remove();
        });
        this.mappingArr = [];
        this.mappingArrowStartEnd = [];
        this.svgArr = [];
    }

appendArrowsInWrapper() {
        const elmWrapper = document.getElementById('arrow-wrapper');
        const rectWrapper = elmWrapper.getBoundingClientRect();
        elmWrapper.style.transform = 'translate(-' +
            (rectWrapper.left + pageXOffset) + 'px, -' +
            (rectWrapper.top + pageYOffset) + 'px)';
        if (this.svgArr.length > 0) {
            this.svgArr.forEach(svg => {
                elmWrapper.appendChild(svg);
            });
        }
    }

`

**Comment by anseki** [comment]
Hi @kd2801, thank you for the comment.
Could you show me your code by using e.g. https://jsfiddle.net/ ?

**Comment by kd2801** [comment]
can't share the entire code. Can you please make some changes in this fiddle https://jsfiddle.net/op2gnk0t/ and alternately add/remove leader lines. Maybe using a toggle button.

**Comment by kd2801** [comment]
In my case, the svgs are appended correctly, its their positions which are not calculated correctly.

**Comment by anseki** [comment]
If you can reproduce that, someone might help you.
To reproduce that, could you show me new example code in https://jsfiddle.net/  ?

**Comment by kd2801** [comment]
Check this https://jsfiddle.net/mzj1kx2q/

**Comment by anseki** [comment]
Hmm... What is expected result for you?

**Comment by anseki** [comment]
Your code has various problems.
For example, you try to use lines that were already removed again. Those lines never work.
See document:
https://anseki.github.io/leader-line/#remove
Why did you remove those?

**Comment by kd2801** [comment]
> Hmm... What is expected result for you?

I want to remove the existing lines and append new lines. The problem is I cant figure out why the positions are not correctly calculated.

**Comment by anseki** [comment]
Removed lines never work.
See document:
https://anseki.github.io/leader-line/#remove

You can use [`hide()`](https://anseki.github.io/leader-line/#show-hide) instead, or make new lines.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
