### ISSUE TITLE
startSocket / endSocket multiple options

### ISSUE THREAD

**Issue by basvankuijck** [anseki/leader-line#106]
First of all, 

thanks a million for your library. It really works flawlessly especially with jQuery's draggable.

Currently by specifing the `endSocket` attribute the endSocket will be fixed to either top, left, right or bottom. Or 'auto' ofcourse.

Is it in a way possible that the `endSocket` (and `startSocket` for that matter) can automatically be chosen, but only for a set of options (e.g. only top or bottom).

Looking at the following example, I've made a 'condition' where true / false have a `startSocket` set (respectively `right` and `left`). And I don't want the incoming line be connected to the left or right handside.
<img width="366" alt="Screenshot 2020-03-13 at 11 21 34" src="https://user-images.githubusercontent.com/1327984/76612717-25bfb880-651d-11ea-848a-10251bd21604.png">

But the incoming line I want it to be either `top` or `bottom`. Setting it to top and dragging the source element to the bottom will result into this:
<img width="397" alt="Screenshot 2020-03-13 at 11 21 45" src="https://user-images.githubusercontent.com/1327984/76612815-5273d000-651d-11ea-86ad-b89394aad2db.png">

In that example I want the line to be connected to the bottom.

So for instance `endSocket` could be either a string or an array:
```js
{
   endSocket: [ 'top', 'bottom' ]
}
```

or

```js
{
   endSocket: 'top'
}
```

**Comment by anseki** [comment]
Hi @basvankuijck, thank you for the comment.
Current version of LeaderLine doesn't support the `startSocket`/`endSocket` options as an array.
However, since the `auto` is no more than a convenient way to select a side, you can select that easily.
For example: https://jsfiddle.net/1vymcqpn/
Selects one of `top` and `bottom`.

**Comment by basvankuijck** [comment]
Ah excellent. Thanks for the quick reply!

**Comment by anseki** [comment]
:smile:
