### ISSUE TITLE
NuxtJS Implementation

### ISSUE THREAD

**Issue by madhurikulkarni** [anseki/leader-line#108]
I have the module in my `index.vue` 
```
head() {
    return {
      script: [
        {
          src: 'js/leader-line.min.js'
        }
      ]
    }
  }
```
and then trying to use it 
```
  mounted() {
    window.LeaderLine(
      document.getElementById('element-1'),
      document.getElementById('element-2')
    )
  }
```
I get an error `TypeError: window.LeaderLine is not a function`. Is this the correct way of using at all, I tried to follow the other posts for vue implementation but no success.

**Comment by anseki** [comment]
Hi @madhurikulkarni, thank you for the comment.

To check that, input this into the console of the page that has problem and press Enter key.
```
LeaderLine
```

**Comment by engtiago** [comment]
Hi I make a change on lib and adapt to use in vue , use this:  https://www.npmjs.com/package/leader-line-vue

**Exemple:** 

```
<template>
<div ref="start">start</div>
<div ref="end">end</div>
</template>
<script>
import LeaderLine from 'leader-line-vue';
new LeaderLine(this.$refs.start, this.$refs.end); 
</script>
```

**Comment by engtiago** [comment]
Anseki tanks for your lib.

**Comment by anseki** [comment]
Hi @engtiago, thank you for the comment. :smile:

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
