### ISSUE TITLE
Leader line in VueJS?

### ISSUE THREAD

**Issue by feelslike1929** [anseki/leader-line#11]
I installed leader line via npm, then imported and used it in my main.js file; however, when I try to then draw a line between two elements after the app has been mounted I receive this error:
`[Vue warn]: Error in mounted hook: "TypeError: __WEBPACK_IMPORTED_MODULE_1__assets_leaderLine_js__.default is not a constructor"`

main.js file has:

```
import LeaderLine from 'leader-line'
Vue.use(LeaderLine)
```

**Comment by anseki** [comment]
Hi @feelslike1929, thank you for the comment.
Try to load it via `<script>` instead of `import`.
https://anseki.github.io/leader-line/#usage

**Comment by anseki** [comment]
No reply came, and I close this issue.
