### ISSUE TITLE
Can we add line to a certain element?

### ISSUE THREAD

**Issue by peaceinbiz** [anseki/leader-line#110]
I have noticed that class .leader-line is always appended at the document root level. 
![image](https://user-images.githubusercontent.com/8372396/77837120-f7bdb380-716d-11ea-83dc-27b874ebfb35.png)

is there an option to add to a certain element?

**Comment by anseki** [comment]
Hi @peaceinbiz, thank you for the comment.
I don't know why you want to do that, however, this may help you: https://github.com/anseki/leader-line/issues/54#issuecomment-498528407
Note that it is not supported.

**Comment by hungtcs** [comment]
Hi @anseki, I need this feature too, the `leader-line` not display when the element is full screen

**Comment by anseki** [comment]
Hi @hungtcs, thank you for the comment.
I don't know why you want to do that, but this may help you: https://github.com/anseki/leader-line/issues/54#issuecomment-498528407
Note that it is not supported.
I couldn't understand that "the element is full screen". Could you explain that?

**Comment by hungtcs** [comment]
@anseki this [demo](https://codepen.io/hungtcs/pen/RwPOgqa), after click the button, the line is gone

**Comment by anseki** [comment]
https://codepen.io/anseki/pen/yLNroNR

**Comment by hungtcs** [comment]
@anseki Thank you for your answer, this can work, but I don't think this can be used as a final solution.
In addition, this will make the `remove method` not work:
https://github.com/anseki/leader-line/blob/f2fa7a40cc33542872ebc29ef9d2fabf36bca570/src/leader-line.js#L3520

I changed to
```javascript
props.svg.remove();
```
Now my problem is solved, thank you!

**Comment by anseki** [comment]
I'm glad if I could help you. :smile:
Note that the `SVG#remove()` is not supported.

**Comment by hungtcs** [comment]
@anseki  But for me, it worked, both on chrome and firefox :laughing:, that's enough. Thank you and your projects, that's really help me a lot.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
