### ISSUE TITLE
Leaderline library is not working in Laravel - VueJS

### ISSUE THREAD

**Issue by rjgodoy** [anseki/leader-line#112]
After installing: 
`npm i leader-line` 

I called into app.js
`import LeaderLine from 'leader-line'`
`Vue.use(LeaderLine)`

And it doesn't work.

I've tried [this](https://github.com/anseki/leader-line/issues/11#issue-308657837), and [this](https://github.com/anseki/leader-line/issues/8#issuecomment-370147614) and many other issues but nothing works.

**Comment by anseki** [comment]
Hi @rjgodoy, thank you for the comment.
So, do you mean that those solutions didn't work?

**Comment by rjgodoy** [comment]
Hi,
Thanks for the reply!
I've been trying but doesn't work.

I called this into app.js:
`import LeaderLine from 'leader-line'`
`Vue.use(LeaderLine)`

If I call the
`new LeaderLine(
                this.$refs.alpha,
                this.$refs.beta
            );` in the component the console return this error:
`"ReferenceError: Can't find variable: LeaderLine"`

And if I call the "import" line inside the component returns:
`"TypeError: Object is not a constructor (evaluating 'new leader_line__WEBPACK_IMPORTED_MODULE_0___default.a(this.$refs.alpha, this.$refs.beta)')"
`

So I don't know how to get it work.

**Comment by anseki** [comment]
Do you mean that those solutions that you indicated didn't work?
Could you explain about result of those?

**Comment by rjgodoy** [comment]
Laravel came with Laravel mix for webpack, so loading the .js into the app.js or directly into the component doesn't load the library.

Simply the library doesn't work via npm and with Vue can't load the libraries with <script src="">

**Comment by anseki** [comment]
Do you mean that the Webpack threw an error?
Also, did you install the skeleton-loader?
If the library was loaded via `<script>` tag, that is added into the Global. That is, the library is `window.LeaderLine`. For example, you can access to `LeaderLine` globally also after this statement:
```js
const LeaderLine = window.LeaderLine;
```

**Comment by rjgodoy** [comment]
No, It's like the webpack from laravel (mix) doesn't call the libraries. The configuration in [this post](https://github.com/anseki/leader-line/issues/14#issuecomment-451038169) and [this](https://github.com/anseki/leader-line/issues/8#issuecomment-370147614) doesn't work... So I cannot get load the libraries from <script> tag in VueJS neither.

How should I call the skeleton-loader from Laravel to work with Vue? Some help please!🙏🏻

**Comment by anseki** [comment]
Could you explain about solutions that you did and the result?
For example, I can't understand these:
+ "doesn't call the libraries" : Do you mean that an error was thrown?
+ "doesn't work" : What happened?
+ "cannot get load the libraries from `<script>` tag" : Why? What did you do?

**Comment by anseki** [comment]
Also, do you understand the Webpack?

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
