### ISSUE TITLE
Line length resizing on zoom out

### ISSUE THREAD

**Issue by nitinsmarty** [anseki/leader-line#113]
Hi, 
Thanks for this awesome library. 
My issue is this. 
When I am zooming out my view, lines are getting cluttered. 
After zoom out:
![Screenshot from 2020-04-17 16-16-28](https://user-images.githubusercontent.com/7836230/79561336-d42fbe00-80c6-11ea-9850-b889156011cb.png)
After zoom in: this is my normal state. 
![Screenshot from 2020-04-17 16-17-12](https://user-images.githubusercontent.com/7836230/79561407-f3c6e680-80c6-11ea-9273-bfd137f44655.png)
I want the Lines to resize by length according to the zoom level.

_Originally posted by @nitinsmarty in https://github.com/anseki/leader-line/issues/47#issuecomment-615179058_

**Comment by nitinsmarty** [comment]
Got it resolved my self.

**Comment by koljagrudinin** [comment]
how?

**Comment by gagwithgaffer** [comment]
@koljagrudinin koljagrudinin looking at the library how to guide, it's possible to change the size of the leader line:

size
Type: number
Default: 4

The width of the leader line, in pixels.

line.size = 20;

So what ever code you're using the change the zoom level of your layout, my thoery is you should be able to dynamically change the line size at the same time. Depending on the zoom factor, likely a simple maths calcultation is required to figure out the equavalent desired line size on each step (if you're not using simple units).  

Example, if your default line size if 10 and you are you are zooming in up to ten steps, then your line size will need to be set accordingly each time you zoom 1 step so the line gets proprotionally smaller i.e. line.size 10/9/8/7/6/5/4/3/2/1 (where line size 1 is set when you have pressed the zoom in button ten times)

And of course we'd apply the same login in reverse to zoom out...

This is the methodology I will be using myself unless i discover another way to achieve it.

**Comment by anseki** [comment]
Hi @gagwithgaffer, thank you for the information. :smile:
