### ISSUE TITLE
I want to achieve line merging with zoom in and zoom out feature.

### ISSUE THREAD

**Issue by nitinsmarty** [anseki/leader-line#114]
What I actually want to achieve is this with zoom in and zoom out feature.
![Screenshot from 2020-04-17 16-29-23](https://user-images.githubusercontent.com/7836230/79562412-aea3b400-80c8-11ea-90ac-595b1f673d6f.png)

Let me know how can I achieve this.

**Comment by nitinsmarty** [comment]
@anseki can you help me with this? how can I achieve such designs with the leader line? 
What I have to is, I have to merge arrows path like above, which are going to a similar destination.

**Comment by anseki** [comment]
Hi @nitinsmarty, thank you for the comment.
Could you explain that details? Also could you show me an example by using e.g. https://jsfiddle.net/ ?

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
