### ISSUE TITLE
LeaderLine with Draggable not work 

### ISSUE THREAD

**Issue by tafaquh** [anseki/leader-line#116]
The draggable item works fine, but the leaderline still stick and not move along with draggable item.
```html
<!DOCTYPE html>
<html>
  <head>
    <script src="leader-line.min.js"></script>
    <script src="plain-draggable.min.js"></script>
  </head>
  <body>
    <div style="height: 400px;background-color: bisque;">
      <div id="start">hai</div><br><br>
      <div id="destination">hello</div>
    </div>
    
    <script>
      var myLine = new LeaderLine(
          document.getElementById('destination'),
          document.getElementById('start'),
          {color: 'black', size:3}
      );
      myLine.setOptions({startSocket: 'auto', endSocket: 'auto'});
      draggable_a = new PlainDraggable(document.getElementById('start'));
      draggable_b = new PlainDraggable(document.getElementById('destination'));

    </script>
  </body>
</html>
```

This is the first output:
![Annotation 2020-04-21 1103312](https://user-images.githubusercontent.com/26229572/79824236-f9bb1100-83bf-11ea-9e6e-8d6ad8867290.png)
and this when I drag the item:
![Annotation 2020-04-21 110331](https://user-images.githubusercontent.com/26229572/79824283-1bb49380-83c0-11ea-9470-cb55ea8744c2.png)

**Comment by tafaquh** [comment]
Yaah, my bad. So I add some parameter in draggable instance like this:
```javascript
     draggable_a = new PlainDraggable(document.getElementById('start'),{
        onMove: function() { myLine.position(); },
        onMoveStart: function() { myLine.dash = {animation: true}; },
        onDragEnd: function() { myLine.dash = false; }
      });
      draggable_b = new PlainDraggable(document.getElementById('destination'),{
        onMove: function() { myLine.position(); },
        onMoveStart: function() { myLine.dash = {animation: true}; },
        onDragEnd: function() { myLine.dash = false; }
      });
```

**Comment by anseki** [comment]
Hi @tafaquh, thank you for the comment.
Only `position` method is required to solve this issue.

**Comment by tafaquh** [comment]
Thanks @anseki, for quick respond. Btw, is it possible to make the line more dynamic, such as connecting lines by dragging from target one to target two?

![image](https://user-images.githubusercontent.com/26229572/79841612-e15bee00-83e1-11ea-92a4-2daf3656a346.png)

for example I have 'entry' node and 'ask-question' node which have not been connected by leaderline when page loaded. Then, I want to manually add line to both node by dragging the line from 'entry' node to 'ask-question' node. Is that possible?

**Comment by anseki** [comment]
Could you create new issue for another topic?
