### ISSUE TITLE
Dynamic Draggable LineLeader

### ISSUE THREAD

**Issue by tafaquh** [anseki/leader-line#117]
is it possible to make the line more dynamic, such as connecting lines by dragging from target one to target two?

![image](https://user-images.githubusercontent.com/26229572/79844843-706b0500-83e6-11ea-9e30-e13b591481dd.png)

for example I have 'entry' node and 'ask-question' node which have not been connected by leaderline when page loaded. Then, I want to manually add line to both node by dragging the line from 'entry' node to 'ask-question' node. Is that possible?

**Comment by anseki** [comment]
Hi @tafaquh, thank you for the comment.
This may help you:
https://github.com/anseki/leader-line/issues/19

**Comment by tafaquh** [comment]
Great! Thanks a lot

**Comment by anseki** [comment]
:smile:
