### ISSUE TITLE
leader-line with Reveal while using section

### ISSUE THREAD

**Issue by sharontabakman** [anseki/leader-line#118]
Hi, 
I'm currently working with Reveal which is based on HTML and I would like to add leader-line to my presentation. Everything works till I'm adding <section> to it. 
For example with section:
![image](https://user-images.githubusercontent.com/49316051/79866090-e66e6c80-83e4-11ea-8952-6911d8832b2f.png)

For example without section:
![image](https://user-images.githubusercontent.com/49316051/79866180-09991c00-83e5-11ea-88e1-976a2f20c673.png)

Is there any simple solution for this issue?

HTML code:
![image](https://user-images.githubusercontent.com/49316051/79866769-f33f9000-83e5-11ea-8b48-c244691c06d1.png)

JS code:
 var startElement = document.getElementById('op2'),
				endElement = document.getElementById('op1');
            new LeaderLine(startElement, endElement, { color: 'red', size: 8 });

**Comment by anseki** [comment]
Hi @sharontabakman, thank you for the comment.
Since you didn't show actual code, this is an estimate.
You added the line before the target elements are rendered. That is, the position of those element are not known.
Then, you have to call `position` method when the target elements are rendered.
For example:
```js
Reveal.addEventListener('slidechanged', function(event) {
  if (event.indexh === 5) { // An index of the section that has the line is 5.
    line.position();
  }
});
```

**Comment by sharontabakman** [comment]
Hi anseki! 
Thank you for responding me but using- `line.position();` does not help.
here is my code:
`<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

		<title>reveal.js</title>

		<link rel="stylesheet" href="../../css/reset.css">
		<link rel="stylesheet" href="../../css/reveal.css">
		<link rel="stylesheet" href="../../css/theme/black.css">

		
		<link rel="stylesheet" href="../../lib/css/monokai.css">
		<link rel="stylesheet" href="styling2.css">
		<link rel="stylesheet" href="../styling2.css">

		
		<script>
			var link = document.createElement( 'link' );
			link.rel = 'stylesheet';
			link.type = 'text/css';
			link.href = window.location.search.match( /print-pdf/gi ) ? '../../css/print/pdf.css' : '../../css/print/paper.css';
			document.getElementsByTagName( 'head' )[0].appendChild( link );
		</script>

		
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
	</head>
	<body>
		<div class="reveal">
			<div class="slides">
				<section>
					<p class="fragment" id="op1">
						work space
					</p>
					<p class="fragment" id="op2" style="margin-top: 500px">
						work space
					</p>
					<span class="fragment"></span>
				</section>
			</div>
		</div>

		<script src="../../js/reveal.js"></script>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
		<script src="../scripts.js"></script>
		<script src="leader-line.min.js"></script>
		
		<script>
			// More info about config & dependencies:
			// - https://github.com/hakimel/reveal.js#configuration
			// - https://github.com/hakimel/reveal.js#dependencies


			new LeaderLine
			(
				document.getElementById('op1'),
				document.getElementById('op2')
			);
			//when going forwards

			Reveal.addEventListener( 'fragmentshown', function( event ) 
			{
				if (window.getComputedStyle(x).visibility == "visible")
					line.position();

			} );
			//when going backwards
			Reveal.addEventListener( 'fragmenthidden', function( event ) 
			{
				
			} );
			
			Reveal.initialize({
				rtl: true,
				margin: 0.1,
				width: 1400,
				height: 800,
				progress: false,
				viewDistance: 10,
				hash: true,
				chalkboard: {
					// optionally load pre-recorded chalkboard drawing from file
					// src: "chalkboard.json", //
					background: [ 'rgba(127,127,127,.1)' , '../../plugin/chalkboard/img/blackboard.png' ],
					toggleChalkboardButton: true
				},
				dependencies: [
					{ src: '../../plugin/markdown/marked.js' },
					{ src: '../../plugin/markdown/markdown.js' },
					{ src: '../../plugin/notes/notes.js', async: true },
					{ src: '../../plugin/highlight/highlight.js', async: true },
					{ src: '../../plugin/math/math.js', async: true },
					{ src: '../../plugin/chalkboard/chalkboard.js' }
				],
				keyboard: {
					67: function() { RevealChalkboard.toggleNotesCanvas() },	// toggle notes canvas when 'c' is pressed
					66: function() { RevealChalkboard.toggleChalkboard() },	// toggle chalkboard when 'b' is pressed
					46: function() { RevealChalkboard.clear() },	// clear chalkboard when 'DEL' is pressed
					8: function() { RevealChalkboard.reset() },	// reset chalkboard data on current slide when 'BACKSPACE' is pressed
					68: function() { RevealChalkboard.download() },	// downlad recorded chalkboard drawing when 'd' is pressed
					88: function() { RevealChalkboard.colorNext() },	// cycle colors forward when 'x' is pressed
					89: function() { RevealChalkboard.colorPrev() },	// cycle colors backward when 'y' is pressed
				}
			});
		</script>
	</body>
</html>
`

As I've mentioned before, the arrow appears on the top left of the window and does not display correctly.
For some reason when I remove the "section" from the code it works..
code without "section":

`<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

		<title>reveal.js</title>

		<link rel="stylesheet" href="../../css/reset.css">
		<link rel="stylesheet" href="../../css/reveal.css">
		<link rel="stylesheet" href="../../css/theme/black.css">

		
		<link rel="stylesheet" href="../../lib/css/monokai.css">
		<link rel="stylesheet" href="styling2.css">
		<link rel="stylesheet" href="../styling2.css">

		
		<script>
			var link = document.createElement( 'link' );
			link.rel = 'stylesheet';
			link.type = 'text/css';
			link.href = window.location.search.match( /print-pdf/gi ) ? '../../css/print/pdf.css' : '../../css/print/paper.css';
			document.getElementsByTagName( 'head' )[0].appendChild( link );
		</script>

		
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
	</head>
	<body>
		<div class="reveal">
			<div class="slides">
				<p class="fragment" id="op1">
					work space
				</p>
				<p class="fragment" id="op2" style="margin-top: 500px">
					work space
				</p>
				<span class="fragment"></span>
			</div>
		</div>

		<script src="../../js/reveal.js"></script>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
		<script src="../scripts.js"></script>
		<script src="leader-line.min.js"></script>

		<script>
			// More info about config & dependencies:
			// - https://github.com/hakimel/reveal.js#configuration
			// - https://github.com/hakimel/reveal.js#dependencies


			new LeaderLine
			(
				document.getElementById('op1'),
				document.getElementById('op2')
			);
			//when going forwards

			Reveal.addEventListener( 'fragmentshown', function( event ) 
			{
				if (window.getComputedStyle(x).visibility == "visible")
					line.position();

			} );
			//when going backwards
			Reveal.addEventListener( 'fragmenthidden', function( event ) 
			{
				
			} );
			
			Reveal.initialize({
				rtl: true,
				margin: 0.1,
				width: 1400,
				height: 800,
				progress: false,
				viewDistance: 10,
				hash: true,
				chalkboard: {
					// optionally load pre-recorded chalkboard drawing from file
					// src: "chalkboard.json", //
					background: [ 'rgba(127,127,127,.1)' , '../../plugin/chalkboard/img/blackboard.png' ],
					toggleChalkboardButton: true
				},
				dependencies: [
					{ src: '../../plugin/markdown/marked.js' },
					{ src: '../../plugin/markdown/markdown.js' },
					{ src: '../../plugin/notes/notes.js', async: true },
					{ src: '../../plugin/highlight/highlight.js', async: true },
					{ src: '../../plugin/math/math.js', async: true },
					{ src: '../../plugin/chalkboard/chalkboard.js' }
				],
				keyboard: {
					67: function() { RevealChalkboard.toggleNotesCanvas() },	// toggle notes canvas when 'c' is pressed
					66: function() { RevealChalkboard.toggleChalkboard() },	// toggle chalkboard when 'b' is pressed
					46: function() { RevealChalkboard.clear() },	// clear chalkboard when 'DEL' is pressed
					8: function() { RevealChalkboard.reset() },	// reset chalkboard data on current slide when 'BACKSPACE' is pressed
					68: function() { RevealChalkboard.download() },	// downlad recorded chalkboard drawing when 'd' is pressed
					88: function() { RevealChalkboard.colorNext() },	// cycle colors forward when 'x' is pressed
					89: function() { RevealChalkboard.colorPrev() },	// cycle colors backward when 'y' is pressed
				}
			});
		</script>
	</body>
</html>
`

**Comment by anseki** [comment]
There are some problems.

+ You have to use `<section>` element for reveal.js. Otherwise reveal.js doesn't work.  
See document: https://github.com/hakimel/reveal.js
+ Since you didn't define the variable `line`, you can't use that. You said that the `position` method doesn't help but you didn't call the method in the first place. You can't reference the `line`. You didn't define the variable `x` also. That is, your code didn't work regardless of LeaderLine.  
Maybe you have to learn ECMAScript (JavaScript) first.  
See document: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_is_JavaScript
+ I don't know why you use the `fragmentshown`.
+ Your HTML code also has some problems. For example, `<html>` element is missing.

Anyway, as I said, the `position` method solves this issue. For example:
https://jsfiddle.net/zu4mqgya/

**Comment by sharontabakman** [comment]
Thank you for the help!! Your example helped me solve the issue between sections.

**Comment by anseki** [comment]
:smile:
