### ISSUE TITLE
demo error

### ISSUE THREAD

**Issue by lizhongkun** [anseki/leader-line#119]
I tried to see your demo, but I found that when the screen size changed, there would be an error!
[https://jsfiddle.net/z0638dyo/](url)
![image](https://user-images.githubusercontent.com/41602501/80168084-983fb000-8614-11ea-8889-dbe8192a21f6.png)

**Comment by anseki** [comment]
Hi @lizhongkun, thank you for the comment.
Is that my demo? Where is that at first posting?
Also, that is correct behavior, the error should be thrown because you changed window size after the element was already removed.

**Comment by lizhongkun** [comment]
Sorry, I read it wrong. It's not your demo. I also found a solution. Thank you for your answer. That's right。[https://jsfiddle.net/30kuar95/](url)

**Comment by anseki** [comment]
:smile:
