### ISSUE TITLE
LeaderLine is a not constructor issue in React

### ISSUE THREAD

**Issue by venu-3** [anseki/leader-line#120]
Uncaught TypeError: leader_line_1.default is not a constructor

**Comment by venu-3** [comment]
Can you please help me with this. I am not able to integrate it with React application

**Comment by anseki** [comment]
Hi @venu-3, thank you for the comment.
Could you explain the issue?

**Comment by venu-3** [comment]
Hi @anseki I am trying to integrate this with through npm in the react application.

     import LeaderLine from 'leader-line';
      var startElement = document.getElementById('Swapped_Sim');
        var endElement = document.getElementById('Circle');
        new LeaderLine(startElement, endElement, {
            color: '#fff',
            outline: true,
            endPlugOutline: true,
            endPlugSize: 1.5
        });

**Comment by anseki** [comment]
You can import LeaderLine by using Webpack and `skeleton-loader`.
https://github.com/anseki/leader-line/issues/8#issuecomment-370147614
Or, you can import it by using `<script>` element.
https://anseki.github.io/leader-line/#usage
And access to that.
https://github.com/anseki/leader-line/issues/8#issuecomment-370148929

**Comment by venu-3** [comment]
Hey @anseki  thank you, that will helps a lot

**Comment by anseki** [comment]
I'm glad if I could help you. :smile: 
Could you close this issue if it was solved?

**Comment by venu-3** [comment]
Sure Will do that

**Comment by venu-3** [comment]
Hey @anseki I am able to acheive the line but the line color is so dim.
How can i acheive that

**Comment by venu-3** [comment]
color: '#00c9c9',
            size: 8,
            dash: true,
            startPlug: 'square',
            opacity:1,
            zIndex:9999,
            path:'straight'

**Comment by venu-3** [comment]
I am using the above attributes. but the line color is so dull

**Comment by anseki** [comment]
You can specify a color of line via [`color`](https://anseki.github.io/leader-line/#options-color) option.
I copied the options that you indicated, and it seems that it works fine.
https://jsfiddle.net/26cwve1y/
BTW, `opacity` and `zIndex` in your code are unknown options. They are ignored.

**Comment by venu-3** [comment]
![image](https://user-images.githubusercontent.com/57657470/80466917-c4339c00-895a-11ea-87ec-9dcbd6563d09.png)

**Comment by venu-3** [comment]
Thanks, @anseki  this library helped me a lot. and Awesome library.

**Comment by anseki** [comment]
Did you achieve changing the color?
Anyway, I'm glad if I could help you. :smile:

**Comment by venu-3** [comment]
Yes, @anseki  I achieved it . there is some Z-INDEX problem in my application.

Thanks a lot

**Comment by venu-3** [comment]
Hey @anseki , Can you help me out,

How to build these type of plugins.
I am very much interested to work this kind of things

**Comment by anseki** [comment]
I see.
The problem of color is unrelated to LeaderLine and this issue.
This is important information for users and me.

So, could you make new issue for another topic?

**Comment by venu-3** [comment]
Sure

**Comment by venu-3** [comment]
@anseki  and I got one more issue like on the transition screens the line once we drawn.

When we close the element the line is staying in the same place it is not moving with the screen

Can you please help me on that

**Comment by anseki** [comment]
Sure

**Comment by venu-3** [comment]
> Sure

thanks

**Comment by anseki** [comment]
It's ok. :smile:

**Comment by venu-3** [comment]
Hey @anseki Did you get any solution for that

**Comment by anseki** [comment]
Sorry, my English is poor.
Do you mean that you can't make new issue?
Could you explain what you tried?

**Comment by venu-3** [comment]
No @anseki ,

I got one more issue like

When we implement these plugin on any floating screens.

the lines are not moving with the screen. It is staying where we drawn the lines.

**Comment by anseki** [comment]
Umm... You might have missed my message.
Please read my message again.

**Comment by venu-3** [comment]
Hi @anseki  Can we bind the leader line to a particular component instead of body.

I tried appendChild it not working

**Comment by anseki** [comment]
Please read my messages again.

**Comment by venu-3** [comment]
I need to raise this as a separate issue?

**Comment by anseki** [comment]
Remember, this is GitHub issue tracking system.
Of course you have to make one issue for each one topic.
See: https://github.com/anseki/leader-line/issues/120#issuecomment-620536560
You can save your time and my time by reading my messages.

**Comment by venu-3** [comment]
okay

**Comment by anseki** [comment]
:smile:
