### ISSUE TITLE
leader line position on transistion screens

### ISSUE THREAD

**Issue by venu-3** [anseki/leader-line#121]
Hi @anseki ,

I implemented the leader line on one of the transition screen.

It is staying there when we close and open the screens.

Because it is appending to the Body.

**Comment by venu-3** [comment]
![image](https://user-images.githubusercontent.com/57657470/80572530-0ffa4a00-8a1c-11ea-94d5-c728d8db33fe.png)

**Comment by venu-3** [comment]
![image](https://user-images.githubusercontent.com/57657470/80572648-42a44280-8a1c-11ea-804c-249cdacedda2.png)

**Comment by venu-3** [comment]
Can you please help me on that

**Comment by anseki** [comment]
Hi @venu-3, thank you for the comment.
You can hide the line by using [`hide`](https://anseki.github.io/leader-line/#show-hide) method.

**Comment by venu-3** [comment]
In this case I need to move the line along the screen

**Comment by anseki** [comment]
How the screen is moved? E.g. `transform` property of CSS.

**Comment by venu-3** [comment]
yes

**Comment by anseki** [comment]
How the screen is moved? 
Could you explain?

**Comment by venu-3** [comment]
.right-panel-dismiss {
	-webkit-animation: slideout 0.7s backwards;
	-moz-animation: slideout 0.7s backwards;
	animation: slideout 0.7s backwards;
}
@keyframes slideout {
	0% {
		transform: translateX(-100%);
	}
	50% {
		transform: translateX(0%);
	}
	100% {
		transform: translateX(0%);
	}
}
@keyframes slideIn {
	0% {
		transform: translateX(100%);
	}
	100% {
		transform: translateX(0%);
	}
}

**Comment by venu-3** [comment]
with this code it is moving

**Comment by anseki** [comment]
The `slideout` animation seems to make the element come in.

**Comment by anseki** [comment]
I couldn't understand your code perfectly.
Anyway, this example may help you.
https://jsfiddle.net/rkvp9xzh/
Note that I copied your CSS code and I replaced `0.7s` with `2s` for test.

**Comment by anseki** [comment]
Also, note that this example doesn't consider web browser compatibility.

**Comment by anseki** [comment]
No reply came, my message and my exertion were ignored, then it was closed wordlessly. I don't know why.

**Comment by venu-3** [comment]
that's why I closed it

**Comment by anseki** [comment]
Your code has problems. For example the `animation` is unneeded.
I couldn't give advice about this because you ignored me.
Your manner is not beneficial to you.
Anyway, thank you for the explaining. :smile:

**Comment by venu-3** [comment]
hey, @anseki  sorry for that I was occupied with some work.

So I haven't looked into your message

**Comment by anseki** [comment]
:smile:
