### ISSUE TITLE
Leadline arrow overlap issue when we are using multiple div

### ISSUE THREAD

**Issue by Veeramuthur** [anseki/leader-line#122]
Hi @anseki 

I am facing overlap arrow issue. when i use 3 different div and one div inside i have 2 div its conneting  startpoint and endpoint. if i use css propery z-index: -1 its hiding my inner arrow also. for more understand i attached jsfiddle link. 

https://jsfiddle.net/veeramuthu/gxc89zh6/3/

I want to hide node1 to node 3 arrow. when its overlaping node 2, but node child arrow show not be hide.

please help me to solve this .

**Comment by anseki** [comment]
Hi @Veeramuthur, thank you for the comment.
You can use [`hide`](https://anseki.github.io/leader-line/#show-hide) method to hide the line.

**Comment by Veeramuthur** [comment]
Hi @anseki 

Thanks for you quick replay. i don't want to hide that line whenever its overlap some other div that time i need hide the line div under. if i use z-index: -1 stuff1 and stuff2 arrow also getting hide.
https://jsfiddle.net/veeramuthu/gxc89zh6/3/

**Comment by anseki** [comment]
Do you mean that you want to change `z-index` property of the element as line?

**Comment by Veeramuthur** [comment]
Hi @anseki 

Yes, my first fiddle - https://jsfiddle.net/veeramuthu/gxc89zh6/3/
second fiddle - https://jsfiddle.net/veeramuthu/sez74p26/2/

if you see the changes is  

 .leader-line {
        z-index: -1;
    }

if i use this property my NODE2 line also hiding.  i dont want NODE2 div line.

**Comment by anseki** [comment]
I see.
You can specify CSS properties to `.leader-line` class. As you said, that changes all lines.

```css
.leader-line {
  z-index: -1;
}
```

Or, you can specify CSS properties to specific element.

```js
line = new LeaderLine(node1, node2);
elmLine = document.querySelector('.leader-line:last-of-type');
elmLine.style.zIndex = '-1';
```
Note that these are not supported. I cannot recommend it.

**Comment by Veeramuthur** [comment]
@anseki 

Thank you. this code givens solution for my problem. now I am able to give z-index custom.

**Comment by anseki** [comment]
:smile:
