### ISSUE TITLE
(Request) Detect and draw fully vertical and/or horizontal lines based on vertices of element blocks.

### ISSUE THREAD

**Issue by humblecoder** [anseki/leader-line#123]
It would be nice to be able to draw fully vertical or horizontal lines (with no angle) on elements whose visual "blocks" intersect.  So, for example, pick a `startSocket` (or `endSocket`) on an element and have the matching element draw as vertical a line as possible from its "auto detected anchor".  This may already be possible, but I'm not seeing it.  🤔

**Comment by anseki** [comment]
Hi @humblecoder, thank you for the comment.
So, do you mean that you want a new method to get another element that is positioned on a vertical or horizontal axis?

**Comment by humblecoder** [comment]
Basically, where possible, I'd like it to automatically detect any areas where a vertical or horizontal line could be drawn (and perhaps split the difference)  rather than approximating an angle (see attached image).

![Screen Shot 2020-05-01 at 5 53 03 PM](https://user-images.githubusercontent.com/913539/80855359-91b1c980-8c0e-11ea-99ab-3260ccf3fabd.png)

**Comment by anseki** [comment]
Sorry, my English is poor.
What does the "automatically detect" mean?
Do you mean that you want to calculate the coordinates?

**Comment by anseki** [comment]
This is simple example that calculates the coordinates:
https://jsfiddle.net/0ets2qfv/

**Comment by humblecoder** [comment]
@anseki that's *exactly* what I'm looking for.  In this case "automatically detect" ultimately means "built-in calculation" rather than having to do it manually like that.

Side Note:  Still not seeing what role `y coordinate` actually plays in `pointAnchor` when you have 100% on one and 0 on the other, but I'll keep digging.

Thanks!!!

**Comment by anseki** [comment]
I'm glad if I could help you. :smile: 

See document for the `pointAnchor`.
https://anseki.github.io/leader-line/

So, could you close this issue if it was solved?

**Comment by humblecoder** [comment]
Done.  And thank you for the amazing response!!!
