### ISSUE TITLE
VUE - v-for not working

### ISSUE THREAD

**Issue by Sanoend** [anseki/leader-line#124]
hellow.
LeaderLine.setLine(this.$refs.start, this.$refs.end) - not working if this.$refs.start or this.$refs.end was created in v-for

not working function isElement

	element.nodeType  - is undefined
      	typeof element.getBoundingClientRect  - is undefined

vue create "nodeType" and "getBoundingClientRect" in the nextTick

**Comment by Sanoend** [comment]
UPD:
Temp workout this probleb:

add str if(newOption.nodeType === Node.ELEMENT_NODE && newOption[0]!=undefined && newOption[0].nodeType === Node.ELEMENT_NODE ){ newOption = newOption[0]; }

after code 
 // anchorSE
    ['start', 'end'].forEach(function(optionName, i) {
      var newOption = newOptions[optionName], newIsAttachment = false;

**Comment by anseki** [comment]
Hi @Sanoend, thank you for the comment.

> LeaderLine.setLine(this.$refs.start, this.$refs.end) - not working

Yes, of course that should not work because the `setLine` is unknown method.
See document: https://anseki.github.io/leader-line/

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
