### ISSUE TITLE
can i add click event on line

### ISSUE THREAD

**Issue by WRZack** [anseki/leader-line#125]
hellow.
i use leaderline.js in my project ,now i need to add a click event on the line to know which line i click.
but in the document i dont see any relative info.

**Comment by anseki** [comment]
Hi @WRZack, thank you for the comment.
This may help you: https://github.com/anseki/leader-line/issues/21
Or
https://github.com/anseki/leader-line/issues?q=is%3Aissue+event+listener
Note that it is not recommended, and it is not supported.

**Comment by WRZack** [comment]
hi @anseki thank you for your reply.
i see #70 and i try to use code in my project like https://jsfiddle.net/g4ksLh9v/
but it dont work ,the following is part of my code 
          const line = new LeaderLine(
            document.getElementById(startBoxId),
            document.getElementById(endBoxId),
            {
              color: '#8F97A0',
              size: 4,
              path: 'grid',
              startSocket: 'right',
              endSocket: 'left',
              startSocketGravity: 20,
              endSocketGravity: 20
            }
          )
          const l = document.querySelector('.leader-line:last-of-type')
          l.addEventListener('dblclick', () => {
            line.remove();
          }, false);

**Comment by anseki** [comment]
I copied your code to JSFiddle instead of you.
https://jsfiddle.net/yh1afr08/
It seems that it works fine.

**Comment by WRZack** [comment]
@anseki thank you for your help.
but i doesnt work in my project ,my project is a vue project and i try to add zindex on the svg,but it also doesnt work.

**Comment by anseki** [comment]
Sorry, my English is poor.
What does the "corrent" mean?
Also, could you show me an example via JSFiddle?

**Comment by WRZack** [comment]
@anseki sorry for my bad spelling，i want say 'correct '.i set zindex on the svg and the svg get style zindex what i set .and it work in correctly in JSFiddle https://jsfiddle.net/e47uoyqm/4/ ,i think maybe it's about my framework.
Now I've changed my way to achieve my function instead of click event.
But I still want to thank you for your help

**Comment by anseki** [comment]
Yes, as I said repeatedly, the UI with clicking line is not good idea.
I think that your changing the way is good. :smile: 
So, could you close this issue if it was solved?

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
