### ISSUE TITLE
Dashed lines are not showing after calling show() method

### ISSUE THREAD

**Issue by akashb5432** [anseki/leader-line#126]
Hi, 
When i create the object of leader lines and passed {dash: true} and lines are displayed as dashed animation.
But when i called hide() method and after that calling show() method with changed lines colour,
 lines are not displaying with dashed lines animation they are displaying as plain lines.
Note: I don't want to create again instance of the leader line.

Looking forward for your response
Thanks

**Comment by anseki** [comment]
Hi @akashb5432, thank you for the comment.
You have to specify `dash: {animation: true}` instead of `dash: true`, to enable animation.
For example: https://jsfiddle.net/fjeu3bda/

**Comment by akashb5432** [comment]
@anseki 
Thanks for your response

**Comment by anseki** [comment]
I'm glad if I could help you. :smile: 
So, could you close this issue if it was solved?
