### ISSUE TITLE
Centering coordinates of anchors

### ISSUE THREAD

**Issue by iksent** [anseki/leader-line#127]
Hello! Thank a lot for your perfect library.

I have a question about lines' connections:
Is it possible to connect elements not only with its' edges, but with the most closest point to center of element?

Take a look at this example, there is a line, which auto-find closest edge of element.
For me this point is not ideal and it could be much better to connect element from one center to another center.

This solution not works for me, because lines are overlaying elements, but they have texts inside and it looks bad:
```
LeaderLine.pointAnchor($from, {
  x: '50%',
  y: '50%',
})
```

Simple example:
![2020-05-12_10-22-22](https://user-images.githubusercontent.com/32956521/81641795-49c74980-943b-11ea-9a4a-df493607d8c9.png)

Real example: 
![2020-05-12_10-17-26](https://user-images.githubusercontent.com/32956521/81641362-4089ad00-943a-11ea-8667-883287fdd569.png)

**Comment by anseki** [comment]
Hi @iksent, thank you for the comment.
This may help you: https://jsfiddle.net/bufj2gad/

**Comment by iksent** [comment]
Hello, @anseki!

Sorry, it can't :(

I like "arc"-path, it looks great.
And "straight" path works like an "arc" from "edge" to "edge" of element. Your example shows how to get around this, but it looses end-arrow - it's not visible behind the square :(

**Comment by anseki** [comment]
Of course you can specify the [`path`](https://anseki.github.io/leader-line/#path) option.

**Comment by iksent** [comment]
Oh, probably you do not understand my problem :(

**Comment by anseki** [comment]
Sorry, my English is poor.
Could you explain that?

**Comment by iksent** [comment]
Can you please take a look again at this "example":

<img src="https://user-images.githubusercontent.com/32956521/81641795-49c74980-943b-11ea-9a4a-df493607d8c9.png" />

Green line is what I want to achieve.
Red line is what I have now.

Imagine, that elements is circles (not squares) and you want to find the shortend way from one to another:

![2020-05-15_11-12-09](https://user-images.githubusercontent.com/32956521/82017739-44693980-969d-11ea-9e03-c959fa68aecf.png)

**Comment by anseki** [comment]
Thank you for the explanation.
However, I couldn't understand that well.
What is different between the green line in your image and the example that I indicated except for the `path`?

**Comment by iksent** [comment]
Default "auto" algorithm of LeaderLine is:
shortest way from center of one side of square to center of another side of square.

My green line not from/to center of sides, but from/to center of squares (BUT not connecting them)

![2020-05-15_12-47-35](https://user-images.githubusercontent.com/32956521/82025360-a8462f00-96aa-11ea-8a95-3d915b6feea0.png)

**Comment by anseki** [comment]
Do you mean that the line was connected to centers of square's sides, in the example that I indicated?

**Comment by iksent** [comment]
No, but:

Your example:
![2020-05-15_13-10-41](https://user-images.githubusercontent.com/32956521/82027374-96b25680-96ad-11ea-82bd-a382cf50ab46.png)

And what I want to achieve:
![2020-05-15_13-10-45](https://user-images.githubusercontent.com/32956521/82027383-9b770a80-96ad-11ea-90cd-ebf4d821f68d.png)

**Comment by anseki** [comment]
Hmm...
Do you mean that the line in the example was connected at correct point but there is no arrow?

**Comment by anseki** [comment]
If you want to change the connecting point, you can do that by only passing the coordinates to `LeaderLine.pointAnchor`.
For example:
https://jsfiddle.net/xr9tgmn2/

**Comment by iksent** [comment]
Yes, your last example is what I need.
Do you have a code, that will do such thing for all side? This one works only from left to right.

**Comment by anseki** [comment]
I wrote the example code. Did you read the code?

**Comment by iksent** [comment]
Yeah, look, it works good from left to right

<img src="https://user-images.githubusercontent.com/32956521/82049875-937c9200-96d0-11ea-8b7d-03e74fc85188.png" width="400px"/>

But not from right to left :(

<img src="https://user-images.githubusercontent.com/32956521/82049925-adb67000-96d0-11ea-8d46-e3bc21e06177.png" width="400px"/>

**Comment by anseki** [comment]
It seems that you did not read the code.
That can calculate coordinates for all sides.
For example: https://jsfiddle.net/n9vko0a4/
You had better not use this code without optimization.

**Comment by iksent** [comment]
Oh, I looked at this example... https://github.com/anseki/leader-line/issues/127#issuecomment-629129848

**Comment by iksent** [comment]
Your last example is exactly what I need!

Thanks a lot for your support and very cool library!

**Comment by anseki** [comment]
I'm glad if I could help you. :smile: 
So, could you close this issue if it was solved?
