### ISSUE TITLE
Get XY coordinates of the pointAnchor

### ISSUE THREAD

**Issue by saul-gush** [anseki/leader-line#128]
Hi there, is there an easy way to get X Y coordinates of the start or end pointAnchor? I am using this to drag a point and the point sits half way on the target. It would be great to get the XY coordinates of the pointAnchor.

**Comment by anseki** [comment]
Hi @saul-gush, thank you for the comment.
Could you explain about the X Y coordinates, the point and the target?
Do you mean that you want to put the pointAnchor at the center of an element?

**Comment by saul-gush** [comment]
![image](https://user-images.githubusercontent.com/63714857/82360956-0acc6180-9a02-11ea-878e-878a5a2e131c.png)

![image](https://user-images.githubusercontent.com/63714857/82361208-76163380-9a02-11ea-83c6-f6d2bd84d4b2.png)

I am creating a draggable handle that attaches to other nodes. I used the target to create a custom icon which can be dragged. The coordinates of both the source/target are very useful because lets say the draggable handle doesnt attach to the next node, I can send the handle back to the original node. That is also draggable so I can use the coordinates to keep the two together. I have worked out a work around by .getBoundingClientRect() of the node, then place the target using a calculation. If the source/target coordinates of the line were available, it would be super useful.

**Comment by anseki** [comment]
Sorry, my English is poor. I couldn't understand that well.
Does the "XY coordinates of the pointAnchor" that you said mean [`x/y` options](https://anseki.github.io/leader-line/#attachments-pointanchor-x-y)?
Do you mean that you want to get current coordinates of the element that is moving by dragging?

**Comment by anseki** [comment]
I can't understand the getting the XY coordinates of the pointAnchor.
You don't have to get those usually because you can specify those. In other words, you should already know those without getting it because you decided those.
If you didn't specify those, those are `'50%'` by default.

**Comment by dsandul** [comment]
Hi @anseki , thanks for the library ) Btw, I'm also interested if I can get the coordinates or top/left offsets of the point from where the arrow starts. Or how it can be calculated

**Comment by anseki** [comment]
Hi @dsandul, thank you for the comment.
It seems that your comment is unrelated to the pointAnchor.
Could you make new issue for another topic?

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
