### ISSUE TITLE
coordinates of start point

### ISSUE THREAD

**Issue by dsandul** [anseki/leader-line#132]
Hi @anseki ,
is there any way to calculate coordinates of the point from where the arrow starts:
<img width="432" alt="Screenshot 2020-05-24 at 17 44 42" src="https://user-images.githubusercontent.com/24316710/82757229-a76a7700-9de7-11ea-9826-abd645698997.png">
thanks in advance

**Comment by anseki** [comment]
Hi @dsandul, thank you for the comment.
The coordinates point at the center of a side of the element.
You can get rectangle of the element by `DOM#getBoundingClientRect` method.

**Comment by dsandul** [comment]
Hi @anseki ,
at the moment I have circles as element 1 and 2 and both elements with drag and drop, so the start point is changing it position when element 2 is moving. I've also tried to use `getBoundingClientRect` of DOM node, but the position of moving start point is not so accurate. I've also tried a way when it's possible to add a marker at the start of the arrow but in this case it's not possible to get the coordinates of the svg marker. 

Or may be there is a way to determine somehow on which side of element the start point is placed? (f.e. top, bottom, right, left etc)

**Comment by anseki** [comment]
Yes, you can determine side of element by [`startSocket`/`endSocket` options](https://anseki.github.io/leader-line/#startsocket-endsocket).

**Comment by dsandul** [comment]
Hi @anseki ,
yes, but it's an input parameter and is it possible to get it after leader-line was rendered, without limiting it position? Something like:
```
const line = new LeaderLine({...});
line.getStartPosition();
```
or maybe you have an idea from where I can get it on the library side

**Comment by anseki** [comment]
Sorry, my English is poor.
Do you mean that you want to get the chosen side when `startSocket`/`endSocket` options are `'auto'`?

**Comment by dsandul** [comment]
yes, exactly

**Comment by anseki** [comment]
When `startSocket`/`endSocket` options are `'auto'`, LeaderLine just only chooses the closest side of element to the another element.

**Comment by dsandul** [comment]
thanks a lot for your quick replies,
can you please reference on how you calculate this closest side?

**Comment by anseki** [comment]
You can calculate that easily by [`Math.sqrt`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/sqrt).

**Comment by anseki** [comment]
For example: https://jsfiddle.net/xnp4hoj3/

**Comment by dsandul** [comment]
> For example: https://jsfiddle.net/xnp4hoj3/
great, that is what I need, thanks again!

**Comment by anseki** [comment]
I'm glad if I could help you. :smile: 
So, could you close this issue if it was solved?
