### ISSUE TITLE
Issue with old line artifacts

### ISSUE THREAD

**Issue by RobotPirateNinja** [anseki/leader-line#135]
Great stuff!  Thanks for this!  It was exactly what I was looking for and I'm hoping it use it pretty extensively.

I have run into one thing that I'm not sure how to resolve, and it may be my inexperience with integrating thes kinds of graphic libraries.

My app...draws two objects (say `<p>`) on the screen and then the leader-line draws the line between them (with characteristics based on metrics of the objects).  It's a weather app (at the moment) so it connects things like Actual Temp and Relative Humidity leading to Dew Point (for example).

The way I have it set up though, when I refresh the page (by submitting a new location),the leader-lines persist on the page (if the `<p>'s` move, which they do with location name changes), until I resize the page (or something else to redraw it).  I can't seem to find the lines in the DOM to remove them programatically either.
 
I'm thinking there's a pretty simple solution for this, but after looking for a few hours, I decided to ry and come to the source.

![image](https://user-images.githubusercontent.com/58650531/82952192-c0993200-9f65-11ea-8261-7edfa7c2d03c.png)

**Comment by RobotPirateNinja** [comment]
Sorry...the objects are connecting 
`<p>` tags

**Comment by anseki** [comment]
Hi @RobotPirateNinja, thank you for the comments.

You have to call `position` method when the layout was changed without resizing the window.
See document: https://anseki.github.io/leader-line/#position

**Comment by RobotPirateNinja** [comment]
I'm a little confused about where to invoke that.  

`self = line.position()`

Here's one line being created...

`temptoFeelslike = new LeaderLine(coreTempUI, spanfeelslike, {
                    startPlugColor: '#FF0000',
                    endPlugColor: '#0000FF',
                    gradient: true,
                    dash: {len: 4, gap: 12, animation: true},`

How/when do I call the position method?    I have these currently as the function of a setTimeout, so it doesn't even try to draw them until everything else is rendered.

**Comment by anseki** [comment]
I have read your comment (https://github.com/anseki/leader-line/issues/135#issue-625211768), then, sorry, I couldn't understand that well (e.g. "two objects (say) on the screen").
However, I took notice of this line:

> The way I have it set up though, when I refresh the page (by submitting a new location),the leader-lines persist on the page (if the's move

I couldn't understand the "if the's move", but I guessed that the "I refresh the page" above means that you changed the layout without resizing the window. Is it right?

**Comment by RobotPirateNinja** [comment]
Yes, sorry, I was trying to say that the `<p>` tags move, but Github rendered them because I didn't use the "code" markup here.

> I guessed that the "I refresh the page" above means that you changed the layout without resizing the window. Is it right?

Correct.  It leaves the old lines up until there is some resize of the window.  Then they immediately disappear.

**Comment by RobotPirateNinja** [comment]
Here's an example..

https://www.youtube.com/watch?v=lTjQC8jKjrg&feature=youtu.be

**Comment by anseki** [comment]
If the "refresh the page" changes the layout, you have to call `position` method when you "refresh the page".

**Comment by anseki** [comment]
For example: https://jsfiddle.net/msj8tzfo/
Click "REFRESH" button.

**Comment by RobotPirateNinja** [comment]
Hrrrm.  I"m trying to have it so there's not a need for additional interaction after the submit > location action.  Essentially the "refresh" is submitting a new location, which goes and gets the new weather data object and then lays everything out...*then* redraws the LeaderLines.

The problem is that it's creating *new* Leaderline objects when it comes back, so can't call them to change it since they don't exist yet. (and calling "temptoFeeslLike.position()" right after creating the new version doesn't seem to affect the old one)

I need a way to trigger the "refresh" without a button. I guess I could just a listener to any mouse movement?

**Comment by RobotPirateNinja** [comment]
Progress....I got an event listener working on click to redraw the lines the right place....

Now it just seem to be keeping the old attributes (like Size).

Anyway, I think this gets me most of the way there.  I'll have to try again tomorrow evening.  Thanks again for your help!  And the code...pretty awesome stuff!

**Comment by anseki** [comment]
Umm... Sorry, I couldn't understand that well.
Do you mean that you want to remove an existing line?

**Comment by anseki** [comment]
Or, to reproduce the issue, could you show an example by using e.g. https://jsfiddle.net/ ?

**Comment by RobotPirateNinja** [comment]
>Do you mean that you want to remove an existing line?

Yes, if there is one from a previous request.

The page starts out empty.  Someone submits a location.  The API's go and get some Lat and Long and Weather information.  The weather object is passed back and rendered on the page (using nbs with node).

The issue I'm having is on the SECOND PASS.  When someone, from the same page after getting their first response, sends *another* request...this causes a small shift in the tags used as endpoints for the Leaderlines, and so it draws new lines (for the second pass), but the lines from the *first pass* are still visible (until either a manual page resize or an event...I currently have it set-up for "mouseover").

I need some sleep, so If this doesn't make sense I'll do another video tomorrow.

I'm not sure how much I can put in a fiddle, since the API's all need private keys to function.

**Comment by anseki** [comment]
If you want to remove a line, you can use [`remove`](https://anseki.github.io/leader-line/#remove) method.
I don't know your App, then I don't know whether the removing the line instead of updating the line is better way or not.

Usually, videos don't make sense to reproduce an issue because nobody can find problem in the code without reading the code.
Therefore, better way to reproduce that is the indicating an example code. In other words, you have to reproduce that in other person's computers, not yours.
You can write an example code in JSFiddle without calling the API because there is a problem in your code other than code that calls API maybe.

**Comment by RobotPirateNinja** [comment]
I'm still trying to set up a fiiddle that recreates the issue.  

>If you want to remove a line, you can use remove method.

That seems to remove the new line as well.  So I end up with no lines.  One thing I have noticed...I've been logging the "leader-line" object in my event handler for the submit on the form.

The first pass it shows empty.  Then it adds an svg for each line, and each pass, it adds a new set.   These seems to persist on each submission until I refresh the page.

`   const oldLeaderLine = document.getElementsByClassName("leader-line")
    if (oldLeaderLine) {
        console.log(oldLeaderLine)
}`

![image](https://user-images.githubusercontent.com/58650531/83103163-69818300-a073-11ea-994f-abb86616f91d.png)

This would be an example with 3 leaderlines being called.  The first pass shows it empty.  The second pass keeps the 3 old objects.  The third pass keeps all six from the first two.

And it seems to maintain the formatting for the old ones as well.   Getting the "position()" to fire has worked to get the lines to reset in position, but not in format.

I made another video.  I understand they don't help that much, but it's the easier way for me to show you what I'm seeing.   I can show you more code if that would help, you think.

Essentially you can see the issue in the video, where I re-submit a location, it gets new data, draws news lines...but then I have to call the position with the event listener to remove the old lines, and their formats (like the width on the "wind speed" one) keep persisting.

https://www.youtube.com/watch?v=Xh15iLJ5bTY&feature=youtu.be

**Comment by anseki** [comment]
> That seems to remove the new line as well. 

Do you mean that you called the `remove` method of new line?
If so, of course the line that own `remove` method was called is removed.
In other words, if you want to remove old line, you have to call the `remove` method of the old line.

Nobody can find bug in your code without reading the code.
However, I guess that you mistook the target and the time to call `remove` method.
For example, if you want to clear (i.e. remove) lines when the form is submitted, you have to call the `remove` method of existing lines in `submit` event listener (this might clear the page also).
To pass the lines to the event listener, you have to save instance of line when you made the lines.

For example:
```js
const lines = []; // Lines container

// This function is called when the page was rendered.
function drawLines() {
  // Add a line as you like, and add the instance into container.
  lines.push(new LeaderLine(elementA, elementB));
  // Add more lines if you want.
  lines.push(new LeaderLine(elementC, elementD));
}

// This function is called when the page is cleared. (form is submitted)
function clearLines() {
  // Remove all existing lines.
  lines.forEach(line => { line.remove(); });
  // Clear the container.
  lines.length = 0;
}
```

**Comment by RobotPirateNinja** [comment]
That did it.   It was really just the question of when to do each thing.   So now I create the lines array/container in the main, call the clearLines after the submit, and call the drawLines after the timeout completes (and the data has been received and mutated).  And it all cleans up nicely on each refresh. 

Thanks again for your help!   This gets the last thing out of the way for me to really start playing with this stuff.

**Comment by anseki** [comment]
I copied the example above to JSFiddle.
https://jsfiddle.net/yzax95nd/
Click the button.

In this way, to solve it faster, you can indicate an example without things that you don't want show such as API or something.

So, the issue was solved?

**Comment by RobotPirateNinja** [comment]
>So, the issue was solved?

Yes, I used the pattern you suggested earlier, and now everything is working as expected.  Thanks again for your help!  I really appreciate it!

**Comment by anseki** [comment]
I'm glad if I could help you. :smile: 
So, could you close this issue if it was solved?

**Comment by RobotPirateNinja** [comment]
Things are working perfectly now.  Thanks again for all your help!!!
