### ISSUE TITLE
Angular implementation

### ISSUE THREAD

**Issue by shubhpaliwal** [anseki/leader-line#136]
Hi,
I have been trying to use your library in my angular project, but haven't found any success yet.
Can you please tell me how to implement this in an angular project.
I have implemented the following steps: 
1. installed the package
2. imported it in my angular.json file under scripts

**Comment by dsandul** [comment]
@shubhpaliwal you can declare `declare let LeaderLine: any;` at the top and then use regular LeaderLine fucntions

**Comment by shubhpaliwal** [comment]
Ok, Let me try this

**Comment by shubhpaliwal** [comment]
It says LeaderLine is not defined after using `declare let LeaderLine: any`

**Comment by dsandul** [comment]
> It says LeaderLine is not defined after using `declare let LeaderLine: any`

Please check you did everything correctly as described: https://stackoverflow.com/questions/54908009/angular-library-for-drawing-lines-between-objects
I've used the same approach and it works fine

**Comment by shubhpaliwal** [comment]
Yeah, I checked it and it shows the same error `ReferenceError: LeaderLine is not defined`

**Comment by dsandul** [comment]
> Yeah, I checked it and it shows the same error `ReferenceError: LeaderLine is not defined`

did you re-run `ng serve` after `npm install`?

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
@dsandul, thank you for your supporting. :smile:

**Comment by maxidirienzo** [comment]
1. install the package via `npm i leader-line`
2. import leader-line in `angular.json` under scripts:
```
"scripts": [
   "./node_modules/leader-line/leader-line.min.js",
]
```

3. In the .ts file of the component you will be using `LeaderLine`, add the following at the top of the file:
```
import 'leader-line';
declare let LeaderLine: any
```

**Comment by anseki** [comment]
@maxidirienzo, thank you for your supporting. :smile:

**Comment by KaustubhBadrike-GEP** [comment]
Doesn't seem to work. [Here's a StackBlitz](https://stackblitz.com/edit/angular-ivy-ms8h65?devtoolsheight=33).

**Comment by anseki** [comment]
Hi @KaustubhBadrike-GEP, thank you for the comment.
Try it in places other than StackBlitz.
