### ISSUE TITLE
Add a "click" event on the endPlug of the line

### ISSUE THREAD

**Issue by electrotype** [anseki/leader-line#137]
First let me say thank you for this library: it does _exactly_ what I need! It is clean and easy to use. Good job.

One thing though:  I'm using your example [here](https://jsfiddle.net/6Lybe0jm/) so the user can create an arrow and position its end where he wants. That works very well!! But, when the arrow is drawn, I would like the user to be able to click the `endPlug` (the end of the arrow) to make the arrow move again (and follow the mouse), so the user can target a new area!

I've read [this](https://github.com/anseki/leader-line/issues/21), and I understand it is "_not recommended because of usability for users (a line is usually thin)_". But the end of my arrow is big enough. Clicking it should not be an issue.

I also understand that you suggest to add a small invisible element, at the end of the line, and to add the click event to _that element_, but seems overkill for me: I'm using your library so a user can link some text descriptions to some _areas in a single image_. I guess I could add map areas and make those clickable, but it would be so much easier if I could simply add event handlers to the end of the arrows.

**Comment by anseki** [comment]
Hi @electrotype, thank you for the comment.

So, do you mean that you are using the example in your app? If so, as I said, you should note that the example may have an issue about compatibility, and also, that may be not good UI.

Anyway, you can customize that to make it allow user to connect existing line to another element.
You have to only restore the `connectMode`.

**Comment by anseki** [comment]
For example: https://jsfiddle.net/L9xy07cp/
In this way, it is easy.
Compare this with the code of previous example.

**Comment by electrotype** [comment]
Hi @anseki , thank you for your replies!

But I'm not sure you understand what I need! In your [last example](https://jsfiddle.net/L9xy07cp/), the user needs to click each *end element* to make the associated arrow move again, right? The problem is that, in my case, there are many arrows to the *same element*!

![](https://i.imgur.com/rXShJBL.png)

Clicking on the endPlugs would be much easier than trying to add image map areas, or invisible divs.

**Comment by anseki** [comment]
That is an example to indicate a way to connect existing line to another element.
I don't think that your UI that needs clicking the `endPlug` is good because of usability, as I said. It depends on style of LeaderLine. And also, I think that your app should clearly indicate a target like [`areaAnchor`](https://anseki.github.io/leader-line/#areaanchor), at least. For example, the third `endPlug` from the left in your image may point the woman, or it may point the man at the right.
Anyway, if you really want to make the user click the `endPlug` without image map area and invisible `<div>` element, you can do that by using the coordinates of clicked point.

**Comment by electrotype** [comment]
> you can do that by using the coordinates of clicked point.

That's a good idea actually. The only problem is that I won't be able to display a "pointer" cursor over the endPlugs.

Thanks for your help anseki!

**Comment by anseki** [comment]
You can display a `pointer` cursor by using additional element like `areaAnchor`.
And also, that should solve many problems (e.g. indicating a target) as I said.

Anyway, I'm happy if I could help you. :smile:
