### ISSUE TITLE
Control direction of animation and placement of pathLabel?

### ISSUE THREAD

**Issue by RobotPirateNinja** [anseki/leader-line#138]
I am adding a middleLabel element via the pathLabel method.   The two elements it is connecting are in fairly stable places, so the line drawn is consistent.

However, because of the way the lines are flowing (essentially top-right to lower-middle), the label is being added on the *bottom* of the line, upside down.  I can get it to the right place on the top of the line by reversing the direction of the line, but the animation option is being using in a functional way to represent data (i.e. it represents "rain" and rain usually goes down and looks funny going up).

So...I can't get it to flow the right way  with the label on the correct side.  Also, because of the variable length of the label (and UX considerations), I can't just place it with the other options.

Is there a way to flip *only* the label *or* the animation direction?

**Comment by anseki** [comment]
Hi @RobotPirateNinja, thank you for the comment.
Does the "animation option" that you said mean `animation` option of `dash` option?

**Comment by RobotPirateNinja** [comment]
Yes, exactly that.

**Comment by anseki** [comment]
An option that changes the direction of `dash.animation` option is not supported.

**Comment by RobotPirateNinja** [comment]
Is there a way to reverse the label side then?     So that you can choose
which side the pathLabel goes on?

**Comment by anseki** [comment]
The `pathLabel` should be drawn in the direction from the `start` element to the `end` element.
If the text is important, you should use `captionLabel` instead.
This may help you: https://github.com/anseki/leader-line/issues/41

**Comment by anseki** [comment]
Yes, you should use `captionLabel` instead for important text because controlling the `pathLabel` is meaningless as I said.
If you want to change the direction of `dash.animation` option, you have to control the animation yourself, i.e. set `style.strokeDashoffset`.

**Comment by anseki** [comment]
Or, you can add a transparent line for the `pathLabel`.
This might be easier way if the position is static.

**Comment by RobotPirateNinja** [comment]
Ok.  There's two options here that seems workable.  Let me see what I can do with a transparent line of exactly the same size.  I like that option a lot.  

If I can't get that working, I'll try the custom animation stuff.  Thanks again for your very helpful responses!

**Comment by RobotPirateNinja** [comment]
Using the transparent opposite line worked perfect. Thanks again!

**Comment by anseki** [comment]
:smile:
