### ISSUE TITLE
Trying to update a disconnected element

### ISSUE THREAD

**Issue by LarsHendriks96** [anseki/leader-line#139]
`A disconnected element was passed`

`Uncaught TypeError: Cannot read property 'right' of null`

this is an error I get, working on my realtime application. I was wondering if there is a way to connect a disconnected element. below is an gif that demonstrates my problem.

[![Image from Gyazo](https://i.gyazo.com/e4b622f242aa7376c362d8f1cfcf2a8b.gif)](https://gyazo.com/e4b622f242aa7376c362d8f1cfcf2a8b)

I tried line.position() but this does not seem to work even though the ID's of both elements are given to the leader line. 

Hopefully, you can help me out.

**Comment by anseki** [comment]
Hi @LarsHendriks96, thank you for the comment.
To reproduce that, could you show me an example by using e.g. https://jsfiddle.net/ ?

**Comment by LarsHendriks96** [comment]
I don't think its that easy to reproduce. But in theory, I do the following:

* drag object
* sent new "page object" to other user
* new user replaces old page object with new page object

and then the lines break because I cannot reconnect the old line to the new location of the page object, and for some reason line.position just does nothing, instead of moving the line to the new position of the element.

Hopefully, this gives you kinda an idea of what it could be.

**Comment by anseki** [comment]
Nobody can find a bug in your code without reading your code. And also, nobody know what is the "page-object" without knowing your app. And also, I don't know why you called `line.position()`.
I hope that we can help you, and you accept that.

Anyway, the library should throw an error when a disconnected element was passed. This is correct behavior.

You can edit this instead of creating new JSFiddle.
https://jsfiddle.net/3xj26d94/

**Comment by LarsHendriks96** [comment]
I've been trying my best to recreate this in jsfiddle, but I just don't get the same outcome. Thank you for your quick response, I will try my best to figure it out.

**Comment by anseki** [comment]
Simply, copy the code that has problem and paste it into JSFiddle's panel.

**Comment by LarsHendriks96** [comment]
The problem has been resolved. Apparently a mistake was made with the updating of an "element". you cannot replace the attaching elements with a new element that has the same elementId. by updating the old element the problem is resolved.

I'm still a beginner when it comes to programming. But I thank you for all your help.

**Comment by anseki** [comment]
You can replace the connected element even if that has same ID.
Maybe you mistook that you tried to replace it with new element before adding it to document (i.e. that is "disconnected element").

Anyway, I'm glad if I could help you. :smile:
