### ISSUE TITLE
can not import leader-line into vue-cli project

### ISSUE THREAD

**Issue by scut-west** [anseki/leader-line#14]
Hi anseki,
I use npm install --save leader-line to install the leader-line into my vue-cli project, but I can not import LeaderLine into the code, the LeaderLine is an empty object.
However, I also try to solve this issue according https://github.com/anseki/leader-line/issues/8, but those two solution also does not work. I can not get the window.LeaderLine object, but I can get the window.LeaderLineAttachment object. What is the usage of it? And can I use it to get the LeaderLine object?
Looking forward to your help. 
Thanks and Best Regards,
West.

**Comment by scut-west** [comment]
Hi @anseki,
about webpack: I have add the config into module.rules
 module: {
    rules: [
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: vueLoaderConfig
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test')]
      },
      {
        test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('img/[name].[hash:7].[ext]')
        }
      },
      {
        test: /\.(mp4|webm|ogg|mp3|wav|flac|aac)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('media/[name].[hash:7].[ext]')
        }
      },
      {
        test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('fonts/[name].[hash:7].[ext]')
        }
      },
      **{
        test: require('path').resolve(__dirname, 'node_modules/leader-line/'),
        use: [{
          loader: 'skeleton-loader',
          options: {procedure: content => `${content}export default LeaderLine`}
        }]
      }**
    ]
  },
and in the Vue file or main.js, I add code 
**import LeaderLine from 'leader-line';**

however, all I attempt does not work

**Comment by scut-west** [comment]
But now I have found a solution, download the leader-line.min.js and put it into static fold, which not arranged by webpack and can use absolute path to get this file.
So, I add **<script src="static/leader-line.js"></script>** into **index.html** 
Finally, I can get the **window.LeaderLine.**
Thanks for your attention and you can close this issue now.
Best Regard,
West

**Comment by anseki** [comment]
:smile:

**Comment by logesh-freshworks** [comment]
@scut-west I am using it in a react project @anseki answer worked fine for me.  Try this

`{
      test: require('path').resolve(__dirname, 'node_modules/leader-line/'),
      loader: 'skeleton-loader',
      options: { procedure: content => `${content} export default LeaderLine` }      
    }`
