### ISSUE TITLE
Scrollmagic

### ISSUE THREAD

**Issue by lalitvohra** [anseki/leader-line#140]
I am trying to use this with scrollmagic library

the problem : 
1. I am drawing a line on scroll (also repositioning it)
2. On the next scroll the lines shift up outside the div that is sticky because of scrollmagic.

How can I prevent this ?

**Comment by anseki** [comment]
Hi @lalitvohra, thank you for the comment.
You have to call `position` method when you changed the layout without resizing the window.
See this: https://anseki.github.io/leader-line/#position
Try the example that indicates "Scroll this".

**Comment by lalitvohra** [comment]
I have tried this. there is a jank in reposition. How can I avoid that ?

**Comment by anseki** [comment]
To reproduce that, could you show an example by using e.g. https://jsfiddle.net/ ?

**Comment by lalitvohra** [comment]
I will try to show an example. 

Is there any way the lines can be forced to reposition based on an element rather than window ?

**Comment by anseki** [comment]
Sorry, I couldn't understand the repositioning.
Do you mean that the `position` method didn't work?
Could you show an example by using e.g. https://jsfiddle.net/ ?

**Comment by lalitvohra** [comment]
Hi Please check this 

https://jsfiddle.net/lalitvohra/g0rbcsy3/40/

You will notice when we scroll down sometimes it flickers. How to avoid this ?

**Comment by anseki** [comment]
Try this: https://jsfiddle.net/ujdte2yk/

BTW, it seems that your code has many problems other than the this issue also.
For example, strange to say, you defined only `box2` and `box3`. Therefore your code doesn't work in some environments. See: https://html.spec.whatwg.org/multipage/window-object.html#named-access-on-the-window-object
And other problems also are contained. You should write code properly even if it is example, otherwise it may be not able to accomplish a purpose, or it may make other problems.

**Comment by lalitvohra** [comment]
Thanks for your help, and I just wanted to quicky show the problem, might have missed out some code. I was finally able to solve it by this code

scene.on("enter", function (event) {
					var bodyRect = document.body.getBoundingClientRect();
	    			        var transform = 'translateY('+bodyRect.top+'px'+')';
					jQuery('body > .leader-line').css({'position': 'fixed', 'transform': transform});
			});

**Comment by anseki** [comment]
If you want to get a scrolling position of body, you should use `pageYOffset` instead of `body.getBoundingClientRect`. And also, you should not use jQuery for only adding CSS properties.

Anyway, I'm glad if I could help you. :smile:
