### ISSUE TITLE
How to move LeaderLine SVG tag from BODY to another container?

### ISSUE THREAD

**Issue by esaracco** [anseki/leader-line#142]
Hello,

I need to move the SVG LeaderLine tag from BODY to another container (DIV).
But when I move it, the line becomes impossible to remove later (a exception is thrown).
Is there a way to do that using the LeaderLine API?

JSFiddle here: https://jsfiddle.net/4fv2q1wn
If you comment line 5, removal is OK. If uncommented, a error is thrown.

Emmanuel

**Comment by anseki** [comment]
Hi @esaracco, thank you for the comment.
This may help you: https://github.com/anseki/leader-line/issues/76

**Comment by esaracco** [comment]
Thanks @anseki, it works like a charm :-)
Sorry for the noise... I close this ticket.

**Comment by anseki** [comment]
:smile:
