### ISSUE TITLE
Wrong coordinates when devicePixelRatio !== 1 in Chrome on Windows 10

### ISSUE THREAD

**Issue by LazerRaptor** [anseki/leader-line#143]
Hello Anseki! Big thanks for your excellent library, I quite enjoy it! 
I am not sure if this issue should be related to your library or chromium where it occurs (in firefox it works fine and I think it worked fine on Linux in both browsers). But here is the thing: e.g. if we zoom in, we will get something [like this](https://ibb.co/tMFydsj). 
One way to fix it is to define coordinates of elements like so: 
```
let scale 
  if (navigator.userAgent.includes('Chrome')) {
   scale = window.devicePixelRatio
  } else {
  scale = 1
  }
let x = element.getBoundingClientRect().x / scale
```
Can anything be done with this problem? Thank you!

**Comment by anseki** [comment]
Hi @LazerRaptor, thank you for the comment.

The `getBoundingClientRect` should return values based on CSS pixels. This is expected behavior. That is, the  `getBoundingClientRect` is not affected by `devicePixelRatio`.
Both Google Chrome and Firefox works fine.
Could you explain more?

**Comment by LazerRaptor** [comment]
Sorry @anseki for this premature issue report! 
I think I see what causes this werid behavior now. The card-like nodes on the screenshot have the following structure (Vue app):
```
<g @click="select" v-for="node in nodes" :key="node.id" :id="node.id" class="node">
  <foreignObject :x="node.x" :y="node.y" :height="node.height" :width="node.width">
   <!-- html  -->
  </foreignObject>
</g>
```
To get updated coordinates after dragging, I call `getBoundingClientRect` on the foreignObject element. For some reason, they get multiplied by `devicePixelRatio` value. Likewise, if I specify foreignObject as the target element for LeaderLine instance, `line.position()` will result in what we can see on the screenshot. 
But it all works properly, if I specify `<g>` element instead of `foreignObject`. 
Again, it all worked fine on Linux, so I am still a bit confused about this. Maybe it's some chromium bug that has something to do with foreignObject elements. Or maybe I am doing something wrong, I don't have much experience working with SVG. 
Anyway, thank you for the quick response and for sharing your great libraries, they are huge help for my project!

**Comment by anseki** [comment]
Thank you for the details.
SVG still has some well known problems. And the specification has changed sometimes. And also, web browsers have bugs about SVG.
If you read the source code of this library, you should see many workarounds.

I hope that your app to be great. :smile:
