### ISSUE TITLE
Help request: Multiple lines connection point overlapping

### ISSUE THREAD

**Issue by maxidirienzo** [anseki/leader-line#145]
Hi @anseki, first of all, congrats for the lib, it's really cool! 

I'm dealing with this kind of graphs, see the lines starting from `box 3`:

![Annotation 2020-07-14 195816](https://user-images.githubusercontent.com/1268622/87484392-63883700-c60c-11ea-8d5c-96e97e479a20.png)

I'd need these lines (could be several from/to each box) to not overlap, something like this:

![Annotation-2020-07-14-195816](https://user-images.githubusercontent.com/1268622/87484824-967efa80-c60d-11ea-9c40-2ed859526d49.jpg)

Is there an easy way without manually recalculating the side (and coordenates) to accomplish this? 

I was thinking something like using `pointAnchor` and recalculating an offset amount (based on external information about the lines connecting to the object) on the automatically chosen side before rendering the line, but couldn't find any events triggered.

**Comment by anseki** [comment]
Hi @maxidirienzo, thank you for the comment.
Sorry, my English is poor.
Do you mean that you want to connect the line to specific point instead of `startSocket`/`endSocket`, and the `pointAnchor` didn't work for that?
If so, could you explain more about the problem of `pointAnchor`?

**Comment by maxidirienzo** [comment]
`pointAnchor` is working perfectly, I'm having problems to retrieve a line's `pointAnchor` after setting it, eg:

```
const line = new LeaderLine(
 LeaderLine.pointAnchor( element1, {x: '100%', y: 30} ),
 LeaderLine.pointAnchor( element12, {x: '100%', y: (target.ix * 24) + 12} ),
```

if later I call `line.end` it does not return the `pointAnchor` but a function... it's not big deal right now but it would be cool the get the anchor information.

**Comment by anseki** [comment]
Sorry, what is the "anchor information"?

**Comment by maxidirienzo** [comment]
For example: you initially set the `start` to `LeaderLine.pointAnchor( element1, {x: '100%', y: 30} )`

Later you get `line.end` and there seems to be no way to change the `x` and `y` properties of the `pointAnchor`, instead you need to reassign a new `LeaderLine.pointAnchor( element1, {x: '100%', y: 50} )` instance to move the line in the `y` axis

**Comment by anseki** [comment]
You can get the `pointAnchor` instance via `line.start` (not `line.end`) because you have set the `start`.
See document: https://anseki.github.io/leader-line/#pointanchor
You can't change the properties of the instance as you said. That is not required.
A smart way is that saving the data (anchor information) into variables because the data was made by your code (not the library).

For example:
```js
const offset1StartX = '100%',
  offset1StartY = 30;

line.start = LeaderLine.pointAnchor(element1, {x: offset1StartX, y: offset1StartY});
```

**Comment by maxidirienzo** [comment]
Correct, I got it's the `start` anchor I need to adjust in order to match my example, but for illustration purposes I copied code that dealt with `end`.

I've end up doing what you've said when recalculating the line anchor positions:
```js
line.start = LeaderLine.pointAnchor(el_start, anchorSourceProps);
line.end = LeaderLine.pointAnchor(el_end, anchorTargetProps);
```

Thanks for your replies!

**Comment by anseki** [comment]
:smile:
