### ISSUE TITLE
[Request] VueJS Component

### ISSUE THREAD

**Issue by Ahmedie-m** [anseki/leader-line#146]
Hello Anseki, this is a great JavaScript library, however I was wondering if you would be willing to turn this to a VueJS compatible component? Right now, just like many others, I am struggling to get it working on VueJS.

This would be my current issue: https://stackoverflow.com/questions/62932910/using-leader-line-on-vuejs

Thanks!

**Comment by anseki** [comment]
Hi @Ahmedie-m, thank you for the comment.
Sorry, my English is poor, and I couldn't understand your comment well.
This might help you:
https://github.com/anseki/leader-line/issues?q=is%3Aissue+VueJS

**Comment by Ahmedie-m** [comment]
Hey @anseki don't worry about your English, it's perfect. Basically this isn't 100% compatible with VueJS, I have looked through all the issues but they require workarounds like skeleton loader and all that. I was wondering if you would be interested in taking a look here and seeing if you could possibly turn it into a working VueJS plugin?

https://vuejs.org/v2/guide/plugins.html

**Comment by anseki** [comment]
I see.
LeaderLine is old now. You should see many legacy codes if you read the source code.
I think that the code should be rewritten for modern code, structure and mechanism before supporting frameworks if the library do that. (I think that replacing all  of code may need time.)
Of course you can do that if you want.

**Comment by Ahmedie-m** [comment]
That makes sense, I am not sure if I have the sufficient skills for that, so I wouldn't really know where to start but I get what you mean and appreciate the response.

**Comment by anseki** [comment]
I might rewrite the code if that is in demand.
Anyway, I thank you for the your comment. :smile: 
So, could you close this issue if it was solved?

**Comment by Ahmedie-m** [comment]
Absolutely, thanks @anseki
