### ISSUE TITLE
Lines appears properly only after resize  browser window

### ISSUE THREAD

**Issue by NareshShetty** [anseki/leader-line#148]
On page load all the lines will be there at the end of the page. If I resize the window its positioned properly no issues after that. 

![image](https://user-images.githubusercontent.com/17543808/89022561-dd742c00-d33f-11ea-96b7-b42393959221.png)

Not sure what I am missing. Followed the same steps as per the documentation

`Before inspect element all the lines will be at the bottom as you see in the image`

![image](https://user-images.githubusercontent.com/17543808/89031464-2e8c1c00-d350-11ea-9246-3b8acf303171.png)

`If I open inspect element it will be aligned properly`

![image](https://user-images.githubusercontent.com/17543808/89031546-524f6200-d350-11ea-8001-b789ae1e06b2.png)

Have a look at top value of each line. Its more than 1000 for all the line on load. Once inspect window is opened its coming to normal position. i.e less than 300

**Comment by anseki** [comment]
Hi @NareshShetty, thank you for the comment.
To reproduce that, could you show me an example by using e.g. https://jsfiddle.net/ ?

**Comment by NareshShetty** [comment]
calling leader lines in `ngOnViewInit()` instead of `ngOnInit()` fixed the issue for me.

Thanks for the response

**Comment by anseki** [comment]
:smile: 
Could you close this issue if it was solved?
