### ISSUE TITLE
How to create a line between different sockets of the same element

### ISSUE THREAD

**Issue by v1nt1248** [anseki/leader-line#149]
Hello, @anseki 

I can't create line between 'top' and 'right' sockets of the same element.  

![2020-08-01 23-37-08](https://user-images.githubusercontent.com/12985652/89110105-113e7700-d450-11ea-9c29-88cdc7ef8799.png)

Thanks!

**Comment by anseki** [comment]
Hi @v1nt1248, thank you for the comment.
As the error message said, the `start` and `end` are required.
Then, you can add another element like first element.
For example: https://jsfiddle.net/v83410Lp/

**Comment by v1nt1248** [comment]
Hi!

You create line between 2 element: 1st - '#wrapper', 2nd - '#target'
If start and end element are '#target' the same error appears.

Thanks!

**Comment by anseki** [comment]
That is correct behavior because your HTML is incorrect.
You have to give different ID to 2nd element ("ID" means "identifier"). This is specification of HTML, and this is unrelated to LeaderLine.
See: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id

**Comment by v1nt1248** [comment]
You are right about HTML element id, but LeaderLine documentation does not say that start element and end element must be different elements.
From your reply i have understood that start element and end element must be different.

Thank you!

**Comment by anseki** [comment]
The document indicates specifying element-1 and element-2 many times.
And also, the error message also says that `start` and `end` are required, even if you mistook.
Therefore, I think that the document has no problem, almost users don't mistake that.
Thank you for your suggestion. :smile:
