### ISSUE TITLE
How to dynamically create a line ?

### ISSUE THREAD

**Issue by gsundeep-tech** [anseki/leader-line#15]
Hi,

Is it possible to create the line dynamically ? 
Please check this example: https://gojs.net/latest/intro/ports.html#DrawingNewLinks
Creating the new lines between the nodes in the UI. if it is possible kindly provide any example.

Regards,
Sundeep Gullapudi.

P.S : Your work is cool 👍 Both Leader Line and Plain Draggable libraries are awesome.

**Comment by anseki** [comment]
Hi @gsundeep-tech, thank you for the comment. :smile:

So, LeaderLine is a library to create a line dynamically because it is standard library that provides a ES class.
Therefore, I think that it can do that you want. It can't create a line statically rather than that it can create a line dynamically.

I might have misunderstood your question. Do you want to create a line when an user did something?

**Comment by gsundeep-tech** [comment]
Yes, I have a requirement in which when the user can draw the lines between the draggable nodes (elements), User can click on a node and draw a line to second node and some action handles when the two nodes are connected.

Thanks,
Sundeep Gullapudi.

**Comment by anseki** [comment]
Also, there is a example that add a LeaderLine dynamically:
https://anseki.github.io/plain-overlay/
Click "SHOW" button.

**Comment by anseki** [comment]
It seems that you want a very simple UI that has no difficult point.
I suggest reading the documents.
https://anseki.github.io/leader-line/#startsocket-endsocket
https://anseki.github.io/plain-draggable/
There are examples that the user drags the elements that are connected by LeaderLine.

Also, the examples I indicated add a LeaderLine dynamically.

That is, for example, you can design an UI that the user drags a "connector" by PlainDraggable to join two elements by LeaderLine.

Tell me a difficult point that you can't solve. Or point it if I misunderstood your question.

**Comment by anseki** [comment]
If you want to know how to synchronize the line and the handle, this simple example might help you:
https://jsfiddle.net/8pn7fqmg/
Drag a red handle and drop that on a blue box.

**Comment by anseki** [comment]
No reply came, and you closed this issue.
Therefore, I think that this issue was already solved.
