### ISSUE TITLE
How i can know coordinates midpoint created line?

### ISSUE THREAD

**Issue by v1nt1248** [anseki/leader-line#150]
Hi!

Please tell me, can i know coordinates midpoint created line?
I need to "bind" another HTML element to this coordinates.

Thanks!

**Comment by anseki** [comment]
Hi @v1nt1248, thank you for the comment.
Does the "coordinates midpoint created line" mean coordinates on the line?

**Comment by v1nt1248** [comment]
H!

Yes exactly :)

**Comment by anseki** [comment]
You can get `<path>` element by this:
```js
document.querySelector('.leader-line .leader-line-line-path')
```
Then, you can get the path data via `d` attribute or `pathSegList` property.
Note that these are not supported.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
