### ISSUE TITLE
Scrolling with many lines lags behind scrolling

### ISSUE THREAD

**Issue by trackedsupport** [anseki/leader-line#151]
When Im scrolling a DIV with just one leaderline, the leaderline stays in position and looks good. When there are a couple leaderlines, they can't keep up and lag behind. Anything I can do to fix this?

Code showing how im calling the position() on each scroll event. 
<img width="494" alt="Screen Shot 2020-08-06 at 9 00 45 PM" src="https://user-images.githubusercontent.com/29817223/89597359-ed03e100-d827-11ea-96b9-b7169384d125.png">

Showing how the leaderline looks not scrolling.
<img width="185" alt="Screen Shot 2020-08-06 at 9 03 39 PM" src="https://user-images.githubusercontent.com/29817223/89597511-63a0de80-d828-11ea-874d-e525b4e8d70d.png">
How the leaderline looks midscroll with 5 other leaderlines on the page. 
<img width="165" alt="Screen Shot 2020-08-06 at 9 03 33 PM" src="https://user-images.githubusercontent.com/29817223/89597513-656aa200-d828-11ea-855d-5c7e5b917d00.png">

**Comment by anseki** [comment]
Hi @trackedsupport, thank you for the comment.
It seems that you mistook usage of `AnimEvent.add`.
To reproduce that, could you show me an example by using e.g. https://jsfiddle.net/ ?

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
