### ISSUE TITLE
PR for this project

### ISSUE THREAD

**Issue by re2005** [anseki/leader-line#152]
Would you accept PR's for this project?

I'm trying to use it with VUE and only thing I miss is exporting the module.

`module.exports = LeaderLine;`

**Comment by anseki** [comment]
Hi @re2005, thank you for the comment.
A PR that adds only `module.exports = LeaderLine;` can't be merged because it is not required.
See also: https://github.com/anseki/leader-line/issues?q=is%3Aissue+import

**Comment by re2005** [comment]
People us usually forking and adding this on their repo.

Are you not interested in add module support to your script ?

**Comment by anseki** [comment]
I think that this old library should be refactored instead of those patching.
Therefore this repository has to keep original code, and you can fork it of course.

**Comment by anseki** [comment]
Thank you for your time. :smile:

**Comment by huantaoliu** [comment]
@anseki  thanks for your awesome lib. do you have any plan to refactor it to a more modern lib with modular support ?

**Comment by anseki** [comment]
Hi @huantaoliu, thank you for the comment.
I don't have a plan to refactor it.

**Comment by lucaslgr** [comment]
Hi @re2005 how did you modified the library to work in a Vue CLI project ? I'm trying to do that in this issue #242

**Comment by re2005** [comment]
@lucaslgr beleza?

My solution was copy the dist .min file or fork the repo and export as module

`module.exports = LeaderLine;`

Import that where do you need.

**Comment by lucaslgr** [comment]
Você é BR ? :DDD
@re2005 interessante! estou pensando em como fazer essa adaptação de uma forma sustentável para o projeto, sou relativamente novo com as automações e gerenciamento de pacotes no javascript, para deixar de uma forma sustentável estou pensando em criar uma pasta "lib" no projeto e deixar o arquivo .min lá e colocar o:

```js
module.exports = LeaderLine;
```

Já que se eu deixar como dependência no package.json ele sempre vai baixar a versão do npm sem o module.exports,
Você me sugeriria alguma ideia melhor?

**Comment by re2005** [comment]
That is an okay idea.
U can also fork and submit ur own version to npm.

Good luck ;)
