### ISSUE TITLE
LeaderLines appearing on other pages of website

### ISSUE THREAD

**Issue by colmoneill** [anseki/leader-line#158]
Hi all,
Thank you for this library, it has been a joy to use.

I'm using Leaderlines on the homepage of the website detailed below. Simple enough usage, drawing lines from specific html object id to another specific html object id.
My issue is that on the other pages of the site, a little LeaderLine artifact is present in the forms detailed below.

website homepage: http://breadfellows.school/ (you will see the leader lines on the top) — screenshot below
![Screenshot_2020-09-02 Breadfellows school](https://user-images.githubusercontent.com/2122318/91995985-62cc7100-ed30-11ea-962e-40676ba9f977.png)

but then on all of the other pages of this (still in development) website, I see little horizontal leader lines in what seems to be a mix of colours from the initial homepage settings. See the two screenshots attached below:
![Screenshot_2020-09-02 Breadfellows school(1)](https://user-images.githubusercontent.com/2122318/91995965-5c3df980-ed30-11ea-8ef4-28b6fb5e1a92.png)

![Screenshot_2020-09-02 Breadfellows school](https://user-images.githubusercontent.com/2122318/91995942-547e5500-ed30-11ea-8e0e-ce0937e9786f.jpg)

Am I forgetting to do something or is this a bug? I'm primarily using Firefox 78.0.1 (64-bit) on Manjaro Linux, but this is happening in my other test browsers too.

Thanks for any info,

Cheers

**Comment by anseki** [comment]
Hi @colmoneill, thank you for the comment.
Do you mean that those lines should not be drawn in the sub pages?

**Comment by colmoneill** [comment]
Hi @anseki thanks for the reply,
no I don't want those lines to be drawn, I didn't expect any lines to be drawn as the html elements I'm making LeaderLines between are not present on sub pages...
Am I doing something wrong?
Thanks again

**Comment by anseki** [comment]
Code in a file `theme/js/main.js` adds new lines (i.e. it calls `new LeaderLine()`), then the lines were drawn.
That is, it is correct behavior, and the LeaderLine worked correctly in your webpages.
Therefore, if you don't want those lines to be drawn, remove the code that adds new lines.
Note that I don't know why you added new lines in the code (`theme/js/main.js`).

**Comment by colmoneill** [comment]
Thanks for this support @anseki but I'm not following you. I import leader-line.min.js and I then wrote the LeaderLine function calls in a second JS file (main.js) with specific allocations of LeaderLines to connect HTML objects on my home page.
On all other pages of the website that are not the homepage, the specific HTML objects that I make connections between using LeaderLines are no longer part of the HTML code of the sub pages. I expected that if the HTML objects are not there, then LeaderLine would not draw them. The function calls that are in my main.js file are specific to one and only one page of the site. Can you see the artefacts that LeaderLine creates on all the other pages of the site?
![Screenshot_2020-09-02 Breadfellows school(edit)](https://user-images.githubusercontent.com/2122318/92106327-26564f00-eddc-11ea-90d4-eb8d0323b471.png)
Thanks again,

**Comment by anseki** [comment]
Sorry, my English is poor.
Do you mean that the HTML elements that are given to LeaderLine don't exist in sub pages?

**Comment by colmoneill** [comment]
Exactly, specifically, the objects with IDs
```
breadfellows-title
schools-title
galleries-title
research-title
communities-title
intro__text
```

are only present on the home page, they are not present on any other pages, this is why I thought LeaderLine would not draw if those IDs were not present elsewhere.

Thanks for the help

**Comment by anseki** [comment]
I see.
It seems that there are several mistakes in your code.

- Your first mistake:  
You gave `pointAnchor` attachments to LeaderLine constructor instead of HTML elements. Therefore, those attachments made anchors based on `<body>` element even if HTML elements you specified don't exist.
- Your second mistake:  
You should not control flow of the code with whether the HTML elements exist or not. That only makes `null` or makes your code fail. That is, the code is buggy code (wrong design). This is unrelated  to LeaderLine.

And also, your code seems to contain strange lines. Maybe those are unrelated to the issue, and I didn't read it well.
Anyway, as I said, if you don't want those lines to be drawn, remove the code that adds new lines. (or, remove `<script src="./theme/js/main.js"></script>` and other lines from the HTML code)

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.

**Comment by colmoneill** [comment]
Thank you for the support

15 Sep 2020 06:54:09 anseki <notifications@github.com>:

**Comment by anseki** [comment]
:smile:
