### ISSUE TITLE
Append Area

### ISSUE THREAD

**Issue by Deler-T-Abdolqader** [anseki/leader-line#159]
leader-line SVG's appended to the body element, is any way to change it? I wanna render it in my element parent.
and then I can use over-flow hidden and ... (because I have scroll on my list)

**Comment by anseki** [comment]
Hi @Deler-T-Abdolqader, thank you for the comment.
You can move the SVG element to another element from `<body>` if you really want it.
For example:
```js
document.getElementById('container').appendChild(document.querySelector('.leader-line'));
```
Note that it is not supported, and it is deprecated.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
