### ISSUE TITLE
How to permanently delete lines from DOM?

### ISSUE THREAD

**Issue by olegkorol** [anseki/leader-line#16]
Hi,

I am trying to delete all leader-lines before unmounting a component in React.
After successfully invoking `line.remove()` and unmounting the component the lines are actually gone (they have been removed from the DOM).

But on screen resize the console gets full of:
```
A disconnected element was passed. index.js:2178
TypeError: n is null. leader-line.js:4:12474
```

As I understand, the lines (which supposedly do not exist anymore) are trying to find out the position of their respective `start` and `end` anchors (which of course do not exist anymore, since the component containing them has been unmounted).

Why could this be happening?
Isn't the method `remove()` the correct way to get rid of the lines?

Thanks a lot in advance!

**Comment by anseki** [comment]
Hi @olegkorol, thank you for the report.
Could you show me example? e.g. using https://jsfiddle.net/

**Comment by olegkorol** [comment]
Thanks for the quick response.
Could I send you a link to an email address @anseki ?

**Comment by anseki** [comment]
Don't use email.
Please use an online service such as https://jsfiddle.net/ .

**Comment by olegkorol** [comment]
It would take much time to reproduce it in jsfiddle.
I will try to debug it by myself, thanks for the help anyway.

**Comment by anseki** [comment]
Ok :smile:

**Comment by andyyatma** [comment]
Hi, did you solve the problem ?
i want to remove all line that i make before

**Comment by olegkorol** [comment]
Sorry, that was a looong time ago - I do not remember anymore :(

**Comment by chesiren** [comment]
> Hi @olegkorol, thank you for the report. Could you show me example? e.g. using https://jsfiddle.net/

hi, i found a way to reproduce the bug https://jsfiddle.net/xeq7cLn4/

when we delete both the lines and their anchor, and then resize the window it gives errors

**Comment by anseki** [comment]
Hi @chesiren, thank you for the comment.
It seems that your code has bugs.
You mistakenly used `remove` method of DOM instead of LeaderLine, then the error was thrown caused by the incorrect DOM.
I fixed the bug in your code: https://jsfiddle.net/q8k30wa7/
See document: https://anseki.github.io/leader-line/#remove
