### ISSUE TITLE
Draw lines position not set properly while scrolling  on a popup window 

### ISSUE THREAD

**Issue by softtechinfo2020** [anseki/leader-line#160]
Draw lines position not set properly while scrolling  on a popup window.Please anyone can help me to fix this issue

**Comment by anseki** [comment]
Hi @softtechinfo2020, thank you for the comment.
Could you show me an example to reproduce that by using e.g. https://jsfiddle.net/ ?

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
