### ISSUE TITLE
Leader Line Inside Scrolling Div

### ISSUE THREAD

**Issue by christian-iron60** [anseki/leader-line#161]
**First of all, this library is pretty amazing. Really good work! Well documented and the arrows/lines are highly customizable.** 
Im developing an online editor with 'nodes', which are connected with 'leader-lines' and this library helped me a lot.

Im just facing a problem, I wasn't able to solve myself. The body has 100% width and height and I have a bigger inner div which is the "editor area". It is scrollable (and later dragable) so the user can navigate though it. The arrows are connecting different divs (nodes) the user can create and drag around. For repositioning I use the .position() function. 
At the moment I just reposition all arrows if I detect a scroll on my inner div but this is pretty inefficient and it's getting jerky.

So I tried to move the arrows to my editor div, like you mentioned in Issue #159 `document.getElementById('container').appendChild(document.querySelector('.leader-line'));`
The arrows scrolls with the div, thats good but now the positions are not calculated correctly. It would be pretty awesome if this library can support appending the leader-lines to another div so they move with them without the need of new calculations (scrolling divs...dragable elements etc.) I think this might be a nice and usefull feature.
If this feature is to complex in general, I would be glad if you can help me finding a way to solve the position calculation problem in my case. 

Its a web application based on angular but I made a minimalistic pure html/css/js example for you.
Just scroll in the div and an click the reposition button
https://jsfiddle.net/2um5caLn/52/

Best regards, Christian

**Comment by anseki** [comment]
Hi @christian-iron60, thank you for the comment.
This may help you: https://jsfiddle.net/2sfxvy8k/

**Comment by christian-iron60** [comment]
Big thanks for you fast reply and your help! Im facing 2 problems now. First I cant use .remove() on a Line because it tries to remove the line from body. So my fix is to append the line back to the body before calling .remove(). Not perfect but its working.

The other real thing is, now I have to update all lines each time I change the transform of the wrapper (the position function of the fiddle). Thats a bit better than repositioning on every scroll event but its not 100% of what I am looking for. Do you have any idea how to solve that?

**Comment by anseki** [comment]
You don't need to call the `position` function in `scroll` event because the wrapper is in the scrolling content. You need that only when the layout of a line was changed.
If you want to call only the `position` method of specific line, you can separate the wrapper for each line or group of lines.

**Comment by christian-iron60** [comment]
Yeah I know that, maybe my text wasnt clear enough :) I tried to say that I have to reposition all lines after changing the transform of the wrapper. So if there was a scroll in past and I want to create a new line or update the position of an existing one I call the function. 
This is much better than on every scroll event like I had to do before. But it still causes a short lag I want to prevent. Seperating the wrapper for each line or per node might be a good idea. I will try it out. Thanks @anseki

**Comment by anseki** [comment]
I'm glad if I could help you. :smile: 
So, could you close this issue if it was solved?

**Comment by christian-iron60** [comment]
Yeah you helped me a lot. Thanks for that @anseki. And as I already said your library is awesome! Good work. 

Just one note if someone reads this. You have to deactivade `positionByWindowResize` because this obviously won't work anymore as it isn't updating the transform of your wrappers. Handle the resize event yourself or if you have everything inside of a `overflow: scroll` div like me, you dont need to update position on windows resize. As mentioned in the documentation you can disable that by setting `LeaderLine.positionByWindowResize = false`.

**Comment by anseki** [comment]
Thank you for the information. :smile:
