### ISSUE TITLE
line.position is not a function

### ISSUE THREAD

**Issue by Renaud-Diez** [anseki/leader-line#162]
Hi,

I try to use the script and almost everything work great.
One exception, I can't call the method "position()" ... as it seems to not be a function.
How can I then re-position lines when divs move ?

Thanks a lot for your help.

Renaud

**Comment by anseki** [comment]
Hi @Renaud-Diez, thank you for the comment.
To reproduce that, could you show me an example by using e.g. https://jsfiddle.net/ ?

**Comment by Renaud-Diez** [comment]
The code I use is the following one: 
var lines = document.getElementsByClassName("leader-line");
[].forEach.call(lines, function(line) {
    line.position();
});

The application runs on a Low-code platform (Reactive Web app on OutSystems) and as you will see if you test it on the hyperlink hereafter the line renders correctly until the screen is scrolled ... when we "resize" the window the line reposition correctly and this is what I would like to do ... re-positionning the line when the screen is scrolled ...

You can see the test here: https://bmedicalsystems-dev.outsystemsenterprise.com/Leader/Leader

**Comment by anseki** [comment]
It seems that you radically misunderstood about DOM and JavaScript.
The `document.getElementsByClassName` you wrote returns `HTMLCollection`, that has absolutely no relation to the LeaderLine.
See document: https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementsByClassName
You can get an instance of LeaderLine by [`LeaderLine` constructor](https://anseki.github.io/leader-line/#constructor).
Then you can call the `position` that is instance method.
For example: https://jsfiddle.net/gnrjL5dx/ (Click the button)

**Comment by Renaud-Diez** [comment]
Indeed, I was wrong!
But thanks to you now it works.

I need now to understand why the following call doesn't work: 

window.addEventListener('scroll', function() {
    line.position();
  });

In the meantime I've found an ugly workaround by changing the scroll into a "mousemove" ... 

Thanks a lot for your help!

**Comment by anseki** [comment]
I might be able to help you if you explain the issue about your `scroll` event handler.

BTW, you don't have to write `[].forEach.call` by using `querySelectorAll` instead because `NodeList` supports `forEach`.
For example:
```js
document.querySelectorAll('.your-class').forEach(elm => elm.style.color = 'blue')
```

**Comment by Renaud-Diez** [comment]
Thanks a lot for the tip!

My issue with the scroll event comes from the application itself ... for a weird reason all other events works properly.

But if you want you can take a look here (it's a crapy test): 

I've used the following code for it and for debugging only:
https://bmedicalsystems-dev.outsystemsenterprise.com/Leader/Leader

`var startElement = document.getElementsByClassName($parameters.In1),
  endElement = document.getElementsByClassName($parameters.In2);
  

var line = new LeaderLine(startElement[0], endElement[0], {color: '#adb5bd', size: 2});

window.addEventListener('mousemove', function() {
    line.position();
  });
  
window.addEventListener('scroll', function() {
    line.position();
});`

**Comment by anseki** [comment]
There is no line in the web page.

**Comment by christian-iron60** [comment]
@anseki The line is vertically in the middle of the page.

@Renaud-Diez I can't help you with the your scrolling event but maybe appending the line to your inner div might be an option.
eg. `document.getElementById('container').appendChild(document.querySelector('.leader-line'));`
See #159 and maybe also #161

**Comment by anseki** [comment]
@christian-iron60, thank you for the help.

@Renaud-Diez, I found a bug in your code.
A `<div>` element seems to be scrolling instead of the `window`. That is, you mistook the target that should be attached event listener (i.e. `addEventListener`) to.
Then, remove both code `window.addEventListener('mousemove', ...` and `window.addEventListener('scroll', ...`, and add this instead.
```js
document.querySelector('.active-screen.screen-container').addEventListener('scroll', () => { line.position(); });
```
You should not  do `appendChild` because that is not supported, and it might break your app.

**Comment by christian-iron60** [comment]
Yeah he should not use `appendChild`. I have only mentioned it, in case he isn't able to solve the scrolling problem. But I see you already found it 👍

**Comment by Renaud-Diez** [comment]
Hello guys,

thanks a lot for your help on this!
It is always a pleasure to be helped and instructed by talented people.

Have a nice day,

Renaud

**Comment by anseki** [comment]
:smile:

**Comment by anseki** [comment]
BTW, you had better use [AnimEvent](https://github.com/anseki/anim-event) for a better performance.

**Comment by Renaud-Diez** [comment]
I've read that on your documentation and it's part of my today tasks ;-) 
Once again, thanks for your help!
