### ISSUE TITLE
Leader Line to PDF using snappy in Laravel

### ISSUE THREAD

**Issue by Shineryc** [anseki/leader-line#163]
Hello anseki,

first i want to say thank you about your project, its help me a lot. But i had trouble when converting page that use leader line to pdf using [snappy-laravel](https://github.com/barryvdh/laravel-snappy). the line position was not render properly, i didn't get any solution yet.

this image from the page
![image](https://user-images.githubusercontent.com/29034635/94150501-6a9cb280-fea3-11ea-9ef1-55939959da7a.png)
and this one from the pdf
![image](https://user-images.githubusercontent.com/29034635/94150874-e139b000-fea3-11ea-9a80-090741e5a815.png)
is there any method to reset this position or fixed this position following the element?

Best Regards

**Comment by anseki** [comment]
Hi @Shineryc, thank you for the comment.
If the line is positioned correctly in HTML page, that is issue of rendering in PDF maybe.

**Comment by Shineryc** [comment]
Thanks for your fast response, is there anyway to styling manually this graph? like adding margin?

**Comment by anseki** [comment]
You can adjust the line in the HTML page via LeaderLine API.
However, you had better ask about the rendering PDF of Snappy in Snappy repository.
If the line is positioned correctly in HTML page, that is issue of rendering PDF.

**Comment by Shineryc** [comment]
Thankyou very much

**Comment by anseki** [comment]
:smile:
