### ISSUE TITLE
Cannot read property 'curStats' of undefined

### ISSUE THREAD

**Issue by MarlenePF10** [anseki/leader-line#164]
Hi anseki!

I'm using your library to link some divs in two different columns. Then I erase these arrows before an ajax call that brings a partial view. Here I can link another bunch of divs in other two columns.
In the first page works everything fine, the issue comes when I press the button to go to the second page. I can draw the arrows in this second page but when it's time to erase them before the ajax call, appears the issue.

I try another thing, I did not draw arrows in the first page, click next and draw arrows in the second page (where appears the issue) and it totally worked. It seems like this only can be done once (?).
I attach a screenshot of the issue.

Hope you can help me,
thanks a lot.
Marlene
![issueLeaderLine](https://user-images.githubusercontent.com/72233615/94873440-cec7f500-0414-11eb-8dae-a533b1b3de51.png)

**Comment by anseki** [comment]
Hi @MarlenePF10, thank you for the comment.
To reproduce that, could you show me an example by using e.g. https://jsfiddle.net/ ?

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.

**Comment by MarlenePF10** [comment]
Hi anseki!
I'm sorry I could not write you back before. The issue showed up because I was trying to remove an arrow that was already deleted, simple as that. The issue is closed.
Thank you so much for your support.
Good luck!
Marlene

**Comment by anseki** [comment]
:smile:
