### ISSUE TITLE
Arrows going out of the scrollable div.

### ISSUE THREAD

**Issue by alstrash** [anseki/leader-line#165]
Hi! I'm having an issue where I have a box that can be scrolled horizontally and when the box gets out of the view, it still appears. Like this 
![image](https://user-images.githubusercontent.com/52118901/96201049-be397380-0f18-11eb-932a-990168509653.png)

I tried the other solutions in old posts but didn't work (the ones using a wrapper). I can't use JSFiddle to recreate the error because It's a full application and I wanted a solution for arrows.

**Comment by alstrash** [comment]
Also, I want to add that my only workaround for this would be z-index but putting a z-index of -1 in the lines eliminates them.

**Comment by anseki** [comment]
Hi @alstrash, thank you for the comment.
So, do you mean that the `z-index` solved the issue?

**Comment by alstrash** [comment]
Nope, it didn't, I don't know why but the arrows don't obey the z-index instruction.

**Comment by anseki** [comment]
Why do you think that the lines don't obey the `z-index` instruction?

**Comment by anseki** [comment]
In other words, do you really think that the `z-index` should solve the issue?

**Comment by christian-iron60** [comment]
Hey, without any code example its hard to guess what the problem is. But I think you are facing the same problem I had. 

If you create the leader-lines they get appended to the body. So if you scroll inside your box and call position() to recalculate the lines, they goes out of the border because they dont live inside of your scroll box. 

You can try making a div with a left and right of your scroll box that hides the lines on both sides (change the background-color and z-index if necessary).

As you probabaly already read, in my case the only way to get everything working correctly, was to append the leader-line to the scroll box. Even if this isn't officially supported it should work if you follow all steps mentioned here #161.
@anseki Pleeeassee officially support it. It would make it sooooo much more flexible 😄

>... but didn't work (the ones using a wrapper)

 Without more details I can't help you get it working.

>  I can't use JSFiddle to recreate the error because It's a full application and I wanted a solution for arrows.

Im sure you can reproduce your scenario in a simple JSFiddle example. Otherwise it's hard to help you.

**Comment by anseki** [comment]
Hi @christian-iron60, thank you for your help. :smile: 
I know that the moving the SVG element into another element is needed by some projects, however that has many problems, then I can't add that, as I said over and over again.
Of course you can make a forked version for your project.

**Comment by Dosenbiiir** [comment]
@anseki I prefer improving the original library then just forking it. But I know there might be many problems to solve then so don't take me to seriuos 😄 Moreover I guess my web experience isn't enough to make it great^^ Cheers.

**Comment by christian-iron60** [comment]
@anseki I prefer improving the original library then just forking it. But I know there might be many problems to solve then so don't take me to seriuos 😄 Moreover I guess my web experience isn't enough to make it great^^ Cheers.

**Comment by anseki** [comment]
I think, a lot of new problems by adding the feature are made more than problems might be solved by the feature because I don't have enough skills for that.

**Comment by christian-iron60** [comment]
Yeah probably.
I don't think you have not enough skills, you did great work here and it seems like you are a smart guy 😃

**Comment by anseki** [comment]
:smile:

**Comment by debugaman** [comment]
Regarding the out of scrollable div issue, I would recommend using iframe as the container of the canvas of leader-lines.
This is my example code on creating drag&drop items and connecting them with leader-lines:

On Top-level frame:
```
        $('.leader-line-container').draggable({
		containment: 'window',
		iframeFix: true,
		appendTo: '.leader-line-container-parent-div',
		helper : function() {
			var $drag = $(this).clone();
			$drag.addClass('dragging');
			return $drag;
		},
		distance : 0
	});

	$('.leader-line-container-parent-div').droppable({
		containment: 'window',
		drop : function(event, ui) {
			var canvas_wnd = $(this).find('iframe')[0].contentWindow;
			canvas_wnd.event(event, ui);
		}
	});
```

In iframe:
```
function event(event, ui){
//implementation
new LeaderLine(...);
}
```

**Comment by anseki** [comment]
Hi @debugaman, thank you for the information. :smile:

**Comment by alstrash** [comment]
Hey! Updates! So, reading everything you all said **was really** useful to know more but, in the end, the solution I implemented was to calculate how much distance there is from the border to the arrow and disappear the arrow if needed, mostly because I'm working with SharePoint and using the solutions you all gave was not effective. 

I'm closing the issue, hope the "math" solution can help somebody searching for help. You're great Anseki keep the good work :)

**Comment by anseki** [comment]
:smile:

**Comment by shayh** [comment]
Hi, if it's still relevant to anyone, before switching to another library, I was able to solve this issue by adding a clip path.
I used `d3-select` to manipulate the svg
```  
    const rect = diagramContainer.getBoundingClientRect();
    selectAll('svg.leader-line defs').append('svg:clipPath')
      .attr('id', `arrow-clip`)
      .append('svg:rect')
      .attr('id', 'clip-rect')
      .attr('x', rect.x)
      .attr('y', rect.y)
      .attr('width', rect.width)
      .attr('height', rect.height);

    selectAll('svg.leader-line g')
      .attr('clip-path', `url(#arrow-clip)`);
```

**Comment by anseki** [comment]
Hi @shayh, thank you for the information :smile:
