### ISSUE TITLE
No non-minified .js file

### ISSUE THREAD

**Issue by unsaved** [anseki/leader-line#167]
I'm trying to troubleshoot failure of LeaderLine embedded in svg file but investigation is hampered by minification.  The file "src/leader-line.js" is apparently not just the non-minified version of "leader-line.min.js" since when I use that everthing aborts early on due to a dependency on AnimEvent (which isn't present).

Please advise how I can get or generate a non-minified version of leader-line.min.js that will work standalone like leader-line.min.js does.

**Comment by anseki** [comment]
The `leader-line.min.js` was made from `src`.
Maybe you mistook without reading the codes and understanding build process.

**Comment by KaustubhBadrike-GEP** [comment]
@unsaved On a clone, change [Gruntfile.js#L47](https://github.com/anseki/leader-line/blob/f2fa7a40cc33542872ebc29ef9d2fabf36bca570/Gruntfile.js#L47)
```diff
-    return uglify.minify(content).code;
+    return content;
```
and rebuild.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.

@KaustubhBadrike-GEP, thank you for your help. :smile:
