### ISSUE TITLE
Doesn't work without HTML

### ISSUE THREAD

**Issue by unsaved** [anseki/leader-line#168]
If there's some reason why leader-line doesn't support embedding in svg files, please tell.  I know that with an HTML file, leader-line works with HTML or SVG elements.  I expect it to work with svg elements in an svg file, at least when rendered with a web browser.  My embedded JavaScript has access to document and document.body, and I see no obvious cause when investigating the stack trace in the minified leader-line code.  (I'm so far unable to work with un-minified per issue #167 ).

> leader-line-1.0.5.4.min.js:2 Uncaught TypeError: Cannot read property 'appendChild' of null
>     at Re (leader-line-1.0.5.4.min.js:2)
>     at leader-line-1.0.5.4.min.js:2
>     at Ze (leader-line-1.0.5.4.min.js:2)
>     at Ye.setOptions (leader-line-1.0.5.4.min.js:2)
>     at new Ye (leader-line-1.0.5.4.min.js:2)
>     at tree2-leader.svg:39

The indicated lowest-level minified source code line is:
`n.body.appendChild(t.documentElement),`
n comes from e.document, but backtracking function parameter e farther isn't feasible to minification.

**Comment by anseki** [comment]
Hi @unsaved, thank you for the comment.
Since the LeaderLine is a library to draw a leader line in your web page (i.e. HTML), it should not work in SVG as you said.
See document: https://anseki.github.io/leader-line/

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
