### ISSUE TITLE
Leader Line when working on full-screen mode

### ISSUE THREAD

**Issue by mcarpinter** [anseki/leader-line#169]
Hi,

I want to use this library in a module which works with the fullscreen mode of the browser. When calling to constructor with the browser at fullscreen, it works but the arrow is not showing. When exiting the fullscreen mode, the arrow is there where the two divs were when the browser was at fullscreen. Is it possible to set z-Index to the arrows or how can I work with them into fullscreen mode?

Thanks

**Comment by anseki** [comment]
Hi @mcarpinter, thank you for the comment.
Open this page: https://anseki.github.io/leader-line/ , and press <kbd>F11</kbd> key.
Then, it seems to work fine.
Maybe, the cause of the issue is not fullscreen.
To reproduce that, could you show me an example by using e.g. https://jsfiddle.net/ ?

**Comment by mcarpinter** [comment]
Hi,

Thanks for the quick response. It is complicated to provide an example since the module that I want to implement this is part of a bigger system. I will try it anyway. 
One thing that is in my mind is the following; I am moving to fullscreen a specific div of the module, not all of it, so when it draws the arrow, it does it over the body, not that div. It may be this the issue?

I am uploading 3 screenshots to see if they help.
Screen1, I click into the tab that is within the red box, and it triggers the fullscreen into the div that is within the orange box
Screen2, The div is at fullscreen, I executed the constructor method for the new line
Screen3, when exiting the fullscreen, the arrow is there at the coordinates of the divs that I wanted to connect

![screen3](https://user-images.githubusercontent.com/49532178/96880426-891aad00-1453-11eb-9f27-981a4c7cb257.jpg)

![screen1](https://user-images.githubusercontent.com/49532178/96880416-8750e980-1453-11eb-8b27-ccc9275c5bcf.jpg)
![screen2](https://user-images.githubusercontent.com/49532178/96880423-88821680-1453-11eb-9c58-0c566d16a7d5.png)

**Comment by anseki** [comment]
[`position`](https://anseki.github.io/leader-line/#position) method might help you if you didn't call the method.
Anyway, I or someone might be able to help you when you show example.

**Comment by debugaman** [comment]
Please note that objects dragging, screen or div scrolling and page size change will cause misposition of the leader-line. It was suggested to use line.position() binding to the events I mentioned above.
Example:
ondrag, jquery.draggable - drag ,document.body.onresize, $(selector).on('scroll', function(){ line.position();}

**Comment by anseki** [comment]
@debugaman, thank you for the information.
Note that the method is called automatically when the window was resized.
And also, attaching the method to events directly is not suggested for a performance.
See document: https://anseki.github.io/leader-line/#position

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
