### ISSUE TITLE
How to draw connection line between the tables ?

### ISSUE THREAD

**Issue by uds214125** [anseki/leader-line#170]
draw a line (any type of) where specific criteria match. 

![image](https://user-images.githubusercontent.com/17702550/97077848-a93d9e00-1604-11eb-8186-fad719cdef63.png)

red texts are "id" of span tag.

What i have tried is available here 
[https://angular-leader-rrvdhy.stackblitz.io/](https://angular-leader-rrvdhy.stackblitz.io/)

please give your thought

**Comment by anseki** [comment]
Hi @uds214125, thank you for the comment.
You can specify HTML/SVG element or Attachment as [`start`/`end`](https://anseki.github.io/leader-line/#start-end).

**Comment by uds214125** [comment]
Hi @anseki , since i am generating table based on dynamic data so my `<span id="{{id}}">` is also dynamic.

for the static code `start/end` works like a charm but for dynamic I am stuck.

![image](https://user-images.githubusercontent.com/17702550/97081615-2840cf80-1621-11eb-96bc-e7c880e4a61e.png)

my updated code is here, https://angular-leader-rrvdhy.stackblitz.io/

when uncomment `loop` and `<span>`  the error is 

` ERROR
Error: Uncaught (in promise): Error: `start` and `end` are required.
Error: `start` and `end` are required.`

**Comment by anseki** [comment]
Do you mean that you want to get DOM without using ID?
Or, do you mean that you want to draw lines between `<tr>` elements that have same "Column" value?

**Comment by uds214125** [comment]
Or, Yes, draw the line between `<tr>` where criteria match i.e, "Column" value.  You can say it as "PrimaryKey" to "ForeignKey".

**Comment by anseki** [comment]
I see.
Your code seems to have two bugs at least:
* It tries to get an element by ID in spite of giving no ID to the element.
* It doesn't check all the "Column" values. I can't understand why it checks `i` that is index of the tables and `j` that is index of columns. Also, strange to say, it tries to get a column by using index of table (i.e. `i`).

At least, you have to check all columns and all columns.

**Comment by anseki** [comment]
For example: https://stackblitz.com/edit/angular-leader-rrvdhy-rwyfhc
Note that this example should not be used for your app because I don't know those data details.
And also, note that these issues have no relation to LeaderLine.

**Comment by uds214125** [comment]
Thanks for pointing two bugs. it seems the issue is related to my dynamic onDrawLine code. I will try to check my code logic. 

code which you forked in that example is dummy json data, created by me.

**Comment by anseki** [comment]
The [`document.querySelector()`](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector) that allows to get an element by ID and others may help you.
So, could you close this issue if it was solved?

**Comment by uds214125** [comment]
there is a logic issue. 
Thanks
