### ISSUE TITLE
@anseki an awesome library which I found as an opensource.

### ISSUE THREAD

**Issue by uds214125** [anseki/leader-line#171]
@anseki an awesome library which I found as an opensource. 

my concern was to dynamically draw the line between the tables based on the condition instead of hard-coded "element's id".

what I mean is that 
![image](https://user-images.githubusercontent.com/17702550/97045970-49a7aa00-1594-11eb-8597-4027d9093a23.png)

please give your thought

_Originally posted by @uds214125 in https://github.com/anseki/leader-line/issues/166#issuecomment-715575443_

**Comment by anseki** [comment]
@uds214125 seems to have mistaken.
