### ISSUE TITLE
Plug events

### ISSUE THREAD

**Issue by KaustubhBadrike-GEP** [anseki/leader-line#173]
I need to attach click and hover events on the endPlug. Is this possible?

**Comment by anseki** [comment]
Hi @KaustubhBadrike-GEP, thank you for the comment.
LeaderLine doesn't support getting the `endPlug`.
You can get an element as LeaderLine if you really want to do that.
```js
document.querySelector('.leader-line')
```
You can get the coordinates of clicking that is the position of the `endPlug`.
Note that this is not supported.

**Comment by KaustubhBadrike-GEP** [comment]
Thanks for prompt reply.
> You can get the coordinates of clicking that is the position of the `endPlug`.
How can this be done?

**Comment by anseki** [comment]
You can use [`MouseEvent.clientX`](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/clientX) and [`MouseEvent.clientY`](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/clientY).

**Comment by KaustubhBadrike-GEP** [comment]
Thanks!

**Comment by anseki** [comment]
:smile:
