### ISSUE TITLE
leader-line under table elements

### ISSUE THREAD

**Issue by K-actus** [anseki/leader-line#174]
Hi.

Would it be possible to draw arrow line between 'td' and 'table' in terms of z-index?
I've already tried #26 and #122, but I couldn't.

**Comment by anseki** [comment]
Hi @K-actus, thank you for the comment.
Could you explain about the "I couldn't"?
Also, to reproduce that, could you show me an example by using e.g. https://jsfiddle.net/ ?

**Comment by K-actus** [comment]
Here you are. https://jsfiddle.net/v59g8noq/1/
I want to draw an arrow which goes under "B" element in this example.
Can I use z-index in this case ?

**Comment by anseki** [comment]
You already did that.
The elements simply just be transparent, that's all.
https://jsfiddle.net/sz3724jp/

**Comment by K-actus** [comment]
Oh, I'm embarrassed to make a stupid mistake...
Thank you for answering sincerely.
I close this issue.

**Comment by anseki** [comment]
:smile:
