### ISSUE TITLE
Feature Request: Multiple Sockets Option

### ISSUE THREAD

**Issue by christian-iron60** [anseki/leader-line#176]
Hey Anseki, I have a feature request.

It would be nice to be able to set an array of start and end sockets. Currently you can only set one start socket direction at time e.g. `startSocked: 'bottom'` or  `startSocked: 'bottom'` ...

But in some cases you need something like: pick the closest side from 2 or 3 sides. eg: `left or right` `bottom or left` and so on.

possible syntax might be:
`line.setOptions({startSocket: 'left, right'});`
`line.setOptions({startSocket: ['left', 'right']});`

If this hurts backwards compability also something like this might be possible:
`line.setOptions({startSocketArray: ['left', 'right']});`
`line.setOptions({startSockets: ['left', 'right']});`    <- this is my favorite 😃 

Also if this needs too much changes adding 'vertical' and 'horizontal' might be an option.
`line.setOptions({startSocket: 'vertical'});`
So at least you have theese 2 directions. 

You already have the code for the 'auto' option, I am sure you can adapt that a bit.
But I don't know if you want to put further work into it. So if you are not interessted on doing such a thing, I guess I will try it on my own 😄 

Best regards, 
Chris

**Comment by anseki** [comment]
Hi @christian-iron60, thank you for the proposal.
How does the `vertical` work?
Also, when is the feature useful?

**Comment by christian-iron60** [comment]
Hi @anseki 

As I understood, currently the `auto ` option picks the shortest way from all 4 sides (top, left, right, bottom) to the destination.
The `vertical` option only checks the shortest way from `top` or `bottom` to the destination. 
(`horizontal` picks from `left` or `right`).

It's not that flexible as e.g. `line.setOptions({startSockets: ['left', 'right, 'top']});` where you have nice control over which side is picked from. But vertical and horizontal setting is still good.

This feature is usefull in all cases you are using the `auto` option, but you need more control over which side can be used.
For example for: flowcharts, other diagrams, dynamic generates elements, draggable elements, layout changes due to different windows sizes....

Here is an example how I `horizontal` expect to behave:
https://jsfiddle.net/4zv9efhc/1/

![leader line](https://user-images.githubusercontent.com/59443835/98830774-15a90180-243b-11eb-9f08-d1fd073c3457.jpg)

**Comment by anseki** [comment]
Thank you for the explanation. I see.
I feel that the API is strange because that option is a variety of the `auto`. That is, the array limits choices of the `auto` to less than four. Therefore, that option is the `auto`.
The `startSocket` and `endSocket` options decide whether you control sockets or LeaderLine controls it.
Then, the API style should be e.g. `startSocket: 'auto', startSocketLimit: ['left', 'right']` or `startSocket: 'auto:left,right'`, etc.
The `startSocket: 'left, right'` looks like an option that makes the line branch like a tree.

Anyway, I don't think that the feature is wanted because you can calculate the distance between sockets very easily. And I like a simple API, but it is to much already.
Also, you are mistaken, you said that the feature is useful in all cases that use the `auto` option. I think that it is not "all cases", and it might be useful in a certain case, and it is not compulsory because you can calculate very easily.

So, I welcome more opinions.

**Comment by christian-iron60** [comment]
I get your point, `startSocketLimit` in combination with `startsocket` sounds good.

> I think that it is not "all cases", and it might be useful in a certain case

Thats why I said "... ,but you need more control over which side can be used". Im not a native speaker so maybe my sentence wasn't that clear. I mean its usefull when you need more control over the `auto` option and one fixed side isn't enough for you.

I know I can calculate it myself but this means I also have to call `getBoundingClientRect`, so its done twice (LeaderLine and my Code). So perfomance get's worse. Also it means you need to write more 'boilderplate' code. So having this option would simplify things. 

I need good perfomance as I am updating position of multiple lines in combination with an element being dragged around. I already changed some code to support scrolling divs without the usage of a wrapper div (position calculation). And I am thinking of making more optimaztions for my specific needs. 
Anyway I can think of more usecases then mine so im also interesed in more opinions :)

**Comment by anseki** [comment]
As far as I know, a person who chooses an option other than the `auto` for all options of LeaderLine (not only `startSocket`/`endSocket`, e.g. `startSocketGravity`, color of something, size of something, etc.) may want to control those oneself.
For example, when a draggable element was moved and approached the left wall, it changes the `startSocket` option to `right` for avoiding overlapping the line and the wall.

The `auto` may be useful for almost cases in basic usage.
And the `auto` is not useful for other cases.

I will think about the feature if that is really needed.
I like a simple API (and simple library), and LeaderLine already became not simple maybe.
Anyway, thank you for your proposal and your comment. I understand your idea. :smile:

**Comment by anseki** [comment]
This issue is closed.
I still welcome comments.
