### ISSUE TITLE
Not able to drag in all position

### ISSUE THREAD

**Issue by emosrb** [anseki/leader-line#177]
Hi Anseki,

I am trying to create something like this https://jsfiddle.net/saurabh97/mc3fe6az/5 but I am not able to drag the box in all direction,for some reason, it's fixed in a certain axis where it's placed. https://jsfiddle.net/saurabh97/zof7qtjw/32/.

And also,

Is it possible to restrict the area in which I can drag these lines?

Is it possible to have these lines how it's drawn in this fiddle https://jsfiddle.net/saurabh97/mc3fe6az/5?

Please help me out here!!

Thanks

**Comment by anseki** [comment]
Hi @emosrb, thank you for the comment.
Sorry, I couldn't understand what you want well.
Does this example help you?
https://jsfiddle.net/tfhugqvx/

**Comment by emosrb** [comment]
Yes, this is what I wanted, but why this is needed?

.center {
  height: 100vh;
}

 and also is it possible to restrict the drag area?

**Comment by anseki** [comment]
I'm glad if I could help you. :smile: 
That is PlainDraggable, and this is LeaderLine repository.
Please close this issue, and open new issue in PlainDraggable repository (not here) if you want.
https://anseki.github.io/plain-draggable/
