### ISSUE TITLE
Path correction

### ISSUE THREAD

**Issue by wadimka78** [anseki/leader-line#178]
Hello!
 I have a lot of "cards" in the "div" wrapper on my page. And I need the lines to run between them, not on top of them. How can I exclude certain DOM elements from the path of the line in the settings ? Is it possible? )

https://c2n.me/49Q5o09

**Comment by anseki** [comment]
Hi @wadimka78, thank you for the comment.
This may help you.
https://github.com/anseki/leader-line/issues/52

**Comment by wadimka78** [comment]
Thank you for your quick response!)

**Comment by wadimka78** [comment]
Yes, of course! Thank you again!)

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
