### ISSUE TITLE
Draw on a specific element, not just in the body

### ISSUE THREAD

**Issue by Tomaszczubaszek** [anseki/leader-line#179]
It would be helpful to draw on a specific element when creating some tabs, scrollable areas, etc. Now I have to try with z-index or hide lines manually.

**Comment by anseki** [comment]
Hi @Tomaszczubaszek, thank you for the comment.
You can move the SVG element to another element from `<body>` if you really want it.
For example:
```js
document.getElementById('container').appendChild(document.querySelector('.leader-line'));
```
Note that it is not supported, and it is deprecated.
This also may help you: https://github.com/anseki/leader-line/issues/54

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
