### ISSUE TITLE
Not rendering on Firefox

### ISSUE THREAD

**Issue by fvoordeckers** [anseki/leader-line#180]
In Firefox (82.0.3) the Leader Lines are not showing up. The SVGs are inserted at the bottom of the page and they seem to be in the correct place if you check the inspector, just not showing up.

Expected (works in Safari and Chrome):
<img src="https://user-images.githubusercontent.com/10943876/100339416-211f2f80-2fda-11eb-944c-8ee15573d2d7.png" width="400" />

Result in FF:
<img src="https://user-images.githubusercontent.com/10943876/100339479-36945980-2fda-11eb-82e7-dd393da688f4.png" width="400" />

**Comment by anseki** [comment]
Hi @fvoordeckers, thank you for the comment.
To reproduce that, could you show me an example by using e.g. https://jsfiddle.net/ ?

**Comment by fvoordeckers** [comment]
Not able to reproduce the exact same issue since my setup is way more complex. Since I'm using quite some absolute elements and z-indexes, it might be related to that. Was able to reproduce that issue here:
https://jsfiddle.net/c8nshzfa/3/

**Comment by fvoordeckers** [comment]
Changing the z-index like this doesn't work, the line still seems to be there if I check the element inspector but it's invisible:
`$('.leader-line').css({ 'z-index': 999 });`

**Comment by fvoordeckers** [comment]
Problem also seems to occur on MS Edge. Safari and Chrome are fine...
Don't know what this issue is yet. But besides that it would be nice to be able to specify a zIndex option.

**Comment by anseki** [comment]
You seem to have mistaken the style.
For example: https://jsfiddle.net/y83v4927/

BTW, this is unrelated to Firefox. Therefore, your code might have another bug.
Google Chrome v87
![ss-ch](https://user-images.githubusercontent.com/4763469/100685806-6b305880-33c0-11eb-9f51-29db0dbce309.png)
Firefox v83
![ss-ff](https://user-images.githubusercontent.com/4763469/100685814-6f5c7600-33c0-11eb-97db-875833377262.png)

**Comment by fvoordeckers** [comment]
I have found the issue! The z-index was part of the issue, but the real issue was that the color I used was a hex value, and I passed it to LeaderLine without the hashtag. Magically it worked on Chrome en Safari.

Thanks for helping out, found the issue while recreating a jsFiddle with the exact same setup.

**Comment by anseki** [comment]
Good :smile: 
So, could you close this issue if it was solved?

**Comment by fvoordeckers** [comment]
Yes, thanks
