### ISSUE TITLE
Uncaught Error: `start` and `end` are required.

### ISSUE THREAD

**Issue by ll931217** [anseki/leader-line#181]
Hello,

I am using the Vuejs version of the plugin, [here](https://github.com/ll931217/ChroniBuild/blob/leader-line/src/views/Character/Tree.vue) is my implementation of the code. I can't seem to understand why it gives that error when I `console.log()` the `this.$refs` that it is using and it returns the element being selected.

![image](https://user-images.githubusercontent.com/12750413/100700839-69bf5a00-33d9-11eb-90d4-a136f2f021b5.png)

Am I missing something here?

**Comment by anseki** [comment]
Hi @ll931217, thank you for the comment.
Sorry, I don't know the plugin that you said.
Ask author of that plugin, not here.

**Comment by ll931217** [comment]
Strange, I tried looking for the owner of the plugin but I couldn't find it. My only clue was here

**Comment by anseki** [comment]
That is not my package.
This is my package:
https://www.npmjs.com/package/leader-line
You should check "Collaborators" field.

**Comment by ll931217** [comment]
Hmmm okay, thanks for your time

**Comment by anseki** [comment]
:smile:

**Comment by albertojm8** [comment]
@ll931217 I'm having the exact same issue with that package, couldn't find any help either.

**Comment by ll931217** [comment]
@albertojm8 hi, please have a look at this [Tree.vue](https://www.github.com/ll931217/ChroniBuild/tree/master/src%2Fviews%2FCharacter%2FTree.vue) file. Hopefully you find something useless from this.

**Comment by vaasav-kumar** [comment]
> Hello,
> 
> I am using the Vuejs version of the plugin, [here](https://github.com/ll931217/ChroniBuild/blob/leader-line/src/views/Character/Tree.vue) is my implementation of the code. I can't seem to understand why it gives that error when I `console.log()` the `this.$refs` that it is using and it returns the element being selected.
> 
> ![image](https://user-images.githubusercontent.com/12750413/100700839-69bf5a00-33d9-11eb-90d4-a136f2f021b5.png)
> 
> Am I missing something here?

i got the same issue, any solution?

**Comment by anseki** [comment]
Hi @vaasav-kumar, thank you for the comment.
That is not my module. You mistook repository to ask the question.
You have to ask author of that plugin, not here.

**Comment by ParhsK** [comment]
Hey @anseki, just ran into the same problem using the angular wrapper of leader-liner and since people here got it from the Vue wrapper, I went ahead and tried with the vanilla  leader-line package and got the exact same error when start and end element are the same

**Comment by anseki** [comment]
Hi @ParhsK, thank you for the comment.
Is this the URL of "vanilla leader-line package" that you said?
https://www.npmjs.com/package/leader-line
Also, do you mean that you passed two elements to the API?

**Comment by ParhsK** [comment]
> Hi @ParhsK, thank you for the comment. Is this the URL of "vanilla leader-line package" that you said? https://www.npmjs.com/package/leader-line Also, do you mean that you passed two elements to the API?

Yes, that's the one. It is also possible to reproduce the error in the [demo page](https://anseki.github.io/leader-line/) if you type the following in the console:

```js
new LeaderLine(
  document.getElementById('ex-010-0'),
  document.getElementById('ex-010-0')
);
```

![image](https://user-images.githubusercontent.com/32374315/189545742-7b23583e-73c7-49be-a4b6-cc0133168cff.png)

Thanks for the quick reply!

**Comment by anseki** [comment]
> > do you mean that you passed two elements to the API?

> Yes, 

No, you didn't pass two elements.
Therefore, the LeaderLine threw the error correctly. That is, this is correct behavior.
See document: https://anseki.github.io/leader-line/
If you want to draw a line from a point in an element to another point in the same element, you can use `pointAnchor`.
For example: https://github.com/anseki/leader-line/issues/353#issuecomment-1233632527

**Comment by ParhsK** [comment]
> > > do you mean that you passed two elements to the API?
> 
> > Yes,
> 
> No, you didn't pass two elements. Therefore, the LeaderLine threw the error correctly. That is, this is correct behavior. See document: https://anseki.github.io/leader-line/ If you want to draw a line from a point in an element to another point in the same element, you can use `pointAnchor`. For example: [#353 (comment)](https://github.com/anseki/leader-line/issues/353#issuecomment-1233632527)

I’ll try using pointAnchor, thanks for pointing that out. However the original issue remains which is that when trying to create a LeaderLine with the same element in both start and end, a weird error appears. At the very least one would expect an explanatory console.error e.g. “The same element cannot be used as both starting and ending point” or some mention of it in the docs.

Awesome package btw, thanks for your work!

**Comment by anseki** [comment]
@ParhsK, thank you for the comment.
LeaderLine is a library to draw a line between two elements. Therefore, pass two elements to LeaderLine.
See document: https://anseki.github.io/leader-line/
Do you mean that the `pointAnchor` didn't help you?
Sorry, my English is poor.

**Comment by ParhsK** [comment]
nevermind, thanks for mentioning the `pointAnchor` option and thanks again for your awesome package!

**Comment by anseki** [comment]
:smile:
