### ISSUE TITLE
Keeping the aspect ratio on zoom?

### ISSUE THREAD

**Issue by esaracco** [anseki/leader-line#182]
Hello anseki,
Is there a way to keep line aspect ratio when zooming out?
https://jsfiddle.net/pkvhrL0w

**Comment by anseki** [comment]
Hi @esaracco, thank you for the comment.
The aspect ratio is kept always.
Your code specifies different ratio for the line and DOM element. You have to specify same ratio for those.
For example: https://jsfiddle.net/p9dqmrwL/

**Comment by esaracco** [comment]
@anseki Thanks. But if I lower the RATIO value in your example, the line length still seems too long when zoom has been set.
For example: https://jsfiddle.net/wun1hd93

**Comment by anseki** [comment]
By default, LeaderLine try to keep lowest limit [`startSocketGravity`/`endSocketGravity`](https://anseki.github.io/leader-line/#startsocketgravity-endsocketgravity) options for current line path and size.
You can specify those if you want.
Or, you can change `path` option that is not affected by `startSocketGravity`/`endSocketGravity` options.
For example: https://jsfiddle.net/ntdv82jo/

**Comment by esaracco** [comment]
@anseki OK. Thanks.

**Comment by anseki** [comment]
:smile:
