### ISSUE TITLE
How to prevent flat effect on MS Edge?

### ISSUE THREAD

**Issue by esaracco** [anseki/leader-line#183]
Hello anseki,
Is it possible to prevent a strange three-dimensional effect with Microsoft Edge? Depending on the position of the start / end elements, the line and arrow may become almost flat.

**Comment by anseki** [comment]
Hi @esaracco, thank you for the comment.
Sorry, I don't know the strange three-dimensional effect.

**Comment by esaracco** [comment]
@anseki Sorry for not being specific enough. Here is 3 images:

![1](https://user-images.githubusercontent.com/4351162/102710231-3cb3e800-42b1-11eb-8c0f-f0d6602a8257.png)
![2](https://user-images.githubusercontent.com/4351162/102710233-3faed880-42b1-11eb-854c-48aec3db0274.png)
![3](https://user-images.githubusercontent.com/4351162/102710235-41789c00-42b1-11eb-8611-010f031b1894.png)

**Comment by anseki** [comment]
Umm... Sorry, what is the strange three-dimensional effect?
Do you mean that the `dropShadow` option doesn't work correctry?

**Comment by esaracco** [comment]
@anseki In the first picture, for example, the orange line is not as large as expected and the arrow profile is flat. I didn't see this rendering with Firefox or Chrome.

**Comment by anseki** [comment]
I don't know the "large as expected and the arrow profile is flat".
To reproduce that, could you show me an example by using e.g. https://jsfiddle.net/ ?

**Comment by esaracco** [comment]
@anseki It seems to be related to the dropShadow option. Set it to true and the line will not appear. Remove it or set it to false and the line will appear. https://jsfiddle.net/ewpcbfmk

**Comment by anseki** [comment]
I [already said about the `dropShadow`](https://github.com/anseki/leader-line/issues/183#issuecomment-748619542) 7 days ago.
However, the line was shown in your example.

**Comment by anseki** [comment]
7 days ago, I guessed that this is an issue about the `dropShadow` option.
If so, you might have specified incorrect value for the `dropShadow` option (e.g. color) in another code that I don't know (not the example in JSFiddle).

**Comment by esaracco** [comment]
@anseki OK, thank you. I still do not see the line in the basic jsfiddle I provided you. I am using a VM to test on Edge. Perhaps the problem come from here or an obsolete version. I close this ticket.

**Comment by anseki** [comment]
I see. :smile:
