### ISSUE TITLE
Getting id's of drawn SVG line

### ISSUE THREAD

**Issue by udit9412** [anseki/leader-line#185]
![16092294524595882915880237716769](https://user-images.githubusercontent.com/30665037/103269295-8ac89a00-49db-11eb-888a-89dc004fe8d6.jpg)

There are multiple leader lines drawn between multiple divs and if a user wants to delete a single line or highlight a single line on clicking, how to track the Id of that line

**Comment by anseki** [comment]
Hi @udit9412, thank you for the comment.
Try this:
```js
const
  line1 = new LeaderLine(elmA, elmB),
  elmLine1 = document.querySelector('body>.leader-line:last-of-type'),

  line2 = new LeaderLine(elmC, elmD),
  elmLine2 = document.querySelector('body>.leader-line:last-of-type');
```
Note that this is not supported by the library.

**Comment by udit9412** [comment]
Thank you so much for the solution. So as per current suggestion I applied that to register an eventListner to trigger a function at call but again function was not triggered on clicking of the line

let element =document.querySelector('body>. leader-line:last-of-type').addEventListener("click", (event) {
alert(s(event.target.nodeName.toUpperCase() element );
console.log("Ciciked")
});

**Comment by anseki** [comment]
Your code has some problems.
For example, the variable `element` has nothing because `addEventListener` method returns nothing. And also, a function must be `event => {}` if you intended to write an arrow function.
And more...
Maybe you have to learn JavaScript and rewrite your code.
For example: https://jsfiddle.net/sbvnh30g/

**Comment by udit9412** [comment]
Thanks for the reply!. Yeah I missed the syntax while writing code in GitHub while it was already an arrow function in the code. And with that particular line I removed variable declaration as it will never return anything but the point is the function was not getting triggered and after some time, while using dev tools, I noticed that "pointer-events" was set to none!important by default which was creating the issue. Now it's solved and thanks for the support

**Comment by anseki** [comment]
:smile:
