### ISSUE TITLE
mouseHoverAnchor style: null not working

### ISSUE THREAD

**Issue by Psychokiller1888** [anseki/leader-line#186]
Hi!

When declaring my mouseHoverAnchor with

```
LeaderLine.mouseHoverAnchor({
	element: device,
	showEffectName: 'draw',
	style: null
})
```

I'm still getting that weird styling....

![](https://puu.sh/H1S1E.png)

How do I get rid of this? I want it to stay the normal element and not to be changed

**Comment by anseki** [comment]
Hi @Psychokiller1888, thank you for the comment.
That is correct behavior. If you want to disable adding style properties, you have to specify the style properties like `style: {backgroundImage: null, backgroundColor: null}`, not `style: null`.
See document: https://anseki.github.io/leader-line/#style

**Comment by Psychokiller1888** [comment]
Thanks for the fast reply!

Still does it though...


![](https://puu.sh/H1Svd.gif)

**Comment by Psychokiller1888** [comment]
And comes with a slight movement also

**Comment by Psychokiller1888** [comment]
And also, where do we see all the props it is changing??

**Comment by anseki** [comment]
Sorry, could you explain that?

**Comment by anseki** [comment]
What did you do?
And, what is result you want?

**Comment by Psychokiller1888** [comment]
Ok:

1. We don't know what css properties you are changing
2. Shooting in the dark with
```
this.connectionLinks[link.id] = new LeaderLine(
	LeaderLine.mouseHoverAnchor({
		element: device,
		showEffectName: 'draw',
		style: {
			backgroundImage: null,
			backgroundColor: null,
			backgroundSize: null,
			backgroundUrl: null,
			width: null,
			height: null,
			top: null,
			bottom: null,
			left: null,
			right: null,
			cursor: device.style.cursor
		}
	}
),
```

3. I do show() the lines when a specific tool on my UI is activated. When activated, you can see that the AliceCore icon slightly moves and that it is still transformed on mouseHover:

![](https://puu.sh/H1SCw.gif)

**Comment by anseki** [comment]
You have to specify `hoverStyle` option.
See document to save time.

**Comment by Psychokiller1888** [comment]
what... are.... the css.... properties.... that are changed....??

**Comment by Psychokiller1888** [comment]
Ok, forget it, I totally drop mouseHoveerAnchor, it's way too complicated to geet ride of a styling I don't want, thx

Consider adding `styling: null` for easier use

**Comment by Psychokiller1888** [comment]
And btw, the documentation says:

```
hoverStyle
Type: Object
Default: undefined

This works same to style option except that these style properties are added when a mouse enters the element.
```

Default: undefined, so we expect it to be.... undefined.... And not plugin defined.......

**Comment by anseki** [comment]
It's ok. :smile:
