### ISSUE TITLE
Adding id support

### ISSUE THREAD

**Issue by Psychokiller1888** [anseki/leader-line#187]
Hi

Would you mind adding an id support? Like in the options of the line, one could add and id, making it easier queryselect our drawn lines?

I'm currently trying to get the lines middlelabel texts, but it's not possible dynamically when wanting a specific one

**Comment by anseki** [comment]
Hi @Psychokiller1888, thank you for the comment.
I think that the option for ID is not required because the SVG element can be got by using the `querySelector` method of DOM easily.

**Comment by Psychokiller1888** [comment]
Not really, you don't know their ids if working dynamically

**Comment by anseki** [comment]
Could you explain that?

**Comment by Psychokiller1888** [comment]
- My lines link devices to locations. They are dynamically shown/hidden depending on the UI state.
- A user can add links (and add devices/locations) at anytime, and remove them
- Devices have settings, which should show all it's links to add parameters to them

querySelectorAll allows to get all the lines, but not a specific one without further work. querySelector allows to get a specific one, with a known parameter which is in a dynamic context not possible.

Storing lines in objects, yes, but that's heavy lifting compared to adding a custom "attr-id" tag to elements, configurable on instanciation. And if you think a bit further, adding `:ref` support would make it even easier to Vue.js users.

I saw that you won't add onClick support for lines, labels and so on, so at least, let us select them properly with an id. Your library is awesome, but lacks things that are very basic imo. You could draw a galaxy map with the library, all the options are awesome, but you can't id select a line or link a listener to them without hacking thourgh the DOM with last-element. You can get line.middleLabel, but you can't get the text of it. This is work to do of course and in no way I'm criticizing your decisions, but these little things make everything so much easier for everybody and cost nothing

**Comment by anseki** [comment]
Do you mean that you don't know how to get a specific line by using the `querySelector` method?

**Comment by Psychokiller1888** [comment]
I know how to get a line, but I can't get them specifically.....

**Comment by anseki** [comment]
Yes, of course you can get specific line by using the querySelector method dynamically.

**Comment by anseki** [comment]
Therefore, the option for ID is not required.

**Comment by Psychokiller1888** [comment]
How do I get the line I want when in that state??

![https://puu.sh/H7KDP.png](https://puu.sh/H7KDP.png)

There's no id. And that's only 2 lines

**Comment by anseki** [comment]
Do you mean that you don't know how to get a specific line dynamically by using the `querySelector` method?

**Comment by Psychokiller1888** [comment]
Yep

**Comment by Psychokiller1888** [comment]
Give me the label text of the device second line

**Comment by anseki** [comment]
Try this:
```js
const
  line1 = new LeaderLine(elmA, elmB),
  elmLine1 = document.querySelector('body>.leader-line:last-of-type'),

  line2 = new LeaderLine(elmC, elmD),
  elmLine2 = document.querySelector('body>.leader-line:last-of-type');
```
Note that this is not supported by the library.

BTW, LeaderLine should never support the option for ID because it doesn't support accessing to DOM elements now.

**Comment by Psychokiller1888** [comment]
Nope, that's last of type.... Not the line of the second link

**Comment by anseki** [comment]
Nope, that specifies new line.
You can get a line that is called "second link" by you when that is added.

**Comment by Psychokiller1888** [comment]
`:last-of-type` => DOM last element of specified type, sementically different from `new line`

They are dynamically added.... Did you read my longer post? That means keeping objects to just keep track and a second and third object

**Comment by Psychokiller1888** [comment]
You still haven't been able to give me the text of the device's second line?

**Comment by anseki** [comment]
Sorry, my English is poor. Take it easy please.
Why you can't get the line when that is added?

**Comment by anseki** [comment]
If you want a second line, you can get that by `querySelectorAll(selector)[1]`.

**Comment by anseki** [comment]
Or, you can add an ID to the element that was got by the `querySelector` method.

**Comment by Psychokiller1888** [comment]
Because that's unecessary object creation to keep tracks of hundreds of lines. So what, everytime a line is created you want us to to put them in a dict with a random id as key, then what? From that you have the line, you can't access the label text, as line.middleLabel doesn't have a method to get the text, so you have to hack your way through the DOM to get the element, then select the svg, then select the text child


No, thaat's not what I want, I want the text of the device's second line. What you posted is the the second matched element

**Comment by Psychokiller1888** [comment]
Your problem here, and why you fail to give the answer, is simply that you don't know which line is the second link, so my question is impossible to answer with selectors that don't know the context.... My lines are DB stored and therefor the entries have ids. These ids added to the lines would make you answer me:

```
for (const lineId in Object.keys(myLines)) {
   const line = querySelect('#lineId')
} 
```

**Comment by anseki** [comment]
Do you mean that you don't know `NodeList`?

**Comment by Psychokiller1888** [comment]
> Or, you can add an ID to the element that was got by the `querySelector` method.

This is true, you can imagine the workload and cycles added for something as simple as the library allowing to add ids

**Comment by Psychokiller1888** [comment]
> Do you mean that you don't know `NodeList`?

Ok, forget it, you don't want to understand. Thanks for the library, but we are migrating to other solutions

**Comment by anseki** [comment]
It's OK.
Good choice! :smile:

**Comment by Psychokiller1888** [comment]
Do you mean you don't know `sarcasm`?

**Comment by anseki** [comment]
Sorry, my English is poor. Take it easy please.

**Comment by abinhho** [comment]
I would like to contribute to this repo but I  have no permission.

Anyway, I did a PR here: https://github.com/anseki/leader-line/pull/292/files

![Screenshot 2022-01-22 at 23 36 29](https://user-images.githubusercontent.com/9253378/150647426-35fb1a5d-bceb-421a-9df2-6a799407fe8f.png)
