### ISSUE TITLE
Dashed square like round

### ISSUE THREAD

**Issue by econavi** [anseki/leader-line#188]
Hi!
Sorry for my english.
I would like to ask.
How to set dashed square of line like round?
[Example](https://prnt.sc/xhs1cm)

**Comment by anseki** [comment]
Hi @econavi, thank you for the comment.
Try this: https://jsfiddle.net/h48n2ps9/

**Comment by econavi** [comment]
Thank you!

**Comment by anseki** [comment]
I'm glad if I could help you. :smile: 
So, could you close this issue if it was solved?

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
