### ISSUE TITLE
请问可以给线条添加点击事件吗？

### ISSUE THREAD

**Issue by xiangjun311** [anseki/leader-line#189]

**Comment by anseki** [comment]
Hi @xiangjun311, thank you for the comment.
Could you provid description and explain that?

**Comment by xiangjun311** [comment]
就是我的业务需求是想在连接线上点击并处理相关业务，但是我看了下文档好像是没有提供点击事件方法，就想问问作者能增加这个方法吗，嘿嘿

**Comment by anseki** [comment]
Sorry, I can't understand Chinese.
This may help you: https://jsfiddle.net/m264sxny/
Note that this is not supported by the library.

**Comment by xiangjun311** [comment]
My business requirement is that I want to click on the connection line and handle related business. However, after reading the document, it seems that there is no click event method, so I want to ask the author whether this method can be added？

**Comment by anseki** [comment]
Do you mean that the example by JSFiddle didn't help you?

**Comment by xiangjun311** [comment]
No, I mean I need a link line click event

**Comment by anseki** [comment]
What is the "link line"? Is not that the LeaderLine?

**Comment by xiangjun311** [comment]
Yes, also leaderline  
![image](https://user-images.githubusercontent.com/35052128/105623702-9aaa9100-5e56-11eb-8ab1-8932e176a91a.png)

**Comment by anseki** [comment]
See this: https://github.com/anseki/leader-line/issues/189#issuecomment-766301848
And click the line.

**Comment by xiangjun311** [comment]
Sorry, I can't access JSFiddle

**Comment by anseki** [comment]
The line in JSFiddle accepts click event.

**Comment by anseki** [comment]
Try this.
[ex01.zip](https://github.com/anseki/leader-line/files/5861710/ex01.zip)

**Comment by xiangjun311** [comment]
thank you

**Comment by anseki** [comment]
I'm glad if I could help you. :smile: 
Could you close this issue if it was solved?

**Comment by xiangjun311** [comment]
I'm sorry, it didn't solve my problem.

But thank you very much

**Comment by anseki** [comment]
It's ok, that is another issue.
Could you close this issue?

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
