### ISSUE TITLE
draw line to connect via pointer of mouse

### ISSUE THREAD

**Issue by rahushakya** [anseki/leader-line#19]
is there any option to draw line from one box (div) to another div, i mean by pointer of mouse, is there any way to do it ?

Reference Ex:  http://sebastien.drouyer.com/jquery.flowchart-demo/  "Two operators" Example

**Comment by anseki** [comment]
You can draw a line dynamically at any time by constructor, methods, options or properties.
For example, it draws a line when you click blue elements.
https://jsfiddle.net/oud1yvgw/
For example, it draws a line when you drag a red handle and drop that on a blue box.
https://jsfiddle.net/8pn7fqmg/

**Comment by anseki** [comment]
See the second example that draws a line when you drag a red handle and drop that on a blue box.
Of course you can add the handle to other elements.

**Comment by anseki** [comment]
BTW, why you don't use jquery.flowchart?

**Comment by rahushakya** [comment]
it has certain limitations, look n feel is bestest i ever seen in your library, that is also we need it to custom the connector , also jquery.flowchart guy is not replying us if we stuck in such n such issues.

**Comment by anseki** [comment]
Sorry, my English is very poor, and the abbreviations in your comment were difficult for me, but I understood those mostly, maybe.

**Comment by anseki** [comment]
No reply came, and I close this issue.
