### ISSUE TITLE
Hi, I have a problem with this awesome library in my project.

### ISSUE THREAD

**Issue by shahnawaz09** [anseki/leader-line#190]
We have a expand collapse element at the top of the page and then we have implemented leader line below it  in a container. so when I am expanding the element the the leader line overlaps with my above element when expanded and is not responsive.

Could you please help me out. I am stuck.

**Comment by anseki** [comment]
Hi @shahnawaz09, thank you for the comment.
Do you mean that the leader line doesn't be fixed when the elements are moved?
If so, you have to call [`position`](https://anseki.github.io/leader-line/#position) method when the layout is changed.

**Comment by shahnawaz09** [comment]
Yes @anseki  the leader lines are not fixed when I expand the above element. How to call position method ?

**Comment by shahnawaz09** [comment]
It gets overlapped with my above element when I expand the element.

**Comment by shahnawaz09** [comment]
var line = new LeaderLine(
      document.getElementById('d1'), document.getElementById('d2'),
      {
        positionByWindowResize: false,
        dash: { len: 2, gap: 2 },
        startSocketGravity: [0, -2],
        path: 'grid',
        startSocket: 'top',
        endSocket: 'top',
        color: '#ffffff',
        size: 0.5,
        endPlug: 'disc',
        endPlugSize: 2.5,

      }
    );
    document.getElementById('testContainerNew').addEventListener('click', function () {
      line.position();
      console.log("clicked");
    });



Please refer mt above code. Its an angular application . Still not working. Could you please help me out.

**Comment by shahnawaz09** [comment]
"testContainerNew" is my expand/collapse element.

**Comment by anseki** [comment]
Do you mean that the `position` method didn't work?

**Comment by anseki** [comment]
For example: https://jsfiddle.net/37duypmo/
BTW, the `positionByWindowResize` in your code is incorrect.
See document: https://anseki.github.io/leader-line/#position

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.

**Comment by shahnawaz09** [comment]
Great help @anseki .. issue got resolved

**Comment by shahnawaz09** [comment]
but when we animate with css keyframes content of a box on page load. then how to call leader line position method.
