### ISSUE TITLE
How to hide an arrow line when elements scroll out.

### ISSUE THREAD

**Issue by K-actus** [anseki/leader-line#192]
Hi.

Can I hide an arrow line when I cant watch the elements?

Here is an example.
https://jsfiddle.net/9uc01edk/19/

I want to show arrow line only while the shape of box B exists in the scrollable box.
Should I get the position of the elements?

Thank you.

**Comment by anseki** [comment]
You can use Intersection Observer API.
For example: https://jsfiddle.net/194os7ry/
This issue is unrelated to LeaderLine.

**Comment by K-actus** [comment]
Sorry.
Thank you for answering.

**Comment by anseki** [comment]
No worries. :smile: 
For details: https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API
