### ISSUE TITLE
QUESTION - Is it possible to define the curve location of the line?

### ISSUE THREAD

**Issue by meyer20** [anseki/leader-line#193]
Hello, I have a question regarding the connection of the lines, I currently have two branches, one of them has a child, the other does not. The branches are connected by the blue diamond below, in the branch that does not have children, the line is making the curve in the middle of the path, while the branch that has children, does it below. Is there anything I can do so that the branch curve that doesn't have children is made in the same position as the other branch?

I'm using startSocketGravity: 5 and endSocketGravity: 5 to avoid looping the line, as there is little space between boxes.

My current settings:
`
  lineSettings = {
    size: 1,
    path: 'grid',
    color: '#cccccc',
    endPlug: 'behind',
    startSocketGravity: 5,
    endSocketGravity: 5
  };
`

`
new LeaderLine(
      origin.stepElement,
      target.addButtonElement,
      {
        ...this.lineSettings,
        startSocket: 'bottom',
        endSocket: 'top'
      },
    ).position();
`

Current behavior:
https://imgur.com/gallery/yzzaxkh

Expected Behavior:
https://imgur.com/gallery/40ZiDUy

**Comment by meyer20** [comment]
I'm closing the issue, it was just my own confusion. The answer is in the question itself.
I was adding the boxes and the endSocket was always being 'top'. As the boxes are being added dynamically I forgot this detail. It was only necessary to define the 'endSocket' as left or right, which worked as expected.

I apologize for any inconvenience.

Your lib is incredible and is helping me a lot in the project I'm working on.

Thank you!

**Comment by anseki** [comment]
:smile:
