### ISSUE TITLE
How to get a specific element of drawn line.

### ISSUE THREAD

**Issue by K-actus** [anseki/leader-line#194]
Hi.

I'm trying to get an element of arrow line which has already drawn.
Certainly, I can get all the elements by `document.querySelectorAll('.leader-line') `.
But I want to get more specific element of line in other function.

Here is an example.
https://jsfiddle.net/c68avonf/17/

Thank you.

**Comment by anseki** [comment]
Hi @K-actus, thank you for the comment.
This may help you: https://jsfiddle.net/ed29oaLc/

**Comment by K-actus** [comment]
Sorry, it was a bad example.

Of course, I can get a simple specific line by defining new variable.
However, what I want to get is a route of several lines like this.
https://jsfiddle.net/e65qzm0r/14/

In this example, it is simplified.
There are more boxes and arrow lines in my case, so I don't like defining all the arrow lines.
I consider adding id to each type of arrows (In the above example, Adding id `#LineA`  to both A1 to A2 and A2 to A3 ),
but the property doesn't seem to be supported.

Do you have any idea?

**Comment by anseki** [comment]
Sorry, I couldn't understand that.
Do you mean that you want to add IDs to elements and remove those by DOM API?

You can remove lines by using the `remove` method very easily. Why don't you use the method?
And also, DOM APIs are not supported by the library, then that may make problems.
Of course I don't suggest that, and I think that it has no particular merit, and it has many problems.

**Comment by K-actus** [comment]
Adding ID is simply one of the solution.

I understand removing lines easily by using the remove method.
But I have no idea to identify each set of lines.

**Comment by anseki** [comment]
Adding ID is not good solution. And also, that is not simple. And also, as I said, that may make other problems.
To identify each line, you only have to set the instance into a variable, like almost apps.
See: https://jsfiddle.net/ed29oaLc/
Do you mean that you want to remove multiple lines?

**Comment by K-actus** [comment]
Yes.
As mentioned above, setting the instance is not a smart solution when there are a lot of lines.

In my case, multiple lines are drawn and they have attributions.
So I would like to **distinguish**  and remove each set of lines by the attributions.
Do you understand the meaning?

**Comment by anseki** [comment]
Sorry, my English is poor.
What is the attributions?

**Comment by K-actus** [comment]
See:https://jsfiddle.net/e65qzm0r/14/

In this example, the attribution is A and B.
It's not a technical term but a simple word named in my brain.

**Comment by anseki** [comment]
Do you want to do this?
https://jsfiddle.net/qunvgyed/
This is essentially the same as the previous example that I already showed.
Also, this is basic logic. You can write more simple code.

**Comment by K-actus** [comment]
OK.
I'm going to use array.
I think there was more useful and simple property in leader-line.
Thank you for answering.

**Comment by anseki** [comment]
Umm...
This pattern is generally used, and it is simplest usage.
I don't know what you want. But almost programs do something via instance. In other words, you can do nothing without the instance.
This is strictly generally speaking.
I'm sorry that I could not be of any help to you.
