### ISSUE TITLE
Custom-arrow-heads

### ISSUE THREAD

**Issue by pko-ableton** [anseki/leader-line#195]
Hey anseki,

I love leader line! The only thing missing for me is to add custom arrow heads. I need a crow-feet / list-arrow / fork-arrow for my work and I don't know how to add this custom arrow head for it to work dynamically with your arrows. Here's what I'd like it to look like (see attached) 
https://thenounproject.com/search/?q=fork+line&i=91396

It would be great if you could add this arrow head to your library. A 3-prong pitch fork. 

If you have a tutorial for me on how to add custom arrow heads, that would be amazing.

Thank you,
PKO

**Comment by anseki** [comment]
Hi @pko-ableton, thank you for the comment.
You mean the `startPlug` and `endPlug` options, right?
I think that the library should be simple as much as possible, and it should be light as much as possible. But it has already many options and `*Plug` values.
Therefore, the library should never add more `*Plug` values. Also, that is not required in many cases.
Of course you can customize it for your app.

**Comment by pko-ableton** [comment]
@anseki thank you for replying. By this "Of course you can customize it for your app" -- You mean I can add custom plug values in to the leader-line.min.js file? or where can I add a custom plug design and how? svg code?

**Comment by anseki** [comment]
I mean that this is OSS.
You might want to customize SVG code or JavaScript code.

**Comment by pko-ableton** [comment]
Sorry But I need help in making my custom arrow head align (orient) with the line correctly. This is the code and the problem I am looking at:

![image](https://user-images.githubusercontent.com/56632986/107645111-96fd7380-6c78-11eb-9e00-94b6e283d49d.png)
![image](https://user-images.githubusercontent.com/56632986/107645148-a381cc00-6c78-11eb-8ba3-0e4cb89110ee.png)

can you tell me how I can adjust the arrow head so that it aligns with the path? What is SideLen, backLen, overhead, etc.? It's not doing anything for me when I change it.

**Comment by anseki** [comment]
Those are parameters to adjust position. Read source code for details.
However, maybe you had better write SVG code instead because LeaderLine is just a library to do that instead of you. That is, you don't require it.
Also, you can use one of SVG utility libraries if you want.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
