### ISSUE TITLE
Line doesn't overlap it's start HTML element

### ISSUE THREAD

**Issue by takemyoxygen** [anseki/leader-line#196]
Consider the following example: a line is drawn from blue rectangle to the red one. 
![image](https://user-images.githubusercontent.com/2439445/106759870-46689380-6644-11eb-881a-d3285056c1b3.png)

This line has a break underneath blue rectangle. If I add `opacity: 0` to the blue one, I get this:
![image](https://user-images.githubusercontent.com/2439445/106760166-8def1f80-6644-11eb-81ca-fe6fe7d3f3d8.png)

You can find the full example here: https://jsfiddle.net/xnfj84dL/16/

Is there any way to render the line over the blue rectangle without specifying `startSocket` or `endSocket` options explicitly?

**Comment by anseki** [comment]
Hi @takemyoxygen, thank you for the comment.
LeaderLine tries to draw lines without hiding the target elements. Therefore, that is correct behavior. Also, this feature is unrelated to `startSocket` and `endSocket` options.
If you want to draw the line over the element, add another element for the target.

**Comment by takemyoxygen** [comment]
@anseki, thanks for the reply!

what I meant by using `startSocket` and `endSocket` is that I could set them explicitly to avoid the line to overlap target elements (`startSocket: 'bottom'` in my example). 

> If you want to draw the line over the element, add another element for the target.
Did you mean to create a hidden HTML element positioned exactly the same as the blue rectangle and use it as a target element for the line?

**Comment by anseki** [comment]
If the shape of new element is the same as the blue element, new mask also becomes the same shape.
Therefore, e.g. `0 x 0` element makes `0 x 0` mask.
For example: https://jsfiddle.net/h7upLg91/

**Comment by takemyoxygen** [comment]
@anseki indeed, that makes sense. Thanks for the help!

**Comment by anseki** [comment]
:smile:
