### ISSUE TITLE
Stop ID From Automatically Updating

### ISSUE THREAD

**Issue by vvg125** [anseki/leader-line#197]
I'm using leader-lines to draw arrows between elements that are dynamically "cloned" by the user.  Whenever an element is cloned, my script reassigns a bunch of IDs to stop them from conflicting with each other and draw the correct arrows.

If I setup a leader-line to start at document.getElementById("element1") and end at document.getElementById("element2") it works fine.  But later, if I change the ID of "element1" to "element3", then create a new "element1", the arrow points from "element3" to "element2".

I want the arrow to consistently and statically point from "element1" to "element2", even if there is a new "element1".

Is there a way to achieve this?

**Comment by vvg125** [comment]
Actually, we can disregard this...  I corrected this issue by store all instances of a leader-line to an array, and making corrections by looping through each instance and setting the start/end parameters according to programming logic.

**Comment by anseki** [comment]
Hi @vvg125, thank you for the comment.
Maybe, you have to learn DOM and JavaScript.
The already made reference never be updated automatically when you change a property (or attribute) of the object.
This behavior is unrelated to LeaderLine. This is JavaScript, also ID "attribute" of DOM. That is, the "ID" is just one of attributes, that does nothing for reference.
The updating `start`/`end` options is good solution.
