### ISSUE TITLE
Help With Angular Project - Not Working. Arrow is not coming. No Errors

### ISSUE THREAD

**Issue by divyasunil** [anseki/leader-line#198]
Steps I Followed

1. installed -- > npm i leader-line  
2. Added script on angular.json
"scripts": [
              "./node_modules/leader-line/leader-line.min.js"
            ]
3.import 'leader-line';
declare let LeaderLine: any

referred the below links

https://stackblitz.com/edit/angular-woohoo-leader-line-btpnps
https://stackblitz.com/edit/angular-leader-line-dash-working-refactor-almost-there

![image](https://user-images.githubusercontent.com/16117757/106861497-d9103d80-66eb-11eb-88f4-ce56dd5eeb5f.png)

**Comment by anseki** [comment]
Hi @divyasunil, thank you for the comment.
This may help you: https://github.com/anseki/leader-line/issues/136

**Comment by divyasunil** [comment]
Is it will not work with Angular Material?

**Comment by divyasunil** [comment]
How I can make this work on the Mat Tab

**Comment by anseki** [comment]
I don't know your app but standard Angular project can work with e.g. Webpack.
However, working with StackBlitz may be not easy. Also, I don't understand StackBlitz well, sorry. Maybe you had better ask to StackBlitz team.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
