### ISSUE TITLE
Add exports

### ISSUE THREAD

**Issue by kirillku** [anseki/leader-line#199]
Hi @anseki, thanks for a great library! 

Would you mind to add exports so it will be possible to use the library as a npm package? Right now I have to use [`exports-loader`](https://webpack.js.org/loaders/exports-loader/) as a workaround.

I see from the discussion in https://github.com/anseki/leader-line/pull/147, that you are planning to rewrite the library at first. Any roadmap for that? Why do you feel legacy code is a blocker for adding exports? Could you please explain more detailed your vision? I would be happy to help with the development.

**Comment by anseki** [comment]
Hi @kirillku, thank you for the comment.
I suggest `skeleton-loader` instead.
https://github.com/anseki/leader-line/issues/8#issuecomment-370147614

**Comment by kirillku** [comment]
@anseki `skeleton-loader` is almost the same as `exports-loader`, it is still a workaround. The proper way would be to add exports so it would work as any other npm package. Could you please explain what is the blocker to make it properly?

**Comment by anseki** [comment]
Thank you for the proposal.
The library is old, and it has low demand now. Also, my motivation for rewriting the legacy code is low.
And also, I have no time to do that. Of course nobody pays the cost.
I very thank you for your proposal. :smile:

**Comment by kirillku** [comment]
@anseki I understand that. And I am not asking you to update things for me. I like the library and want to use it without any workarounds (like `skeleton-loader` or `exports-loader`). I would create a pr to add exports but you already rejected it couple of times (https://github.com/anseki/leader-line/pull/147, https://github.com/anseki/leader-line/pull/62). I see you also rejected ts definitions. This why I wrote it as an issue and asked you how can I help to move it forward.

Creating a fork doesn't seem a good solution for me. You are saying you don't have time to work on this library, this is totally fine and understandable, it's not your job. But why you don't allow others to contribute? I feel, this is what open source is about.

**Comment by anseki** [comment]
I think that the prolonging the life of legacy software is not prudent.
Also, many users don't want that.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.

**Comment by xiaohk** [comment]
> I think that the prolonging the life of legacy software is not prudent.

😢😢😢
