### ISSUE TITLE
Package for use with bundlers

### ISSUE THREAD

**Issue by c0bra** [anseki/leader-line#2]
Thanks for the great library!

It would be nice to be able to import this into a larger app being bundled by webpack/rollup. Right now the global variable that's defined requires a legacy library plugin to get it in.

**Comment by anseki** [comment]
Hi @c0bra, thank you for the comment.
You can import the library by specifying an entry point to the source code with customary practice.
LeaderLine uses some packages but those are contained by Grunt. Therefore, you can import that with a building script, e.g. Webpack loader that gets like the `Gruntfile.js`.

**Comment by c0bra** [comment]
Thanks for the tip. I ended up using rollbar-plugin-legacy which works fine except for debugging in the browser.

If I used a loader that executed grunt tasks I'd end up with basically the same minified build file, right? I understand that there's css and whatever else getting appended that you have to bring in.

**Comment by anseki** [comment]
I don't know "rollbar-plugin-legacy" but I used Webpack and loaded the library into my app by using [skeleton-loader](https://github.com/anseki/skeleton-loader) instead of Grunt.
Sorry, my English is very poor, I hope that these information helps you.

**Comment by c0bra** [comment]
Sorry I mean's rollup, not rollbar.

And no worries, I think your English is fine! Thanks for your help.

**Comment by olegkorol** [comment]
Were you able to import the library @c0bra?

**Comment by c0bra** [comment]
@olegkorol yes I was able to get it working.

**Comment by AdarshPawar29** [comment]
> @olegkorol yes I was able to get it working.

How did you import on React typescript app?
