### ISSUE TITLE
Draw arrow from coming from and going to the same element

### ISSUE THREAD

**Issue by James-Curran** [anseki/leader-line#20]
Is there any easy way to do this? Been playing around and by disabling the check I can get it to render an SVG but the it has no size, obviously due to the x/y coords being the same as it's the same element. Any painless ways to change the style to have an arch that returns to the element it came from?

**Comment by anseki** [comment]
Hi @James-Curran, thank you for the comment.
Sorry, my English is very poor, and I could not understand your question well.
Do you mean that you want to draw a line from an edge of an element to another edge of the element?

**Comment by James-Curran** [comment]
No problem, thank you for the quick reply!
Yes basically that is what I would like to do i.e. element1 -> element2, element2 -> element2, element2 -> element3

**Comment by anseki** [comment]
Is that this?
https://jsfiddle.net/6gafmuve/

**Comment by James-Curran** [comment]
Wow...brilliant! Thank you so much, will close now.

**Comment by anseki** [comment]
:smile:
