### ISSUE TITLE
Combine pointAnchor and mouseHoverAnchor

### ISSUE THREAD

**Issue by Verhoeckx** [anseki/leader-line#200]
Hello LeaderLine developes,

I have a short question:
How do you combine the 'attachments' pointAnchor and mouseHoverAnchor?

**Comment by anseki** [comment]
Hi @Verhoeckx, thank you for the comment.
What does “combine” mean?
This example uses `mouseHoverAnchor` and `areaAnchor`.
https://anseki.github.io/leader-line/#ex-040-cols

**Comment by Verhoeckx** [comment]
Hello Anseki,

With combine I mean that the LeaderLine start at a certain x and y position of the start element (pointAnchor) and also use the mouse hover effect (mouseHoverAnchor) on the start element.

**Right now I solved it this way:**
```
var line1 = new LeaderLine(
LeaderLine.pointAnchor( document.getElementById('hi-im-jeroen-text'), { x:'60%', y:'60%' }),
LeaderLine.pointAnchor( document.getElementById('passion-text'), { x:'50%', y:'0%' }),
{hide: true}
);
```
**and** 
```
document.getElementById('hi-im-jeroen-text').addEventListener('mouseover', function() { line1.show('draw'); }, false);
document.getElementById('hi-im-jeroen-text').addEventListener('mouseout', function() { line1.hide('draw'); }, false);
```

**Comment by anseki** [comment]
Your solution is good.
Otherwise, you have to add new element to specify the point.

**Comment by Verhoeckx** [comment]
Ah, good to hear! Thanks for thinking along!!

**Comment by anseki** [comment]
:smile:

**Comment by Verhoeckx** [comment]
Thanks for this great library! I was _exactly_ what I was looking for!!

**Comment by anseki** [comment]
Thank you! :smile:
