### ISSUE TITLE
Is it possible to revert the direction of the draw animation?

### ISSUE THREAD

**Issue by Verhoeckx** [anseki/leader-line#202]
Hello @anseki,

Is it possible to revert the direction of the draw animation?

Right know the _show_ animation goes from the start element to the end element, and the _hide_ animation goes from the end element to the start element. I would like the _hide_ animation also to go from the start element to the end element (so it finishes at the end element).

How is this controlled? I couldn't find a CSS rule for it.

How can I make a small donation to the project?

**Comment by anseki** [comment]
Hi @Verhoeckx, thank you for the comment.
The option that controls the direction of the draw animation is not supported.
You may be able to use another LeaderLine to hide (cover) the line, but this is not smart.

**Comment by Verhoeckx** [comment]
Hi @anseki,

I understand that you can't support every use case. No problem!
I tried with adding a second Leaderline but the result was never perfect. I keep it the way it is.

Thanks for the help!

**Comment by anseki** [comment]
Do you mean that the second LeaderLine didn't work?

**Comment by anseki** [comment]
Try this:
https://jsfiddle.net/py48uhm6/
Note that this is not supported. Also, the code should be optimized maybe.

**Comment by Verhoeckx** [comment]
Hi @anseki!

My first attempt wasn't successful, however, last night I gave it another try and now it works!

This is how I did it:
```
var line1a = new LeaderLine(
    LeaderLine.pointAnchor( document.getElementById('hi-im-jeroen-text'), { x:'60%', y:'60%' }),
    LeaderLine.pointAnchor( document.getElementById('passion-text'), { x:'50%', y:'0%' }),
    {hide: true}
);	

var line1b = new LeaderLine(
    LeaderLine.pointAnchor( document.getElementById('passion-text'), { x:'50%', y:'0%' }),
    LeaderLine.pointAnchor( document.getElementById('hi-im-jeroen-text'), { x:'60%', y:'60%' }),
    {hide: true}
);
```

```
var optionsA = {
	startSocket: 'bottom', 
	endSocket: 'top',
	gradient: {
            startColor: 'rgba(192, 192, 192, 0.1)',
            endColor: 'rgba(192, 192, 192, 0.2)'
	},
	size: 8,	
	path: 'grid',	
	endPlug: 'behind'
}

var optionsB = {
	startSocket: 'top', 
	endSocket: 'bottom',
	gradient: {
            startColor: 'rgba(192, 192, 192, 0.2)',
            endColor: 'rgba(192, 192, 192, 0.1)'
	},
	size: 8,	
	path: 'grid',	
	endPlug: 'behind'
}
```

```
line1a.setOptions(optionsA);
line1b.setOptions(optionsB);
```

```
document.getElementById('hi-im-jeroen-text').addEventListener('mouseover', function() { 
	line1a.show('draw'); 
	setTimeout(function() {line1b.show('none')}, 500);
	setTimeout(function() {line1a.hide('none')}, 500);
}, false);
document.getElementById('hi-im-jeroen-text').addEventListener('mouseout', function() { line1b.hide('draw'); }, false);	
```

Maybe not the shortest code but it's simple and easy to understand.


You can see the result here:
https://jeroenverhoeckx.com/

When the text contains a link, the animation seems to halts?

**Comment by anseki** [comment]
Do you mean that this example didn't help you? https://github.com/anseki/leader-line/issues/202#issuecomment-776419623
Of course you can choose a way you like.

**Comment by Verhoeckx** [comment]
Oh, I didn't mean that! 
I wrote my code _before_ you replied.

So I think both code are good!

Thanks for thinking along :-)!

Sometimes a leaderline seems to hang. Do you why that happens?

**Comment by anseki** [comment]
I'm glad if I could help you. :smile: 

Could you make new issue for another topic?
And write details in the new issue.

**Comment by Verhoeckx** [comment]
Thanks a lot :smile: !

I will make a new issue for the other problem.
