### ISSUE TITLE
Hiding a leaderling on mousout not always works.

### ISSUE THREAD

**Issue by Verhoeckx** [anseki/leader-line#203]
Hello @anseki,

As you can see in the video below the hiding of a leaderline not always works.  
Do you have an idea why it doesn't?  
  
https://user-images.githubusercontent.com/64807887/107648922-302e8900-6c7d-11eb-85f2-92ae2e0744aa.mp4
  
You can also try it yourself on this website: https://jeroenverhoeckx.com/  
  
The code that I use for showing and hiding a Leaderline is:  
```
document.getElementById('hi-im-jeroen-text').addEventListener('mouseover', function() { 
	line1a.show('draw', animOptions); 
	setTimeout(function() {line1b.show('none')}, duration);
	setTimeout(function() {line1a.hide('none')}, duration);
}, false);

document.getElementById('hi-im-jeroen-text').addEventListener('mouseout', function() { 
	line1b.hide('draw', animOptions); 
}, false);
```

Besides the above, I'm just curious: where are from (which country)?

Regards,

Verhoeckx

**Comment by anseki** [comment]
Hi @Verhoeckx, thank you for the comment.
Maybe the `line1b.show()` in `setTimeout` callback is called after `line1b.hide()` in `mouseout` listener is called.
You can check that by DevTools of your web browser, or you can use `console.log` to check sequence of those.

**Comment by Verhoeckx** [comment]
Hello @anseki,

_Yes!! That was it!! Thanks a lot :partying_face: !!_

I also fine-tuned the animation further. 
It looks quite good now: https://jeroenverhoeckx.com/

_Thanks for helping me!!_

Greeting from The Netherlands!

**Comment by anseki** [comment]
:smile: 
So, could you close this issue if it was solved?

**Comment by Verhoeckx** [comment]
Yes, it was solved!

**Comment by Verhoeckx** [comment]
I found out that using _draw_ effect on mousover, and the _fade_ effect on mouseout, looks more nicely so I reverted  part of the code :frowning: . A second Leaderline is now not necessary anymore. Hopefully the above conversation and code will help others.

**Comment by anseki** [comment]
I didn't read your code that solved this issue, and I conjecture that it canceled the effects that are no longer needed by `clearTimeout`.
