### ISSUE TITLE
Animation on LeaderLine instance init

### ISSUE THREAD

**Issue by OleksandrFomin** [anseki/leader-line#204]
Is there a way to make draw animation on init rather than on hover?I run the function on click and I would really like to have the drawing animation as I make a click 
Here is a chunk of my code for reference

`      const line = new LeaderLine(
        LeaderLine.pointAnchor(leaderEnd, { x: -50, y: 45 }),
        LeaderLine.pointAnchor(leaderStart, { x: 35, y: 100 }),
        {
          path: 'grid',
          startPlug: 'behind',
          endPlug: 'disc',
          animation: true,
          size: 2,
          dropShadow: true,
          color: getColor(index, 1),
          endPlugSize: 4,
          endPlugColor: getColor(index, 0.2),
        }
      )
`

**Comment by anseki** [comment]
Hi @OleksandrFomin, thank you for the comment.
You can use [`show` / `hide` methods](https://anseki.github.io/leader-line/#show-hide) to start the animation.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
