### ISSUE TITLE
Offset for middleLabel

### ISSUE THREAD

**Issue by gtoroptsev** [anseki/leader-line#205]
Hi anseki!
Thank you for this great plugin.

I have a question, is it possible to setup offset for middleLabel?
For example, I would like the text to be displayed on top of the line (see screenshot)
I tried offset option, but looks like it is working for start & end labels only

![26ce7e14a5](https://user-images.githubusercontent.com/25869136/109775091-7e023580-7c1a-11eb-959a-0df1f59a4ded.png)

**Comment by anseki** [comment]
You are confusing the [`offset`](https://anseki.github.io/leader-line/#offset) option with the [`lineOffset`](https://anseki.github.io/leader-line/#attachments-captionlabel-lineoffset) option.
If you tried the `offset` option (not `lineOffset`), of course the attachment is positioned at the specified coordinates relative to the socket. This is correct behavior.

**Comment by gtoroptsev** [comment]
Thank you for fast reply.

I undestand the difference between offset & lineOffset
I want to place Middle label on the same level as Start & End Label (on top of the line), is that possible?

![ffb43d3d97](https://user-images.githubusercontent.com/25869136/109790313-b27ded80-7c2a-11eb-9a2a-4f9ad32059fc.png)

**Comment by anseki** [comment]
The library doesn't support the moving the `middleLabel` to the same `top` of the `startLabel`.
Then, you can move that by changing `y` attribute of the element.
For example: https://jsfiddle.net/6ymLo8v4/ (Click "Move Label" button)
Note that this is not supported.

**Comment by gtoroptsev** [comment]
That would be a nice to have feature - to support offset for middleLabel.
***
Anyway, thank you very much for this example, it will help me!

**Comment by anseki** [comment]
:smile:
