### ISSUE TITLE
How to make LeaderLine move with Draggable element?

### ISSUE THREAD

**Issue by SHEELINUNI** [anseki/leader-line#206]
Hi ! I'm new to html and js, now I'm using PlainDraggable and Leaderline creat a page that can let pictures on that page moveable, and there are links between these pictures. I successfully use PlainDraggable to make all pictures on my page be draggable, and I see your document and see some examples show that the lines between the div boxes can be dynamically updated after the div box be moved, I don't know how to do that using Leaderline... I'm a noob to js, so if you could tell me how to do that, I will be thankful to you !

**Comment by SHEELINUNI** [comment]
Oh , seems I find the way do that ! This project is so good and I'm going to use it a lot in the front end of my Flask project ! TY !

**Comment by SHEELINUNI** [comment]
One more thing, I want to put the start point of the leaderline on the specific point on my picture, is this possbile ?

**Comment by anseki** [comment]
Hi @SHEELINUNI, thank you for the comment.
You can indicate a point or area of an element instead of the element via [`pointAnchor`](https://anseki.github.io/leader-line/#pointanchor) or [`areaAnchor`](https://anseki.github.io/leader-line/#areaanchor) attachment.

If you have another question, make new issue for the another topic.

**Comment by RamonRodriguez05** [comment]
How you finally made that ´the lines between the div boxes can be dynamically updated after the div box be moved? Can you write an example please??

**Comment by anseki** [comment]
Hi @RamonRodriguez05, thank you for the comment.
There are the document for the dynamically updating lines and the example:
https://anseki.github.io/leader-line/
