### ISSUE TITLE
How can I create a line with anchor in the middle of another line ?

### ISSUE THREAD

**Issue by guizmoau** [anseki/leader-line#207]
Thanks for the great work and this lib is functionning perfectly so far, I just have a very specific use case that might be able to do from the standard lib functions (without adding specific code in the lib)

Here is my actual line 

let newLine = new LeaderLine(
                    document.getElementById(to), 
                    document.getElementById(from), 
                    {
                        endPlug: 'arrow3',
                        color: 'rgba(173,216,230)',
                        middleLabel: 'Label œ',
                        endPlugSize: 2,
                        dash: {animation: true}
                    }
                );

I want to create another line that would anchor at the middle of my existing line (where the middle label is actually postionned)

I am digging into the documentation to understand how to do it but not sure I found how.
Anyone might be able to help me ?

Thanks.

**Comment by anseki** [comment]
Hi @guizmoau, thank you for the comment.
You can create new line that connects to an anchor at the middle of another line by adding an element as the anchor.

**Comment by guizmoau** [comment]
Hi @anseki , thanks a lot you for your answer.

Can you please give me an example on how to add the anchor ?

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
