### ISSUE TITLE
Why not support 'npm install'?

### ISSUE THREAD

**Issue by wuzhibo0902** [anseki/leader-line#208]
Why not support 'npm install'?

**Comment by anseki** [comment]
Hi @wuzhibo0902, thank you for the comment.
Could you explain that?
Did you try the `npm install`?
Did you see this NPM page? https://www.npmjs.com/package/leader-line
Do you mean that an error occurred?
Could you explain what happen?

**Comment by wuzhibo0902** [comment]
I want use it in my Vue SPA，like this:
1. install dependency
`npm install LeaderLine`
2. import
`import LeaderLine from 'LeaderLine'`

**Comment by wuzhibo0902** [comment]
> You mistook the name of package.
> That's all. 😄

Oh, I get it.
