### ISSUE TITLE
How to configure animation speed?

### ISSUE THREAD

**Issue by pykong** [anseki/leader-line#209]
@anseki thank you very much for creating this gem of JavaScript library, as it helps me to create beautiful architecture diagrams in HTML.

I wonder whether there is a way to configure the speed of an animation.
So I want some dashed to move very fast and others very slowly.
There is only the `timing` option but it only affects the easing not the speed of the "dash flow".

**Comment by anseki** [comment]
Hi @pykong, thank you for the comment.
This may help you: https://jsfiddle.net/g9avc3bq/

**Comment by pykong** [comment]
Thank you so much!
Indeed I have misunderstood the `duration` parameter.
This is exactly what I needed.

**Comment by anseki** [comment]
:smile:
