### ISSUE TITLE
Events for line

### ISSUE THREAD

**Issue by cwtuan** [anseki/leader-line#21]
Is there events such as `hover`, `click` for a line?

I want to show 'delete icon' when hover on a line and remove a line when click on a line.

**Comment by anseki** [comment]
Hi @cwtuan, thank you for the comment.

LeaderLine doesn't support events except events for `mouseHoverAnchor`.
You can use any event via DOM (SVG DOM) and methods such as `addEventListener`, but it is not recommended because of usability for users (a line is usually thin), and also, it is not supported.
It may be better that the user clicks an element that was connected the line or a handle (small element) for line to remove the line.

**Comment by cwtuan** [comment]
Hi @anseki, 
The line is SVG dom? How can I access it?
```
        const line = new LeaderLine(fromSpanDom, toSpanDom, leaderLineOptions);
        console.log('draw line', line);
```
I got something like:

![image](https://user-images.githubusercontent.com/3455798/43753072-84c8bbfa-9a36-11e8-8a93-ce059e6d1c41.png)

**Comment by anseki** [comment]
You can access it via `document.querySelector('.leader-line')`.
As I said, it is not recommended and not supported.

**Comment by cwtuan** [comment]
Could I change the arrow color when mouse hover?

**Comment by anseki** [comment]
Of course you can change the color via [`color`](https://anseki.github.io/leader-line/#options-color) option.

**Comment by cwtuan** [comment]
```
const leaderLineOptions = {
  color: 'yellow',
  hoverStyle: {color:'red'},
};
new LeaderLine(start, end, leaderLineOptions);
```

Could I just set hoverStyle like this? It seems not working.
I would like to change the line to red when mouse hover.

**Comment by cwtuan** [comment]
And could I add `id` property to the svg dom like this?
```
const leaderLineOptions = {
  id: 'myid'
};
new LeaderLine(start, end, leaderLineOptions);
```

**Comment by anseki** [comment]
See document for `hoverStyle`: https://anseki.github.io/leader-line/#hoverstyle

Please make new issue for `data-user`.

**Comment by cwtuan** [comment]
```
const leaderLineOptions = {
  color: 'yellow',
  hoverStyle: {color:'red'},
};
new LeaderLine(start, end, leaderLineOptions);
```

`hoverStyle` seems not working. The line doesn't change to red when mouse hover.

**Comment by anseki** [comment]
The `hoverStyle` is an option for `LeaderLine.mouseHoverAnchor`.
And also, that doesn't change style of the line.

**Comment by anseki** [comment]
I don't know your plan well but this is example that set hover style of the SVG element as a line.
https://jsfiddle.net/zbfokm5L/
Remember, it is not recommended and not supported.

**Comment by cwtuan** [comment]
Thanks for the reply.
