### ISSUE TITLE
A problem in Vue project

### ISSUE THREAD

**Issue by whatthezzzz** [anseki/leader-line#210]
I putleaderline into my Vue project as per documentation, but its not working
![image](https://user-images.githubusercontent.com/52396728/111273100-5c6b6a00-866e-11eb-8568-336656647f24.png)
![image](https://user-images.githubusercontent.com/52396728/111273246-8a50ae80-866e-11eb-836f-4a34469a7737.png)
There was a mistake
![image](https://user-images.githubusercontent.com/52396728/111273312-a05e6f00-866e-11eb-9f01-16b6a4ab8f9f.png)
So how to solve it
thx

**Comment by anseki** [comment]
Hi @whatthezzzz, thank you for the comment.
LeaderLine doesn't have `setLine` method.
Document: https://anseki.github.io/leader-line/
You mistook a repository to ask the question, maybe.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
