### ISSUE TITLE
Bug Report: Crashed in IE, when I create a line use gradient option and call method remove it later.

### ISSUE THREAD

**Issue by wuzhibo0902** [anseki/leader-line#211]
A sample:
`
var line = new LeaderLine(document.getElementById('start'), document.getElementById('end'), {
  startPlugColor: '#A83104',
  endPlugColor: '#C68503',
  gradient: true
});
setTimeout(function() {
  line.remove();
}, 5000);
`

**Comment by anseki** [comment]
Hi @wuzhibo0902, thank you for the comment.
I tried your code, then that worked fine without error.
Could you explain about "crash"? And version of the IE?

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
