### ISSUE TITLE
path grid lines not aligned properly

### ISSUE THREAD

**Issue by mastanmoka** [anseki/leader-line#212]
Hi,
I am using path as grid in leader-line, but the problem here is the lines which are connected short distanced boxes are not created properly(line in red circle). How to resolve this issue?
Thanks in advance.
<img width="263" alt="snap" src="https://user-images.githubusercontent.com/38342703/112425970-12187600-8d5d-11eb-8716-014e1b2b0801.PNG">

**Comment by anseki** [comment]
Hi @mastanmoka, thank you for the comment.
In your image, the line seems to have created properly.
What is a line you want?

**Comment by mastanmoka** [comment]
Thanks for quick reply.
In above image, the line having unnecessary loops. I want a line path without unnecessary steps/loops.

**Comment by anseki** [comment]
That loop is necessary path, and that is correct behavior because LeaderLine tries to keep a measurable size (default length) of grid.
You can adjust the path via options if you need.
For example: https://jsfiddle.net/L9owh7a2/

**Comment by mastanmoka** [comment]
This is what I am looking for..
Thank you @anseki

**Comment by anseki** [comment]
I'm glad if I could help you. :smile: 
Could you close this issue if it was solved?
