### ISSUE TITLE
Dodge other elements with multiple lines

### ISSUE THREAD

**Issue by mastanmoka** [anseki/leader-line#213]
Hi,

I have gone through this example to dodge other elements https://jsfiddle.net/bg7chnvf/ .
This was very good example but in my scenario I have to dodge other elements with more than one line.
So, how to do that?

Thanks in advance.

**Comment by anseki** [comment]
Hi @mastanmoka, thank you for the comment.
You can do that by the same algorithm irrespective of the number of lines.

**Comment by mastanmoka** [comment]
Hi @anseki, if you provide one example with multiple lines, it will good for me.
Can you please provide an example with more no. of lines?

**Comment by anseki** [comment]
Do you mean that the example code didn't help you?
The algorithm in the example can be used for multiple lines.
Did you read the code?

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
