### ISSUE TITLE
can't change animation duration

### ISSUE THREAD

**Issue by kaaaaaaaaaaa** [anseki/leader-line#215]
Hey,

First of all: thank you for this amazing library!

I am trying to draw-animate some lines. The drawing is working but it uses the default duration. There is something wrong with my syntax but I feel like I have tried every possible combination of brackets and commas.

```
   let line = new LeaderLine(start, end, {color: 'red', path: 'arc', size: 2, hide: true});
         $(window).click(()=> {
           line.show('draw', {
                              animOptions: { duration: 10000 }
                            });
         })
```

Can someone spot my mistake?

**Comment by anseki** [comment]
Hi @kaaaaaaaaaaa, thank you for the comment.
You have to write like this:
```js
line.show('draw', {duration: 10000});
```
See document: https://anseki.github.io/leader-line/#show-hide

**Comment by kaaaaaaaaaaa** [comment]
Thank you, that was it!

**Comment by anseki** [comment]
:smile:
