### ISSUE TITLE
Feature request: Corner sockets

### ISSUE THREAD

**Issue by pykong** [anseki/leader-line#216]
@anseki thanks again for creating and maintaining this nice little gem of a library! It really fills a niche for me I was not able to find any other suitable library for.

What is your thought about extending the possible anchor types to the corners of an element?
So in addition to `top`, `bottom`, `left`, and `right`, we would then also have:
- `top-left`
- `top-right`
- `bottom-left`
-  `bottom-right`

My use case for this is to draw a straight connection between two elements that are diagonally positioned in regards to each other.

**Comment by anseki** [comment]
Hi @pykong, thank you for the comment.
You can connect a line to a corner of an element by using [`pointAnchor`](https://anseki.github.io/leader-line/#pointanchor) attachment.

**Comment by pykong** [comment]
@anseki Thank you for your answer. I was not aware of the possibilities of the `pointAnchor`.
Closing.

**Comment by anseki** [comment]
:smile:
