### ISSUE TITLE
How to get selected leader-line when click on line

### ISSUE THREAD

**Issue by rrui0026** [anseki/leader-line#219]
Hi @anseki, Thanks for sharing this library. For example I have draw 10 lines source to destination dynamically, Is there any way to select and get the particular line when click on line?.

**Comment by anseki** [comment]
Hi @rrui0026, thank you for the comment.
This may help you: https://github.com/anseki/leader-line/issues/102#issuecomment-582812108

**Comment by rrui0026** [comment]
Thanks @anseki, This logic helped.

**Comment by anseki** [comment]
:smile:
