### ISSUE TITLE
Custom data to svg dom

### ISSUE THREAD

**Issue by cwtuan** [anseki/leader-line#22]
could I add custom data like data-user property to the svg dom like this?
```
const leaderLineOptions = {
  "data-user": 'my_user_id'
};
new LeaderLine(start, end, leaderLineOptions);
```

**Comment by anseki** [comment]
You can add the user-data property to both an instance of LeaderLine and a SVG element.
See: https://github.com/anseki/leader-line/issues/18

**Comment by cwtuan** [comment]
```
        const line = new LeaderLine(fromSpanDom, toSpanDom, leaderLineOptions);
        line.id = `my_id`;
        line["data-user"]= `my_user`;
```

![image](https://user-images.githubusercontent.com/3455798/43765476-9b7a01f2-9a62-11e8-823d-f5f5c0a6e0c7.png)

Seems not working.

**Comment by anseki** [comment]
As I said, you can access it via `document.querySelector('.leader-line')`.
And it is not recommended and not supported.

**Comment by cwtuan** [comment]
So custom user-data property is not able to attach to svg dom currently?

**Comment by anseki** [comment]
You can add any property to a SVG element.
For example:

```js
const elm = document.querySelector('.leader-line');
elm.id = 'my_id';
elm.setAttribute('data-user', 'my_user');
```

This behavior has no relation with LeaderLine.

**Comment by cwtuan** [comment]
OK, i got it. Thanks

**Comment by anseki** [comment]
:smile:
