### ISSUE TITLE
LeaderLine not showing in angular 10

### ISSUE THREAD

**Issue by jerinic-dusan** [anseki/leader-line#220]
Hi, I'm having issues displaying LeaderLine in angular. 
LeaderLine object is successfully created using new LeaderLine(...) and i can console.log it (https://imgur.com/a/7pJzHuR), but its never shown.
I'm using this article to implement LeaderLine, since its basically only source for implementing it in angular: https://medium.com/ngconf/using-leader-line-to-draw-lines-between-two-angular-components-71a7c316a163

**Comment by anseki** [comment]
Hi @jerinic-dusan, thank you for the comment.
Could you explain more? What is you trying to?
Do you mean that the Angular and this issue are correlated?
If your code has problem, to reproduce that, could you show an example by using e.g. https://jsfiddle.net/ ?

**Comment by jerinic-dusan** [comment]
Hi @anseki, thanks for responding so quick.
Yes, I believe there is a correlation between angular and this issue, since I've only seen 1 working example online and many unanswered stackoverflow questions about similar issues. 
I'll try to get back to you as soon as I can with the example of the issue. 
Though, I'm not sure I'll be able to recreate it in fiddle since its angular feature has been added recently and its in alpha.
I'll play around with it more during following days and I'll send you the https://stackblitz.com/ example of the issue as soon as I can. 
Thanks again!

**Comment by anseki** [comment]
Ok,
If you show an example, we or someone might can help you.

**Comment by jerinic-dusan** [comment]
Hi again,
Since I wasn't able to recreate the bug in a stackblitz project, I'm going to close the issue. 
In my project, line simply wouldn't show. There weren't any errors, while the stackblitz would throw undefined error for LeaderLine object..
This inconsistency between angular, stackblitz and this library is too much for me to handle right now. 
Thanks again for your help, but if you could, it would be greatly appreciated if you posted your own clear instructions in documentation for implementing LeaderLine in angular, for next persons sake.

**Comment by anseki** [comment]
I don't know your app but the library in standard Angular project can work with e.g. Webpack.
However, working with StackBlitz may be not easy because some libraries don't work with StackBlitz. Also, I don't understand StackBlitz well, sorry.
Maybe you had better ask to StackBlitz team or use another library that is better.

**Comment by brickolicious** [comment]
My Angular material (side-nav-container) was overlapping the arrows. Try inspecting the DOM and removing your items, it could be you find the line underneath
