### ISSUE TITLE
print output

### ISSUE THREAD

**Issue by GodSvarog** [anseki/leader-line#221]
how can I center the lines when printing (ctrl+p)?

**html:**
![image](https://user-images.githubusercontent.com/34054918/115350294-47976e80-a1f8-11eb-9408-98e2fe81ad7b.png)

**print:**
![image](https://user-images.githubusercontent.com/34054918/115350375-5e3dc580-a1f8-11eb-803e-5cda30bfb975.png)

**Comment by anseki** [comment]
Hi @GodSvarog, thank you for the comment.
I didn't read your code but it seems that the line was positioned correctly, and the "start" and "end" were moved.
Try to adjust media queries for printing to position those correctly.
Or, you can also print the page as an image.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
