### ISSUE TITLE
Error: Access denied: issue

### ISSUE THREAD

**Issue by Spartan074** [anseki/leader-line#223]
Error: Access denied: {"from":{"namespace":" "}}
I am getting this issue while using leader-line in my project if you have any solution regarding this issue

Thank you in advance

**Comment by anseki** [comment]
Hi @PranavThakur1234, thank you for the comment.
To reproduce that, could you show an example by using e.g. https://jsfiddle.net/ ?

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
