### ISSUE TITLE
Animate on end position update?

### ISSUE THREAD

**Issue by spottedev** [anseki/leader-line#224]
Is it possible to animate when updating the end element?
For example:

<div class="origin"></div>

<ul>
<li class="item-a active">element 1</li>
<li class="item-b">element 2</li>
<li class="item-c">element 3</li>
</ul>

let line = new LeaderLine(document.querySelector('.origin'), LeaderLine.pointAnchor(document.querySelector('.active'))`

So I'd like the "active" class to change and the line to animate accordingly but I've not found out how to do this?
I've tried manually update the position after an element change but it doesn't animate

`line.end = document.querySelector('.item-b')`

Thanks

**Comment by anseki** [comment]
Hi @spottedev, thank you for the comment.
Do you mean that you want a line that follows a moving element?
If so, this example may help you:
https://anseki.github.io/leader-line/#startsocket-endsocket
The line follows an element that is moved by dragging.

**Comment by spottedev** [comment]
Hi, sorry. The code isn't really clear above. Here's what I mean:

https://jsfiddle.net/s8ca0r1o/4/

So given a list of items (like menu), where we click and the active element classname switches to 'active', is there any way to animate it this? So we aren't following the same element... how exactly could this be animated?

Thanks

**Comment by anseki** [comment]
Do you mean that you want to swich element that is joined with animation?

**Comment by anseki** [comment]
Like this?
https://jsfiddle.net/f27acs3z/

**Comment by spottedev** [comment]
Yes, that's exactly what I meant! Perfect! Thanks a lot!

**Comment by anseki** [comment]
:smile:
