### ISSUE TITLE
How do I use LeaderLine in vue

### ISSUE THREAD

**Issue by knoxHuang** [anseki/leader-line#228]
```
const line = new LeaderLine({ start: props.els[0].$el, end: props.els[1].$el });
```

![image](https://user-images.githubusercontent.com/7564028/117101963-dfc15600-ada9-11eb-9f87-2c3ac0dcd7fc.png)

Why does it prompt me ‘A disconnected element was passed.’

Hope to answer my confusion, thx

Maybe we can communicate in Chinese 😄

**Comment by knoxHuang** [comment]
原因是因为我是放置在 showdown 下，被隔离了，导致无法获取到，希望组件能处理是否在 showdown 下的情况

**Comment by anseki** [comment]
Hi @knoxHuang, thank you for the comment.
Sorry, I can't understand Chinese.
