### ISSUE TITLE
[Request] Click listener for line

### ISSUE THREAD

**Issue by ninovanhooff** [anseki/leader-line#23]
Would it be possible to register an event listener for when the line is clicked? I'd like to remove a line when clicked

**Comment by anseki** [comment]
Hi @ninovanhooff, thank you for the comment.
These may help you:
https://github.com/anseki/leader-line/issues/21
https://github.com/anseki/leader-line/issues/10

**Comment by anseki** [comment]
No reply came, and I close this issue.

**Comment by ninovanhooff** [comment]
Sorry for my late reply. For future reference; the linked issues indicate that the functionality I requested is not planned to be implemented, and details the mousde events which are supported atm. A css class may be used to select lines in the dom, but lines do not have an id

**Comment by anseki** [comment]
Yes, the function you requested should not be implemented because of usability for users.

**Comment by iramguir** [comment]
@anseki : Thanks a lot for your effort on this plugin and specially the sharing of it. I did develop a cool feature for one of my apps.

Regarding this particular need of handling click events, I too went through the same read and I think I understand concerns about usability of users.

Assume when usage of a app is officially limited to  large displays (not mobile devices), and line widths are thick. In such case, I think its managable for users to click on lines except when lines are overlapping.

I read that it s possible to attach click event listners indirectly. But lines do not have IDs. In that case if I manage to take control of lines's click listner, is there a way to get ids of elements connected with line at on click of line. Or when line is created is there a way to give an ID.

Sorry about asking for instructions to tweak wonderful piece of code in ways not recomended. :)

**Comment by anseki** [comment]
Hi @iramguir, thank you for your comment.
Sorry, my English is poor.
Do you mean that you want to get a SVG element as specific leader line?

**Comment by AhmedAyachi** [comment]
@iramguir extend the leaderline class and add an element key as :
`this.element=document.body.querySelector(`:scope>svg.leader-line:last-of-type`);`
like this every leaderline you create will has it svg element in it
