### ISSUE TITLE
Short lines renders weird

### ISSUE THREAD

**Issue by MrTilllus** [anseki/leader-line#235]
Hey everithing is super nice but, 
if the distance between the two points is too short the line is becoming weird. 
My line is the following:
`new LeaderLine(startElement, endElement, {
							color: 'red', 
							size: 1,
							endPlug: 'behind',
							path:'grid'
						});`

and it looks like this
![image](https://user-images.githubusercontent.com/47024056/119495783-0f3d0000-bd63-11eb-8e5a-9ec85186b45a.png)
is there a way to avoid this?
Its important to use the path: grid!

**Comment by anseki** [comment]
Hi @MrTilllus, thank you for the comment.
The line seems to have been drawn properly.
This may help you: https://github.com/anseki/leader-line/issues/212

**Comment by MrTilllus** [comment]
Wow thats a fast answer *-*
Thanks now is it perfect 👍

**Comment by anseki** [comment]
:smile:
