### ISSUE TITLE
Timing one line to draw straight after another?

### ISSUE THREAD

**Issue by alexr8** [anseki/leader-line#236]
Hi, firstly just want to say what a useful library this is and it's great you are so active answering questions in here!

Im trying to create a line with a middle point that draws in. So Point A -> Point B -> Point C.

So if I understand correctly i would do this by creating two lines:

Line1: Point A -> Point B
Line2: Point B -> Point C

I want to make it look like a single animation of the line from Point A to Point C via Point B. Is there any way of triggering Line2.show('draw') as soon as Line1.show('draw') is complete? Or would I need to manually set a timer - e.g. if the duration of Line1 draw is 500ms, set a timer and trigger Line2.draw() when the timer finishes?

![image](https://user-images.githubusercontent.com/35040195/119984874-d8145c00-bfb9-11eb-8a36-12246db89cb0.png)

**Comment by alexr8** [comment]
Hi @anseki , thank you so much for the swift response! That third example looks exactly what i'm trying to do - out of interest is there a way you could dynamically get the path values?

I guess the points are relative to the svg context so it wouldn't be possible to just get the p1/p2/p3 position on the page through javascript and convert that to the svg co-ordinates, but wondered if there was an attribute i could access once they are loaded into leader-line (something like line1.startPoint for example).

Alternatively I was thinking i could create two lines still p1 -> p3 and p1 -> p2, and just grab the p3 co-ordinates out the first svg path, keep that line hidden, and then insert the p3 point into the path of the second svg at the end?

**Comment by anseki** [comment]
You can get the path data dynamically by using XML DOM `pathElement.getAttribute('d')` method or SVG DOM `pathElement.getPathData()` method that returns `SVGPathSegment` list.
Note that Chromium removed APIs, then it needs polyfill such as https://github.com/jarek-foksa/path-data-polyfill.js .

You can convert screen (viewport) coordinates to SVG coordinates by using SVG DOM `svgElement.getScreenCTM()` method.
For example:
```js
const point = svgElement.createSVGPoint();
point.x = clientX;
point.y = clientY;
point.matrixTransform(svgElement.getScreenCTM().inverse());
```

**Comment by alexr8** [comment]
Thanks for your help, in the end I've ended up creating my own tailored solution as what I need to do was starting to deviate quite a lot from leader line library, but your help above has been very useful in helping me understand how to draw svg lines properly! Do you have a donation button for your library?

**Comment by anseki** [comment]
Ok. :smile: 
I'm glad if I could help you.
Could you close this issue?
