### ISSUE TITLE
Drawing on the div instead of the web

### ISSUE THREAD

**Issue by Mytheses** [anseki/leader-line#237]
Hi is it possible to provide some guideline for this positioning issue?
![image](https://user-images.githubusercontent.com/62224193/120133029-f79bc680-c1fd-11eb-9c6c-2f77b607a662.png)
![image](https://user-images.githubusercontent.com/62224193/120137697-73e6d780-c207-11eb-9da7-907bb5e70f1d.png)

First image is the line that didnt append onto the div
Second image is the line being appended to the div

The reason I use append is due to I only want the line to show only on that tab.

Here is a snippet of the code

![image](https://user-images.githubusercontent.com/62224193/120137760-97118700-c207-11eb-8e95-34ac3fb64026.png)
![image](https://user-images.githubusercontent.com/62224193/120137779-a1cc1c00-c207-11eb-809d-df724d87e5ad.png)

Thanks in advance for the guide

**Comment by anseki** [comment]
Hi @Mytheses, thank you for the comment.
This may help you: https://github.com/anseki/leader-line/issues/54#issuecomment-500712640

**Comment by Mytheses** [comment]
> Hi @Mytheses, thank you for the comment.
> This may help you: [#54 (comment)](https://github.com/anseki/leader-line/issues/54#issuecomment-500712640)

Hi, apprecite the quick reply.  I found another workaround for this instead of drawing on the div which is I destroy the element and regenerate it only when entering the page.

However when I regenerate it the position seems to be different from the first time.
As attached image the first one is firstly entered
![image](https://user-images.githubusercontent.com/62224193/120153208-05167800-c221-11eb-9d04-31612bccada6.png)
![image](https://user-images.githubusercontent.com/62224193/120153229-0c3d8600-c221-11eb-8041-98a6148922a0.png)
 Second image is after destroy and regenerated

**Comment by anseki** [comment]
Do you mean that the example I indicated didn't help you?
Anyway, I don't know the bug in your code because I can't read your code.
You had better use `show`/`hide ` methods instead of adding and removing a line.

**Comment by Mytheses** [comment]
> Do you mean that the example I indicated didn't help you?
> Anyway, I don't know the bug in your code because I can't read your code.
> You had better use `show`/`hide ` methods instead of adding and removing a line.

Alright. Thanks for the input.

The example you indicated did help but the position is off. So I work on the current workaround

**Comment by anseki** [comment]
I see.
We might be able to find the bug in your code if you show the code by using e.g. https://jsfiddle.net/ .
The timing might be the cause of the problem. You have to make new line in `window.addEventListener('load', () => { ... });` event listener.

**Comment by Mytheses** [comment]
> I see.
> We might be able to find the bug in your code if you show the code by using e.g. https://jsfiddle.net/ .
> The timing might be the cause of the problem. You have to make new line in `window.addEventListener('load', () => { ... });` event listener.

I am using angular ngAfterViewInit to generate the line which I think should works the same as this function you mentioned?

**Comment by anseki** [comment]
We might be able to find the bug in your code if you show the code by using e.g. https://jsfiddle.net/ .

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
