### ISSUE TITLE
Converging lines meeting at the same point

### ISSUE THREAD

**Issue by loperxo** [anseki/leader-line#238]
Is there a way to making multiple lines meeting at the same point to converge

**This is what it looks like at the moment:**
![image](https://user-images.githubusercontent.com/19159215/120289772-8b7e9880-c2b9-11eb-82b4-823c41bd7b2d.png)

**This is what I am hoping to achieve:**
![image](https://user-images.githubusercontent.com/19159215/120290143-f92ac480-c2b9-11eb-960c-03065b201c26.png)

**Comment by anseki** [comment]
Hi @loperxo, thank you for the comment.
You have to add an element for the point.
For example: https://jsfiddle.net/7k49uLse/

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
