### ISSUE TITLE
LeaderLine.captionLabel

### ISSUE THREAD

**Issue by BigEazy85** [anseki/leader-line#239]
Is there a way to swap out the caption label with an image?
![Capture](https://user-images.githubusercontent.com/85199713/120395112-7548fa80-c302-11eb-804b-71eea3ce4dc5.JPG)

**Comment by anseki** [comment]
Hi @BigEazy85, thank you for the comment.
Could you explain more?
Do you mean that you want to convert a LeaderLine element into an image that is another format?
Or, do you mean that you want to add your image on a shown line?

**Comment by BigEazy85** [comment]
Hi @anseki ! I appreciate the support. What I am trying to do is add an image to the middle caption label between my two points (on the line). Rather than the text saying “ROCK” I would like there to be an image of a rock.

**Comment by anseki** [comment]
I see.
LeaderLine now doesn't support adding an image on a line.
Therefore, you have to add an element.

**Comment by anseki** [comment]
For example: https://jsfiddle.net/qcfxrkua/
Note that this is not supported by the library.

**Comment by BigEazy85** [comment]
This is close to what I am trying to achieve. I have multiple Leader Lines that I am trying to add these icons/images to. Here is an example: https://jsfiddle.net/ygop4tqm/1/ 

How would I add the same icon to the "ROCK1"

**Comment by anseki** [comment]
You can do that by the same way.
You have to add an element for each image.

**Comment by BigEazy85** [comment]
Could you please show how I would go about that with my fiddle? I think the issue is that it is only applying to the first .leader-line class. https://jsfiddle.net/zb98hdku/

**Comment by anseki** [comment]
https://jsfiddle.net/3n4rmsqh/
Replace `new LeaderLine(PARAMS...)` with `newLeaderLine(imageUrl, imageWidth, imageHeight, PARAMS)`.

BTW, some parameters in your code are meaningless. See above example that is the same as your line.

**Comment by BigEazy85** [comment]
Thank you so much for all of your help and this awesome tool! I appreciate it big time! Cheers

**Comment by anseki** [comment]
I'm glad if I could help you. :smile: 
Could you close this issue?
