### ISSUE TITLE
leadline does not stick to main endpoint

### ISSUE THREAD

**Issue by mahdan** [anseki/leader-line#24]
Hi,

I have implemented your great leader-line tool. but when i am using it and i suddenly change the position of the connecting endpoint the line doesn't move but instead it draws a new line. please could you help so if the endpoint position moves by and element getting smaller or any other element change size the leadline sticks to the endpoint

Thank you
Mand

**Comment by anseki** [comment]
Hi @mahdan, thank you for the comment.
You can redraw the line for the moved element by using [`position`](https://anseki.github.io/leader-line/#position) method.

**Comment by mahdan** [comment]
HI @anseki 
Thanks for getting back to me so quickly, its really appreciated. i tried that and it didnt work, it still kept the old line. could you send me an example. this is the code im using

$("#btnl1o3b1").click(function(){
    $("#myBtn3 > i").addClass("hidden");
    $("#l2c3").removeClass("hidden");
    $(".card-bot3 > .card-footer").removeClass("hidden");
    $("#l2c3r1").removeClass("hidden");
    $("#l2c3r2").addClass("hidden");
    $("#l2c3r3").addClass("hidden");
    $("#l2c3r4").addClass("hidden");
    $("#l2c3r5").addClass("hidden");
    $("#opt4").removeClass("hidden");
    let start = document.getElementById('opt3'),
    end = document.getElementById('endpoint3'),
    line = new LeaderLine(start, end),
    self = line.setOptions({
      startPlug: 'disc',
      endPlug: 'disc',
      color: '#6192ff',
      position: end
    });
  }); 

Thanks
Mand

**Comment by mahdan** [comment]
Hi @anseki 

I hope you had a great weekend? Thanks you again for your speedy reply and solution. However when I applied it I hit another stumbling block. Please could you help? I have put everything on a google drive and made a little video to see what i mean. all of it can be found here https://drive.google.com/drive/folders/1ARQBs_sXPUoabR17SJj5EQmjIRrYkUp8?usp=sharing

Thank you so much for your support
Mand

**Comment by anseki** [comment]
Do you mean that the example I indicated did not work?
Did you click the "MOVE" button?
Please let me know what happened after you clicked the button.

**Comment by mahdan** [comment]
no your example was perfect but when i used it in my code after a little editing it redrew the line but didn't delete the old svg line, as you will be able to see from the video in the google drive folder i shared

**Comment by anseki** [comment]
I see.
Could you show me an example to reproduce the problem?  By using such as https://jsfiddle.net/.
Because nobody can read code via a video.

**Comment by mahdan** [comment]
thanks for getting back to me so quickly again i really appreciate it. all the code can be found in the bot_builder_prototype folder just click on the html file to launch it and play arounf and all the code can be found in the js folder and html
Thank you

**Comment by anseki** [comment]
Could you reproduce the problem on the https://jsfiddle.net/ please?

**Comment by mahdan** [comment]
@anseki managed to fix it, was a bug in my code. thank you for all your help
