### ISSUE TITLE
Can I export it as Svg after I connected everything 

### ISSUE THREAD

**Issue by ramaUptimeAI** [anseki/leader-line#240]
Hi @anseki,

I want to export it as svg after I connected all of my images/divs. Is there any way to export it as svg?

**Comment by anseki** [comment]
Hi @ramaUptimeAI, thank you for the comment.
You don't have to export it because this is a library to make SVG as a line. That is, it is already SVG.

**Comment by ramaUptimeAI** [comment]
I knew it, but how to download it as a whole group.

**Comment by anseki** [comment]
What is the "group"?
Do you mean that you want to convert the web page (HTML) to a SVG?
If so, you have to embed that via `foreignObject` element.

**Comment by ramaUptimeAI** [comment]
@anseki, The whole group mean, suppose I connected four images using leader-line and now want to add one export button at the top or in the navbar or somewhere, so when that button is clicked I want to download it as svg.

**Comment by anseki** [comment]
What does the group contain?
That is, do you mean that you want to convert the web page (HTML) to a SVG?
It seems that the "group" you said contains elements other than LeaderLine objects too.
In other words, do you mean that you want to get an image like screenshot of a part of the web page?

**Comment by ramaUptimeAI** [comment]
yes, kind of a bit

**Comment by anseki** [comment]
Sorry, my English is poor.
Why is that "kind of a bit"?

**Comment by anseki** [comment]
Yes, you want a screenshot of a web page, not LeaderLine.
You can get a screenshot easily.
Of course, you don't have to convert SVG.

**Comment by liguorain** [comment]
1. The SVGs  are all child nodes of `document. body`. They have no common parents with their "starting point" and "ending point". So if you want to take a screenshot through a `JS` library like `html2canvas`, you can take a screenshot of the whole page. It sounds a bit difficult, but an `iframe` can solve it;

2. These SVGs share some `ref(s)` and the same `style`. According to my observation,`html2canvas` doesn't know how to deal with these public parts, so you need to deal with them yourself. These public parts are provided by the first `SVG` at the end of `document.body`, copy them and add them to each `SVG` node, then add the 'xmlns' attribute to each `SVG`;

Another feasible solution is to use 'webRTC' APIs for screen capture. But you may not like it.

**Comment by anseki** [comment]
Hi @liguorain, thank you for the comment.
The html2canvas is useful and popular tool, but rendering SVG is unfortunately not easy yet for current version of html2canvas as far as I know. Especially styled SVGs such as LeaderLine are not rendered correctly in many cases.
I think that most easy and certain way to get a screenshot is using API of rendering engine such as Blink. If @ramaUptimeAI want to do that automatically, headless browser can be used for that maybe, but I don't know whether @ramaUptimeAI want a function in a web page or not.
Anyway, there are multiple ways to get a screenshot, I hope that @ramaUptimeAI find out best one for @ramaUptimeAI. :smile:

**Comment by ramaUptimeAI** [comment]
@liguorain and @anseki Thank you so much for the information. It will be helpful to find out and learn those things. 

@anseki  I don't need specifically only svg, what I want is to save as an image or something after I drawn and connected the elements. 

As, I mean to say is I want to save the data which I drawn and connected those lines. So, for that I can save it an object I think so.

**Comment by ramaUptimeAI** [comment]
Thanks @anseki . I think with html2canvas will be helpful as you mentioned it. Will check on that.

**Comment by anseki** [comment]
Ok. :smile: 
However, as I said, the html2canvas doesn't work well for you maybe.
html2canvas team may help you if you want it.
So, could you close this issue?
