### ISSUE TITLE
Z-index of the lines?

### ISSUE THREAD

**Issue by Pugsly99** [anseki/leader-line#241]
I'm currently connecting a progression of buttons that also trigger draggable modals, the lines are over everything. I have been playing with all the other elements z-index's and still having no success, is there any solution for the lines being moved all the way to the back? Thank you

**Comment by anseki** [comment]
Hi @Pugsly99, thank you for the comment.
You can specify the `z-index` property.
For example:
```css
.leader-line {
  z-index: 123;
}
```

**Comment by Pugsly99** [comment]
Thank you for your quick response, so when I do effect the z-index with negative values the lines disappear. I will continue to play with it but just wondering if you have a solution.

**Comment by Pugsly99** [comment]
I have found my solution Thank you

**Comment by anseki** [comment]
Ok. :smile: 
So, could you close this issue?

**Comment by Pugsly99** [comment]
so the
 .leader-line {
  z-index: 123;
}
did not work for any negative value as it just disappeared for me but when I did this
.leader-line {
  z-index: 0;
}
and then styled my button or whatever with this
.zIndex {
  position: relative;
  z-index: 10;
}
it worked

**Comment by BigEazy85** [comment]
@Pugsly99 Thanks for the reply! I will give this a try!

**Comment by anseki** [comment]
@Pugsly99, thank you for the information.
So, could you close this issue?
