### ISSUE TITLE
How can I import this library using Webpack with Vue CLI project ?

### ISSUE THREAD

**Issue by lucaslgr** [anseki/leader-line#242]
I've tried this to install as @anseki has said in #8, installing skeleton-loader and creating the webpack.config.js as below:

```js
module.exports = {
  entry: "./src/main.js",
  output: {
    path: __dirname,
    filename: "bundle.js",
  },
  module: {
    rules: [
      {
        test: require("path").resolve(__dirname, "node_modules/leader-line/"),
        use: [
          {
            loader: "skeleton-loader",
            options: {
              procedure: (content) => `${content}export default LeaderLine`,
            },
          },
        ],
      },
    ],
  },
};

```

but I still getting the error below:
![image](https://user-images.githubusercontent.com/30275723/121577329-ca21fa80-c9ff-11eb-9e49-c876c5f8ec1b.png)

**Comment by anseki** [comment]
Hi @lucaslgr, thank you for the comment.
Did Webpack output message before that error you indicated?
In other words, Webpack bundled those modules correctly?

**Comment by lucaslgr** [comment]
Hi @anseki ! Thanks for your attention,
So, the webpack didn't output any message before this erros, but I don't know exactly if those modules was bundled, how cal I check this ?

Do you have some example of to import this library in a Vue CLI project with Webpack ?

**Comment by anseki** [comment]
You can run the Webpack CLI by this command:
```
npx webpack
```
`webpack.config.js` in current directory is loaded.
Before above command, you have to install `webpack-cli` if you don't have.
```
npm install webpack-cli
```

**Comment by lucaslgr** [comment]
@anseki  In a Vue project CLI I can't modify directly the webpack.config.js, I need to set it in a vue.config.js as is shown in this documentation:
https://cli.vuejs.org/guide/webpack.html#modifying-options-of-a-loader, So I'm trying to do that in this way, have a look:

```js
chainWebpack: (config) => {
    // Skeleton Loader
    config.module
      .rule("js")
      .test(/\.js?$/)
        .include.add(require("path").resolve(__dirname, "node_modules/leader-line/"))
      .use("skeleton-loader")
      .loader("skeleton-loader")
      .options(() => {
        return {
          procedure: (content) => `${content}export default LeaderLine`,
        };
      })
      .end();
  },
```

But I've got these errors below:

```js

 ERROR  TypeError: config.module.rule(...).test(...).include.add(...).loader is not a function
TypeError: config.module.rule(...).test(...).include.add(...).loader is not a function

```

**Comment by anseki** [comment]
You seem to have misunderstood maybe.
You can modify directly the Webpack config (with a few exceptions) by `configureWebpack` option.
https://cli.vuejs.org/guide/webpack.html
That error is usually made by a problem about `require`. Then, it may be solved by using simple `configureWebpack` option.

**Comment by lucaslgr** [comment]
I'm sorry @anseki I'm a beginner with use configuration of webpack, thanks for your patience with me.
What do you recommend me is set in file vue.config.js this code below:

```js
// vue.config.js
module.exports = {
  configureWebpack: {
    module: {
    rules: [
      {
        test: require("path").resolve(__dirname, "node_modules/leader-line/"),
        use: [
          {
            loader: "skeleton-loader",
            options: {
              procedure: (content) => `${content}export default LeaderLine`,
            },
          },
        ],
      },
    ],
  },
  }
}

```

I don't understand well

**Comment by anseki** [comment]
Try this:
```js
  module: {
    rules: [
      {
        test: require('path').resolve(__dirname, 'node_modules/leader-line/'),
        use: [{
          loader: 'skeleton-loader',
          options: {procedure: content => `${content}export default LeaderLine`}
        }]
      }
    ]
  }
```

**Comment by anseki** [comment]
:smile:
