### ISSUE TITLE
Leader-Line Implementation in Webflow

### ISSUE THREAD

**Issue by kiwikreativ** [anseki/leader-line#243]
Hi @anseki 

I really would like to implimate you're "leader-line" code into Webflow.

i  create two divs with the ID start & end.
then I create a "embed code" with the following code:

<script>
new LeaderLine(
  document.getElementById('start'),
  document.getElementById('end')
);
</script>

after this, I add the .js code at the end of the <head> tag:

<script src="https://mapme.shop/leader-line.min.js"></script>

But there are no adding lines in my Project.
Can you help me out?

Thanks my friend!

**Comment by anseki** [comment]
Hi @kiwikreativ, thank you for the comment.
Could you explain about result?
For example, an error message was shown in console?
Also, what is "the end of the tag"?

**Comment by kiwikreativ** [comment]
Hey thanks for this fast reply.

Webflow didn't give me Error Messages about embed JavaScript codes.


Here´s my HTML Code:
Maybe you could find the Problem! 

<body>
  <div class="section">
    <div class="div-block">
      <div class="div-block-8 w-clearfix">
        <div id="bg" class="bg"></div>
        <div class="div-block-13">
          <div id="mydiv" class="icon-coffee-wrapper">
            <div id="ring" class="icontext">Dein Text...</div>
            <div id="mydivheader" data-w-id="f1f4033c-d4bc-3d3e-3abf-f38f4d36173a" class="icon-coffee-wrapperdrag"></div>
            <div class="line"></div>
          </div>
        </div>
        <div class="frame"></div>
        <div class="typo">
          <h1 id="p1" class="headline">Deine Story</h1>
        </div>
      </div>
    </div>
    <div class="icon_container">
      <div class="icon_palette_wrapper">
        <div class="div-block-12">
          <h1 class="heading-2">Wähle dein Wunschicon!</h1>
        </div>
        <div class="div-block-11"><img src="images/verlobungsring.svg" loading="lazy" height="" data-w-id="688c95c0-4b68-c3e0-b492-b96904634cd8" alt="" class="image-2 coffee"><img src="images/blume-1.svg" loading="lazy" height="" alt=""><img src="images/diamant.svg" loading="lazy" height="" alt=""></div>
      </div>
      <div class="icon-edit-window">
        <div class="div-block-17">
          <h3 class="heading-4">Ändere dein Icon</h3>
        </div>
        <div class="icon-edit-wrapper">
          <div class="div-block-14"></div>
          <div class="div-block-15">
            <h3 class="heading-3">Verlobungsring</h3>
          </div>
        </div>
        <div class="div-block-16">
          <h1 class="infotext_headline black">Ändere hier deinen Text</h1>
          <div class="html-embed-2 w-embed">
            <form id="email-form" name="email-form" data-name="Email Form"><input type="text" class="text-field w-input" maxlength="18" name="headline" data-name="headline" placeholder="Dein Text..." id="ring" required="" onchange="ringfunction(this.value)"></form>
          </div>
        </div>
      </div>
    </div>
    <div class="div-block-2">
      <div class="div-block-4">
        <div class="start-headline">
          <h1 class="heading">Erstelle deine<br>Wunschkarte</h1>
        </div>
        <div class="map-choose">
          <div data-w-id="83413914-d177-c11b-acc7-7b307287bc2f" class="div-block-10">
            <div class="c-icon welt"></div>
            <p class="paragraph">Weltkarte</p>
          </div>
          <div class="div-block-10">
            <div class="c-icon land"></div>
            <p class="paragraph">Landkarte</p>
          </div>
          <div class="div-block-10">
            <div class="c-icon city"></div>
            <p class="paragraph">Stadtkarte</p>
          </div>
        </div>
        <div class="worldmap-wrapper">
          <h1 class="infotext_headline">Dein Land, deine Geschichte</h1>
          <div class="w-embed">
            <form id="form" name="wf-form-form" data-name="form" method="post"><select id="dropdown" name="field" class="select-field w-select" onchange="myfunction(this.value)">
                <option value="">Wähle dein Land...</option>
                <option value="https://uploads-ssl.webflow.com/604f9b5285ee3ef899b2103b/60c1361940e08a852127014f_usa.svg">USA</option>
                <option value="https://uploads-ssl.webflow.com/604f9b5285ee3ef899b2103b/60c136190ca9340363a0e3f9_australia.svg">Australien</option>
              </select></form>
          </div>
          <h1 class="infotext_headline">Schreibe deine Headline</h1>
          <div class="w-embed">
            <form id="email-form" name="email-form" data-name="Email Form"><input type="text" class="text-field w-input" maxlength="18" name="headline" data-name="headline" placeholder="Deine Headline..." id="p1" required="" onchange="headlinefunction(this.value)"></form>
          </div>
          <h1 class="infotext_headline">Dein Wahrzeichen</h1>
          <a data-w-id="a127c1d1-9181-4ec3-86d5-0969daf47640" href="#" class="button w-button">Icon einfügen</a>
        </div>
      </div>
    </div>
  </div>
  <div>
    <div class="div-block-18">
      <div class="w-embed w-script">
        <script>
script src="https://www.dropbox.com/s/23it41aivex5c27/leader-line.min.js?dl=0";
new LeaderLine(startElement, endElement, {color: 'red', size: 8});
var startElement = document.getElementById('element-1'), endElement = document.getElementById('element-2');
</script>
      </div>
      <div class="div-block-22">
        <div id="element-1" class="element-1"></div>
        <div id="element-2" class="element-2"></div>
      </div>
    </div>
  </div>
  <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=604f9b5285ee3ef899b2103b" type="text/javascript" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <script src="js/webflow.js" type="text/javascript"></script>
  
  <script>
function myfunction(x) 
{
    document.getElementById("bg").style.backgroundImage = "url('"+x+"')";
    document.getElementById("lbg").style.backgroundImage = x;
}
function headlinefunction(x) 
{
    document.getElementById("p1").innerHTML = x;
    document.getElementById("lp").innerHTML = x;
}
function ringfunction(x) 
{
    document.getElementById("ring").innerHTML = x;
    document.getElementById("icotxt").innerHTML = x;
}
// Make the DIV element draggable:
dragElement(document.getElementById("mydiv"));
function dragElement(elmnt) {
  var pos1 = 0, pos2 = 0, pos3 = 0, pos4 = 0;
  if (document.getElementById(elmnt.id + "header")) {
    // if present, the header is where you move the DIV from:
    document.getElementById(elmnt.id + "header").onmousedown = dragMouseDown;
  } else {
    // otherwise, move the DIV from anywhere inside the DIV:
    elmnt.onmousedown = dragMouseDown;
  }
  function dragMouseDown(e) {
    e = e || window.event;
    e.preventDefault();
    // get the mouse cursor position at startup:
    pos3 = e.clientX;
    pos4 = e.clientY;
    document.onmouseup = closeDragElement;
    // call a function whenever the cursor moves:
    document.onmousemove = elementDrag;
  }
  function elementDrag(e) {
    e = e || window.event;
    e.preventDefault();
    // calculate the new cursor position:
    pos1 = pos3 - e.clientX;
    pos2 = pos4 - e.clientY;
    pos3 = e.clientX;
    pos4 = e.clientY;
    // set the element's new position:
    elmnt.style.top = (elmnt.offsetTop - pos2) + "px";
    elmnt.style.left = (elmnt.offsetLeft - pos1) + "px";
  }
  function closeDragElement() {
    // stop moving when mouse button is released:
    document.onmouseup = null;
    document.onmousemove = null;
  }
}
</script>
</body>

**Comment by kiwikreativ** [comment]
Hey! Thanks for the fast reply.

Here is the Domain of the Site:
https://leader-lines.webflow.io

And Heres the Code:

<body>
  <div class="div-block">
    <div class="w-embed w-script">
      <script>
new LeaderLine(
  document.getElementById('element-1'),
  document.getElementById('element-2')
);
</script>
    </div>
    <div id="element-1" class="start"></div>
    <div id="element-2" class="end"></div>
  </div>
  <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=60c34c97650fabbc5ebf6d0a" type="text/javascript" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <script src="js/webflow.js" type="text/javascript"></script>
  
</body>

**Comment by anseki** [comment]
Regardless of the LeaderLine, you can't get element that doesn't exist. Your code tries to get elements that don't exist yet.
That is, there is the code `document.getElementById('element-1')` before `<div id="element-1">` (this is not loaded yet).
Move the code to after the elements, or write this code instead:
```js
addEventListener('load', () => {
  new LeaderLine(document.getElementById('element-1'),
    document.getElementById('element-2'));
});
```

**Comment by kiwikreativ** [comment]
@anseki oh man!!! Your awesome. Now it works. 
Thanks you so much!

**Comment by anseki** [comment]
:smile:
