### ISSUE TITLE
From a box + click + add new square + conection line

### ISSUE THREAD

**Issue by LeninZapata** [anseki/leader-line#244]
Hello, you can add an example like [funnelytics.io](https://funnelytics.io) I would like to make a plugin where you can add an element and connect it with another but I would like to know if your tool can do it.

It could be something simple, the customization would come from my part but I need a new painting to be created and joined with lines, an example of adding element (a div) based on arrows to be able to add options within each div

**Comment by anseki** [comment]
Hi @LeninZapata, thank you for the comment.
Sorry, my English is poor.
Do you mean that you want to make something like funnelytics.io?
What is my tool?
You can add an element and connect it with another by using the library.
Also, this is duplicated: https://github.com/anseki/plain-draggable/issues/91
Did you mistake that? Should that issue be removed?

**Comment by LeninZapata** [comment]
```
Do you mean that you want to make something like funnelytics.io?
What is my tool?
```
Yes, your library looks very versatile and it seems that it is the most complete but I cannot see usable examples. I would like you to make examples but usable. One of them would like a mini funnelytics.io to be simulated
![image](https://user-images.githubusercontent.com/42600954/121794319-bf689080-cbcc-11eb-81dd-3615103f5047.png)
![image](https://user-images.githubusercontent.com/42600954/121794325-cbece900-cbcc-11eb-9d17-6b85fd36fdeb.png)

- https://cherub7.github.io/Story-graph/pages/story_builder.html
- https://www.elated.com/res/File/articles/development/javascript/jquery/drag-and-drop-with-jquery-your-essential-guide/draggable-options.html

I would like you to make an example of type funnelytics.io to be able to re-edit it, I could give credits to your library in my plugin but if you want to have a guide example with your library that as I mentioned above is the most complete
https://www.youtube.com/watch?v=CHHEzNYOUbI

I would like you to give me your comments

**Comment by anseki** [comment]
Do you mean that you want an example that draws lines by mouse operations?
If so, this may help you: https://github.com/anseki/leader-line/issues/102

**Comment by LeninZapata** [comment]
I think that's what I was looking for. Thank you. I'll do some tests. If I have any questions I will not hesitate to ask you, thank you very much.

**Comment by anseki** [comment]
:smile: 
This also may help you: https://github.com/anseki/leader-line/issues/225#issuecomment-835641812
So, could you close this issue?
