### ISSUE TITLE
replace middle label with an svg

### ISSUE THREAD

**Issue by separse** [anseki/leader-line#245]
how can I replace a middle label in a leader line with an SVG which has a function as a button?! 
I tried appendChild but it does not work out.
I use the leader line in an angular project and I put it in ngAfterViewInit.

**Comment by anseki** [comment]
Hi @separse, thank you for the comment.
Could you explain about the "it does not work out" you said? (e.g. any error?)
Or, this may help you: https://github.com/anseki/leader-line/issues/239

**Comment by separse** [comment]
Hi @anseki, Thank you for answering. I read #239 and it was helpful but I did not achieve what was I need.

![leaderline-middle-label](https://user-images.githubusercontent.com/60772175/122174629-1d7cc880-ce98-11eb-9aed-12fa79ec9bb3.png)

 Now I can replace the middle label with what I want like a Rock, but I need these Rock sticks to the line not going around, and also because I use draggable lists and lines also move with the lists but this Rock does not move with the line.

![leaderline-middle-label - 2](https://user-images.githubusercontent.com/60772175/122175352-d93df800-ce98-11eb-97c5-4217d15890ec.png)

Maybe it'll help that I show What I need. I need these relation lines which shows in below.

![leaderline-middle-label - 3](https://user-images.githubusercontent.com/60772175/122176294-aea06f00-ce99-11eb-9a3b-72999777fdda.png)

**Comment by anseki** [comment]
Sorry, my English is poor.
What is the "line not going around"?

**Comment by separse** [comment]
My English is not good either :))
I mean I want the Rock to stick to the line and have no space between the line and the Rock like last photo which i sent to you.

**Comment by anseki** [comment]
What is different about the position you want and the position of middle label?
Did you see this? : https://github.com/anseki/leader-line/issues/239#issuecomment-852692825

**Comment by separse** [comment]
yes, I see, when lines move, a gap occurred between a line and the middle label of it.

**Comment by anseki** [comment]
Do you mean that you want the image that is re-positioned automatically when the elements are moved?

**Comment by anseki** [comment]
For example: https://jsfiddle.net/reo6m1vc/

**Comment by separse** [comment]
Exactly! tank you so much.
I just have another question for you. when I use multiple lines between items, like this picture, I could only click on the first line and the other line which is behind the environment of the first line is not clickable.

![Uploading leaderline-middle-label - 4.png…]()

**Comment by anseki** [comment]
:smile: 
Could you make new issue for another topic after closing this issue?

**Comment by separse** [comment]
Sure, thank you so much again  :)
