### ISSUE TITLE
Failed to execute 'removeChild' on 'Node' error on calling line.remove()

### ISSUE THREAD

**Issue by thebuggycoder** [anseki/leader-line#246]
Hi there,
First of all thanks for this awesome library. There's one small issue I'm currently getting this error when calling `line.remove()`.
I'm saving the created line objects in an array called `activeConnectors` and I have appended the generated SVG elements to a custom element with -

```javascript
document.getElementById('connectors').appendChild(document.querySelector('.leader-line'));
```
And later when removing the lines I'm calling a `forEach` loop -
```javascript
activeConnectors.forEach(connector => {
  connector.remove();
}
```
But I keep getting the below error - 
```
Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`
```

Thanks in advance for your help.

**Comment by anseki** [comment]
Hi @thebuggycoder, thank you for the comment.
The `.appendChild(document.querySelector('.leader-line'))` is a bad knowhow. Then you should not use that if you don't understand that.
The `remove` method should work fine by removing the `.appendChild(document.querySelector('.leader-line'))`.

**Comment by thebuggycoder** [comment]
Thanks for the quick response @anseki .
Unfortunately, I kind of need to use the `appendChild` method.
I'm drawing the leader lines between dynamically loaded components in an angular application so the generated SVGs need to be inside a custom element instead of the page `body`.

I haven't tried it yet but would it work if I call the `Node.removeChild()` method on parent element where the nodes are appended and just remove the SVG directly?

Or does `line.remove()` have any additional steps?

**Comment by anseki** [comment]
Try this example: https://github.com/anseki/leader-line/issues/54#issuecomment-521137273
The example removes lines after 3secs.
Note that these are not supported. These may make your app code become wrong because this is solving the bad knowhow by using another bad knowhow.

**Comment by thebuggycoder** [comment]
Thanks @anseki , I'll give this a try. Closing the issue now.

**Comment by anseki** [comment]
:smile:
