### ISSUE TITLE
click on lines

### ISSUE THREAD

**Issue by separse** [anseki/leader-line#247]
When I use multiple lines between items, like this picture, I could only click on the first line and the other line which is behind the environment of the first line is not clickable.
![leaderline-middle-label - 4](https://user-images.githubusercontent.com/60772175/122225347-3a31f400-ceca-11eb-83c0-347ee1f3de27.png)

**Comment by anseki** [comment]
Hi @separse, thank you for the comment.
What does “click” mean?
That is, for usability, LeaderLine elements should be unclickable.
You might have customized the library. Of course I don't know that.
Or, do you mean that you want to select the element by clicking in DevTools of browser?

**Comment by separse** [comment]
no I mean when I click on a line I want to do a function like open a popup. now I can do this for the right line in the picture but the second line actually is placed behind the whole environment of the first line so it is not possible to click on it.

**Comment by anseki** [comment]
If you can't click the line, the library is working correctly.
For usability, LeaderLine elements should be unclickable.
Therefore, if you can click the line, the library is broken, or your usage may be wrong.
Or, you might have customized the library. Of course I don't know that.
Could you explain the customizing? Or could you show me an example by using e.g. https://jsfiddle.net/ to reproduce that?

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
