### ISSUE TITLE
Can you define where in the DOM the line is added?

### ISSUE THREAD

**Issue by Turbotailz** [anseki/leader-line#25]
I'm having some issues with z-index because the lines are added to the `body` element and I have a `div` that needs to pop up over *everything* on the page. I can't get it to work as the lines will always be on top. I could hide the lines but the `div` needs to be semi-transparent and I'd prefer if they could appear through the background.

If I could append the lines to a certain element that would solve the problem but I can't seem to find anywhere to do this.

**Comment by anseki** [comment]
Hi @Turbotailz, thank you for the comment.
You can get a SVG element as the line by `document.querySelector('.leader-line')`.
Note that it is not supported.
See: https://github.com/anseki/leader-line/issues/13

**Comment by Turbotailz** [comment]
I'd like to suggest adding an option where you can define which element the lines are appended to.

In the meantime I have solved this with jQuery: 

```js
let lines = $('.leader-line');
$('.lines-container').append(lines);
```

**Comment by anseki** [comment]
Thank you for the suggestion.
However that option should not be added.
See: https://github.com/anseki/leader-line/issues/13#issuecomment-394721338
Also, you can move the element easily if you want, and jQuery is not required as I said.
For example:
```js
document.querySelector('.lines-container').appendChild(document.querySelector('.leader-line'));
```

**Comment by michael-ecb** [comment]
When you do it and like me are in react, when you call line.remove() there an error:
Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

**Comment by anseki** [comment]
Hi @michael-ecb, thank you for the comment.
Please make a new issue for the different topic. And explain details for that such as how to reproduce the problem.

**Comment by jivenhui** [comment]
Has this been resolved yet?

**Comment by anseki** [comment]
Hi @jivenhui, thank you for the comment.
Yes, this issue was already closed.
You can make new issue if you want.
