### ISSUE TITLE
Is there a way to get a reference to a specific leader line on a page?

### ISSUE THREAD

**Issue by RuNpiXelruN** [anseki/leader-line#250]
HI @anseki, firstly thank you for your amazing libraries!

Second, is there a method that can return either all, or a specific leader-line on a page??
Use case, i'm using Vue. I have multiple lists of elements, each with their own leader-line to a parent. I want to be able to get a reference to a specific leader-line when I move one of these elements so that I can update the leader-line position. 

Is there also a way to get all leader-line's on a page??

**Comment by anseki** [comment]
Hi @RuNpiXelruN, thank you for the comment.
The library has no method that gets all lines.
However, you can get SVG element by using DOM method if you really want.
For example:
```js
line = document.querySelector('.leader-line');
```
Note that this is not supported by library, and it is not recommended.

**Comment by RuNpiXelruN** [comment]
Thanks for reply @anseki . 
My use case is that I am building a flow chart/marketing automation tool. As an example, an element may be dragged into a part of the flow chart, the leader-line to it's parent is drawn. The page may be filled with these elements with leader-lines drawn to their parent, and also to their children below. A user may decide to click and drag an element into the same row as their parent. This now requires me to find it's leader-lines, remove them, and re-draw new ones to the elements new parent and children.
Does that make sense?
I guess I was just hoping that there was a unique identifier on each leader-line that I could store as part of an element's attributes to make looking them up easier. I do notice that each leader-line has a unique id similar to `leader-line-1-line-path` in their `defs`...so for now I'm storing that id and looking up the associated leader-line by doing 
`document.getElementById('leader-line-1-line-path').parentElement.parentElement`
it at least gets me the leader-line and allows me to remove it or call position() on it

**Comment by anseki** [comment]
Sorry, my English is poor.
Do you mean that you want to get each SVG element of added lines?
If so, you can do that. For example:
```js
const line1 = new LeaderLine(start1, end1),
  svg1 = document.querySelector('body>.leader-line:last-child'),
  line2 = new LeaderLine(start2, end2),
  svg2 = document.querySelector('body>.leader-line:last-child');
```
Note that this is not supported by library, and it is not recommended. Therefore, of course ID of SVG elements too.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
