### ISSUE TITLE
Impossibility to select a single line

### ISSUE THREAD

**Issue by TheWiseMan** [anseki/leader-line#251]
I have encountered a problem while using you library (which is amazing by the way), you should consider adding the possibility for each line to be marked in a distinct way...
For example, we should be able to set an attribute or a class (or an id) at the creation of the line.
Thank your for your effort.

**Comment by anseki** [comment]
Hi @TheWiseMan, thank you for the comment.
Sorry, could you explain more?

**Comment by TheWiseMan** [comment]
Maybe you should consider adding a method "setAttribute" which allows the user to add a custom attribute to a single class (for later use of selectors).
I had a tight schedule so I used a workaround of storing all leaderlines in dictionary... But it makes my code much less clean 😅.

**Comment by TheWiseMan** [comment]
Even though, once again, I really like your library !

**Comment by anseki** [comment]
Thank you for your explanation.
Sorry, my English is poor.
Do you mean that you want to get each SVG element of added lines?
If so, you can do that. For example:
```js
const line1 = new LeaderLine(start1, end1),
  svg1 = document.querySelector('body>.leader-line:last-child'),
  line2 = new LeaderLine(start2, end2),
  svg2 = document.querySelector('body>.leader-line:last-child');
```
Note that this is not supported by library, and it is not recommended.

**Comment by TheWiseMan** [comment]
Hmmm... No, rather like a way to access the .position method directly from the svg object ?

**Comment by anseki** [comment]
All instance methods and properties are accessed via the instance itself. You don't have to access to the SVG element.
For example:
```js
const line1 = new LeaderLine(start1, end1);
line1.position();
```
This is specification of ECMAScript (JavaScript).
See document: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes

**Comment by TheWiseMan** [comment]
Yes, but when generating the leaderlines programatically, I am forced to store all of the instances, and to modify all of them individually (with filters in some cases).
Anyways, I think I'll stick with my way of doing it now, thanks for your help !

**Comment by anseki** [comment]
I see. I didn't see your code but it seems that your app is rare case.
In almost cases, instance method is called by using the instance. This is normal usage for ECMAScript.
I'm glad if I could help you. :smile:
