### ISSUE TITLE
Empty Leaderline object issue

### ISSUE THREAD

**Issue by antoninCabane** [anseki/leader-line#253]
Hello everyone,

I am using Leaderline as part of a link editor between simulation model inputs and outputs.
In order:
- I create a Leaderline variable ( new Leaderline(..))
`const currentConnectorObject = new LeaderLine(
    LeaderLine.pointAnchor(SVGOutputSlotContainer,
        {
            x: '50%',
            y: '50%'
        }
    ),
    LeaderLine.pointAnchor(SVGInputSlotContainer,
        {
            x: '50%',
            y: '50%'
        }
    ),
    {
        startSocket: 'right', 
        endSocket: 'left',
        startPlug: 'disc',
        startPlugColor: 'rgb(0,128,0)',
        startPlugSize: 2,
        endPlug: 'disc',
        endPlugColor: 'rgb(0,128,0)',
        endPlugSize: 2,
    }
)`

- I move the DOM element into a wrapper
`var currentConnectorElement = document.querySelector('body>.leader-line:last-of-type');
            
// déplacement du connecteur pour contrer les contraintes de LeaderLine
document.getElementById("LeaderLineWrapper").appendChild(currentConnectorElement)

currentConnectorElement = document.getElementById("LeaderLineWrapper").lastChild

var currentConnectorElement = {
     currentConnectorObject: currentConnectorObject, 
     currentConnectorElement: currentConnectorElement
}`

- I place the LeaderLine variable in a VueJS 3 data object
`currentLink.connectorElement = currentConnectorCreated.currentConnectorElement
 currentLink.connectorObject = currentConnectorCreated.currentConnectorObject`

I exit the function performing these actions and the Leaderline variable becomes an empty object.

From
`1: LLink
actionButton: circle
connectorElement: svg.leader-line
connectorObject: Ye {_id: 1} <---------
`

to

![image](https://user-images.githubusercontent.com/48324436/130820371-fc1cf992-9b74-43ad-854a-f7537b6a064b.png)

I've been trying to understand for two days why the Leaderline object disappears but I can't find it.

It's very difficult to explain the entire process but what are the reasons that can transform a Leaderline object into an empty object ? remove action ? auto destruction :'( ? 

Sorry if it is not clear but English is not my language.

Thanks in advance for yours feedbacks,
Antonin

**Comment by anseki** [comment]
Hi @antoninCabane, thank you for the comment.
The `.appendChild(document.querySelector('body>.leader-line:last-of-type'))` is a bad knowhow. Then you should not use that if you don't understand that because that is not supported by the library.
The `remove` method should work fine by removing the `.appendChild(...)`.

**Comment by antoninCabane** [comment]
Thank you for your answer and sorry for the time of my answer,

This move of the Leaderline element is necessary in my project because the lines must be integrated in a scrallable canvas and 
smaller than the original container.

The function I presented is called in two different conditions:
 - At the creation of the links in a modal interface. At this moment, the DOM elements are VISIBLE and the link between these two 
two elements is actually created (Creation of the Leaderline object, moving it to the wrapper and storing it in my Javascript tree)
Even if the library does not support this mechanism of displacement, in this case, everything works (the .position() function for example).

 - When loading a project. At this moment, I recreate all the Leaderline links between elements which are not visible in the interface but 
the DOM elements are present in the HTML tree. So, I have the impression that when I create a Leaderline object between two DOM elements in "display: none",
the Leaderline object is empty, is this normal?

Another thought, I moved my Leaderline elements into a container to avoid their overflow in the modal :
![image](https://user-images.githubusercontent.com/48324436/132213219-3176cd84-2fa9-42de-8f23-cf1fa9ab6447.png)

do you see another solution to do this?

Thanks in advance,
Antonin CABANE

**Comment by anseki** [comment]
Sorry, my English is poor.
Do you mean that the line is not drawn correctly between elements that have `display: none`?
If so, as the [document](https://anseki.github.io/leader-line/#start-end) says, an element that has bounding-box is accepted. An element that has `display: none` doesn't have bounding-box because it is not rendered.

**Comment by antoninCabane** [comment]
Thanks for all your feedback, I found where the problem came from and changed the logic to solve it.

Indeed, it is written in the doc that the beginning and end elements of a Leaderline link must be
rendered in the interface.
You will notice that it is possible to create a Leaderline link between two visible elements, line.hide() the Leaderline link,
elem.style.display("none") one of the two elements (or both) and then make them visible later and redisplay the Leaderline svg element, it works.

My problem came from the fact that the start/end DOM elements of the Leaderline links were dynamic according to the two simulation models currently selected. This dynamism was done with the Vue JS 3 renderer, so that the DOM elements used as start and end of Leaderline disappeared... and then reappeared when the link creation modal was displayed. Leaderline seems to destroy a link when one of the two elements of start or end disappeared.

Sorry for the inconvenience, your library is really nice to use, thanks you a lot !
Antonin.

**Comment by anseki** [comment]
I'm glad if I could help you. :smile: 
Could you close this issue if it was solved?
