### ISSUE TITLE
Specify start and end as pictures

### ISSUE THREAD

**Issue by 13160671810** [anseki/leader-line#254]
Can the start and end be specified in the <image> tag, or can only be specified in the <div><span> tag, now I want to point to the image to appear this effect.New LeaderLine(startElement, endElement) In this line-out method, can startElement and endElement specify images
![image](https://user-images.githubusercontent.com/37618640/131607641-0d760989-a70b-492c-9439-239ba71cf9fe.png)

**Comment by anseki** [comment]
Hi @13160671810, thank you for the comment.
Was the issue already solved?
