### ISSUE TITLE
Is it possible to have the leader line avoid or go around html elements on the dom?

### ISSUE THREAD

**Issue by JBenzie** [anseki/leader-line#255]
Basically, I have an html table which consists of x number of cells that have been rounded to look like dots. I currently have leader-line implemented so that the user can draw a line connecting two dots. I'd like to have the leader line go in between the cells and avoid overlapping or going behind the other dots. I haven't had any success, and I suspect that it's not possible, but figured I'd ask!

In the attached screenshot, the dot with "84ms" is connected to the one with "126ms". Essentially, I'd like the line to go between the dots instead of behind the one with "17".

![image](https://user-images.githubusercontent.com/8457770/132568476-ce51634e-d597-4640-aeb7-fee76e2090cf.png)

Thanks in advance!
jerry

**Comment by anseki** [comment]
Hi @JBenzie, thank you for the comment.
Sorry, do you mean that you want to move the line to foreground?
If so, you can specify the `z-index` property.
For example:
```css
.leader-line {
  z-index: 99;
}
```

**Comment by JBenzie** [comment]
I actually set the z-index to make the line go behind the dots. What I'm looking to do is have the line "avoid" the dots by going in between them instead of behind or overlapping them. Essentially, the line would traverse the empty space between the dots. But I'm not sure if it's possible to make the line aware of the dots, if that makes sense..

Thanks!

**Comment by anseki** [comment]
Sorry, my English is poor.
Do you mean that you want to change the path of lines?
For example:
https://jsfiddle.net/5t4nsq7v/
Or, if you want to change those dynamically, this may help you: https://github.com/anseki/leader-line/issues/52#issuecomment-487812774

**Comment by JBenzie** [comment]
Yes, exactly. I want the path of the line to dodge other elements (the dots in this scenario). I'll go through the comment you've provided as I think that may be what I'm looking for. Thanks for your help!

**Comment by anseki** [comment]
:smile: 
Could you close this issue if it was solved?

**Comment by JBenzie** [comment]
Sure, I haven't tried this implementation yet, but I feel like it's what I'm looking for.
Thanks again!

**Comment by AlexSkrypnyk** [comment]
@anseki 
Thank you for this amazing project!

Avoiding elements is not a rare case. Looking at the fiddles you provided, it looks quite complicated to define all those behaviours. It would be awesome if we could just pass an array of DOM objects that should be avoided and the plugin would draw a line around them.

Could you please consider re-opening this issue?

**Comment by anseki** [comment]
Hi @AlexSkrypnyk, thank you for the comment.
This issue doesn't have to be re-opened because it was already solved. I will consider adding an option to change the path of line instead if many requests come. It seems a rare case now.
However, the fiddle that I provided is very simple, it has only 13 lines and only specifying options to constructor.
