### ISSUE TITLE
May it be possible to set the minimal grid length property as parameter?

### ISSUE THREAD

**Issue by ramferan** [anseki/leader-line#256]
First of all congratulations for these amaizing libraries Leader-line & Plain-draggable, I found them very usefull.

I'm implementing both of them in a drawing editor and I would need to set a lower grid lenght than default value, but it's not seteable as parameter. I've resolved by hardcoding MIN_GRID_LEN parameter within the code but it would be nice to could do it as an object option.

This is the result with actual value of grid length (setted to 30)

![image](https://user-images.githubusercontent.com/6375066/132673950-71f53478-0d4d-45b7-b3fb-a0b3a08e9874.png)

And this is the result changing the value to 0:
![image](https://user-images.githubusercontent.com/6375066/132675603-a24113e8-e893-48d9-a059-fc0e06c00ea5.png)

**Comment by anseki** [comment]
Hi @ramferan, thank you for the comment.
The line seems to have been drawn properly.
This may help you: https://github.com/anseki/leader-line/issues/212

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.

**Comment by ramferan** [comment]
Hi @anseki , 

The line was drawn indeed but not correctly if the internal pameter `MIN_GRID_LEN ` is set to default.
Hence we need to change it in the source code from `MIN_GRID_LEN =30` to `MIN_GRID_LEN =0`

It would be nice to have it as a parameter in the object constructor.

Thanks in advance.

**Comment by anseki** [comment]
Hi @ramferan, thank you for the proposal.
However, the parameter is not implemented because it breaks the logic of code (e.g. infinite loop) and it is unneeded as I said (that issue can be solved by another option).
Thank you. :smile:
