### ISSUE TITLE
z-index  of leader line

### ISSUE THREAD

**Issue by guirama** [anseki/leader-line#26]
Hi,

More than an issue, I m finding a method to cntrol z-index of leader lines. In my case I have a custom developed modal appearing in front of page content, leader lines (while attached elements are behind the modal) are appearing in front of modal,

Can this be controlled with CSS ?

Best Regards

Indubuk

**Comment by anseki** [comment]
Hi @guirama, thank you for the comment.
Try this:
```js
document.querySelector('.leader-line').style.zIndex = 123;
```
Note that it is not supported.

**Comment by guirama** [comment]
I didn't work, but your suggestion helped me to resolve it. I applied same on my modal with CSS, a higher z-index.

Thanks a lot.

**Comment by anseki** [comment]
:smile:
