### ISSUE TITLE
Leader Lines Connecting Issues

### ISSUE THREAD

**Issue by Allabakshu** [anseki/leader-line#261]
Hi Team can u help in this issue

![tree](https://user-images.githubusercontent.com/47346893/134728897-45d9476f-3513-40ea-9e4d-2ce4a8710a6e.PNG)

when ever i close the parent node the leade lines are irrelevant to the position

![tree2](https://user-images.githubusercontent.com/47346893/134729303-1adbe441-db79-4f46-b3b7-9dad74f452d3.PNG)

how can i connect those leader lines to parent node when ever i close the parent node wise versa when ever i expand parent node those need to connect back to child nodes

**Comment by anseki** [comment]
Hi @Allabakshu, thank you for the comment.
You have to call [`position`](https://anseki.github.io/leader-line/#position) method.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
