### ISSUE TITLE
Leader line duplicates itself when used with Plain Draggable

### ISSUE THREAD

**Issue by brunoMachado92** [anseki/leader-line#262]
Hello,

I'm trying to use the leader line with PlainDraggable, but on drag, the line gets duplicated. The duplicated line refreshes the position correctly, the first stays static.
![Capturar1](https://user-images.githubusercontent.com/13498580/135848460-39cfc83b-2566-4d58-b8fd-9e09e8e60ab6.PNG)
![Captura2](https://user-images.githubusercontent.com/13498580/135848466-31bfbc2b-ce55-4c70-af8a-27111d53c667.jpg)

The code:
`
requirejs(["node_modules/leader-line/leader-line.min", "node_modules/plain-draggable/plain-draggable.min"], function () {
    "use strict"
    var elStart = document.getElementById('start')
        , elEnd = document.getElementById('end')
        , line1
        , draggable;

    draggable = new PlainDraggable(
        elEnd,
        {
            onMove: function () {
                line1.position();
                line1.dash = true;
            },
            onDragEnd: function () {
                line1.dash = false;
            }
        }
    );

    draggable = new PlainDraggable(
        elStart,
        {
            onMove: function () {
                line1.position();
                line1.dash = true;
            },
            onDragEnd: function () {
                line1.dash = false;
            }
        }
    );

    line1 = new LeaderLine(
        elStart,
        elEnd
    );
});
`

The version:
Leader-line: 1.0.5
Plain-draggable: 2.5.14

Am I missing something in the code?

Thank you

**Comment by anseki** [comment]
Hi @brunoMachado92, thank you for the comment.
I copied your code and tried it, then it seems to work fine.
https://jsfiddle.net/peg1a7cq/
I think that another part of your code that was not indicated by you has a bug, the initialize-function was called twice.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
