### ISSUE TITLE
SVG is wider than the line

### ISSUE THREAD

**Issue by ofir-o** [anseki/leader-line#263]
Hey, thanks for the library!

I am having a small problem where the rendered SVGs are wider than the leader lines.

For example, this is the SVG size of the diagonal line:

![image](https://user-images.githubusercontent.com/25366713/137160105-682460cf-ac92-4e89-80a0-62aa9781120a.png)

Another example with a short line:

![image](https://user-images.githubusercontent.com/25366713/137161118-40f21e93-323a-425d-a0a3-641c76432894.png)

I'd love some help with this as it is adding scrollbars to my page.

**Comment by anseki** [comment]
Hi @ofir-o, thank you for the comment.
The SVG element needs the size to draw the line that contains the path (cubic curve and its segments), mask, anchor, etc.
You can change the path for the size of the SVG. For example: https://jsfiddle.net/Lj0m5egb/
