### ISSUE TITLE
Cant get unminified JS

### ISSUE THREAD

**Issue by anandtrivedi11** [anseki/leader-line#27]
Hi Can you please provide the Unminified Js file.

I need it so I can attach a parent element to the leaderline

**Comment by anseki** [comment]
Hi @anandtrivedi11, thank you for the comment.
Sorry, what do you mean that attach an element to unminified JS file?
The minified JS should work fine.

**Comment by anandtrivedi11** [comment]
Hi, What I want to do is like for example you can set different attributes to the line using  
path: "straight",
color: "orange", etc. 
I want to have an attribute with which i can set svgs parent element.

The requirement for this is that right now All the svgs are screated outside of <body>. I want them to be created inside body which would require a prent element to be given to them. I need it for Z-indexing purposes.

I am using them on a map to connect popovers and some points on map so that it tells which popover belongs to which point. Your Leaderline is perfect except just when I set Z-index of it to lesser than that of HTML element it disappears from the map completely

**Comment by anseki** [comment]
You can create multiple instances with different options (e.g. `path`, `color`, etc.) in single page.
See: https://anseki.github.io/leader-line/

Anyways, if you really want to customize the library, there are all files including source files of JS CSS and others, build script, meta file and others in this repository. Of course you can get (fork) those.

**Comment by anandtrivedi11** [comment]
Thank you so much for your quick response.  Like to re articulate my request 
1) Currently In my project I am including leader-line.min.js and its working well
2) What i want is , un-minified version of leader-line.min.js 
3) When I am importing leader-line.js which is in your src folder, it gives error due to other dependent files are missing .
4) So is there any way I can create a single leader-line.js file including all dependencing without uglification or minification.

**Comment by anseki** [comment]
Sorry, my English is poor.
Do you mean that an error occurred when you build it?

**Comment by anandtrivedi11** [comment]
Hi,
When I am using it in my project it is working fine.

By error I mean is that when I cloned your project and installed all dependencies for it using NPM it gave an error. I did this part becuase I wanted an Unminified version of JS

**Comment by anseki** [comment]
Which error was given when you installed NPM packages?

**Comment by anseki** [comment]
I don't know why you want the un-minified file, and I don't know what error was given when you installed NPM packages.
If you can explain about those, I might be able to help you.

**Comment by anseki** [comment]
Unfortunately no reply came, and I close this issue.
