### ISSUE TITLE
The distance of the rows from each other

### ISSUE THREAD

**Issue by emresaracoglu** [anseki/leader-line#270]
Hello,

Lines are not visible because there is no space between the texts. 
Is it possible to automatically zoom out if there are arrows between the lines?

https://jsfiddle.net/emresaracoglu/bgxtfk14/

Sample:

![WSAYP1](https://user-images.githubusercontent.com/297968/139536501-f166c7d7-309a-495c-a8ea-a03831078735.png)

Thank you

**Comment by anseki** [comment]
Hi @emresaracoglu, thank you for the comment.
Your example in JSFiddle seems to show lines correctly.
And I couldn't find the problem in your image.
Anyway, you can use `*SocketGravity` and `size` options to adjust lines. To do that automatically, you have to find when that is required in your app.

**Comment by emresaracoglu** [comment]
Thanks for your valuable response @anseki 
Actually, I mean; to show the arrows more clearly, that is, to create a wider perspective.

Image can explain better;
![2 fw](https://user-images.githubusercontent.com/297968/139542907-66155260-9d9d-4214-abc5-a50055fd1b68.png)

**Comment by anseki** [comment]
Like this?
https://jsfiddle.net/dxoLt6rz/

**Comment by emresaracoglu** [comment]
It is possible with CSS of course, even drawing arrows is possible with CSS, but I was wondering if there is something to do this automatically.

**Comment by anseki** [comment]
[As I said](https://github.com/anseki/leader-line/issues/270#issuecomment-955361648), you have to find when that is required in your app. In other words, I don't know what does the "automatically" mean.
For example, If you want to add the margin of the element when those elements are positioned in the same line, you can get that by using `getClientRects` or `getBoundingClientRect` method.

**Comment by emresaracoglu** [comment]
I will be searching into your suggestion, thank you for your interest and help.

**Comment by anseki** [comment]
I'm glad if I could help you. :smile: 
Could you close this issue if it was solved?

**Comment by emresaracoglu** [comment]
I'm still trying to fix the problem but
Yes, we can close, thanks again.

**Comment by anseki** [comment]
I think reference document such as MDN helps you.
https://developer.mozilla.org/en-US/docs/Web/API/Element/getClientRects
Good luck :smile:
