### ISSUE TITLE
Connect with one element out of viewport

### ISSUE THREAD

**Issue by AgathaCrystal** [anseki/leader-line#271]
Hi :)

first of all: Thanks for this cool library!

I'm trying to connect the "out now" with the "out now" further down (offcanvas) the page, like shown in the screenshots.

![1](https://purnell.custom-server.de/themes/purnell/img/question/line-1.JPG)
![2](https://purnell.custom-server.de/themes/purnell/img/question/line-2.JPG)

This is the expected behaviour after I scrolled down a few pixels and reloaded the page:
![3](https://purnell.custom-server.de/themes/purnell/img/question/line-3.JPG)

Both elements are positioned with 
`    display: flex;
    align-items: center;`
and it seems to have something to do with the issue.

Heres is the URL to my dev server: [https://purnell.custom-server.de/](url)

Am I doing something wrong or is this a bug?

Greetings

Phil

**Comment by anseki** [comment]
Hi @AgathaCrystal, thank you for the comment.
You have to call [`position`](https://anseki.github.io/leader-line/#position) method if the layout of your web page is changed without resizing the window.
The element having `display:flex` is moved automatically when the viewport is scrolled. That is, the layout is changed.
Try the example in the document about the `position` method. Move the view having "Scroll this".

**Comment by anseki** [comment]
Oh sorry, I misread the `flex` as `fixed` (`position` property).
Anyway, you have to call the `position` method for changed layout, or use `addEventListener('load', ...)` to wait for finishing the layout.

**Comment by AgathaCrystal** [comment]
Oh wow, I didnt expect such a quick answer! Thanks alot, ill check it out and update this post!!!

**Comment by AgathaCrystal** [comment]
So I used the the following code and i works flawless: 
`window.addEventListener('load', function () {
        var line = new LeaderLine(
            document.getElementById('top-button'),
            document.getElementById('outnow-hl'),
            { startSocket: 'bottom', offset: [50, 0], endSocket: 'right', startPlug: 'disc', endPlug: 'disc' });
        line.position();
    });`

Thanks for the superfast answer and your help!

**Comment by anseki** [comment]
Remove `line.position()` at the last in your code because it is not required and it takes a cost.
The `position` method is required for fixing a line after the layout is changed, for example a line is created before finishing the layout (i.e. without `addEventListener('load', ...)` to wait for that).
I'm glad if I could help you. :smile:
