### ISSUE TITLE
Using leader-line with Swiper Js.

### ISSUE THREAD

**Issue by Xteripus** [anseki/leader-line#272]
I am trying to build a timeline with Swiper and leader-line.js. I tried to use it with Swiper's on transition funcitons but it doesn't work properly.
I want to make lines stick to Swiper's container so when swiper element moves the line moves with it.

Here is my codepen: https://codepen.io/Xteripus/pen/yLopBNp?editors=1010

**Comment by anseki** [comment]
Hi @Xteripus, thank you for the comment.
This may help you: https://codepen.io/anseki/pen/qBXpEWV?editors=1010

**Comment by Xteripus** [comment]
Thank you for your interest and help,
I am using particles js in my page too and unlike the codepen link my slider shows this unwanted display until transition ends.
https://prnt.sc/1y99x7y
Is there any way to avoid this? Or can adding animation solve this? Thanks in advance!

**Comment by anseki** [comment]
Sorry, my English is poor.
Do you mean that my example didn't work?

**Comment by Xteripus** [comment]
Well it works if page is empty like codepen, but with content, it lags as seen in video preview that I shared with you above.

**Comment by anseki** [comment]
You can use the `position` method to fix the line for new layout, like the example.

**Comment by Xteripus** [comment]
I implemented your whole code it including position method and as seen in video it lags a bit. Is there a way to fix it?

**Comment by anseki** [comment]
To reproduce that, could you show me an example code by using e.g. codepen?
Note that nobody can find a bug by video because nobody can read code in video.

**Comment by Xteripus** [comment]
I know they can't the point that I am trying to make is the code works but it calculates slow.
But I solved it by changing slider speed to 0

**Comment by anseki** [comment]
:smile:
