### ISSUE TITLE
When using a percentage to define left in the absolute layout, how to solve the situation as shown in the figure below.

### ISSUE THREAD

**Issue by lansensmile** [anseki/leader-line#273]
When using a percentage to define left in the absolute layout, how to solve the situation as shown in the figure below.
![image](https://user-images.githubusercontent.com/13849634/141731802-9d0ebffd-5cd4-41b5-aebb-f4cf953a21ef.png)

`<template>
  <div class="main">
    <span id="span1">111111</span>
    <span id="span2">222222</span>
    <span id="span3">333333</span>
  </div>
</template>
<script>
import LeaderLine from 'leader-line';
export default {
  name: 'N3S',
  components: {
  },
  created() {
    // this.getLine();
  },
  mounted(){
    this.getLine();
  },
  methods: {
    getLine(){
      new LeaderLine(
        document.getElementById('span1'),
        document.getElementById('span2'),
        {
          size: 5,
          color: '#707788',
        }
      );
      new LeaderLine(
        document.getElementById('span2'),
        document.getElementById('span3'),
        {
          size: 5,
          color: '#707788',
        }
      );
    }

  },
};

</script>

<style scoped>

#span1,#span2,#span3{
  position: absolute;
  background-color: #00afff;
  top: 100px;
}
#span2 {
  left: 30%;
}

#span3 {
  left: 60%;
}

</style>

`

**Comment by anseki** [comment]
Hi @lansensmile, thank you for the comment.
To draw lines after finish the layout of the page, use `load` event.
For example:
```js
addEventListener('load', () => {
  new LeaderLine(...)
});
```

**Comment by lansensmile** [comment]
Hello, I use the timer to delay 10 seconds, and then draw the line. It still has the same effect. Is it convenient for you to give a demo? Thank you very much.

**Comment by anseki** [comment]
I copied your code:
https://jsfiddle.net/1qrk4xdt/

**Comment by lansensmile** [comment]
Hi @anseki , thank you for your answer. I modified it according to your method, but it still didn't solve the problem. The specific code is as follows, please help me to see where the problem is.



<script type="text/javascript">
import LeaderLine from 'leader-line';
export default {
  name: 'test',
  components: {
  },
  created() {
    console.log("created");
    console.log(document.getElementById("main"));
  },
  mounted(){
    console.log("mounted");
    this.getWidth()
    console.log(document.getElementById("main"));
    addEventListener('load',getLine(),true)
  },
  updated() {
    console.log("updated");
  },
  activated() {
    console.log("activated");
  },
  destroyed() {
    console.log("destroyed");
  },
  methods: {
    getWidth(){
      console.log(document.documentElement.clientWidth);
      console.log(document.getElementById("span3").offsetLeft);
    }
  },
};

function getLine()
{
  console.log("getLine");
  new LeaderLine(
    document.getElementById('span1'),
    document.getElementById('span2'),
    {
      size: 5,
      color: '#707788',
    }
  );
  new LeaderLine(
    document.getElementById('span2'),
    document.getElementById('span3'),
    {
      size: 5,
      color: '#707788',
    }
  );
}
</script>

**Comment by anseki** [comment]
Sorry, your codes in your comment are illegible.
https://github.com/anseki/leader-line/issues/273#issue-1053259630
https://github.com/anseki/leader-line/issues/273#issuecomment-976133197
Could you show me an example by using e.g. https://jsfiddle.net/ ?

**Comment by lansensmile** [comment]
Hello, I have copied the code into this website, the link is as follows:
https://jsfiddle.net/ef2mxkzq/4/
Thank you very much.

**Comment by anseki** [comment]
I tried your example, then that didn't draw a line.
I tried it with Google Chrome and Firefox.
![ss-01](https://user-images.githubusercontent.com/4763469/142998810-7e5a22b4-4228-4d65-832a-1d207817f81f.png)

**Comment by anseki** [comment]
I added the library to your example, and removed unnecessary `addEventListener` from that.
https://jsfiddle.net/soxbL0dm/

**Comment by lansensmile** [comment]
This problem occurs when the screen width becomes larger. The specific phenomenon can be seen in the figure belo
![微信图片_20211124103634](https://user-images.githubusercontent.com/13849634/143161449-d4bcd028-3bd9-4dda-9030-9b0e26a7b748.png)
w

**Comment by anseki** [comment]
I tried it with Google Chrome and Firefox.
![ss01](https://user-images.githubusercontent.com/4763469/143170693-e83de9c4-9ff5-4562-8455-790992da1ca1.png)
Which web browser do you use?

**Comment by lansensmile** [comment]
Hello, I have tested with multiple browsers, including Google, ie, 360, etc. You need to adjust the browser size, and then click to run. Try different screen sizes and you will find this phenomenon. Especially when the screen width is wide.

**Comment by anseki** [comment]
I see.
Did you try this?: https://github.com/anseki/leader-line/issues/273#issuecomment-975256109
And, did the issue occur?

**Comment by lansensmile** [comment]
Yes, you can see https://github.com/anseki/leader-line/issues/273#issuecomment-976230354 
In my project, this problem exists in common resolutions. The opening of the largest window of the browser is abnormal, but the abnormal situation will be restored when the window is reduced. The reverse operation is the same.

**Comment by anseki** [comment]
No, you seem to misunderstand.
My example (https://github.com/anseki/leader-line/issues/273#issuecomment-975256109) is pure JS.
Your example (https://github.com/anseki/leader-line/issues/273#issuecomment-976230354) is not.
Therefore, if the issue didn't occur in pure JS, the issue might be caused by the framework.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
