### ISSUE TITLE
leader line overlapping

### ISSUE THREAD

**Issue by maninalliappan** [anseki/leader-line#274]
Hi Team,

When I scrolling page, the leader line is overapping

Please look  example : https://angular-woohoo-leader-line-h2r72m.stackblitz.io,

steps :

1. First point two item.
2.  then scroll  down windows scroll. and up the window scroll, 
3. now you can reproduce issue

**Comment by anseki** [comment]
Hi @maninalliappan, thank you for the comment.
You have to call `position` method when the layout is changed.
https://anseki.github.io/leader-line/#position
Try to scroll an example saying "Scroll this" in the document.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
