### ISSUE TITLE
Incorrect stroke-width of text in google chrome 96

### ISSUE THREAD

**Issue by econavi** [anseki/leader-line#275]
Hi! Something is wrong with google chrome 96.  
Some labels get stroke-width: 10px and have incorrect position.  
![image](https://user-images.githubusercontent.com/29106097/142356785-07fef6ac-dcb9-4d66-b5d3-f47b7081f145.png)

**Comment by econavi** [comment]
![image](https://user-images.githubusercontent.com/29106097/142370089-8cede833-d52f-4fb1-b84f-1355d040fc43.png)

**Comment by anseki** [comment]
Hi @econavi, thank you for the comment.
This was solved by v1.0.7.

**Comment by econavi** [comment]
Thanks a lot!
