### ISSUE TITLE
ReferenceError: LeaderLine is not defined

### ISSUE THREAD

**Issue by Nehasoni988** [anseki/leader-line#276]
I added the leader-line.min.js file in my Vue project directory and given its path in index.html.

Now, when I am initiating its constructor, it is throwing an error that LeaderLine is not defined.

new LeaderLine(
					document.getElementById(`start_wr`),
					document.getElementById(`end_wr`),
				);

@anseki

**Comment by anseki** [comment]
Hi @Nehasoni988, thank you for the comment.
The loading the library might have failed, or your code might have tried to access to the library before that was loaded.
The library can be accessed after that was loaded.
For example: https://jsfiddle.net/w3mcryte/

**Comment by Nehasoni988** [comment]
Okay, got it.
Thanks!

**Comment by anseki** [comment]
I'm glad if I could help you. :smile: 
Could you close this issue if it was solved?

**Comment by Nehasoni988** [comment]
Sure, :-)
