### ISSUE TITLE
How is fluid path computed?

### ISSUE THREAD

**Issue by xiaohk** [anseki/leader-line#277]
Hello, I really like how the arrow curve looks like in `fluid` mode.

I am wondering how is the svg path computed? It seems it uses some gravity forces.

https://github.com/anseki/leader-line/blob/f2fa7a40cc33542872ebc29ef9d2fabf36bca570/test/spec/func-PATH_FLUID.js#L11-L16

I couldn't find the exact code where the final path string is constructed.

Could you please point me to that function? Thank you! ٩( ᐛ )و

**Comment by anseki** [comment]
Hi @xiaohk, thank you for the comment.
The code that makes the path is here:
https://github.com/anseki/leader-line/blob/master/src/leader-line.js#L1705

**Comment by xiaohk** [comment]
Thank you for the pointer! It is very helpful!

I am trying to understand the path generation process for the first leader line on the [demo page](https://anseki.github.io/leader-line/).

<img width="422" alt="image" src="https://user-images.githubusercontent.com/15007159/143284672-2cd42bd5-5214-4965-9a1e-80ab9f1ff90f.png">

I think this line would fall into the `[SOCKET_RGIGHT, SOCKET_LEFT]` category. Suppose the start point is [x1, y1], and the end point is [x2, y2]. Then, based on the code, the first control points is computed as [x1 + (x2 - x1) / 2, y1]. The second control point is [x2 - (x2 - x1) / 2, y2], without considering the `MIN_GRAVITY`.

I looked up the path for this leader line: `M 398 647 C 515.275390625 647 519.8154238867103 711.4886449453619 632.0006324759555 712.899405689712`.

The start point is [398, 647], and the end point is [632.0006, 712.8994]. Then, the control points would be [515.0003, 647] and [515.0003, 712.8994]? The second control point is quite different from the one used in the path string. I am wondering if you can give me some hints on the deviation?

Thanks!

**Comment by anseki** [comment]
LeaderLine supports [`*Plug`](https://anseki.github.io/leader-line/#startplug-endplug) that has different size.
Therefore, the path has to be adjusted for each plug.
https://github.com/anseki/leader-line/blob/master/src/leader-line.js#L1912

**Comment by xiaohk** [comment]
> LeaderLine supports [`*Plug`](https://anseki.github.io/leader-line/#startplug-endplug) that has different size.
> Therefore, the path has to be adjusted for each plug.
> https://github.com/anseki/leader-line/blob/master/src/leader-line.js#L1912

Ah, I see. Thank you so much for your help! Happy Thanksgiving! (๑•̀ㅂ•́)و✧

**Comment by anseki** [comment]
:smile:
