### ISSUE TITLE
Making path go a longer route

### ISSUE THREAD

**Issue by Draghmar** [anseki/leader-line#278]
Hi
Great library! I wonder if it's possible to achieve something like this?
![Untitled](https://user-images.githubusercontent.com/275348/143200362-c6aee52c-4d8d-4fc1-ac31-06fd9ebe0b2f.png)
You can call it: don't touch the element. ;)
I know I can define what sides should be used as a start/end but the path still goes the shortest route possible.

**Comment by Draghmar** [comment]
Hm...ok, weird. For some reason I did set it as a 'straight' for the first one and 'grid' for the second and it worked this way. So I think this issue of mine can be closed but if you could confirm that this is actually a normal behaviour and not some random thing that happen, I'd be appreciate. :)

**Comment by anseki** [comment]
Hi @Draghmar, thank you for the comment.
Yes, you should use `grid` in that case. :smile: 
So, could you close this issue if it was solved?

**Comment by Draghmar** [comment]
Thanks for confirmation! :)
