### ISSUE TITLE
Option for smoothing out grid paths

### ISSUE THREAD

**Issue by blakesisu** [anseki/leader-line#28]
Hi, this is more a question than issue, but I'm curious if there's a straightforward way of making the 'bends' in the lines for the 'grid' paths more fluid? Otherwise I'm really enjoying this library, thanks!

**Comment by anseki** [comment]
Hi @blakesisu, thank you for the comment.
You can specify `fluid` instead of `grid` to make the line be smooth.
https://anseki.github.io/leader-line/#path

**Comment by blakesisu** [comment]
I've been toying with that option, and while it's great, the grid path has been more useful for me in my current project. I'm really just looking to soften the 'bends' in the svgs. If you have any advice how I might do something of the sort that would be awesome (what I'm asking is akin to a border-radius for a html element). Thanks!

**Comment by anseki** [comment]
Like this?
https://jsfiddle.net/s843m2pa/

**Comment by blakesisu** [comment]
Here's a snippet of my grid. The placement is fantastic, but the bends are rigid, if I could get the grid bends to bend like fluid lines it would be right on spec with what I'm doing. I guess I am asking for a border-radius-y option for the grid path option, it would be pretty awesome. Fluid is great but I building to match spec which is a mix rigid and fluid at the moment. 

![2018-09-26-121700_317x806_scrot](https://user-images.githubusercontent.com/33074598/46103816-9daded80-c186-11e8-8dac-10149c5df40a.png)

**Comment by anseki** [comment]
Do you mean that the `*SocketGravity` couldn't make it?

**Comment by blakesisu** [comment]
I'm actually using socket gravity while using grid path to extend or shorten paths in particular spots, but the socket gravity doesn't seem to give any fluidity to the svgs when using grid path, if that is what you meant. And I haven't been able to configure a particular combinations start/end socket gravities while using fluid that give a grid like behavior with fluid turns.

**Comment by anseki** [comment]
See:
https://jsfiddle.net/s843m2pa/

**Comment by blakesisu** [comment]
Thank you so much for giving me examples, and while they look great, I need the lines to be completely vertical and horizontal, except at the bends, where some type of radius option would be super helpful. It stills seems that with the fluid option this isn't possible.

**Comment by anseki** [comment]
I see.
There are two cases:

- **A**: If the R is a half of width of the line, it is very easy, by `stroke-linejoin`.
- **B**: If the R is not value above, the path data have to be changed.

For example:
https://jsfiddle.net/a1ye4kj7/

**Comment by blakesisu** [comment]
That B svg is definitely what the spec is calling for. I take it any path data changes comes with some significant logic/calculation? I'm not to savvy with SVGs, and don't have a much time, so forking and fiddling with the code for a few days are probably not an option, at least at the moment.

**Comment by anseki** [comment]
Sorry, my English is poor.
Do you mean that you want how to get the path?

**Comment by anseki** [comment]
For example:
https://jsfiddle.net/m4p5zvsg/

**Comment by blakesisu** [comment]
It's a pesky language, no apologies needed :) But omg that. That's it. I would very much like to send a beer your way right now! Thanks, I'll give your logic a whirl tomorrow at work. I think this would be a fantastic option to include in the library, maybe you would decide to support such functionality one day ;)

**Comment by GO3LIN** [comment]
This is absolutely a feature to be included in the library, thanks a lot anseki !!

**Comment by anseki** [comment]
Hi @GO3LIN, thank you for the comment.
This seems to be a feature in low demand now, but I will rethink if more requests come.
Thank you.

**Comment by machinaeXphilip** [comment]
i would love to see it and for sure use it in two projects of mine.

**Comment by anseki** [comment]
Hi @machinaeXphilip, thank you for the impression about the `grid`.

**Comment by solid-droid** [comment]
Best library  to draw lines :)  ( I think this is the only most powerful library to draw svg lines )
I would also love to see this feature

I saw this in pinterest..
![fb536602c1d389c2e9de60ee1b397e2d](https://user-images.githubusercontent.com/32586986/147400410-7715f81b-4a81-4a0d-aba7-cd799fb8902a.jpg)

**Comment by anseki** [comment]
Hi @solid-droid, thank you for the comment. :smile:

**Comment by rockwellll** [comment]
hello @anseki. Sorry for tagging you. Thank you for this tremendous package, it has legit saved my life. I do have one question tho.

In https://github.com/anseki/leader-line/issues/28#issuecomment-425339319 you pointed out how to make the grid lines have rounded borders. I have copy-pasted the `addArc` method into the class. And i'm trying to apply the function on all grid lines. Like so

```js
 connect() {
    this.initialLine = new LeaderLine(
      this.conditionTarget,
      this.ifTarget,
      { color: "black", endPlug: "behind", path: "grid", endSocket: "top", size: 2}
    )

    this.lineToElse = new LeaderLine(
      this.conditionTarget,
      this.elseTarget,
      { color: "black", endPlug: "behind", path: "grid", endSocket: "top", size: 2}
    )

    this.ifToEndLine = new LeaderLine(
      this.ifTarget,
      document.getElementById("end-connector"),
      { color: "black", endPlug: "behind", path: "grid", endSocket: "left", size: 2}
    )

    this.elseToEndLine = new LeaderLine(
      this.elseTarget,
      document.getElementById("end-connector"),
      { color: "black", startSocket: "bottom", endPlug: "behind", path: "grid", endSocket: "right", size: 2}
    )

    document.querySelectorAll(".leader-line-line-path").forEach((line) => {
      line.setAttribute('d', this.addArc(line.getAttribute('d'), 10));
    })
  }

addArc(pathData, radius) {
    var reL = /^L ?([\d.\-+]+) ([\d.\-+]+) ?/,
      newPathData, curXY, curDir, newXY, newDir,
      sweepFlag, arcXY, arcStartXY;

    function getDir(xy1, xy2) {
      if (xy1.x === xy2.x) {
        return xy1.y < xy2.y ? 'd' : 'u';
      } else if (xy1.y === xy2.y) {
        return xy1.x < xy2.x ? 'r' : 'l';
      }
      throw new Error('Invalid data');
    }

    function captureXY(s, x, y) {
      newXY = {x: +x, y: +y};
      return '';
    }

    function offsetXY(xy, dir, offsetLen, toBack) {
      return {
        x: xy.x + (dir === 'l' ? -offsetLen : dir === 'r' ? offsetLen : 0) * (toBack ? -1 : 1),
        y: xy.y + (dir === 'u' ? -offsetLen : dir === 'd' ? offsetLen : 0) * (toBack ? -1 : 1)
      };
    }

    pathData = pathData.trim().replace(/,/g, ' ').replace(/\s+/g, ' ')
      .replace(/^M ?([\d.\-+]+) ([\d.\-+]+) ?/, function(s, x, y) {
        curXY = {x: +x, y: +y};
        return '';
      });

    if (!curXY) { throw new Error('Invalid data'); }
    newPathData = 'M' + curXY.x + ' ' + curXY.y;

    while (pathData) {
      newXY = null;
      pathData = pathData.replace(reL, captureXY);
      if (!newXY) { throw new Error('Invalid data'); }

      newDir = getDir(curXY, newXY);
      if (curDir) {
        arcStartXY = offsetXY(curXY, curDir, radius, true);
        arcXY = offsetXY(curXY, newDir, radius);
        sweepFlag =
          curDir === 'l' && newDir === 'u' ? '1' :
            curDir === 'l' && newDir === 'd' ? '0' :
              curDir === 'r' && newDir === 'u' ? '0' :
                curDir === 'r' && newDir === 'd' ? '1' :
                  curDir === 'u' && newDir === 'l' ? '0' :
                    curDir === 'u' && newDir === 'r' ? '1' :
                      curDir === 'd' && newDir === 'l' ? '1' :
                        curDir === 'd' && newDir === 'r' ? '0' :
                          null;
        if (!sweepFlag) { throw new Error('Invalid data'); }
        newPathData += 'L' + arcStartXY.x + ' ' + arcStartXY.y +
          'A ' + radius + ' ' + radius + ' 0 0 ' + sweepFlag + ' ' + arcXY.x + ' ' + arcXY.y;
      }

      curXY = newXY;
      curDir = newDir;
    }
    newPathData += 'L' + curXY.x + ' ' + curXY.y;
    return newPathData;
  }
```

But, for some reason i get the error "Invalid data" just before assiging xy, here

```js
    pathData = pathData.trim().replace(/,/g, ' ').replace(/\s+/g, ' ')
      .replace(/^M ?([\d.\-+]+) ([\d.\-+]+) ?/, function(s, x, y) {
        curXY = {x: +x, y: +y};
        return '';
      });

    if (!curXY) { throw new Error('Invalid data'); }
```

any ideas why might that be happening?. Thank again.

**Comment by anseki** [comment]
Hi @rockwellll, thank you for the comment.
That error means that the `pathData` that was passed to the method is invalid.
Check the `pathData` by e.g. `console.log(pathData)`.

**Comment by rockwellll** [comment]
here is the log @anseki.

```
    document.querySelectorAll(".leader-line-line-path").forEach((line) => {
      console.log("d attr is", line.getAttribute('d'));
    })
    document.querySelectorAll(".leader-line-line-path").forEach((line) => {
      line.setAttribute('d', this.addArc(line.getAttribute('d'), 10));
    })
```

<img width="766" alt="Screenshot 2022-01-03 at 20 45 40" src="https://user-images.githubusercontent.com/38360603/147962391-6d339684-3908-4c30-b458-08a98d806f2c.png">

**Comment by anseki** [comment]
It seems that the error was not thrown with the log.
Another part of your code might have a bug. For example, you don't have to call the `addArc` method every time.

**Comment by anseki** [comment]
This may help you:
https://jsfiddle.net/sbfzpquc/

**Comment by rockwellll** [comment]
@anseki Thank you very much. It did do the trick for me, huge thanks man. 

One more question if i may. Why adding manually after drawing each line, and why i cannot use something like

```js
   document.querySelectorAll(".leader-line-line-path").forEach((line) => {
      line.setAttribute('d', this.addArc(line.getAttribute('d'), 10));
    })
```

Any ideas why using the latter approach doesn't work?. I'm only saying this because i'll be removing and adding these lines dynamically during run-time. Thanks again

**Comment by rockwellll** [comment]
Is it possible to be able to add a unique id to the lines that have been drawn?. I think the approach you used in the fiddle above, where i get the last line(after drawing) and assing something unique onto it ?

```js
 const SELECTOR = 'body > .leader-line:last-child .leader-line-line-path';

  // after drawing line

  document.querySelector(SELECTOR).classList.add("some unique class")
```

right?

**Comment by anseki** [comment]
The `addArc` method adds arcs for passed line. Therefore, you have to call the method only once by a line.
However, your code calls the method repeatedly when you call the `connect` again because the `querySelectorAll` method gets all lines (not only current line).
Also, your class should not have the `addArc` method because that doesn't use instance.

I'm glad if I could help you. :smile:

**Comment by rockwellll** [comment]
You saved my life, huge thanks again!!.

**Comment by OrhanTozan** [comment]
I really need the rounded grid as a feature

**Comment by anseki** [comment]
Hi @OrhanTozan, thank you for the comment. :smile:
