### ISSUE TITLE
Non-linear gradient

### ISSUE THREAD

**Issue by Draghmar** [anseki/leader-line#280]
Hi
I've seen in the docs that you can make lines with gradient. But as far I understand you can only define start and stop color being at 0% and 100%. Is there a way to move start positions for the colors? An example of I'm looking for would be equivalent in CSS:
```css
background: linear-gradient(#000 40%, #fff 60%);
```

**Comment by anseki** [comment]
Hi @Draghmar, thank you for the comment.
Only `startColor` and `endColor` options are supported for `gradient`.
Therefore, you have to edit `stop` elements or add another effect for custom gradient.

**Comment by Draghmar** [comment]
OK, so you're saying I have two options here:
1. Access `svg` and it's `stop` elements.
2. Make some override to your gradient function to implement defining `offset` for `stop` elements and maybe even making more `stop` elements.

If that the case I have at least two questions. ;)
1. How can I access `svg` element that is associated with defined `LeaderLine` class? I can't seem to find any method for that...but maybe I'm blind. ;) I've seen that created element is assigned to `props.svg` but I don't see anything that could access this property.
2. Is there a way to make a plug-in or something like that? Or would I have to simply edit your code directly? Don't see anything about that in the docs so I'm guessing the later...

**Comment by anseki** [comment]
LeaderLine doesn't support accessing the element. If you really want to access to the SVG element, you can do that by `querySelector`.
```js
document.querySelector('body > .leader-line:last-child')
```
LeaderLine doesn't support plug-in. If you understand SVG, you can customize those but remember that it is not recommended.

**Comment by anseki** [comment]
For example:
https://jsfiddle.net/hpt1jdgz/
Note that this is not supported by the library.

**Comment by Draghmar** [comment]
Just curious: Is there a reason why you didn't give access to the svg element from the class itself when it's used within?

I think your approach for getting the svg element will be good enough for me at the moment. Thanks!

I already looked at your code that generates gradient and from the first glance I think I could modify this so it could take more advanced parameters. If I'll actually do this (so little time for side projects these days :() I'll send you PR so you could review it and maybe incorporate into your code.

**Comment by anseki** [comment]
The API to get the SVG element is not supported because it is not required and the library can't control that.
If you want to customize the SVG element, you had better make that without the library because it is a library to make SVG elements simply. Also, it seems that you can do that. :smile:

**Comment by Draghmar** [comment]
From my point of view this library is to make lines that utilizes SVG to achieve the effect and the resulted SVG is integral part of that process which would suggest that being able to interact with SVG line to make some custom changes would be at the same level like with any other customization available through the methods. But it's your library so it's your call. :)

Anyway thanks for suggestions how to deal with my issue. It did the trick I wanted and I'm happy with the result! :D

**Comment by anseki** [comment]
Typically, when a library provides the way to customize itself, almost libraries support plug-in system instead of API to access to internal thing (e.g. DOM, data, etc) because the library can't control that (i.e. it is out of design). And LeaderLine doesn't support plug-in system at the moment.
Thank you for your comment. :smile:
