### ISSUE TITLE
Links not getting updated when scrolling

### ISSUE THREAD

**Issue by Mahesh9959-mahi** [anseki/leader-line#281]
Hi @anseki,

when I scroll the links are not getting updated to the respective positions,  Each and every scroll I have to redraw the entire links in that I'm facing performance issues. Is there any way to update it

**Comment by anseki** [comment]
Hi @Mahesh9959-mahi, thank you for the comment.
To reproduce that, could you show me an example by using e.g. https://jsfiddle.net/ ?

**Comment by Mahesh9959-mahi** [comment]
Hi @anseki ,

Thanks for the quick response. I'm not able to create a fiddle for this issue since one more additional library is involved. I'm attaching the screenshots of the issue. I hope it would understandable
![BeforeScroll.PNG](https://user-images.githubusercontent.com/68947472/145023665-c48b3fb4-908d-4ddb-b69b-73cc6f72ecd1.PNG)![AfterScroll.PNG](https://user-images.githubusercontent.com/68947472/145023818-3db23325-fc95-44ac-8460-ea9c934917b5.PNG)

**Comment by anseki** [comment]
Sorry, nobody can find a bug in your code without reproducing that and reading the code.
Maybe, you didn't call [`position`](https://anseki.github.io/leader-line/#position) method when the layout was changed (i.e. it was scrolled).
Try to scroll the example above (the element saying "Scroll this").

**Comment by Mahesh9959-mahi** [comment]
Hi @anseki ,

How Can we call for 1000+ lines which are creating dynamically. Can you please provide any working example for this 

Thank you

**Comment by anseki** [comment]
You can see the example code in the source code of the page above.
Very easy way to handle multiple lines is using `Array#forEach` method.

**Comment by Mahesh9959-mahi** [comment]
Hi @anseki,

How do we get the removed lines information ? I'm getting issue like "disconnected element was passed" when I loop all links

**Comment by anseki** [comment]
LeaderLine should throw the error when an element that doesn't exist in the document (not removed line) is passed.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
