### ISSUE TITLE
Support for ES6 modules?

### ISSUE THREAD

**Issue by TotoShampoin** [anseki/leader-line#282]
I'd like VSCode to have intellisense working with LeaderLine, which would make it faster to work with it.
But for that to work, there needs to be a module version of LeaderLine.
Is it possible?

**Comment by anseki** [comment]
Hi @TotoShampoin, thank you for the comment.
I don't have a plan to refactor the library with ECMAScript 2015 at the moment.
I will think that when more requests come.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
