### ISSUE TITLE
How to control the lines to not to go out of scope...

### ISSUE THREAD

**Issue by sachinbahal294** [anseki/leader-line#284]
Hi @anseki , I have used the `line.position()` for handling scroll, but as the lines are following the scroll they are going out of page/scope.
Please let me know how this can be handled...?
Thanks in Advance !!!

![image](https://user-images.githubusercontent.com/13145289/146003621-cec8cf91-654a-4ded-a571-e31692435303.png)
![image](https://user-images.githubusercontent.com/13145289/146003748-fc236000-c30e-45be-9841-b9c340667e0c.png)

**Comment by anseki** [comment]
Hi @sachinbahal294, thank you for the comment.
Do you mean that you want to hide the lines?

**Comment by sachinbahal294** [comment]
Yes, lines should hide if they are scrolled above/below the view part, and should appear again

**Comment by anseki** [comment]
You can hide the line and show it by `show`/`hide` methods.
https://anseki.github.io/leader-line/#show-hide

**Comment by sachinbahal294** [comment]
i think `hide/show` won't work here, is there any other solution in which we can restrict the lines to not show over a specific div ?

**Comment by anseki** [comment]
I didn't read your code, therefore I don't know why the `show`/`hide` methods don't work in your code, sorry.
Typical cases are solved by the `show`/`hide` methods.
For example: https://github.com/anseki/leader-line/issues/192#issuecomment-768777086
Try to scroll the box in the example above.

**Comment by sachinbahal294** [comment]
Thanks @anseki , I think this is what I need

**Comment by anseki** [comment]
I'm glad if I could help you. :smile: 
Could you close this issue?

**Comment by sachinbahal294** [comment]
Sure thanks @anseki
