### ISSUE TITLE
Draggable bezier handles?

### ISSUE THREAD

**Issue by ViltsuV** [anseki/leader-line#285]
Hi!

I just found this project, quickly went through the features and I didn't see draggable bezier handles. I was wondering if you've considered adding such a feature? 
Here's what I mean: https://codepen.io/Karl-H/pen/jOyqjoK

Otherwise this project looks great! Looking forward to trying it out.

Thanks!

**Comment by anseki** [comment]
Hi @ViltsuV, thank you for the comment.
Sorry, I couldn't understand the feature.
This may help you instead of LeaderLine.
https://anseki.github.io/plain-draggable/#ex-020-slider

**Comment by ViltsuV** [comment]
Ah, right. Somehow I missed that while looking through plain-draggable. Thanks!

**Comment by anseki** [comment]
:smile:
