### ISSUE TITLE
The line is covered

### ISSUE THREAD

**Issue by EscanorTargaryen** [anseki/leader-line#286]
The library works fine but if I put an image above the line it gets covered, is it possible to fix this?

**Comment by anseki** [comment]
Hi @EscanorTargaryen, thank you for the comment.
This may help you: https://jsfiddle.net/qzjob9ft/

**Comment by EscanorTargaryen** [comment]
ok thanks, it's a z-index problem, is it possible to configure where you put the svg, its z-index and other style parameters (like top and left parameters) with the code?

**Comment by EscanorTargaryen** [comment]
is it possible to ask you for help privately? like discord

**Comment by anseki** [comment]
Of course you can specify the CSS properties (such as `z-index`, `left` and `top`) in your CSS code.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
