### ISSUE TITLE
path type arc doesn't rotate

### ISSUE THREAD

**Issue by wijju** [anseki/leader-line#287]
Thank you so much for this library but I have an issue in path type 'arc', well I have 5 elements which are showing in below image.

![arc](https://user-images.githubusercontent.com/96767004/147541476-20a0b99f-688a-4724-acd3-d7d67a395a44.JPG)

First Element is solar box which is giving power to inverter, second element is power consumption which is taking power from inverter.
I want to show line like this
![arc2](https://user-images.githubusercontent.com/96767004/147541696-90b0e07f-17b4-4705-81e9-5642d1078518.JPG)

is it possible for fix ?

**Comment by anseki** [comment]
Hi @wijju, thank you for the comment.
Exchange the elements between `start` and `end` options.

**Comment by wijju** [comment]
Yes I did and after that I still have same issue

**Comment by anseki** [comment]
Try this: https://jsfiddle.net/kdtq7hf4/
If you show your code by using e.g. https://jsfiddle.net/ , I might find a bug in your code.

**Comment by wijju** [comment]
could you please check this link.

https://jsfiddle.net/Wijju/g4c57p0o/53/

**Comment by anseki** [comment]
Do you want to do this?
https://jsfiddle.net/zkLpdy0x/

**Comment by wijju** [comment]
well I have already done this what you have done, this is right but simply I want lines going backward instead of forward...

It looks like that the line is coming from consumption box to inverter box, but I actually want line start  from inverter box and goes to  consumption box...

**Comment by wijju** [comment]
please see the example url below, though it's kinda different UI from my case but concept is same.

https://www.solarweb.com/PvSystems/PvSystem?pvSystemId=046173e7-2d74-4e9b-ade3-a5e7014db4dc

**Comment by anseki** [comment]
Sorry, my English is poor. And also, I couldn't see your example because I don't have an account of that service.
Anyway, do you want to pull the line in the direction of the socket? If so, you can specify [`*SocketGravity`](https://anseki.github.io/leader-line/#startsocketgravity-endsocketgravity) options.

**Comment by wijju** [comment]
Hi @anseki , Thank you so much for the help.
My problem has been solved,  `startSocketGravity` solved my problem.

Below is the output which I wanted to do.

https://jsfiddle.net/Wijju/g4c57p0o/70/

**Comment by anseki** [comment]
I'm glad that I could help you. :smile: 
So, could you close this issue?

**Comment by wijju** [comment]
Yeah Sure, Thank you very much.
