### ISSUE TITLE
Line disappears when clip-path defined

### ISSUE THREAD

**Issue by nate-clark-ii** [anseki/leader-line#288]
Hello,

I am having an issue where I specify a clip-path for the line and the line disappears. See this for an example https://jsfiddle.net/k79xobhe/3/ . You'll notice that when you remove the following code, the lines appear again. `.leader-line {
  clip-path: url(#clip);
}`

However, the lines then goes outside the white border when scrolling. I am unsure how to resolve. I have attempted to follow the logic in this https://github.com/anseki/leader-line/issues/54 , but I require the logic to work with multiple lines which are created by the user.

Thank you for the assistance, the libraries you have created are excellent.

**Comment by anseki** [comment]
Hi @nate-clark-ii, thank you for the comment.
Sorry, my English is poor, then I couldn't understand your words. And your code seems to be strange. For example, `<rect>` element doesn't accept `calc()`. The `calc()` is CSS function.
I think that you should learn SVG and CSS at least.
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/rect
https://developer.mozilla.org/en-US/docs/Web/CSS/calc()

**Comment by nate-clark-ii** [comment]
Hi @anseki, thank you for the reply. The issue I am having is these lines outside of the box on scroll. I was thinking the issue was to do with my svg clip path, but I may be mistaken, I am not very familiar with svg.  See https://jsfiddle.net/59870cyq/

![image](https://user-images.githubusercontent.com/84359096/149345115-935b1e69-0657-4ce6-9716-dfd4939a70b9.png)

**Comment by anseki** [comment]
I see.
You have to adjust the SVG clip path with the lines.
This example may help you: https://github.com/anseki/leader-line/issues/54#issuecomment-499513836

**Comment by nate-clark-ii** [comment]
@anseki I appreciate the help. I was able to achieve my desired result by storing references to dynamically created lines and assigning them each a separate SVG mask per your method.

**Comment by anseki** [comment]
I'm glad if I could help you. :smile: 
FYI, you can use CSS `clip-path` instead of SVG `clip-path`. This may be easy way if you are beginner at HTML, CSS, SVG and JavaScript.
For example:
https://jsfiddle.net/dc0j7tgk/
