### ISSUE TITLE
[Help Wanted] Typescript / Angular usage

### ISSUE THREAD

**Issue by zak905** [anseki/leader-line#289]
Hi, 

I tried using the library from Typescript / Angular without luck. After importing the library using `npm`, I did `var LeaderLine = require('leader-line');` 

However the constructor invocation does not work when I use `new LeaderLine(document.getElementById('div1'), document.getElementById('div2'))`, I get `LeaderLine is not a constructor`

I also tried without the new keyword `LeaderLine(document.getElementById('div1'), document.getElementById('div2'))`, I get  `LeaderLine is not a function`

**Comment by zak905** [comment]
I found an example in StackOverflow https://stackoverflow.com/questions/54908009/angular-library-for-drawing-lines-between-objects

I hope it will help somebody

**Comment by anseki** [comment]
:smile:
