### ISSUE TITLE
How to add remove (x) icon to end of line

### ISSUE THREAD

**Issue by abinhho** [anseki/leader-line#291]
Thank you for your helpful library, I would like to ask how to add a remove icon to each line, the user clicks on that button and the line will be removed?

<img width="570" alt="Screenshot 2022-01-22 at 22 09 34" src="https://user-images.githubusercontent.com/9253378/150644124-cc555843-0e4c-46f9-891d-13341e0725a5.png">

**Comment by anseki** [comment]
Hi @abinhho, thank you for the comment.
You can do that very easily by using [`remove`](https://anseki.github.io/leader-line/#remove) method.
Call the method when the remove button is clicked.

**Comment by abinhho** [comment]
@anseki Thank you for your answer. But my question is how to add `x` icon. Not how to remove a line. 🙇

**Comment by anseki** [comment]
Sorry, my English is poor.
Could you explain that? For example, HTML, CSS, etc...?

**Comment by abinhho** [comment]
@anseki Are you Japanese? if so let's use Japanese.
Lineの削除ボタンを付けたいですが、どうやって作りますでしょうか？
例えば：
```
const line = LeaderLine(fromEl, toEl, {
    removeButton: '<span @onclick="line.remove()">X</span>'
})
```

以上、よろしくお願い致します！

**Comment by anseki** [comment]
Do you mean that you want to add the buttons dynamically?

**Comment by anseki** [comment]
If you want to add the buttons dynamically, you can do that by using DOM API.
For example: https://jsfiddle.net/0awz7gtd/
Click `X` buttons.

**Comment by abinhho** [comment]
@anseki Nice! thank you so much!

**Comment by anseki** [comment]
:smile: 
Could you close this issue?

**Comment by abinhho** [comment]
Closed!
