### ISSUE TITLE
Is it possible to do straight line with arc in center?

### ISSUE THREAD

**Issue by Smithpovvi** [anseki/leader-line#293]
I try to undarstand how I can realize it
![Screenshot 2022-01-27 102628](https://user-images.githubusercontent.com/71154144/151311371-dce1598d-521c-41c3-9194-b223beb3cd39.png)

**Comment by Smithpovvi** [comment]
![image](https://user-images.githubusercontent.com/71154144/151313411-863e06d3-ac99-4b57-8ba2-af187ac295bb.png)

**Comment by Smithpovvi** [comment]
![image](https://user-images.githubusercontent.com/71154144/151313492-9cd7abca-09a7-4414-9e03-8a555a7e5123.png)

**Comment by Smithpovvi** [comment]
> Hi @Smithpovvi, thank you for the comment. This may help you: https://jsfiddle.net/fs0ghLn3/

Thanks!)

**Comment by anseki** [comment]
:smile: 
Could you close the issue?
