### ISSUE TITLE
How can I configure SVG to be placed within a given dom,Because scrolling out of range is still displayed at the top, it is not hidden

### ISSUE THREAD

**Issue by littlesunnn** [anseki/leader-line#295]

**Comment by anseki** [comment]
Hi @littlesunnn, thank you for the comment.
Could you provide description?

**Comment by littlesunnn** [comment]
such as
<body>
  <svg/> // your default insert
  ...
  <div id="xxx">
    <svg/>  // i want to here, if "xxx" scroll, overflow:hidden not enabled 

  .....
  </div>
</body>

**Comment by littlesunnn** [comment]
![image](https://user-images.githubusercontent.com/34085134/152715684-4b9638c8-67ad-408f-b6d4-cf4a47b423e6.png)

**Comment by anseki** [comment]
You can move the SVG element to another element from `<body>` if you really want it.
For example:
```js
document.getElementById('container').appendChild(document.querySelector('.leader-line'));
```
Note that it is not supported, and it is deprecated.
This also may help you: https://github.com/anseki/leader-line/issues/54

**Comment by littlesunnn** [comment]
but this make svg position changed

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
