### ISSUE TITLE
Offset point of start and end along element

### ISSUE THREAD

**Issue by tobiasger** [anseki/leader-line#296]
By default it seems like the start and end point of a line is positioned in the center of whichever side you choose with `startSocket` and `endSocket`. Is there a way to create an offset, if I for example would like the start point to be placed at one of the edges of a element instead of at the center?

**Comment by tobiasger** [comment]
Ah, okay! I thought that it was only possible to use that with the end point. Thank you!

**Comment by anseki** [comment]
:smile:

**Comment by tobiasger** [comment]
I'm a bit uncertain about how to use the `pointAnchor` both on the start point and the end point. And also to be able to pass general options such as `size`, `path` etc to that. Are there any examples for using `pointAnchor` for both the start and end point and then passing options to that?

**Comment by anseki** [comment]
The [above document](https://github.com/anseki/leader-line/issues/296#issuecomment-1032819686) that I told you contains many examples. You can read those in the source code of the page.
