### ISSUE TITLE
Feature request: Custom pathLabel

### ISSUE THREAD

**Issue by tobiasger** [anseki/leader-line#298]
Would be nice if you could place either a custom SVG or a HTML element as the `pathLabel`. In my example I want to have circles with a number in it, and with the current options for `pathLabel`, it's not possible to do except for maybe using a custom font that would have the circle as part of the font.

**Comment by anseki** [comment]
Hi @tobiasger, thank you for the comment.
Sorry, my English is poor. Do you mean that you want to show an image such as SVG element instead of text?

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
