### ISSUE TITLE
Offset plug from edge of element?

### ISSUE THREAD

**Issue by c0bra** [anseki/leader-line#3]
There may be an easy way to do this; if so, my apologies.

I'd like to find a way to offset a plug from its target element by an arbitrary amount of pixels.  I see that you can set the x,y coords relative to element but without knowing which side or point the plug will be at there's not a way to find which direction the offset should be in.

**Comment by anseki** [comment]
When [`startSocket`/`endSocket`](https://anseki.github.io/leader-line/#startsocket-endsocket) is `auto` (default), the closest side is chosen automatically.
Do you mean that you want to get the chosen side?

**Comment by c0bra** [comment]
No I mean instead of this:

![image](https://user-images.githubusercontent.com/105007/34399541-ce6502e8-eb4d-11e7-96ff-2488f0fb7c6c.png)

I want to be able to set an offset of, say 10px:

![2017_12_27_21_39_09_leaderline](https://user-images.githubusercontent.com/105007/34399630-b357f658-eb4e-11e7-8d9a-8b5e088328e7.png)

**Comment by anseki** [comment]
[`pointAnchor` attachment](https://anseki.github.io/leader-line/#pointanchor)  allows to set the offset.
`x` and `y` options specify coordinates relative to the element.

**Comment by c0bra** [comment]
Right but I would need to know the side first. If the anchor point was on the right it would be

x: 10px, y: 50%

**Comment by anseki** [comment]
When startSocket/endSocket is auto (default), the closest side is chosen automatically.
Do you mean that you want to get the chosen side?

**Comment by c0bra** [comment]
Yes, getting the chosen side would work.

**Comment by anseki** [comment]
Does the "offset" you said mean the near direction always?
In other word, do you want to make a gap between the element and the arrow?
So, do you want to do this?:
https://jsfiddle.net/wf76eqk2/

**Comment by c0bra** [comment]
Yes that's perfect! Thank you!

**Comment by anseki** [comment]
😄 
One more example of several ways.
It's more simple, easy and more high performance (less elements), maybe.
https://jsfiddle.net/owdtb3uy/
