### ISSUE TITLE
Not drawing lines in inactive bootstrap tab

### ISSUE THREAD

**Issue by orctom** [anseki/leader-line#301]
Hi there,

https://jsfiddle.net/b75zk4nu/4/

Those boxes are in the 2nd tab, not drawing the line.
If moved to the 1st (default active) tab, it draws.

I would `new LeaderLine()` on clicking the 2nd tab as the work around.

**Comment by TigranAdoyan** [comment]
Hi orctom 
This is should work
`var line = new LeaderLine(
  document.getElementById('callout'), 
  document.getElementById('test'),
  {
    path: 'arc', 
    color: 'red', 
    size: 2, 
    endPlug: 'arrow1',
    hide: true
  });
  
const homeButton = document.getElementById('home-tab');
const contactTab = document.getElementById('contact-tab');

contactTab.addEventListener('click', function() { line.show(); });
homeButton.addEventListener('click', function() { line.hide(); });`

**Comment by anseki** [comment]
Hi @orctom, @TigranAdoyan, thank you for the comments.
This may help you:
https://jsfiddle.net/zut6eofr/
