### ISSUE TITLE
Increase line length

### ISSUE THREAD

**Issue by Poylar** [anseki/leader-line#302]
hi, thank you for your lib. 
Can I enlarge the line so that it follows the edge of the container? ( I draw red line)
![Screenshot_4](https://user-images.githubusercontent.com/45768057/157200223-43906ff2-773b-4402-a0c1-6d96d07d4b5d.png)

`
let line = new LeaderLine(document.querySelector(`.start-line-1`), document.querySelector(`.end-line-1`), {
  path: 'grid',
  endPlug: 'behind',
});

line.setOptions({ startSocket: 'right', endSocket: 'right' });

`

**Comment by anseki** [comment]
Hi @Poylar, thank you for the comment.
You can adjust the line by `*SocketGravity` option.
For example:
https://jsfiddle.net/1n89z32e/

**Comment by Poylar** [comment]
thank you, that works. one more questions: 
how i can increase space around my titles?i need add more margin from title to line.

**Comment by anseki** [comment]
Could you explain more?
What are the titles?
Could you show an example by using e.g. https://jsfiddle.net/ ?

**Comment by Poylar** [comment]
so i just wanna remove this (increase spaces) 
![Screenshot_5](https://user-images.githubusercontent.com/45768057/157227675-35f001a3-b7e8-4ef1-817c-07b9964ae080.png)

**Comment by Poylar** [comment]
cut line

**Comment by Poylar** [comment]
justr can i control line lenght?

**Comment by anseki** [comment]
Do you mean that you want to specify a point to join the line?
If so, you can use `pointAnchor`.
For example: https://jsfiddle.net/20xqf7bt/

**Comment by Poylar** [comment]
for some reason jsfiddle dont work for me. can you codepen pls?

**Comment by anseki** [comment]
This is result of the example.
![ss01](https://user-images.githubusercontent.com/4763469/157232807-dd71caf1-5a42-4097-ba39-809fc4afddaa.png)
If you want to run the example in CodePen, you can do that by just copying the code.

**Comment by Poylar** [comment]
i mean website jsfiddle dont open for me

**Comment by Poylar** [comment]
https://codepen.io/poylar/pen/yLPWMpK
can you check pls. when i set pointAnchor, my 'setOptions' is broken or what I do wrong?

**Comment by anseki** [comment]
See: https://codepen.io/anseki/pen/PoOvpRb

**Comment by Poylar** [comment]
thank you!!

**Comment by anseki** [comment]
:smile: 
Could you close this issue?
