### ISSUE TITLE
How start drawing on viewport?

### ISSUE THREAD

**Issue by Poylar** [anseki/leader-line#303]
I flipped through 3 pages but did not find a similar question and it is not entirely clear from the documentation for me personally how to use it.
Question: how to draw a line when the page loads? How to specify these parameters correctly? Is there any codepen

**Comment by anseki** [comment]
Hi @Poylar, thank you for the comment.
You can use [`Window#load`](https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event) event to do something when the page is loaded.
For example:
```js
addEventListener('load', () => {
  // Do something here
});
```
This is specification of DOM, not LeaderLine.

**Comment by anseki** [comment]
Codepen that works when the page is loaded is here:
https://codepen.io/anseki/pen/PoOvpRb

**Comment by Poylar** [comment]
yes i know about window.onload, but i want to set animation 'draw'  when onloaded. i try to line.show() on load and this 'fade' effect, but i want 'draw' effect. and how i can set line hide by default ?

**Comment by anseki** [comment]
You can use [`hide`](https://anseki.github.io/leader-line/#hide-option) option that is constructor option to hide the line until `show` method is called.

**Comment by Poylar** [comment]
okay, but my first questions?
this dont work
`
  line = new LeaderLine(elmStart, LeaderLine.pointAnchor({ element: elmEnd, x: elmEnd.getBoundingClientRect().width + 90 }), {
    path: 'grid',
    endPlug: 'behind',
    startSocket: 'right',
    endSocket: 'right',
    startSocketGravity: document.querySelector('.container').getBoundingClientRect().right - elmStart.getBoundingClientRect().right,
    color: bodyStyle.getPropertyValue('--blue'),
    size: 1,
    showEffectName: 'draw',
    animOptions: { duration: 500, timing: [0.58, 0, 0.42, 1] },
  });

line.hide();

`

**Comment by anseki** [comment]
Sorry, what is that?
Could you explain more?
Also, it seems that you don't use `hide` option (not `hide()` method).

**Comment by anseki** [comment]
I don't know what you want to do, but this may help you:
https://codepen.io/anseki/pen/PoOvpRb

**Comment by Poylar** [comment]
yes, thank you.thats help!

**Comment by anseki** [comment]
:smile:
