### ISSUE TITLE
How I can use line.position() with custom path?

### ISSUE THREAD

**Issue by Smithpovvi** [anseki/leader-line#306]
![image](https://user-images.githubusercontent.com/71154144/159946971-2d7e1c9b-7c2a-4cad-9408-33d0876c7d6b.png)
I have this case, if I use line.position() path return default state.
![image](https://user-images.githubusercontent.com/71154144/159947246-80a34b12-8de6-4b42-88f7-6c50b4bf75b7.png)

**Comment by Smithpovvi** [comment]
And I want to implemented angle for line
![image](https://user-images.githubusercontent.com/71154144/159947559-866a7f96-bd42-40f0-a3ca-1860bf4e9f25.png)

**Comment by Smithpovvi** [comment]
My code for path modificate 
![image](https://user-images.githubusercontent.com/71154144/159948140-becbb62e-56e1-4d20-9662-90af71886aca.png)

**Comment by anseki** [comment]
Hi @Smithpovvi, thank you for the comment.
See this: https://github.com/anseki/leader-line/issues/293

**Comment by Smithpovvi** [comment]
Ah sorry I don't undarstand how I need calculate it. Because I have a line constantly changing depending on the position of two elements

**Comment by Smithpovvi** [comment]
![image](https://user-images.githubusercontent.com/71154144/160075135-238ff62d-cdfc-4fd1-b5e9-930dbd927c22.png)

**Comment by Smithpovvi** [comment]
general rule: disc indent 40pt, break in the middle of the horizontal (round point 32)

**Comment by anseki** [comment]
Yes, of course you can adjust those via `*SocketGravity` options.

**Comment by Smithpovvi** [comment]
Thanks, I will try

**Comment by Smithpovvi** [comment]
In my case this value should be 0 always? 
![image](https://user-images.githubusercontent.com/71154144/160090613-ca0ba04c-e30f-439d-a23e-236ccd2897d2.png)

**Comment by Smithpovvi** [comment]
this code +/- working but I have problem with scroll in the opposite direction
![image](https://user-images.githubusercontent.com/71154144/160091647-ef4ff99e-9d7d-448d-a4a2-7174fe11dfcb.png)

**Comment by anseki** [comment]
What is the problem with scroll in the opposite direction?

**Comment by Smithpovvi** [comment]
![image](https://user-images.githubusercontent.com/71154144/160092133-f5bd9296-b275-4fb4-add5-2cb66b319e6f.png)
![image](https://user-images.githubusercontent.com/71154144/160092188-c83ee5aa-f685-46ba-b841-faba522fd025.png)

**Comment by Smithpovvi** [comment]
Ah yes, I did need to repeat logic on scroll event)

**Comment by Smithpovvi** [comment]
It all right

**Comment by anseki** [comment]
Sorry, I couldn't understand that.
Do you mean that the issue was solved?

**Comment by Smithpovvi** [comment]
Yes, with *SocketGravity and Position()

**Comment by anseki** [comment]
:smile: 
Could you close this issue?
