### ISSUE TITLE
Mouse Click event on list of leader lines

### ISSUE THREAD

**Issue by ChenCheng2Cs** [anseki/leader-line#307]
I want to add event listener for leader lines in an array
I noticed that document.querySelector('.leader-line') can only access to first svg dom in an array.
How can I access to all other leader lines in the array
Thanks

**Comment by anseki** [comment]
Hi @ChenCheng2Cs, thank you for the comment.
You can get a `NodeList` by `querySelectorAll` method and get an element in the list by the index number.
For example:
```js
elementA = document.querySelectorAll(selector)[3];
elementB = document.querySelectorAll(selector)[999];
```
This is a method of DOM, not LeaderLine. Note that it is not supported by LeaderLine, then not recommended.
See document: https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
