### ISSUE TITLE
Is there a way to trigger manually the code called when resizing the window

### ISSUE THREAD

**Issue by hervegirod** [anseki/leader-line#308]
The code after line 5173 here : `window.addEventListener('resize', AnimEvent.add(function(/* event */) {`
trigger an update of the graphics when the window is resized. In my use case the target part of the arrow does no go where it should, but it does as soon as I resize the window. Note that if I just call `position ` it does not change the arrows. Is it possible to trigger externally the code called when resizing the window, which is:
```
      Object.keys(insProps).forEach(function(id) {
        update(insProps[id], {position: true});
      });
```

It seems that I am not able to access the `insProps` from outside the function.

Note that the creation of my LeaderLine is performed in a function triggered by the `onLoad` event, in:
`<body onload="initLines()">`

And I am doing:
```
     var line = new LeaderLine(
       document.getElementById(theStartDiv),
       document.getElementById(theTargetDiv)
     );
```

**Comment by anseki** [comment]
Hi @hervegirod, thank you for the comment.
Sorry, my English is poor.
What is the "the code alled"?
And, What does the "it does not change the arrows" mean? Do you mean that the `position` method throws an error?

**Comment by hervegirod** [comment]
Sorry, my fault, it was "code called" (a typo). I added two images showing the result before resizing the window manually, and afte
![example1](https://user-images.githubusercontent.com/1689829/160280998-02ea840f-945f-428a-ac88-24c4df8cb044.png)
![example2](https://user-images.githubusercontent.com/1689829/160280999-b1ff238b-07a9-4384-9b4a-dc4cc944f27e.png)
r

**Comment by hervegirod** [comment]
I understand my problem. It was linked to the fact that I changed a style, but this change was not propagated by the browser immediately. I had something like:
```
     document.getElementById("commentPanel").style.width = "250px";
     document.getElementById("mainContent").style.marginLeft = "250px"; 
```
With `commentPanel `being the left div, and `mainContent `the right div.
I added a top0 div as a parent of the two divs, and this code did the trick:
```
   document.getElementById("top0").style.display = 'none';
   document.getElementById("top0").offsetHeight;
   document.getElementById("top0").style.display = 'block';
```

**Comment by anseki** [comment]
I see. :smile: 
So, could you close this issue if it was solved?

**Comment by hervegirod** [comment]
Yes!!!

**Comment by hervegirod** [comment]
Close
