### ISSUE TITLE
Lines overflowing 

### ISSUE THREAD

**Issue by DAC696** [anseki/leader-line#314]
Hey there @anseki  hope you are doing fine 
I am using leader line in vuejs environment 
the issue i am facing is my leaderlines get overflown if they are in a container that has scrollable its like they exist and passover everywhere 

![image (2)](https://user-images.githubusercontent.com/59389498/163994983-2b11985c-40c1-4381-85c6-1c5ad07e28c9.png)

**Comment by DAC696** [comment]
https://www.awesomescreenshot.com/video/8474666?key=5d128a422ea293f005288483990e5599

video reference

**Comment by anseki** [comment]
Hi @DAC696, thank you for the comment.
Sorry, my English is poor.
Do you mean that you want to hide the line when it is moved to outside of the scrollable element?
If so, this may help you:
https://github.com/anseki/leader-line/issues/54#issuecomment-499513836

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
