### ISSUE TITLE
UPDATED: Can't see the lines but the relation between div is correct

### ISSUE THREAD

**Issue by carolinarjona** [anseki/leader-line#315]
Hello! 👋🏻
Nice to meet you all!

I'm a novice developer and I have some questions about some problems.

I'm using Angular and I'm trying to import leader-line in my project.

1. Intall with **npm i leader-line**
2. In angular.json:
**"scripts": [
              "./node_modules/leader-line/leader-line.min.js"
]**
4. At the top of the component.ts file:
**import 'leader-line';
declare let LeaderLine: any;**
5. In the ngAfterViewInit:
**const line = new LeaderLine(
      this.document.getElementById('card-34327'),
      this.document.getElementById('card-34328'),
);**

I'm also stop and re-start the project after install the library and I always have this problem in the console:
![image](https://user-images.githubusercontent.com/79989429/164427128-abea0208-7e6f-4f2a-a7fd-1ba319407553.png)

My cards (divs) are created dinamically and I add their ids, maybe that's the problem?

Thank you so much! Have a nice day! 😊

**Comment by anseki** [comment]
Hi @carolinarjona, thank you for the comment.
Maybe, the library was not loaded correctly in your project.
Are you using any online service such as StackBlitz?

**Comment by carolinarjona** [comment]
Hello @anseki!

I did a quick example here: https://stackblitz.com/edit/angular-ivy-zsiwjm?devToolsHeight=33&file=src/app/app.component.ts

Thank you!

**Comment by anseki** [comment]
Sorry, my English is poor.
Do you mean that you want to use StackBlitz?
https://github.com/anseki/leader-line/issues/315#issuecomment-1105023699

**Comment by carolinarjona** [comment]
Don't worry! 😊

No, I mean I show you a Stackblitz example with the error that I see in the console.

**Comment by anseki** [comment]
Is the error thrown even if your app runs as standard Angular project?
I recommend that run it as standard Angular project because it can work with e.g. Webpack.
The working with StackBlitz may be not easy. Also, I don't understand StackBlitz well, sorry. Maybe you had better ask to StackBlitz team.

**Comment by carolinarjona** [comment]
I'm using in a Angular project with Webpack and I don't know if I'm missing something when I have done the import of the library 😢

**Comment by anseki** [comment]
An example for `webpack.config.js` is here: https://github.com/anseki/leader-line/issues/8#issuecomment-370147614
You might have to adjust it for a version of Webpack that you use.

**Comment by carolinarjona** [comment]
Okay! I finally import it! 😁 But I have a new problem in the console: 'start and end are required' but I put the document.querySelector('card-1') and document.querySelector('card-2') in the constructor 🤔 .

**Comment by anseki** [comment]
You have to write `document.querySelector('.card-1')` (if you specified `class` attribute) or `document.querySelector('#card-1')` (if you specified `id` attribute).
This is specification of DOM.

**Comment by carolinarjona** [comment]
Okay! I finally have the start and the end 😊 But now I can't see the line. I did a console.log of the leaderLine and the connection is correct, but I don't see them 😅 What is happening?

Thank you!

**Comment by anseki** [comment]
I didn't see your code but I infer:

* Check that the start/end elements are shown correctly.
* Check that the elements were already positioned when the line is made. For example, you might make and position the elements dynamically,

Without reference to LeaderLine, when you develop something with web browsers, you should use DevTools.
You can use it for checks above also. For example, write `debugger` statement at a breakpoint that you want to check.
```js
debugger;
const line = new LeaderLine(document.querySelector('.card-1'), document.querySelector('.card-2'));
```
If you are using modern browser, the running is paused at the break point, and you can check the elements and you can do more in DevTools of your browser.
For example, input `document.querySelector('.card-1')` into "Console" (*not `console.log()`*), and push Enter key.

**Comment by carolinarjona** [comment]
Thank for your help, @anseki!

I have more doubts but I'm going to open another issue because it's different! :)

**Comment by anseki** [comment]
:smile:
