### ISSUE TITLE
Dynamic line connecting not working for angular

### ISSUE THREAD

**Issue by RaviGuggilam** [anseki/leader-line#317]
Dynamic rendering not working, below is the piece of code. Following packages are used for development ( "leader-line-new": "^1.1.9","ngx-leader-line": "^0.0.3",)

xxxxxxx.html
`<div
      #card{{i+1}}="ldrDest"
      ldrDest
      class="card custom-card"
      *ngFor="let data of details; let i = index"
    >
      <div class="card-header">Card {{ i + 1 }} Text</div>
      <div class="card-body">
        <button
          class="btn btn-secondary m-1"
          #start
          [ldrConnectTo]="button['targetCardNo']"
          *ngFor="let button of data.buttons"
        >
          {{ button.name }}
        </button>
      </div>
    </div>
`
--------------------
xxxxxx.json
[
  {
    cardNo: 1,
    text: "Card No : 1",
    buttons: [
      { name: "Yes", questionId: "q1", targetCardNo: 11 },
      { name: "No", questionId: "q1", targetCardNo: 11 },
    ],
  },
  {
    cardNo: 2,
    text: "Card No: 2",
  },
  {
    cardNo: 3,
    text: "Card No: 2",
  },
];

**Comment by RaviGuggilam** [comment]
but ngx-leader-line is wrapper on top of leader-line

https://www.npmjs.com/package/ngx-leader-line

**Comment by anseki** [comment]
No, I don't know that it is wrapper also.
Therefore, you had better ask to the team of those libraries.
