### ISSUE TITLE
[SOLVED] How to move an object along a path?

### ISSUE THREAD

**Issue by SuddenDevelopment** [anseki/leader-line#32]
thanks for his lib. it's great in what it does.

I'd like to leave a line in place for a while once drawn and move an object along it. I think I can do this pretty easy if I can get the path back from this library for a line created. Any advice?

**Comment by anseki** [comment]
Hi @SuddenDevelopment, thank you for the comment.
Sorry, my English is poor.
Do you mean that you want how to use motion path animation of SVG?
Or, do you mean that you want to get path data from drawn leader line?

**Comment by SuddenDevelopment** [comment]
when I draw a leader line with this library (which is very nice and easy to use) I want to be able to animate move an object like a div or an icon along that path. from source to destination.

**Comment by SuddenDevelopment** [comment]
yes, that's exactly what I want. and I can do that in svg.js but I need to give it a path. I want to give it the path from a created leaderline and I dont see any properties for that. Can you please tell me how to get a svg path for a created leaderline? thanks.

**Comment by anseki** [comment]
Try this:
```js
// After the line was created
document.querySelector('.leader-line .leader-line-line-path').getAttribute('d')
```
Note that it is not supported.

**Comment by SuddenDevelopment** [comment]
thanks, by the way. I have one some pretty fun stuff with this already. look forward to sharing it with you.

**Comment by SuddenDevelopment** [comment]
I have multiple lines on the same page, from what I can tell there's no way to get a unique query for a line. I dont think it passes back an id, I cant pass in an ID, or a class or something to uniquely identify and track it. I'm still looking

**Comment by SuddenDevelopment** [comment]
nevermind, I found it sorry for all the commentary. I'll post a gist on how to do it:
leader-line-2-line-path

**Comment by SuddenDevelopment** [comment]
for anyone looking for this same thing... when you create a line it returns an object with an "_id" property. You can use that to find the path and pass it to svg for other things.

document.getElementById('leader-line-'+intIdFromLine._id+'-line-path').getAttribute('d');
