### ISSUE TITLE
Leader Line Position causes lag when number of leader lines is high 

### ISSUE THREAD

**Issue by TinuTennyson** [anseki/leader-line#322]

**Comment by TinuTennyson** [comment]
I am using leader lines to show Dependency lines between different divs. When the number of lines are in hundreds, and I scroll the main div, I call the position method, but it appears very slow while repositioning. Takes 4 to 5 seconds to get redrawn to its new position after horizontal scroll. Surprisingly it doesn't lag at all on vertical scroll. Please let me known the solution to this problem

**Comment by anseki** [comment]
Hi @TinuTennyson, thank you for the comment.
Check whether the `position` method is called too frequently or not. The `scroll` event especially is fired too many even if you don't have to call the `position` method.
You can use e.g. [AnimEvent](https://github.com/anseki/anim-event/) library to control calling event listeners.

**Comment by anseki** [comment]
Or, you can move the SVG elements to the scrollable element instead of calling the `position` method if you really want it.
For example:
https://jsfiddle.net/6pw9edaj/
Note that it is not supported, and it is deprecated. You should not use this if you can't understand the logic.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.

**Comment by TinuTennyson** [comment]
Thanks.  Issue can be marked as resolved
