### ISSUE TITLE
The line is strange while using "grid"

### ISSUE THREAD

**Issue by lurise** [anseki/leader-line#323]
Hi, when I use the path of "grid", the line looks like very strange, what should I do to fix it?
![屏幕快照 2022-05-04 下午11 39 29](https://user-images.githubusercontent.com/48511899/166718636-c72f3062-aab4-4c71-bca5-c6ad8e5729c7.png)

**Comment by lurise** [comment]
tks for the awesome project, I have found solution from previous issues.

**Comment by anseki** [comment]
:smile:

**Comment by yuleiQ** [comment]
> Hi, when I use the path of "grid", the line looks like very strange, what should I do to fix it? ![屏幕快照 2022-05-04 下午11 39 29](https://user-images.githubusercontent.com/48511899/166718636-c72f3062-aab4-4c71-bca5-c6ad8e5729c7.png)



How do I solve the same problem？

**Comment by anseki** [comment]
Hi @yuleiQ, thank you for the comment.
See this: https://github.com/anseki/leader-line/issues/212#issuecomment-806435881

**Comment by anseki** [comment]
No reply came from @yuleiQ but the issue seems to have been already solved by solving of @yuleiQ's another issue. :smile:
