### ISSUE TITLE
Leader line gives error index.js:1 `baseWindow` was not found.  when using inside react new window library

### ISSUE THREAD

**Issue by zakim2307** [anseki/leader-line#324]
```js
const addConnections = (start, end, i, j, boolValue) => {
        if (isFirstRun.current.children[i].id && isEndRun.current.children[i].id) {
            console.log(isFirstRun.current.children[i], isEndRun.current.children[j].id, isEndRun.current.children[j])
            let line = new LeaderLine(isFirstRun.current.children[i], isEndRun.current.children[j], {
                hide: boolValue
            })
            lines[i][j] = line
            setEndValue(null)
        }
    }
```

adding this code in react new window which opens a new window for a particular reason which we are using 
gives the error stating 
`baseWindow` was not found.
we are using react new window and several other libraries its a huge project so
please help sos

**Comment by anseki** [comment]
Hi @zakim2307, thank you for the comment.
That is warning message.
Is there any problem? Could you explain the problem?

**Comment by zakim2307** [comment]
Thanks @anseki for the response, the problem is it gives an error when  like this
![Screenshot from 2022-05-10 15-16-50](https://user-images.githubusercontent.com/53618883/167600606-7d844018-c6c6-4357-9927-f73ba26aa4f3.png)

**Comment by zakim2307** [comment]
and the window closes automatically saying `baseWindow` was not found
and other error if you can see in the bottom says Uncaught error: cannot get frames
and as i have said we are using a library called react-new-window that opens react app in a new window in that window we are using this library

**Comment by zakim2307** [comment]
I believe that since we are opening it in a secondary window and not the main window it is giving this error so please if there could be an answer to this error

**Comment by anseki** [comment]
It seems that the target elements are contained in different windows. And the library can't access the window caused by security.
Could you show an example by using e.g. https://jsfiddle.net/ ?

**Comment by zakim2307** [comment]
im going to create a github repo for you a public repo that you can clone and see jsfiddle is good but dont know how to use

**Comment by zakim2307** [comment]
https://github.com/zakim2307/leader-line
check this repo please

**Comment by zakim2307** [comment]
check the remote branch or main branch please both have same code
thank you please check asap i am past my deadline

**Comment by anseki** [comment]
It seems that you mistook a repository to ask the question.
You are using "react-leader-line" (I don't know that), and this is a repository of "leader-line".
Then, you have to ask the question at a repository of the library that you are using, not here.

**Comment by zakim2307** [comment]
sorry bro and thanks anyways

**Comment by anseki** [comment]
It's ok. :smile:
