### ISSUE TITLE
Click events and pointer events for SVG

### ISSUE THREAD

**Issue by simondemai** [anseki/leader-line#325]
Hi Anseki, congratulations for your library which is incredibly useful and well done! 

Like many others, I need to add a click handler on the lines. I understand from your replies that this feature is not supported, but I really need that functionality on my app and I wonder if you can help me with a problem.

Following your advice, I'm using `querySelector('.leader-line:last-of-type')` to add an `EventListener` to the line and it works well. My problem is that the click event is active _on the entire bounding box_ and not only _on the line_. 

Here is a JSFiddle demonstrating the problem:
https://jsfiddle.net/pqkz9awL/

You will see that the line disappear when clicking on any point within the area with the red border.
Do you know of a way I can restrict the click handler to **only** the line?

Hope is clear, thanks in advance for your help.

**Comment by simondemai** [comment]
This is perfect! Thank you so much Anseki 🙂

**Comment by anseki** [comment]
:smile:
