### ISSUE TITLE
start socket and end socket only be left and right

### ISSUE THREAD

**Issue by Adyasha8105** [anseki/leader-line#327]
The string indicates which side of the element the leader line connects. It can be `top`, `right`, `bottom`, `left` or `auto`. If `auto` (default) is specified, the closest side is chosen automatically. This is what I got to know from the documentation.

But I want the leader line to be only `right` and `left` (according to the closet side) because this is what I am facing if I enable auto and it looks odd.

<img width="549" alt="Screenshot 2022-05-23 at 1 59 54 PM" src="https://user-images.githubusercontent.com/54095539/169777608-55e75b4e-27c0-447c-8932-1337c187028d.png">

@anseki Do let me know is there any way I can solve this issue? Other than that it's working awesome!

**Comment by anseki** [comment]
Hi @Adyasha8105, thank you for the comment.
This may help you: https://github.com/anseki/leader-line/issues/106

**Comment by Adyasha8105** [comment]
Hey, @anseki thanks for replying. I have a doubt about the function `update`. Can you tell me for right and left?
`
function update() {
  line.setOptions(
    draggable1.top < draggable2.top
      ? {startSocket: 'bottom', endSocket: 'top'}
      : {startSocket: 'top', endSocket: 'bottom'}
  ).position();
}
`

**Comment by anseki** [comment]
I'm glad if I could help you. :smile: 
Could you close this issue?
