### ISSUE TITLE
Multiple Steps for a Line

### ISSUE THREAD

**Issue by xMarkusSpringerx** [anseki/leader-line#328]
Hey, I want to draw a line for multiple points, this means, instead of drawing from start to end I have some other points which are in the middle but should still be covered.
Is there a way to achieve this? I'm happy to get some feedback.

<img width="841" alt="Bildschirmfoto 2022-05-24 um 10 52 48" src="https://user-images.githubusercontent.com/2272176/169991692-1e4fce5a-c732-4951-be7d-07020b38cf92.png">

**Comment by anseki** [comment]
Hi @xMarkusSpringerx, thank you for the comment.
Do you mean that you want to make the leader line indicate a point that is not `start`/`end` element?
You can use [`pointAnchor`](https://anseki.github.io/leader-line/#pointanchor), and you can make the leader line indicate anywhere in the document.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
