### ISSUE TITLE
On Hover: line color changes

### ISSUE THREAD

**Issue by Adyasha8105** [anseki/leader-line#329]
I want to change the color of the line on hover and I tried this example (https://jsfiddle.net/zbfokm5L/) but when my mouse is not in the line also the color changes. It's because of SVG. 

But @anseki  how can I change the color only when my mouse is exactly on the line like [this](https://dbdiagram.io/)?

<img width="385" alt="Screenshot 2022-05-24 at 6 37 27 PM" src="https://user-images.githubusercontent.com/54095539/170042201-42b04ad7-4e00-4a79-ad53-98734dcd28b0.png">

**Comment by anseki** [comment]
Hi @Adyasha8105, thank you for the comment.
Try this: https://jsfiddle.net/93jzcgno/
BTW, I don't think that this is good UI.

**Comment by Adyasha8105** [comment]
svg.leader-line {
  pointer-events: auto!important;
}

But then I can't able to drag the table.

**Comment by anseki** [comment]
No of course, the changing color and the dragging element have absolutely no relation to each other.

**Comment by anseki** [comment]
No reply came, but the issue was closed because it was already solved maybe. :smile:
