### ISSUE TITLE
Unable to draw lines on a popup window

### ISSUE THREAD

**Issue by vivekgn217** [anseki/leader-line#33]
Hi,

First of all this is an amazing library, but i noticed that we are not able to draw lines on a popup window. The line is drawn below it , is there a workaround for this ?.

Thanks in advance.

**Comment by anseki** [comment]
Hi @vivekgn217, thank you for the comment.
I don't know your popup window (library), but this may help you.
https://jsfiddle.net/pfnx0ehk/ (Click "OPEN" button)
Using [PlainModal](https://anseki.github.io/plain-modal/)

**Comment by vivekgn217** [comment]
Hi Anseki,

Thanks for the Prompt reply. I am using webix(framework) popup window. It looks like the z-index for webix popup is high so the drawings were drawn below the window. I have increased the z-index of leader line and its working fine. Thanks a lot for your support. Amazing work and support .

**Comment by harika-c** [comment]
Hi , 

Facing the same issue with LeaderLine  , line is forming under the popup and i tried the both ways which are mentioned above
Below is my code . Could you please help me on this

<div class="modal crt-skill fade"  id="myRpaMapModal" role="dialog">
                <div class="modal-dialog modal-md">
                    <div class="modal-content crt-content" id="modal-content">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <div class="modal-body">
                            <div class="form-contain">
                                <form onSubmit={(e) => e.preventDefault()}>
                                    <h1>Map Excel columns with Rpa </h1>
                                    <div className="params">

                                  
                                            <form onSubmit={(e) => e.preventDefault()} >
                                                <h5>Excel Parameters</h5>
                                                {excel.map((data, index) => (
                                                    <div key={index} class="frm-block" >

                                                        <input draggable="true" id="start" ref={this.myRef}  onDragStart={(e) => { this.dragStart(e, index) }} disabled="disable" value={data} type="text" />
                                                    </div>
                                                ))}
                                            </form>
                                            {/* <canvas id="drawContainer" width="100" height="500"  ></canvas> */}
                                       
                                            <form onSubmit={(e) => e.preventDefault()} >
                                                <h5>RPA Parameters</h5>
                                                {keys.map((data, index) => (


                                                    <div key={index} class="frm-block" >

                                                        <input  id="end" ref={this.myRef1} onDrop={(e) => { this.drop(e, index) }} onDragOver={(e) => { e.preventDefault(); }} disabled="disable" value={data.inputPlaceHolder != "" ? data.inputPlaceHolder : (data.inputLabel != "") ? data.inputLabel : ""} type="text" />
                                                    </div>


                                                ))}
                                            </form>
                                        

                                    </div>
                                    <div class="frm-btns">
                                        <button class="btn-outline" onClick={() => this.handleIgnore()} data-dismiss="modal">Ignore & Play</button>
                                        <span onClick={() => this.handleSubmit()} class="primary-btn" >Accept & Play</span>
                                    </div>
                                </form>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div >

**Comment by anseki** [comment]
Hi @harika-c, thank you for the comment.
Could you explain about the "both ways" you said?

**Comment by harika-c** [comment]
@anseki  1. using PlainModal ,when i trying to access modal using the below statement 
var modal = new PlainModal(document.getElementById('modal-content'));  i was getting this  error : 'PlainModal' is not defined  no-undef   . Even though i added the script tag in my html file , component file <script src="plain-modal.min.js"></script> 
2. I have increased the  z-index value to 2   for #start , #end .  (Please correct me if im doing something wrong here)

**Comment by anseki** [comment]
You mistook the URL of  PlainModal maybe.
Try this example: https://github.com/anseki/leader-line/issues/33#issuecomment-443587661

**Comment by harika-c** [comment]
thanks for replying , it is working now i had to add leaderline script tag and the below css in my css file .
.leader-line {
    z-index: 9001;
  }

Thank you so much @anseki

**Comment by anseki** [comment]
:smile:
