### ISSUE TITLE
leader line leaves its original position after resize

### ISSUE THREAD

**Issue by Shahidkhan997** [anseki/leader-line#332]
hi i am facing issue with leader lines its changes position after zoom in zoom out in browser and also resize

**Comment by anseki** [comment]
Hi @Shahidkhan997, thank you for the comment.
It seems that there is no problem with zooming in/out in my browser and environment.
![ss01](https://user-images.githubusercontent.com/4763469/170456548-4337ff64-f029-4b13-b7fb-7ff3a22898cf.gif)
Could you explain your situation?

**Comment by Shahidkhan997** [comment]
@anseki  i am using angular facing issue on redrawing leader lines on same component but it is working fine when i load it for the first time..

**Comment by anseki** [comment]
I can't find the bug in your code because I didn't read the code but I guess that you didn't call [`position`](https://anseki.github.io/leader-line/#position) method.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
