### ISSUE TITLE
Leader line startPlug position is not at midpoint of any side

### ISSUE THREAD

**Issue by omkarajagunde** [anseki/leader-line#333]
Hello there,

First of all loved your work on LeaderLine as well as PlainDraggable, its simply awesome and in detailed library with extensive controls, thanks for giving such a library to the world

I was trying to implement some project where the startPlug is showing on the left top corner instead of midpoint of top or left side, how can i solve this problem, below are the screenshots of the same

this startPlug is actually a div having PlainDraggable so when i move this big div around and call line.position() it actually re positions correctly on the midpoint of respective side but when i save all the values and try to load the LeaderLine with these values then the below result is produced

Blue arrow shows the correct starting point that it must show for startPlug

![Screenshot 2022-06-04 at 11 34 54 AM](https://user-images.githubusercontent.com/50138744/171986990-da74446e-76e0-47e9-bc3d-24d591a5a7e4.png)

Because of this the arrows get overlapped on starting div

![Screenshot 2022-06-04 at 11 39 15 AM](https://user-images.githubusercontent.com/50138744/171987006-7ac66b7a-b6ce-4535-b1e8-ef97813383db.png)

**Comment by anseki** [comment]
Hi @omkarajagunde, thank you for the comment.
Sorry, my English is poor, then your words are difficult for me.
Do you mean that the `position()` method works correctly when other than the loading?
Maybe, you called the method  too early. You have to call the method after those elements are rendered. That `<div>` has no size yet. In other words, the line was joined at the midpoint of the element correctly, after that, the element was resized.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.

**Comment by omkarajagunde** [comment]
Hey @anseki, 

im really very very sorry for replying this late sir, got caught up with few other things, but you were correct as always :), the above issue was solved, i was calling LeaderLine() constructor first and then my div's width was getting calculated and applied, so now i waited till the div's width is applied then gave call to LeaderLine(),

As always thanks for your prompt help! We here really appreciate your work in making and putting LeaderLine as well as PlainDraggable here under MIT license, 

Also we would really love to hear your programming journey, experiences, story behind creation of LeaderLine & PlainDrggable, and please sir your english is good, you are always clear with your thoughts we feel, i really respect you for your js skills, i also admire and aspire you to contribute something really useful from my end in opensource, can you guide me and be my mentor for the same? (I don't whether this is the right platform to talk this or not)

Wish you a healthy and prosperous life, thanks again and sorry for making this reply big one...

**Comment by anseki** [comment]
Don't worry. :smile:
