### ISSUE TITLE
Determine the direction of middle part of leader line

### ISSUE THREAD

**Issue by TinuTennyson** [anseki/leader-line#334]
Hi 

Could you please let me know if there's a way to find out the direction of the middle portion of the leader line, 
the scanario is this, i have multiple divs which i am connecting via leader line, but i need to show an arrow in middle for which im using
              middleLabel: LeaderLine.captionLabel('▼', {fontSize: 10, outlineColor: 'grey'}),

Now the thing is that sometimes for  few lines the middle portion line of the leader line is vertical and sometimes its horizontal, i need to find a way to correctly direct the arrow icon in middle portion segment of leader line based upon if its vertical or horizontal, or whether the endplug is to the left of start plug or to the right etc.

**Comment by anseki** [comment]
Hi @TinuTennyson, thank you for the comment.
You should face the issue https://github.com/anseki/leader-line/issues/322 that is not solved yet before this issue because that may affect this issue.

**Comment by TinuTennyson** [comment]
I'm sorry...do you mean you want me to close the issue 322 ?

**Comment by anseki** [comment]
It's OK. :smile: 
It seems that the issue was already closed by a bot.

Sorry, my English is poor.
Do you mean that the issue https://github.com/anseki/leader-line/issues/322 was solved? And doesn't it affect this issue?

**Comment by TinuTennyson** [comment]
Yes...your solution to previous issue #322 helped, could you please help out with this new one i've stated above?

**Comment by anseki** [comment]
Do you mean that you want to specify the `startSocket`/`endSocket`?
If so, you can use `setOptions` method.

**Comment by anseki** [comment]
Does the "middle line segment" mean a part of a line?
If so, you have to check the path data of `<path>` of SVG because that is made by multiple things.
Then, you can get an angle of the point from the bezier curve.

**Comment by anseki** [comment]
If the path has vertices, `marker-mid` attribute (or CSS property) makes markers.
For example:
https://jsfiddle.net/5tcqa7pr/

**Comment by TinuTennyson** [comment]
![ll_d](https://user-images.githubusercontent.com/6064262/174128616-ba9a0510-3a75-4851-8cad-e004d40ac864.jpg)

**Comment by TinuTennyson** [comment]
i mean i want to know if there's any way in leader lien to find out whether we can get any information regarding the mid lien segment which i have encircled. i am planning to attach a arrow in this middle line segment but to find out the direction towards which the arrow should point (Example Downwards in this case) i need to know in which direction the middle line segment is whether its horizontally positioned or vertically

**Comment by anseki** [comment]
Try this: https://jsfiddle.net/yzk8nshd/
Note that this is not supported by the library.

**Comment by TinuTennyson** [comment]
Thanks Anseki...i will try with your given example. Issue can be closed for now.

**Comment by anseki** [comment]
:smile:
