### ISSUE TITLE
LeaderLine not working

### ISSUE THREAD

**Issue by vaniekwan** [anseki/leader-line#336]
Hi ,
I'm really new in web and ,  
I was trying to implement the library , however it is giving me an error message 
"Content-Type is not a script MIME type ", I've been trying to solve it , however I can't seem to find any solution 

thank you very much

**Comment by anseki** [comment]
Hi @vaniekwan, thank you for the comment.
That error message seems to have been thrown by your web browser when the web browser was trying to load the script file. That is, the error message is not from the library. The library is not loaded yet.
The MIME configuration of your web server seems to be wrong. For example, if you are using Apache web server, add this to configuration of the server.
```
AddType text/javascript .js
```

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
