### ISSUE TITLE
Line always on top

### ISSUE THREAD

**Issue by RamonRodriguez05** [anseki/leader-line#337]
Hello, 

I have the next question: i have joined to elements with a line and its correct, but when i move one element and there is other elements in my page, the line goes behind and i need it always on top. Is that possible? I attach two images: one with the arrow right and the other with the arrow behind the element. I hope you understand what im saying. If it's possible to be always on top, could you give me an example code, please? Thank you so much
![Correct arrow](https://user-images.githubusercontent.com/38938362/176307963-91e5319c-f37b-45f3-b1cd-eaf86864b7aa.png)
![arrow back](https://user-images.githubusercontent.com/38938362/176307965-d06960c7-e2f7-4ab6-8e74-84832c0b590f.png)

**Comment by anseki** [comment]
Hi @RamonRodriguez05, thank you for the comment.
You can specify the `z-index` CSS property.
For example:
```css
.leader-line {
  z-index: 99;
}
```
Note that it is not supported by the library.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
