### ISSUE TITLE
Need to be able to specify the container for the SVG elements

### ISSUE THREAD

**Issue by rmwiseman** [anseki/leader-line#338]
First, thanks for this excellent little package!

I think I might be trying to use it in a slightly unorthodox way, as I've got a scrollable DIV element (i.e., `overflow:auto`) that contains the elements being joined by arrows.  The arrows' SVG elements are added to the body element, however, which means that they are visible even for overflowing elements.

Would it be straightforward to added an option to specify to which container element the arrows are added?  If I can add the arrows to the scrollable DIV, then they will stay correctly positioned regardless of the scroll position.

**Comment by anseki** [comment]
Hi @rmwiseman, thank you for the comment.
You can move the SVG element to another element from `<body>` if you really want it.
For example:
```js
document.getElementById('your-container').appendChild(document.querySelector('.leader-line'));
```
Note that it is not supported, and it is deprecated.
This also may help you:
https://github.com/anseki/leader-line/issues?q=is%3Aissue+querySelector
https://github.com/anseki/leader-line/issues/54

**Comment by rmwiseman** [comment]
Many thanks for the swift reply.  I'll give that a try.

**Comment by anseki** [comment]
:smile:
