### ISSUE TITLE
Draw line inside the container instead <body> tag

### ISSUE THREAD

**Issue by tonoai** [anseki/leader-line#34]
Hi develop team,

Can I draw the connector between to div inside the parent container, which has the scroll bar?

Thank you

**Comment by anseki** [comment]
Hi @tonoai, thank you for the comment.
Yes of course you can draw the line anywhere in a document.

**Comment by tonoai** [comment]
Hi @anseki,

I have the container (the gantt chart (we can scroll in this container).), and I wanna draw the line between 2 elements of this containter.
But, the line is not inside the container  It looks drawing base on the body tag.
How I can use it?

Thanks

**Comment by anseki** [comment]
You seem to mix two meanings about "inside":

1. In HTML structure, the element as the line is added into `<body>` element.
2. In view of web browser, the line is positioned at the inside of the target element (i.e. container).

You can position the line regardless of HTML structure.
And, you can re-position it by `position` method when elements are moved.
For example: https://anseki.github.io/leader-line/#position
You will see an example that draw a line in scrollable element.

**Comment by anseki** [comment]
To allow definite lines drawing and positioning accurately, those should be positioned based on document. And those should avoid being affected by other elements or something.
The option that changes the structure makes many problems.

You can move the element to another element from `<body>` if you really want it. However it is not supported.

**Comment by anseki** [comment]
BTW, a leader line is added to the innermost document that has two target elements.
Therefore, the line is added to your container instead of outer `<body>` if you use `<iframe>` element as the container.

**Comment by tonoai** [comment]
Thank you

**Comment by anseki** [comment]
:smile: 
Could you close this issue if it was solved?

**Comment by tonoai** [comment]
yes, sure :D
