### ISSUE TITLE
Can not set id of a leader line

### ISSUE THREAD

**Issue by sagarpdesai** [anseki/leader-line#341]
There is no option to set ID of a leader line.

**Comment by anseki** [comment]
Hi @sagarpdesai, thank you for the comment.
In ECMAScript, you can add properties to an object (LeaderLine instance).
```js
const line = new LeaderLine(...);
line.id = 'YOUR-ID'
```

**Comment by sagarpdesai** [comment]
Thanks @anseki for the prompt response, but that is not what I am looking for.
I am looking for some way to add an id attribute to the <svg> element itself so that the element can be later manipulated using d3 or some other library. 

I am also looking for some way to add click events to the leader line itself. Do you have any suggestions on implementing events?

**Comment by anseki** [comment]
You can get the `<svg>` element without adding ID.
```js
const svg = document.querySelector('.leader-line');
```
Note that it is not supported by the library, and it is deprecated.

**Comment by sagarpdesai** [comment]
I am trying to use leader-line to create a workflow diagram, so I will be having multiple leader lines. I need to provide actions (remove, add label, etc. ) on the leader-lines. So, I need some unique identifier on each leader-line.

**Comment by anseki** [comment]
Of course you can also add ID to the `<svg>` element via DOM API.
```js
svg.id = 'YOUR-ID'
```

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
