### ISSUE TITLE
Lines are not clickable in Angular & Devtools

### ISSUE THREAD

**Issue by eukuz** [anseki/leader-line#342]
Thank you for this great library :)

I'm trying to create an angular app where lines are deleted with double click on them (just like in [issue #325 ](https://github.com/anseki/leader-line/issues/325)). 

The problem is that lines are not clickabe. Moreover, they cannot be selected from the devtools ([screenshot](https://ibb.co/4SG5J9n))

You can find the source [here](https://github.com/eukuz/forLeaderLineIssue) (for some reason lines don't show up when running this repo from [stackblitz](https://stackblitz.com/github/eukuz/forLeaderLineIssue))

How to make the lines clickable inside an angular application?

**Comment by anseki** [comment]
Hi @eukuz, thank you for the comment.
This may help you: https://github.com/anseki/leader-line/issues/70#issuecomment-536640174

**Comment by eukuz** [comment]
I understand _how to_ add an Event Listener, the problem is that the lines cannot be clicked :) 
please, have a look at the ([screenshot](https://ibb.co/4SG5J9n))

**Comment by anseki** [comment]
Do you mean that this CSS code did not work?
```css
svg.leader-line { pointer-events: auto!important; }
```
If so, it might conflict with something in your CSS code.

**Comment by eukuz** [comment]
Thank you very much, my friend) This property solved my problem.

I suggest you make a short Q&A section in the Readme about what is not supported and deprecated, but is often requested. :)

Have a nice day 🌞

**Comment by anseki** [comment]
:smile:
