### ISSUE TITLE
vue3 how to use

### ISSUE THREAD

**Issue by pengyinghao** [anseki/leader-line#346]
<img width="917" alt="image" src="https://user-images.githubusercontent.com/34115313/180348865-2b2a8196-2128-4d2d-8cee-a016abb8a69a.png">
<img width="503" alt="image" src="https://user-images.githubusercontent.com/34115313/180348883-9c7364cf-2f58-45e1-8d46-5f99a72561e6.png">

**Comment by anseki** [comment]
Hi @pengyinghao, thank you for the information. :smile:

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
