### ISSUE TITLE
No licence? 

### ISSUE THREAD

**Issue by Nurech** [anseki/leader-line#350]
Your MIT licence on [README.md](https://github.com/anseki/leader-line#readme) badge link leads nowhere, please update it. 
https://github.com/anseki/leader-line/blob/master/LICENSE-MIT

**Comment by Nurech** [comment]
Created PR https://github.com/anseki/leader-line/pull/351

**Comment by anseki** [comment]
Hi @Nurech, thank you for the report. :smile:
