### ISSUE TITLE
arc of fixed height

### ISSUE THREAD

**Issue by devashishp1999** [anseki/leader-line#352]
Hi, I want to make the arc of fixed height irrespective of the distance between two "div" elements.

[JsFiddle Link to Demo code](https://jsfiddle.net/devashishpujari/rk9q2byo/14/)

Everything is perfect and I've got the desired result except **1 issue**

Behind the scenes the library is using `C = curveto` for path.
Can I modify It to `Q = quadratic Bézier curve` Manually? So that its height of the arc can be fixed between two elements.

Thanks for the amazing library

**Comment by devashishp1999** [comment]
`document.getElementById('leader-line-1-line-path')` Not supported?
Will this☝️ overwrite the `<path>` values that are set/generated by the library?

**Comment by anseki** [comment]
No, `getElementById` method doesn't change the element. It only gets the element.
https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementById

**Comment by devashishp1999** [comment]
Firstly, thanks a lot for a response!

Yes, the method returns  an element(s) for a CSS selector passed. I was asking, Is it **not-supported** by the library? or what you meant by that.

Actually I wanted to achieve following UI.

![image](https://user-images.githubusercontent.com/34485206/186605860-c379fca9-e695-4cd2-951a-e30e60e16006.png)

It's a number-line and a hopping arrow with some additional interaction features. 
I want the functionality like what I've shown in [this jsFiddle](https://jsfiddle.net/devashishpujari/xh2n9m5w/17/).

I was struggling to create a triangle at the end & the Leader-Line has some more cool customisation features to implement without learning more about `<svg>`.

OR there could be an additional feature in Leader-Line library to create a line with these features. I just wrote a basic function for this.😇

> function drawArc(rect) {
     const { width, height } = rect?.getBoundingClientRect();
     return `M 0 ${height} q ${width / 2} -${height} ${width} 0`;
}

Thanks for your time <3.

**Comment by anseki** [comment]
Yes, is it not supported by the library.
Sorry, my English is poor.

**Comment by anseki** [comment]
[bot] No reply came, then this abandoned issue is closed.
