### ISSUE TITLE
How would I draw a self-loop 

### ISSUE THREAD

**Issue by QadiymStewart** [anseki/leader-line#353]
![image](https://user-images.githubusercontent.com/28968495/187685514-058a120a-b8a6-435e-96ec-ad3e0d998698.png)

Trying to replicate a self-loop but library crashes, how would I go about implementing? Basically, if Source == Target create a loop line.

**Comment by anseki** [comment]
Hi @QadiymStewart, thank you for the comment.
Sorry, my English is poor.
What does the "library crashes" mean? Was any error thrown?
Also, what is "self-loop"?

**Comment by QadiymStewart** [comment]
I get the following 
![image](https://user-images.githubusercontent.com/28968495/187767099-7e2bd7c8-0255-44d9-aa35-8ac1805df966.png)

Apart from that I'm trying to re create the line circled in red in previous comment.

**Comment by anseki** [comment]
That error message means that your code has a bug.
Could you show your code?

I couldn't understand the image that was indicated by the red circle.
Are there two lines in the circle?
1. The element "UnknownActivity1" to the element "651"
2. The element "651" to the element "UnknownActivity1"

**Comment by anseki** [comment]
If you want to draw a line from an element to the same element (is this "self-loop"?), you can use [`pointAnchor`](https://anseki.github.io/leader-line/#pointanchor).
For example:
https://jsfiddle.net/fhd7bxuo/

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
