### ISSUE TITLE
Not usable as a "real" npm module

### ISSUE THREAD

**Issue by witek** [anseki/leader-line#354]
LeaderLine is not usable as a "real" npm module with `require()` because it does not export itself properly.

Solution would be to add the following as the last line of the source code:

```javascript
module.exports = LeaderLine;
```

**Comment by anseki** [comment]
Hi @witek, thank you for the comment.
For loading the library, see document: https://anseki.github.io/leader-line/#usage
If you want to import the library, use a packer such as Webpack.
For example: https://github.com/anseki/leader-line/issues/199
