### ISSUE TITLE
Put leader lines in the background behind a modal

### ISSUE THREAD

**Issue by Zander1983** [anseki/leader-line#356]
When I pop up a modal, the leader lines still show through the modal. Is there something I can do with CSS to prevent this? I tried changing the z-index, but it didnt help

![Screenshot 2022-09-16 at 19 36 47](https://user-images.githubusercontent.com/996960/190708491-d8523984-9bd1-43ae-a992-4c726687e262.png)

**Comment by anseki** [comment]
Hi @Zander1983, thank you for the comment.
I don't know why the CSS `z-index` property didn't help you. Could you show an example?
That usually works fine.
For example: https://jsfiddle.net/hq5n79td/

**Comment by Zander1983** [comment]
That worked! Thank you. I was putting the z-index: 0 on the SVG. I did as you did and put on the modal and works perfectly.

**Comment by anseki** [comment]
:smile:
