### ISSUE TITLE
Add the possibility to use a different parent than the body

### ISSUE THREAD

**Issue by julientaq** [anseki/leader-line#359]
Hi there
Thanks for your work on leader-line, pretty cool stuff.

I’m making webcomic, and i’d like to test the possibility to build leader-line to link text blocks.

I’m using different section with css `:target` to show/hide part of the comics. The line not being children of the section, i need to add some js while my css would have done the job.

I read in previous issues that you say to move them using javascript, but if we could define the `parent` in the function, it would be much more usable.
 
That would also allow custom CSS for the lines depending on their location in the DOM.

**Comment by anseki** [comment]
Hi @julientaq, thank you for the comment.
Sorry, my English is poor.
Why do you think that the function is usable more than JavaScript? Also, is the "function" not JavaScript? Do you mean that you want to use CSS functions to change the DOM tree?

BTW, you can move the SVG element very easily because you have to add just one line to your code.

**Comment by julientaq** [comment]
I hope you can understand me correctly, feel free to tell me if something is unclear, not easy when english is neither your or my native language.

What i mean is that you can’t really use css to change the DOM tree, but you can use the browser for more and more things, without js.

For example

```css

#this {
    display: none
} 

#this:target {
    display:block
}
```

The element `#this` will only be displayed, if it’s a target of a link, without any js needed.

You can end up making a multi page on a single url without any js to move between pages.

That means that we can leverage this to show/hide stuff on the screen based on the DOM tree. But the markup need to be quite specific.

> BTW, you can move the SVG element very easily because you have to add just one line to your code.

That’s what i ended up doing. For each `section`, creates all the lines and move them to the parent. I think i understand why you may think it’s not needed in the library. Now i need to figure out how to give ID and classes to each of them so i can manipulate them easily.

This library is very friendly to use, and also very powerful. You did a great job there :)

**Comment by julientaq** [comment]
I managed to do what i wanted,

I think it would be nice to add in the doc how to add id and classes  to the svg in the docs. Even if it’s not “supported” by the library, it’s pretty useful to know how to manage those.

```
outputArray.push(new LeaderLine(array[index], array[index + 1], options ));
  
document.querySelector('body>.leader-line:last-of-type').id = `${idwrap}-${el.classList}-${index}`; 
```

**Comment by anseki** [comment]
Ok. :smile: 
FYI, the selector `body > .leader-line:last-child` is better for almost cases.

Thank you for your suggestion about document, but that should not be added to the document because that it is not supported and it is deprecated, as mentioned in the past issues.
Maybe you are not beginner, then you can move the element if you want.
Good luck :v:

**Comment by julientaq** [comment]
Thanks, i managed to make it work.
 
Also, if it’s deprecated and not supported, what other options do we have to add id and classes?

Thanks again for the great work

**Comment by anseki** [comment]
> Also, if it’s deprecated and not supported, what other options do we have to add id and classes?

You don't have to add ID and classes to get the element if you draw lines by yourself.
Usually, you can draw lines easily by using e.g. SVG. LeaderLine is a library for beginners. That is, if you want to draw line and make DOM or SVG for you, you should not use LeaderLine.
Or, use another library that you like. You can find a library that is more customizable. Typically, best way is using no library.
