### ISSUE TITLE
Multiple lines positioning.

### ISSUE THREAD

**Issue by saieen** [anseki/leader-line#36]
Hello

I really like this plugin as its perfect for a small project i'm working on. Does 95% of the job very well except for 1 little issue. I have a fixed menu on the left which can be expanded / collapsed as desired. When this menu expands / collapses, the lines become disconnected with their elements. If it were 1 line i would have used the position method to update its position. but i will have 10s of lines between different elements. How can i update position of all these at once when menu is opened / closed? I have the screen shots attached to show before and after menu opens and closes.

Also, i want to add some extra classes to the SVG elements (add to leader-line class). How can i do this?

Thanks for your help and support.

![issue-1](https://user-images.githubusercontent.com/45909658/50050473-dc8a7a00-00c9-11e9-8757-91be67b29d2e.jpg)
![issue-2](https://user-images.githubusercontent.com/45909658/50050474-dd231080-00c9-11e9-91c8-be258784044b.jpg)

**Comment by anseki** [comment]
Hi @saieen, thank you for the comment.
Sorry, do you mean that you want to update the position without the `position` method?
And, why you don't use the `position` method?

**Comment by saieen** [comment]
> Hi @saieen, thank you for the comment.
> Sorry, do you mean that you want to update the position without the `position` method?
> And, why you don't use the `position` method?

Hello

I do want to use the position method but your examples show it for 1 line (line.position()). But as you can see in the screen shots, i have 4 lines (and there could be as many as 100 lines at any given time). How can i use position on all these 4 lines whenever document / window is resized?

Thanks!

**Comment by anseki** [comment]
The position is fixed automatically when the window was resized. You don't have to do anything.
You should call the `position` method only when elements were moved without resizing the window.
You can call the `position` method regardless of the number of lines.
For example, 4 lines:
```js
line1.position();
line2.position();
line3.position();
line4.position();
```

Try this to add a class to the SVG element:
```js
// After the line was created
document.querySelector('.leader-line').classList.add('foo');
```
Note that it is not supported.
Also, you should consider compatibility for `classList`.
See: https://github.com/anseki/m-class-list

**Comment by saieen** [comment]
Thanks. I will definitely look into these.

Regards

WMA.

**Comment by anseki** [comment]
I'm glad if I could help you. :smile: 
Could you close this issue if it was solved?

**Comment by anseki** [comment]
:cry: No reply came, then I close this issue.

**Comment by saieen** [comment]
Sorry brother. Was budy with some urgent work so forgot to close the thread.

Thank you very much for your help and support.

Much appreciated!


Regards

WMA.

**Comment by anseki** [comment]
:relaxed::ok_hand:

**Comment by Mahesh9959-mahi** [comment]
@anseki 
Hi, My requirement is to delete multiple lines at a time.  How do we select multiple lines to delete in leader line

**Comment by anseki** [comment]
Hi @Mahesh9959-mahi, thank you for the comment.
Could you make new issue for another topic?

**Comment by Mahesh9959-mahi** [comment]
Sure
