### ISSUE TITLE
width line startAnchor and endAnchor 

### ISSUE THREAD

**Issue by AlirezaBabaeii** [anseki/leader-line#361]
How to increase the width of the yellow dots?

I want something like the picture on the right (Purple color).

![xarrow](https://user-images.githubusercontent.com/99098510/194828855-ef0c12b8-0111-42c4-aafd-751e77737312.jpg)

**Comment by anseki** [comment]
Hi @AlirezaBabaeii, thank you for the comment.
Sorry, what are the `startAnchor` and `endAnchor`?
Also, what is the problem?

**Comment by AlirezaBabaeii** [comment]
> Hi @AlirezaBabaeii, thank you for the comment.
> Sorry, what are the `startAnchor` and `endAnchor`?
> Also, what is the problem?


Hello
you're welcome
thanks for the reply
My problem is exactly that I want the width of the points that I marked with green color to increase

![line](https://user-images.githubusercontent.com/99098510/195063315-4afc7e27-efeb-44dd-83b1-f6fb2cdc0b28.png)

**Comment by anseki** [comment]
Like this?
https://jsfiddle.net/83mgLcs9/

**Comment by anseki** [comment]
You seem to have specified `*SocketGravity` option. Therefore the width of the points were reduced.
If you don't specify those, the width of the points are kept.
Or, you can also specify to make those more long.
For example:
https://jsfiddle.net/m4c6xs2z/

**Comment by AlirezaBabaeii** [comment]
> You seem to have specified `*SocketGravity` option. Therefore the width of the points were reduced. If you don't specify those, the width of the points are kept. Or, you can also specify to make those more long. For example: https://jsfiddle.net/m4c6xs2z/

That was the problem
Thanks for the help

**Comment by anseki** [comment]
I'm glad if I could help you. :smile: 
Could you close this issue?
