### ISSUE TITLE
leader-line mount point

### ISSUE THREAD

**Issue by Bingjiajia** [anseki/leader-line#363]
What happens when the start and end tags can be dragged and dropped？ Whether the mount point can be set

**Comment by anseki** [comment]
Hi @Bingjiajia, thank you for the comment.
Could you explain that?

**Comment by Bingjiajia** [comment]
There are two div elements in a container. If do not drag the container, can wire, and if drag, cannot follow the wire. how to solve

**Comment by Bingjiajia** [comment]
Is it possible to mount the line to the container and follow it around,when container drag

**Comment by anseki** [comment]
Sorry, my English is poor. I couldn't understand your words well.
Do you mean that you want to draw a line between draggable elements?
Try this example:
https://anseki.github.io/leader-line/#ex-191-stage
Drag the yellow box.

**Comment by anseki** [comment]
Or, if you have a problem in your code, show me an example by using e.g. https://jsfiddle.net/ .

**Comment by Bingjiajia** [comment]
哈哈，我的谷歌翻译的中文。场景是这样的，我在一个容器内，添加了多个div元素，然后元素之间用线连接上。但是我把这个容器设置为可拖拽，然后拖拽释放后如何让容器内的连线也跟着容器走呢

**Comment by anseki** [comment]
Sorry?

**Comment by Bingjiajia** [comment]
Thank you. I have solved it

**Comment by anseki** [comment]
Ok :smile: 
Could you close this issue?

**Comment by yuleiQ** [comment]
> 哈哈，我的谷歌翻译的中文。场景是这样的，我在一个容器内，添加了多个div元素，然后元素之间用线连接上。但是我把这个容器设置为可拖拽，然后拖拽释放后如何让容器内的连线也跟着容器走呢

咋解决啊

**Comment by anseki** [comment]
No reply came from @yuleiQ but the issue seems to have been already solved by solving of @yuleiQ's another issue. :smile:
