### ISSUE TITLE
How use html element in middleLabel

### ISSUE THREAD

**Issue by AlirezaBabaeii** [anseki/leader-line#364]
Hi how to use html element in middleLabel ? 

![Screenshot from 2022-10-12 15-05-34](https://user-images.githubusercontent.com/99098510/195332914-6dd95a37-d379-4cc9-aeb7-fe9569f0df36.png)

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.

**Comment by AlirezaBabaeii** [comment]
please not close issues not solved problem
i can use leader line use in react js and bind react component to middleLabel how do this work?

**Comment by AlirezaBabaeii** [comment]
> Hi @AlirezaBabaeii, thank you for the comment. This may help you: #245

sorry I did not catch
please not close issues not solved problem
i can use leader line use in react js and bind react component to middleLabel how do this work?

**Comment by anseki** [comment]
> sorry I did not catch

It's ok. So, did you catch that now? Did you read it?
