### ISSUE TITLE
Lines are overlapping with others

### ISSUE THREAD

**Issue by KasunGamage** [anseki/leader-line#365]
![image](https://user-images.githubusercontent.com/37896307/196636757-9c42f7c1-3846-46d1-a08f-2dfbc60b4bde.png)

how can we give a gap between those lines?

my code to create a line.

 ```
private createLine(startPoint: any, endPoint: any): void {
    const colorPlaceholderGray = '#4f555e'; // not working if i use a constant from Colors;
    const line = new LeaderLine(
      startPoint,
      LeaderLine.pointAnchor(endPoint, {
        x: 0,
        y: 20,
      })
    );
    line.setOptions({
      path: 'grid',
      startPlug: 'disc',
      startPlugOutline: true,
      startPlugColor: Colors.white,
      startPlugOutlineColor: Colors.primary,
      startPlugOutlineSize: 2.5,
      startPlugSize: 3,
      endPlug: 'arrow3',
      endPlugSize: 3,
      endPlugOutline: true,
      endPlugOutlineSize: 1.5,
      endPlugColor: Colors.white,
      endPlugOutlineColor: colorPlaceholderGray,
      startSocket: 'right',
      endSocket: 'left',
      size: 2,
      color: colorPlaceholderGray,
      dash: true,
    });
    // save the created line
    this.leaderLineElements.push(line);
    this.elementLines.push(document.querySelector('.leader-line:last-of-type'));
  }
```

**Comment by anseki** [comment]
Hi @KasunGamage, thank you for the comment.
I don't know what are lines you want. If you want to adjust length of a part of line toward first corner of `grid` path, you can specify [`*SocketGravity`](https://anseki.github.io/leader-line/#startsocketgravity-endsocketgravity) options to do that.

**Comment by KasunGamage** [comment]
![image](https://user-images.githubusercontent.com/37896307/196662857-002b8e67-d438-4e28-8ba3-8620fe90cf2b.png) that option not going to help me. I think now you can understand the issue clearly. The number 1 and number 2 lines needed to be separated. otherwise, I cannot identify which one goes where.

**Comment by anseki** [comment]
Umm... Why are there number 1 at three points?

**Comment by KasunGamage** [comment]
the left side is the start points. the right side is the endpoints.

**Comment by KasunGamage** [comment]
![Uploading image.png…]()
expectation.

**Comment by anseki** [comment]
Are those not two points? Umm... strange...
Sorry, I can't understand why the options don't help you.
For example:
https://jsfiddle.net/fvya5brc/

**Comment by KasunGamage** [comment]
![image](https://user-images.githubusercontent.com/37896307/196670585-844587ad-aa64-4ad7-98e4-3f52e35658d4.png)
this is what happen if we add  startSocketGravity: 48 to all the leader lines

**Comment by anseki** [comment]
That is correct behavior because you specify that to all the lines.
See document: https://github.com/anseki/leader-line/issues/365#issuecomment-1283712117

**Comment by anseki** [comment]
Do you mean that you want to adjust it automatically?

**Comment by KasunGamage** [comment]
will try. thanks for your time.

**Comment by anseki** [comment]
If you add many lines, the path other than `grid` may be better.
Good luck :smile:
