### ISSUE TITLE
How to place pathLabel directly on the middle of a line?

### ISSUE THREAD

**Issue by eukuz** [anseki/leader-line#366]
Dear @anseki, thank you for the library!

It's needed to place a pathlabel in the middle of a leader-line path both horizontally and vertically. So the line goes through the text and direction matters
![image](https://user-images.githubusercontent.com/37394070/197353498-5baff730-3875-4bac-b5b7-4fbf6ea5202b.png)

Your answer to the #334 issue was close, but js animation cannot be applied here due to the performance reasons
I also played with the dominant-baseline css proprerty for textPath tag but it did't give me desired result - the label wasn't placed in the middle on a path neither horizontally nor vertically

How can it be done?

**Comment by anseki** [comment]
Hi @eukuz, thank you for the comment.
Could you explain that the `dominant-baseline` property didn't work?
BTW, the https://github.com/anseki/leader-line/issues/334 didn't use JS animation.

**Comment by eukuz** [comment]
The `pathLabel` property of the leader line generates a `<textPath>` tag. I tried to apply the CSS property `dominant-baseline` to the tag for placing the text just in the center or a line path

**Comment by eukuz** [comment]
Speaking of #344 and JS animation I meant [this your comment ](https://github.com/anseki/leader-line/issues/334#issuecomment-1158424436) and jsfiddle

**Comment by eukuz** [comment]
So I need the pathLabel to be like strikethrough with the leader line path 
![image](https://user-images.githubusercontent.com/37394070/197390391-41d81f13-63bd-4c3d-b1ff-94699176dd67.png)

**Comment by anseki** [comment]
Could you explain that the `dominant-baseline` property didn't work? Do you mean that the property didn't change it at all?
The https://github.com/anseki/leader-line/issues/344 (not 334) is a topic about "Socket position".
And the JSFiddle example in the https://github.com/anseki/leader-line/issues/334 didn't use JS animation. Maybe you mistook a `animateMotion` element of SVG to move an element. It is not JS animation, and it doesn't animate.

**Comment by eukuz** [comment]
Yes, you're right animateMotion.
`dominant-baseline` property placed with value : "middle" didn't placed the pathLable to the middle. 
`dominant-baseline` property placed with value : "hanging" placed the pathLable closer to middle, but not exactly

**Comment by anseki** [comment]
I see.
Try this: https://jsfiddle.net/m12hc8sx/
You might have to consider compatibility with browsers.
And note that this is not supported by the library.

**Comment by eukuz** [comment]
Thank you :)

**Comment by anseki** [comment]
:smile:
