### ISSUE TITLE
【bug】Click on the relationship line, and the adjacent lines disappear

### ISSUE THREAD

**Issue by avrinfly** [anseki/leader-line#368]
As shown in the example
https://jsfiddle.net/avrinfly/0482pkhr/5/
When I click on the red line, the red line does not disappear, but the green line disappears
![demo3](https://user-images.githubusercontent.com/30068005/197376455-de63a40a-c06b-43f2-97d2-a5a7dd012061.gif)

**Comment by anseki** [comment]
Hi @avrinfly, thank you for the comment.
Your code has a bug. See this: https://jsfiddle.net/rvn8Lxga/
Note that this is not supported by LeaderLine.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.

**Comment by anseki** [comment]
:smile:
