### ISSUE TITLE
Drawing leaderline from click event 

### ISSUE THREAD

**Issue by rdimaunahan** [anseki/leader-line#369]
Hi anseki. Wonderful library btw! I just want to ask if there's a way to define start and end of the leaderline by clicking the element? This is the flow that I am trying to do:

Click event -> checks if click is = 1 -> if not then set clicked element to start element -> else set clicked element to end element -> draw leaderline

Thank you!

**Comment by anseki** [comment]
Hi @rdimaunahan, thank you for the comment.
Of course you can do that. That seems to be very easy code.

**Comment by rdimaunahan** [comment]
I got to code it, now my task that I am trying to solve is storing the line drawn so that it can be retained after page refreshes. Is there a way to do that?

**Comment by anseki** [comment]
Does the "page refresh" mean "page reloading"?
FYI, these may help you: https://github.com/anseki/leader-line/issues/102#issuecomment-581453724 , https://github.com/anseki/leader-line/issues/102#issuecomment-581695752

**Comment by rdimaunahan** [comment]
I got it to store by storing the start and end element and redrawing it after the page reloads. I have one more question. I am attaching the leader line into a draggable element, both start and end. Every time I move the element, the leader line does not follow. How do you make sure that the leader line follows the element when moved?

**Comment by anseki** [comment]
:smile:
