### ISSUE TITLE
Using Leader-line and PlainDraggable together 

### ISSUE THREAD

**Issue by jorgemonte** [anseki/leader-line#37]
Hi! 

First, I'd like to say that this library is pretty cool and the documentation is great as well. The only aspect I am missing is about working examples showing Leader-line and Plaindraggable working together. I applied both on my project and when I move the draggable object (SVG circle) the lines are staying fixed on their initial position. I don't understand this behavior, would you mind to help with that? 

I tried to find coding examples everywhere but did't have success.

Thank you!

**Comment by anseki** [comment]
Hi @jorgemonte, thank you for the comment.

The [`position`](https://anseki.github.io/leader-line/#position) method of LeaderLine has to be called in the [`onMove`](https://anseki.github.io/plain-draggable/#options-onmove) event handler of PlainDraggable.
That is, you should call the `position` method when the layout is changed without resizing the window, regardless of PlainDraggable, SVG, etc.

An example using LeaderLine and PlainDraggable is here:
https://anseki.github.io/leader-line/#startsocket-endsocket

**Comment by jorgemonte** [comment]
Thank you anseki. Do you have an example of code? I am not sure yet if I understood well. I am building circles on my website and they are draggable. I need lines linking them and I really think that using Leader-line will be perfect to that. Thanks!

**Comment by jorgemonte** [comment]
I will show you the example of what I did until now: (ugly code warning lol)

```
startElement = document.getElementById('Ellipse_36');
 	endElement = document.getElementById('Ellipse_9');

 	draggable = new PlainDraggable(startElement);
 	draggable.containment = {left: 0, top: 0, width: '100%', height: '100%'};

 	draggable2 = new PlainDraggable(endElement);
```

```
new LeaderLine(startElement, endElement, {
  startPlug: 'square',
  endPlug: 'hand'
});
```
Its just because at the example you sent I just see the visual example but not the block of code that shows the leaderLine and the draggable together. I would appreciate to see both together at a sample of code so I will be able to understand better how they are implemented. Sorry for bothering you, it's just that Im still a beginner. Thanks!

**Comment by anseki** [comment]
Ok, I try to explain step by step:

1. When the layout is changed without resizing the window, you have to call the [`position`](https://anseki.github.io/leader-line/#position) method of LeaderLine.
2. To call the `position` method, you have to save an instance of LeaderLine into a variable because the method is "instance method".  
i.e. A return value from `new LeaderLine(...)` has to be saved into a variable. e.g. `var line = new LeaderLine(startElement, endElement)`
3. To hook the time to call the `position` method, you have to set the [`onMove`](https://anseki.github.io/plain-draggable/#options-onmove) event handler of PlainDraggable. The handler function that was set will be called when the draggable element was moved. That is, it is called when the layout is changed.  
e.g. `draggable.onMove = function() {...}` OR `new PlainDraggable(element, {onMove: function() {...}})`

For example:
https://jsfiddle.net/zb7Lp5o9/

**Comment by anseki** [comment]
:smile:

**Comment by Veeramuthur** [comment]
Hi thank you.. it very useful 

i am using DOM to generate the div element and i am using leaderline and plain dragable but position is not updating.
for (var i = 0; i < LinkElement.length; i++) {
 var plaincomponent = new LeaderLine(
                                          document.getElementById(LinkElement[i].LeftElementName),
                                          document.getElementById(LinkElement[i].RightElementName),
                                       { color: '#ff0000', size: 2, path: 'straight', dash: { animation: true } });

                            function fixLine() {
                                startant.position();
                                plaincomponent.position();                             
                            }

                            new PlainDraggable(document.getElementById(LinkElement[i].LeftElementName), { onMove: fixLine, containment: document.body });
                            new PlainDraggable(document.getElementById(LinkElement[i].RightElementName), { onMove: fixLine, containment: document.body });
 }

it only updateing the position my last element (e.g i= 4) its not working for first element(e.g i=1).. please help me to solve this..
thanks..

**Comment by anseki** [comment]
Hi @Veeramuthur, thank you for the comment.
It seems that the comment is a duplicate of https://github.com/anseki/plain-draggable/issues/59 .

**Comment by Veeramuthur** [comment]
I am going to close that duplicate one.if possible you can close that duplicate one.. is there any solution for my Question??

**Comment by anseki** [comment]
I see.
The duplicate messages confused me, it's ok now. :smile:
