### ISSUE TITLE
Dragging lines after reload

### ISSUE THREAD

**Issue by rdimaunahan** [anseki/leader-line#371]
Hi anseki!
 
I am trying to drag the leaderline connected to a draggable element. The line.position() works but only when the page is not reloaded. All leaderline gets stored and redrawn after refresh but I can't use line.position() anymore since the lines are stored line. Is it possible to use line.position for svg element isntead?

**Comment by anseki** [comment]
Hi @rdimaunahan, thank you for the comment.
Was this issue solved?
