### ISSUE TITLE
Using remove()

### ISSUE THREAD

**Issue by rdimaunahan** [anseki/leader-line#372]
Hi anseki,

I am trying to add an event listener to the SVGDom by following issue #70 but the line won't get removed. Is the remove() function still working? Referencing the documentation about remove() in your page.
![image](https://user-images.githubusercontent.com/42995972/199085157-1b2e8456-c381-4856-b88d-aa0054f964f2.png)

**Comment by anseki** [comment]
Hi @rdimaunahan, thank you for the comment.
To reproduce that, could you show an example by using e.g. https://jsfiddle.net/ ?

**Comment by rdimaunahan** [comment]
https://jsfiddle.net/ec4p0br5/ 
Here is the code I'm testing

**Comment by anseki** [comment]
Try this: https://jsfiddle.net/26keovcu/
This may help you: https://github.com/anseki/leader-line/issues/70#issuecomment-536640174

**Comment by rdimaunahan** [comment]
Okay I see what I'm missing. Thank you for your help! Closing issue now.

**Comment by anseki** [comment]
:smile:
