### ISSUE TITLE
How to combine two points with one point

### ISSUE THREAD

**Issue by yuleiQ** [anseki/leader-line#375]
![image](https://user-images.githubusercontent.com/32067691/201085373-ce1ca64a-fd9d-4f56-b7c3-f85398c6ad00.png)

Look at the picture，how to combine two points with one point? thanks

**Comment by yuleiQ** [comment]
@anseki My data structure is 
```
list: [
        {
          name: '1',
          isParent: true,
          children: [
            {
              name: '2',
              steps: ['check'],
              children: [
                {
                  name: '3',
                  steps: ['clone', 'cache'],
                  children: [
                    {
                      name: '4',
                      steps: ['uncache', 'sonar-properties-create', 'sonar-scan', 'collect-result'],
                      children: [
                        {
                          name: '51,
                          steps: ['uncache', 'build-and-push', 'write-url'],
                          children: [],
                        },
                        {
                          name: '52',
                          steps: ['uncache', 'build-and-push2',  'write-url'],
                          children: [],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
```

I want to  name: 51 and 52 two group with one point name: 6, please help me

**Comment by anseki** [comment]
Hi @yuleiQ, thank you for the comment.
This may help you.
https://jsfiddle.net/nocgpv8y/

**Comment by yuleiQ** [comment]
> Hi @yuleiQ, thank you for the comment. This may help you. https://jsfiddle.net/nocgpv8y/


---------------------------------------------------------------------------------------------------------
First of all, thank you for your reply. 
My English is poor. I want to ask how to converge two points into one under my data structure？How to merge 51 and 52 groups at 6。

In addition,I want a dom to scroll when pipeline exceeds length. But the lines overlap. I have called the position () method according to issue54。
The situation is as follows
![企业微信截图_1668150717950](https://user-images.githubusercontent.com/32067691/201288864-3f860f34-fd4e-4e29-b186-552ec2c7e38f.png)

**Comment by anseki** [comment]
Sorry, I couldn't understand your question well.
The example that I showed seems to be merging two elements as you said. That looks like the your red lines in https://github.com/anseki/leader-line/issues/375#issue-1443781527 . What is problem?
Do you mean that you want to make new element (object)? Could you explain result you want?

**Comment by yuleiQ** [comment]
> Sorry, I couldn't understand your question well. The example that I showed seems to be merging two elements as you said. That looks like the your red lines in [#375 (comment)](https://github.com/anseki/leader-line/issues/375#issue-1443781527) . What is problem? Do you mean that you want to make new element (object)? Could you explain result you want?

thanks~The first question is my question~

call position() , the lines overlap how to fix?

**Comment by anseki** [comment]
Do you mean that the issue (https://github.com/anseki/leader-line/issues/375#issue-1443781527) was solved?
Could you make new issue if you have another issue?

**Comment by anseki** [comment]
Also, could you close this issue if it was solved?

**Comment by yuleiQ** [comment]
> Also, could you close this issue if it was solved?

yes,thank your help

**Comment by anseki** [comment]
Could you close this issue?

**Comment by yuleiQ** [comment]
thanks

**Comment by anseki** [comment]
:smile:
