### ISSUE TITLE
Delay occurs when sliding with position  in a dom

### ISSUE THREAD

**Issue by yuleiQ** [anseki/leader-line#376]
Hi, @anseki。Thank you for providing such a good project~

I encountered some problems in use，Delay occurs when sliding with position()  in a dom。After the delay, it returns to the correct position。
```
document.getElementById('treedom').addEventListener('scroll', () => {
    if (this.lines && this.lines.length) {
        this.lines.forEach(line => {
          line.position();
        });
      }
  });
```
I want to upload the video. I uploaded the [video](https://github.com/yuleiQ/video/blob/main/1668179406226894.mp4) in the github, but I'm not sure if you can see it.

**Comment by anseki** [comment]
Hi @yuleiQ, thank you for the comment.
To reproduce that, could you show an example by using e.g. https://jsfiddle.net/ ?

**Comment by yuleiQ** [comment]
Because I can't use this tool, I transferred the components I encapsulated to github. Do you have a Vue environment to run? Thank you.

[Process-tree](https://github.com/yuleiQ/video/tree/main)

**Comment by yuleiQ** [comment]
I think the problem is that there are too many recursive rendering lines. I render about 20 lines at a time. I also try your library AnimEvent, but it seems to have no effect

**Comment by yuleiQ** [comment]
I have solved this problem，close issue，thank you

**Comment by anseki** [comment]
:smile:  :thumbsup:
