### ISSUE TITLE
How to implement mind mapping with startSocketGravity  

### ISSUE THREAD

**Issue by avrinfly** [anseki/leader-line#377]
hello anseki,
I want to implement the function of mind-mapping with leaderline，
But in fact, the effect is the following case:
![image](https://user-images.githubusercontent.com/30068005/201880546-9876be39-414e-4501-8538-56cdca4e03a6.png)
The effect that I want to achieve is the following:
![image](https://user-images.githubusercontent.com/30068005/201882769-a313cce6-0acc-41c4-91dd-b28ef0d18cf3.png)
I found the property [startSocketGravity](https://anseki.github.io/leader-line/#startSocketGravity) in the documentation but don t know how to use it.
I hope you can help me answer this question 🙏

**Comment by anseki** [comment]
Hi @avrinfly, thank you for the comment.
The `startSocketGravity` and `endSocketGravity` options accept `number`, `Array` or `string` as force of gravity at a socket.
Or, you maybe want to use `fluid` for [`path`](https://anseki.github.io/leader-line/#path) option, not `arc`.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
