### ISSUE TITLE
Issue connecting two close elements

### ISSUE THREAD

**Issue by amibrk** [anseki/leader-line#379]
Hi,

I have an issue when trying to connect two close elements.
Instead of a small line I'm getting a long line that doesn't look good.

This is what I get :

![image](https://user-images.githubusercontent.com/60754503/202422436-3db75117-5f71-4908-bdd1-b9437bf08b06.png)

I'm expected to something like this :

![image](https://user-images.githubusercontent.com/60754503/202422731-5ca68aa4-9e5c-4c0b-92c5-a437072df7ed.png)

Any thoughts how can I resolved it?

Thanks

**Comment by amibrk** [comment]
Thanks for the quick reply. 
Works great.

**Comment by anseki** [comment]
:smile:
