### ISSUE TITLE
How can I change how the arc line is drawn? (mirror it)

### ISSUE THREAD

**Issue by Marchiuzzz** [anseki/leader-line#380]
Hi, first of all - wonderful package, love the amount of customizability it has.
However, I couldn't find in the documentation how to achieve what I want. Basically, I have two elements position vertically, I need an arc arrow between them, I've figured out how to draw it but now I just need to flip it on x axis, what parameters should I look into to find the answer for this?

![image](https://user-images.githubusercontent.com/73941456/203783345-94853e4e-bcb8-4ee5-bc31-77a85e64608e.png)

Should be 
![image](https://user-images.githubusercontent.com/73941456/203783555-09786cb5-9afc-4396-a7d0-54eb6e999cfe.png)

**Comment by anseki** [comment]
Hi @Marchiuzzz, thank you for the comment.
This may help you: https://github.com/anseki/leader-line/issues/287#issuecomment-1001949850

**Comment by Marchiuzzz** [comment]
@anseki Thanks, I managed to solve it by switching the start and end elements and switching the plugs of endpoints so that start plug is arrow and end plug is "behind"

**Comment by anseki** [comment]
I'm glad if I could help you. :smile: 
So, could you close this issue?

**Comment by Marchiuzzz** [comment]
Sure, thanks again
