### ISSUE TITLE
[Request] DOM elements as labels

### ISSUE THREAD

**Issue by CheeseCrustery** [anseki/leader-line#382]
There seem to be lots of people, like in issue #23, #21 or #10, who want to add a `click` event to a line.

Instead, how about a feature where you can just add your own DOM elements as labels for a line. This would be extremely customizable, because you could just add styling or events directly to the label like with any other HTML element. 

If that is not technically possible, please at least add a `click` Event for labels.

**Comment by anseki** [comment]
Hi @CheeseCrustery, thank you for the comment.
That should not be implemented as already mentioned in the past issues over and over again.
And, you wrong, users who wanted that are not many, also, those were already solved.
However, your plan the "labels" may be another solution. I will think that if more requests come.
Thank you. :smile:

**Comment by CheeseCrustery** [comment]
Well, you know whats best for your library.
Thanks for considering.

**Comment by anseki** [comment]
:smile:
