### ISSUE TITLE
How to make several parallel connections/lines between couple of nodes

### ISSUE THREAD

**Issue by meddany** [anseki/leader-line#383]
Hi,
Firstly , I want to thank your for such a greal lib. it is awesome brother ..  Thanks for sharing this with world.. 

2ndly ,How is it possible to draw  several lines between the same start and end without overlapping ?

something like below :-
![image](https://user-images.githubusercontent.com/78307117/209017694-51abbd23-4f2d-41da-85e4-7768c7594d92.png)

i have tried many times. but as below which highlighted with red pen, they are overlapping.

![image](https://user-images.githubusercontent.com/78307117/209018354-2496bcf6-7e9d-4bb3-b00a-4baf4620d3b3.png)

i am trying to achieve a thing like below ..

![image](https://user-images.githubusercontent.com/78307117/209023975-b7fe54d6-8c25-492d-aa61-08e7001762c6.png)

Thanks in advance.

**Comment by anseki** [comment]
Hi @meddany, thank you for the comment.
This may help you: https://jsfiddle.net/xL1087d6/

**Comment by meddany** [comment]
Hi @anseki ,

Thanks for your reply,

i tried one of your solutions but shows as below :

![image](https://user-images.githubusercontent.com/78307117/209118603-44a89eec-c2b3-4db8-b5be-019f914db8c2.png)

is they anyway to adjust the line position to automatically attach to correct side ?

**Comment by anseki** [comment]
You seem to have mistaken the options.
Those are not automatic but you can get coordinates easily.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
