### ISSUE TITLE
startSocket endSocket position 'auto' not working properly

### ISSUE THREAD

**Issue by zakk616** [anseki/leader-line#384]
```
startSocket: 'right',
endSocket: 'left',
```

![image](https://user-images.githubusercontent.com/26119949/209760401-53e848cc-3c9c-4be3-81f8-84a51bfd715e.png)

Works fine!

**Problem**

```
startSocket: 'auto',
endSocket: 'auto',
```

![image](https://user-images.githubusercontent.com/26119949/209761401-366a3432-95d4-4833-8b66-03d3d03699af.png)

facing issue with line position.

**Comment by anseki** [comment]
Hi @zakk616, thank you for the comment.
You have to specify `{startSocket: 'bottom', endSocket: 'top'}` to the line, because nobody knows where is a problem and nobody knows a correct line for you.

**Comment by zakk616** [comment]
> Hi @zakk616, thank you for the comment. You have to specify `{startSocket: 'bottom', endSocket: 'top'}` to the line, because nobody knows where is a problem and nobody knows a correct line for you.

actually these cards are being produced dynamically and the screen size is also responsive, I can not specify `{startSocket: 'bottom', endSocket: 'top'}`  but `{startSocket: 'auto', endSocket: 'auto'}` so the line should be drawn and redirected automaticaly.

`{startSocket: 'bottom', endSocket: 'top'}` works fine when on desktop and mobile screen.
**Desktop Screen:**
![image](https://user-images.githubusercontent.com/26119949/209776671-50189c73-6e75-4be2-9aa6-e2dc98759eac.png)

**Mobile Screen:**
![image](https://user-images.githubusercontent.com/26119949/209777149-ff36317d-4dfe-4110-87d1-9b43621e0d88.png)


but when cards are shown on medium screens the line direction does not work properly.

**Comment by anseki** [comment]
Sorry, we don't know what the "properly" mean for you.
You can get coordinates of elements easily by using e.g. `getBoundingClientRect`, to choose a socket that you want.

**Comment by zakk616** [comment]
to provide `startSocket` `endSocket` dynamicaly when the page resizes, one needs to implement `getBoundingClientRect` to grab new position of the element first and then draw the line on new position and provide `startSocket` `endSocket`.

**Comment by zakk616** [comment]
to provide `startSocket` `endSocket` dynamicaly when the page resizes, one needs to implement `getBoundingClientRect` to grab new position of the element first and then draw the line on new position and provide `startSocket` `endSocket`.

**Comment by anseki** [comment]
Yes. :smile:
