### ISSUE TITLE
line position issue in collapse div

### ISSUE THREAD

**Issue by zakk616** [anseki/leader-line#385]
the lines don't work currect in a collapsing div.

https://jsfiddle.net/zakk616/mtj2hpb7/11/

is there any solution when the collapse changes the lines should re-render?

**Some Screenshots:**
when collapse is open
![image](https://user-images.githubusercontent.com/26119949/210047248-fc9bf6be-f1ca-4684-b0ca-bbcec6d1ee36.png)

when collapse is closed
![image](https://user-images.githubusercontent.com/26119949/210047337-cb10ce3e-b3a1-4174-bb06-8e06c619235c.png)

**Comment by anseki** [comment]
Hi @zakk616, thank you for the comment.
You can use [`position` method](https://anseki.github.io/leader-line/#position) for that.
However, it seems that you don't need that, you only want to [hide the lines](https://anseki.github.io/leader-line/#show-hide) maybe.

**Comment by zakk616** [comment]
I implemented this solution:

```
var lines = [];
function drawLines(length) {
        for (let i = 1; i < length; i++) {
            var start = document.getElementById('history-card-' + i);
            var end = document.getElementById('history-card-' + (i + 1));

            lines.push(new LeaderLine(start, end, {
                color: '#00b97d', size: 2, path: 'grid',
                startSocket: 'right',
                endSocket: 'left',
            }));
        }
    }

    function showHide() {
        if (lines.length > 0) {
            lines.forEach(line => {
                line.remove();
                lines = [];
            });
        }
        else {
            setTimeout(() => {
                drawLines(data.length);
            }, 100);
        }
    }
```

now on collapse i call `showHide()`

**Comment by anseki** [comment]
That is not good code because that removes lines wastefully instead of hiding lines, and also that clears `lines` repeatedly that is not required.
Good luck. :thumbsup:
