### ISSUE TITLE
position() error

### ISSUE THREAD

**Issue by yuleiQ** [anseki/leader-line#386]
when I call position(), display error, but I don't know why
<img width="876" alt="image" src="https://user-images.githubusercontent.com/32067691/210329033-4e719f93-b8c6-4b8d-aab6-5de3f95ae06f.png">

```
window.addEventListener('scroll', () => {
      this.drawPosition();
    }, true);

drawPosition() {
      if (this.lines && this.lines.length) {
        this.lines.forEach(line => {
          line.position();
        });
      }
    },

```

**Comment by anseki** [comment]
Hi @yuleiQ, thank you for the comment.
The `this.lines` seems to contain `undefined`. Your code has a bug maybe.
However, of course I didn't read other parts of your code.
For example, that checks `this.lines.length` wastefully, you can replace the line with:
```js
      if (this.lines) {
```
Because the `.forEach()` method does nothing when the array is empty.

**Comment by anseki** [comment]
This may help you: https://jsfiddle.net/xqd92ke8/

**Comment by yuleiQ** [comment]
> Hi @yuleiQ, thank you for the comment. The `this.lines` seems to contain `undefined`. Your code has a bug maybe. However, of course I didn't read other parts of your code. For example, that checks `this.lines.length` wastefully, you can replace the line with:
> 
> ```js
>       if (this.lines) {
> ```
> 
> Because the `.forEach()` method does nothing when the array is empty.

I tried, it seems that it is not because of the error here, because my lines are an array

**Comment by anseki** [comment]
Try this example code: https://github.com/anseki/leader-line/issues/386#issuecomment-1369781207
The `forEach()` problem is another problem of your code. That doesn't throw an error but it makes wrong behavior wastefully.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
