### ISSUE TITLE
Possibility of having line ends on corners

### ISSUE THREAD

**Issue by guirama** [anseki/leader-line#39]
Hi,

Is there a way to start or end a line in a corner (e.g top-right , bottom-right etc)

Best Regards

Indunil

**Comment by anseki** [comment]
Hi @guirama, thank you for the comment.
You can use [`pointAnchor`](https://anseki.github.io/leader-line/#pointanchor) to connect line to top-right, etc.

**Comment by anseki** [comment]
:cry: No reply came, then I close this issue.
