### ISSUE TITLE
Using this within a modal that's scrollable

### ISSUE THREAD

**Issue by SlapBassist** [anseki/leader-line#4]
I tried using this within a scrollable bootstrap modal, but since the svg's are seemingly attached to the body of the document, it does not scroll with the rest of the page. Is there a way around this?

**Comment by anseki** [comment]
Hi @SlapBassist, thank you for the report.

So, I couldn't see that case.
Could you show me an example?
e.g. https://jsfiddle.net/

**Comment by SlapBassist** [comment]
So I'm unable to easily recreate it in jsfiddle as I think it's getting messed up within the context of that window, but I'm not sure.

https://jsfiddle.net/L1kxhrr7/

If it helps, the application that I have, which I can't share easily, is an angular 4/bootstrap application, it uses ngx-bootstrap to open up a modal which has a lot of content so it's scrollable in some cases. When you scroll down, if an arrow is visible, the arrow does not scroll with the content of the modal.

**Comment by SlapBassist** [comment]
I updated it a little bit so it follows the behavior my app has, so basically if you click a row on the left column, it will highlight it showing you have selected that row, and then if you select a row on the right column, it will create a leader line object on those two elements. Nothing shows up in this window, which I imagine is similar to what is happening in my app, but if you check the dom, the svgs are there. In my app something shows up, but here maybe it does not since it's in a small window on jsfiddle:

https://jsfiddle.net/L1kxhrr7/1/

**Comment by SlapBassist** [comment]
Awesome, yes that position function helped sort this out. I now capture the browser scroll event and call this position function on each arrow to fix it. Great library btw!

**Comment by anseki** [comment]
😄 
I recommend you to use [AnimEvent](https://github.com/anseki/anim-event) for `scroll` event with a better performance.
