### ISSUE TITLE
Get instance of DOM element

### ISSUE THREAD

**Issue by RauppRafael** [anseki/leader-line#40]
Is it possible to get the reference to the DOM element instance?

**Comment by anseki** [comment]
Hi @RauppRafael, thank you for the comment.
Try this to get the SVG element:

```js
// After the line was created
document.querySelector('.leader-line');
```

Note that it is not supported by the library.
Also, this is a SVGDOM, it is not DOM.

**Comment by anseki** [comment]
I am glad if I could help you. :smile: 
Could you close this issue if it was solved?

**Comment by stagefright5** [comment]
> Hi @RauppRafael, thank you for the comment.
> Try this to get the SVG element:
> 
> ```js
> // After the line was created
> document.querySelector('.leader-line');
> ```
> 
> Note that it is not supported by the library.
> Also, this is a SVGDOM, it is not DOM.

Can you add the reference to this SVGDOM object as a property of LeaderLine instance?
For example,

```javascript
const l = new LeaderLine(start, end);
// access the element ref like this
const svgDomRef = l.svgDOM
```

**Comment by anseki** [comment]
Hi @stagefright5, thank you for the comment.
Do you mean that `querySelector` method doesn't work?

**Comment by stagefright5** [comment]
> Hi @stagefright5, thank you for the comment.
> Do you mean that `querySelector` method doesn't work?

Thanks for replying.
What I'm saying is, using the `querySelector`, I  will have to query the svg element after it gets attached to the DOM. Instead of that, it will be better and performany if the library itself saves the element reference in the leader line instance because you already have the reference when you create the element.

**Comment by anseki** [comment]
I see.
However, that is not good idea because the library should not support getting SVGDOM as I said in
https://github.com/anseki/leader-line/issues/40#issuecomment-453793653 .
And also, it has almost no effect on the performance because the `querySelector` is called only once by one line.

**Comment by stagefright5** [comment]
Can you explain why it is not a good idea for the library to support getting SVGDom?
Also, regarding the performance, what if I have multiple lines?

**Comment by anseki** [comment]
The library doesn't consider that the SVG element is edited by something that is not the library itself.
About the performance, it might have effect if you have a thousand lines. However, a thousand lines apply big load to a web browser regardless of the getting SVGDOM.

**Comment by anseki** [comment]
LeaderLine is not a library to help to handle SVG.
If you want that, you had better use a library for SVG such as Snap.svg instead.

**Comment by stagefright5** [comment]
Noted. Thank you.

**Comment by anseki** [comment]
:smile:
