### ISSUE TITLE
Typescript typings

### ISSUE THREAD

**Issue by massimilianorango** [anseki/leader-line#42]
Hey! Super cool library! :) I couldn't find any TypeScript typings, is there a possibility you're gonna include them in the npm package?

**Comment by anseki** [comment]
Hi @massimilianorango, thank you for the comment.
The package has no type definition, then you can write that easily and you can contribute it to DefinitelyTyped.
http://definitelytyped.org/

**Comment by anseki** [comment]
No reply came, then I close this issue. :cry:
