### ISSUE TITLE
Custom plug style?

### ISSUE THREAD

**Issue by c0bra** [anseki/leader-line#44]
Is it possible to define a custom svg element to use as a plug?  For instance, I have a sketchy-looking arrowhead I'd like to use.

**Comment by anseki** [comment]
Hi @c0bra, thank you for your comment.
The current API has options to customize the style of plugs, and it has no option to replace SVG elements, but of course you can replace those source code (Note that it is not supported).

**Comment by c0bra** [comment]
Hmm, I will give that a shot.

**Comment by anseki** [comment]
:smile:  :thumbsup:
