### ISSUE TITLE
Panzoom help.

### ISSUE THREAD

**Issue by gumireddyprashanth** [anseki/leader-line#45]
Hi Anseki,

This library is excellent no issues no bugs, just perfect.

I need a help for my project.
I'm using 'panzoom' library to zoom and drag elements in side a div.
i have to draw a line between two elements, using your excellent library i drew line.
but the problem is after i zoom out or drag the elements aside, the drawn line is still stuck there.
i know issue is not with leaderline library.
but would need your help to fix the issue.

Thank You

**Comment by anseki** [comment]
Hi @gumireddyprashanth, thank you for your comment.

When the layout was changed by something such as dragging element, the [`position`](https://anseki.github.io/leader-line/#position) method has to be called to re-draw the line.
See this example, and drag a yellow element:
https://anseki.github.io/leader-line/#startsocket-endsocket

**Comment by gumireddyprashanth** [comment]
Thanks Bro it worked!!

**Comment by anseki** [comment]
I am glad if I could help you. :smile: 
Could you close this issue if it was solved?

**Comment by anseki** [comment]
No reply came, then I close this issue. :cry:
