### ISSUE TITLE
startSocketGravity and endSocketGravity limitations

### ISSUE THREAD

**Issue by logesh-freshworks** [anseki/leader-line#46]
![leaderline](https://user-images.githubusercontent.com/41358969/54686326-075bf280-4b3f-11e9-8a1e-f138770f99e3.png)

Hi, I am trying to achieve something like above(The connection from right of top box to left of bottom box) with startSocketGravity and endSocketGravity. But All I could achieve is this. 

![Screenshot 2019-03-20 at 6 43 38 PM](https://user-images.githubusercontent.com/41358969/54686850-39ba1f80-4b40-11e9-954d-86fda9de3449.png)

If there is an option to add radius to grid path its also ok for me.  After a lot of tweaking, I decided to ask for help from you guys. Could you please guide me? Thanks in advance.

**Comment by anseki** [comment]
Hi @logesh-freshworks, thank you for your comment.

At the moment, LeaderLine supports five styles as [`path`](https://anseki.github.io/leader-line/#path).
It seems that the style you are hoping for is not contained in those.
So, you may have to change path-data if you want the style.
For example: https://jsfiddle.net/m4p5zvsg/
https://github.com/anseki/leader-line/issues/28 may help you.

**Comment by logesh-freshworks** [comment]
Thank you @anseki for the quick reply I will try this.

**Comment by anseki** [comment]
:smile:
