### ISSUE TITLE
Zoom Help

### ISSUE THREAD

**Issue by thomaspalmer** [anseki/leader-line#47]
I am using a zoom function on my app. It is updating the Leader Line with the position method, but when you're zooming out things turn funny... see image.

I think a fix would be to constrain Leader Line to the div that is zooming so that they zoom out with the rest of the page, is this possible? Any thoughts?

![Screenshot 2019-03-22 at 11 52 26](https://user-images.githubusercontent.com/2190634/54821188-59189000-4c99-11e9-9df1-2b9534318756.png)

**Comment by anseki** [comment]
Hi @thomaspalmer, thank you for your comment.
So, we couldn't find the problem from your image, also we don't know your expected result.
Could you indicate an example code? For example, reproduce the issue on https://jsfiddle.net/

**Comment by thomaspalmer** [comment]
Apologies, decided to go a different route.

**Comment by anseki** [comment]
:smile:

**Comment by nitinsmarty** [comment]
Hi, 
I want to open this thread.
My issue is similar to this. 
When I am zooming out my view, lines are getting cluttered. 
After zoom out:
![Screenshot from 2020-04-17 16-16-28](https://user-images.githubusercontent.com/7836230/79561336-d42fbe00-80c6-11ea-9850-b889156011cb.png)
After zoom in: this is my normal state. 
![Screenshot from 2020-04-17 16-17-12](https://user-images.githubusercontent.com/7836230/79561407-f3c6e680-80c6-11ea-9273-bfd137f44655.png)
I want the Lines to resize by length according to the zoom level.

**Comment by nitinsmarty** [comment]
What I actually want to achieve is this with zoom in and zoom out feature.
![Screenshot from 2020-04-17 16-29-23](https://user-images.githubusercontent.com/7836230/79562412-aea3b400-80c8-11ea-90ac-595b1f673d6f.png)

**Comment by anseki** [comment]
Hi @nitinsmarty, thank you for the comment.
It seems that you posted duplicate comments repeatedly.
https://github.com/anseki/leader-line/issues/47#issuecomment-615179058
https://github.com/anseki/leader-line/issues/113
https://github.com/anseki/leader-line/issues/47#issuecomment-615183415
https://github.com/anseki/leader-line/issues/114
Is something wrong?

**Comment by nitinsmarty** [comment]
@anseki Yeah. Earlier commented here. But later on, I logged two separate issues.
