### ISSUE TITLE
Set z-index for the plugs an lines separately

### ISSUE THREAD

**Issue by logesh-freshworks** [anseki/leader-line#48]
Hi, This is more of a question than an issue. Is there an option to set z-index for the line and plugs separately?  Please check the image below. I had to set z-index of the leaderline higher than the rectangle html element in order for the plugs to appear above the element. But I dont want the line to appear over the element. Can anyone please help me?  Thanks in advance.

![Screenshot 2019-03-27 at 7 16 43 PM](https://user-images.githubusercontent.com/41358969/55081084-36391200-50c5-11e9-9bea-94cff719bde4.png)

**Comment by anseki** [comment]
Hi @logesh-freshworks, thank you for your comment.
LeaderLine now doesn't support an option to set `z-index`.
Therefore, you have to customize that for the `z-index` you want.

All lines have each SVG element. That is, a line and its plugs are contained in one SVG element.
Therefore, easy way to set `z-index` to only plugs is adding new elements as plugs on your elements.

**Comment by anseki** [comment]
No reply came, then I close this neglected issue.

**Comment by ahmedshaaban00** [comment]
@anseki The z-index doesn't affect anything because the svg elements are being set inside the body element which makes it in a greater dom layer than other children. What should be the solution here?

**Comment by anseki** [comment]
Hi @ahmedshaaban00, thank you for the comment.
Before facing `z-index`, maybe you should fix a bug in your code if it has a bug.
https://github.com/anseki/leader-line/issues/141#issuecomment-726959594
