### ISSUE TITLE
Allowing for arrows to be draggable?

### ISSUE THREAD

**Issue by SlapBassist** [anseki/leader-line#5]
Is there any way for these arrows to be draggable? So I'd love to be able to drag the arrow pointer from one div to the next. I am creating a mapping tool of source columns to destination columns, so this would be very useful.

**Comment by anseki** [comment]
Hi @SlapBassist, thank you for the comment.
The draggable line is very easy.
These examples may help you:

* https://anseki.github.io/leader-line/#startsocket-endsocket  
Drag the yellow box.
* https://anseki.github.io/leader-line/#offset  
Drag the yellow box.

More details:
https://anseki.github.io/plain-draggable/

Also, this is an example for draggable line.
https://anseki.github.io/plain-draggable/#ex-050-stage

**Comment by anseki** [comment]
Also, an example for "Snap".

https://jsfiddle.net/3tn2bLer/1/

* The plugs of the line are draggable.
* The dragging is snaped to blue boxes.
* The color of a plug is changed only when it is connected to blue box.

**Comment by SlapBassist** [comment]
Great! The last example is exactly what I needed, with the "plugs" being draggable. Thanks!

**Comment by anseki** [comment]
😄 
So, was this issue solved?

**Comment by anseki** [comment]
😢 No reply came, and I close this issue.
