### ISSUE TITLE
Wrong lines

### ISSUE THREAD

**Issue by krol1k** [anseki/leader-line#50]
Wrong lines are drawn. This is corrected by resizing the window.

```js
jQuery(window).scroll(function() {
   var hT = jQuery('#n-1').offset().top,
       hH = jQuery('n-1').outerHeight(),
       wH = jQuery(window).height(),
       wS = jQuery(this).scrollTop();
   if (wS > (hT+hH-wH)){
       
       line.show('draw', {
        animOptions: {
          duration: 3000,
          timing: [0.5, 0, 1, 0.42]
        }
       }
       ); 
       if (typeof(Event) === 'function') {
  window.dispatchEvent(new Event('resize'));
} else {

  var evt = window.document.createEvent('UIEvents'); 
  evt.initUIEvent('resize', true, false, window, 0); 
  window.dispatchEvent(evt);
}
   }
});
```

But it doesn't work on Safari.

**Comment by elliottbenzle** [comment]
Found the same issue. 'left' and 'top' styles are way off. After resizing the window this resolves itself. Will post back if I can find a solution.

**Comment by anseki** [comment]
Hi @krol1k and @elliottbenzle, thank you for the comments.

You have to call `position` method when the layout was changed without resizing the window.
See document: https://anseki.github.io/leader-line/#position

**Comment by anseki** [comment]
No reply came, then I close this neglected issue.
