### ISSUE TITLE
Separate lines when using grid path

### ISSUE THREAD

**Issue by henrik79** [anseki/leader-line#51]
Hi,

Is it possible to add space between lines when using path "grid"?

So that they don't overwrite each other.

[https://jsfiddle.net/8nqjkcfm/1/](https://jsfiddle.net/8nqjkcfm/1/)

BR

Henrik

**Comment by anseki** [comment]
Hi @henrik79, thank you for your comment.

Do you mean that you want to avoid overlapping lines?
Like this? : https://jsfiddle.net/z80cjtdx/

**Comment by henrik79** [comment]
Exactly. Just what I was looking for. Thanks!

Wonderful plugin :)

/Henrik

**Comment by anseki** [comment]
I'm glad if I could help you. :smile: 
So, could you close this issue if it was solved?

**Comment by henrik79** [comment]
Yes, we can close it. Thanks.
