### ISSUE TITLE
How to adjust path of line

### ISSUE THREAD

**Issue by myronzylka** [anseki/leader-line#52]
hi,
i have been facing issue in multiple elements on same page as line take starting and ending element which lead to over lapping other elements present on that page.is there any method to avoid overlapping as element postioning is dynamic. for ex i am attaching the screenshot.
![flow](https://user-images.githubusercontent.com/42038210/56359557-81939b80-61ff-11e9-9be5-574a52fc3b0e.jpg)

**Comment by anseki** [comment]
Hi @myronzylka, thank you for your comment.

You should call [`position`](https://anseki.github.io/leader-line/#position) method if the layout was changed without resizing the window.

**Comment by myronzylka** [comment]
hi @anseki,
i have already been using position method for layout.may be i was not able to explain it properly.the issue is when we draw between two elements  it should not overlap other elements all these three element in pic are fixed  but the line dint considered the third one.i wanted itself consider the sutable path which do not intersect other elements so that they are not overlaped

**Comment by anseki** [comment]
Hmm... Sorry, my English is poor. I couldn't understand your words well.
What is the "line dint" that you said?
Also, could you explain by indicating two figures (expected result and an actual result) that contain only minimum required elements and lines? (your first figure contained too many lines and elements.)

**Comment by myronzylka** [comment]
sorry my english is also not good.
i have made expected lines with teal(greenish) color for connecting element 3 to element 1  whereas i have circled the actual line with red as you could see the circled svg is overlapping a element 2 (which look similar to the connecting element 1 and 3 ) i actually wanted if svg could take different path if any other element (like element 2 here ) comes in its path.so if svg could take
![flow (2)](https://user-images.githubusercontent.com/42038210/56414270-ae02f280-62a7-11e9-8ffc-cf31e5e71330.png)
 any of expected path or any more sutaible path instead

**Comment by anseki** [comment]
Hmm... Sorry, I couldn't understand those...
* What is the "line dint"?
* What is the "convient"?
* Which is the "element1", "element2" and "element3"? Do you mean that the element1 contains four icons and three arrows?
* Could you explain by indicating **two figures** (expected result and an actual result) that contain **only minimum required** elements and lines? (your figure contained too many lines and elements.)

**Comment by anseki** [comment]
Also, do you want grid lines like the green lines in your figure?

**Comment by myronzylka** [comment]
Sorry there were spelling mistakes.
yes you are right element 1 contains 4 icons and three arrows. so like this, there are three elements eg-Element 1 in the image. 
-> In this jsfiddle IF YOU CHANGE startSocket to 'left' and endSocket to  'right' , you will be able to see the result given in below image. I wanted, if svg could change path if any element like box 2 and box 3 come in between its path.
 
![Screenshot from 2019-04-19 14-20-11](https://user-images.githubusercontent.com/42038210/56416537-c9bdc700-62ae-11e9-992e-3e5831f67c82.png)

**Comment by anseki** [comment]
Do you mean that the boxes are positioned dynamically?
And the line should dodge box-2 and box3.

**Comment by anseki** [comment]
Or, do you mean that the lines should not intersect?

**Comment by myronzylka** [comment]
ya boxes can be positioned dynamically and line should dodge box-2 and box-3

**Comment by anseki** [comment]
Hmm... That is rare case.
If you really want that, you have to change path data with coordinates of all elements.
The lines can intersect each other?

**Comment by myronzylka** [comment]
ya. they can intersect each if additional feature of curving line where intersecting will be great but not necessary.

**Comment by anseki** [comment]
Sorry, my English is poor. I couldn't understand your words well.
Do you mean that the lines that intersect each other look like joined lines?

**Comment by anseki** [comment]
You can customize the style to avoid looking like joined lines.
For example, three styles:
https://jsfiddle.net/ef0npmay/

**Comment by anseki** [comment]
You can create the line that dodges elements automatically by changing the path data when those are positioned.
However, that seems strange, and that may make another problem (e.g. performance, breakdown for too many elements, etc.).

I don't know what you are making, but I think that the UI is hard to use.
I suggest an UI that allows the user to adjust lines manually. This is flexible maybe.
For example:
https://jsfiddle.net/2Lvq1gnj/
Of course this example is incomplete. You might make "Add Relay" button.

**Comment by myronzylka** [comment]
But I cant ask person to change it manually I have to show person the way
he is selecting i.have to draw path accordingly

**Comment by anseki** [comment]
Do you mean that you want the line that dodges elements automatically?

**Comment by myronzylka** [comment]
ya i have to make changes in my code so that i can solve 99% cases or if it is possible on your hand i will be thankfull.i want line to dodge elements autimatically.

**Comment by anseki** [comment]
Thank you for your suggestion.
However, that feature should not be implemented because that is rare case.

As I said, you can create the line that dodges elements automatically by your way and your timing.
For example: https://jsfiddle.net/gmtwpL16/
This is example, therefore:
You might use another `path` such as `arc`.
You might add more elements.
You might change the path data. (See https://github.com/anseki/leader-line/issues/28)

**Comment by anseki** [comment]
No reply came, then I close this abandoned issue.

**Comment by anseki** [comment]
ADDITION:
https://jsfiddle.net/bg7chnvf/

**Comment by MDeus** [comment]
How can I adapt this code to a case where I have around 20 obstacles and like 10 leader lines. My application can have any number of obstacles and leader lines created and I don't want the leader lines to go over the elements which is what I have right now.

**Comment by anseki** [comment]
Hi @MDeus, thank you for the comment.
Which code are you talking about?

**Comment by MDeus** [comment]
Hi @anseki this is  a fiddle of my graph: [fiddle](https://jsfiddle.net/maudelined/xjmtw36u/37/). This is an example of a graph with 6 nodes and 5 edges. I am converting every edge into a leaderline. The only issue is that the edges cross over the nodes. I saw the fiddle you uploaded but your example only had one leaderline and I am not sure how I would adopt it to my code where the number of leaderlines I may have may even rich 100.

**Comment by anseki** [comment]
I see.
So, which code are you talking about? There are several examples in this issue.

**Comment by MDeus** [comment]
I'd say that I was not able to apply any of the examples to my issue. But I was referring to your most recent example.

**Comment by MDeus** [comment]
ok, Thank you so much I will try that! One last question, what does the gX and gY represent, is it the position of the element within the script?

**Comment by anseki** [comment]
Those are the coordinates with "grid" units instead of pixels.
