### ISSUE TITLE
It's not working when we update html using ajax 

### ISSUE THREAD

**Issue by AnkurBhadania** [anseki/leader-line#53]
When I was used the ajax to update or replace HTML it gives an error. "A disconnected element was passed." and "Uncaught TypeError: Cannot read property 'right' of null".

I have created a demo with a setTimeout method. after 10 seconds it not working 

https://jsfiddle.net/fmdx3n15/2/

**Comment by anseki** [comment]
Hi @AnkurBhadania, thank you for your comment.

So, I tried your example, and that worked fine without the error.
Could you reproduce that?

**Comment by AnkurBhadania** [comment]
@anseki Please check after 10 seconds. it stops working on resize

**Comment by anseki** [comment]
I see.
You should have said that the error is thrown when window is resized.

So, as the message said, "A disconnected element was passed".
That is, those elements were removed (i.e. those became disconnected elements) when you replaced the HTML code.
This is specification of HTML/DOM, it is unrelated to LeaderLine.
See: https://jsfiddle.net/cmyx5wjn/

**Comment by AnkurBhadania** [comment]
@anseki  thanks for your help. it working fine now.

**Comment by anseki** [comment]
I'm glad if I could help you. :smile: 
So, could you close this issue if it was solved?
