### ISSUE TITLE
Animating elements on top of lines (ie. dots)

### ISSUE THREAD

**Issue by szmigieldesign** [anseki/leader-line#55]
Hello,

it appears that this script will be very helpful for one particular section of a new website I'm developing. It seems very robust while being simple to implement. Many thanks for sharing!

However, I was thinking about adding a dot (perhaps with a pseudo-element or SVG) that would animate (with CSS anims) from start to end of each line. Basically such object would have to follow the line path.

Is it possible in current state of this script? How you would recommend to approach this issue?

**Comment by anseki** [comment]
Hi @szmigieldesign, thank you for your comment.

Sorry, I couldn't understand the "dot" well.
Does the `dash` option help you?
https://anseki.github.io/leader-line/#animation

**Comment by szmigieldesign** [comment]
Hello @anseki,

perhaps it'll be easier to explain with the design itself:
https://www.dropbox.com/s/6drsl3nrtkeaz39/Screenshot_2019-06-07%20Zeplin%20-%20Project.png?dl=0

You'll see the lines connecting divs. The lines have dots on top of them. It would be awesome if I could somehow animate the dots so that they follow line paths - just like the dash animation but with dots "on top of the line" kind of thing.

**Comment by anseki** [comment]
I see.
That is usually called "Motion Path", and it can be implemented easily with `animate​Motion` of SVG.
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/animateMotion

**Comment by szmigieldesign** [comment]
Thanks for the tip. As far as I'm aware - I'd have to modify the source to render additional circle element in SVG generated by the script and have it animated, right?

**Comment by anseki** [comment]
You can add a `<circle>` element by the script as you said, or you can add a SVG document into the HTML code because SVG supports reference to symbol.
For example: https://jsfiddle.net/dpaefb03/
Also, the third line is an example using `dash` option that I suggested before.

**Comment by szmigieldesign** [comment]
@anseki, thanks a ton for this example! That'll do :-)

**Comment by anseki** [comment]
I'm glad if I could help you. :smile:
So, could you close this issue if it was solved?

**Comment by szmigieldesign** [comment]
Sure, thing! 

PS. Method 3 with dashes if fine for simple dots animating on path. What I didn't get at first is to duplicate lines - one for the line itself and the second one for animation. It works great.
