### ISSUE TITLE
Need to support events on path/line and label

### ISSUE THREAD

**Issue by Umer-Hayyat** [anseki/leader-line#58]
Hi, 

Thank you for building such a useful utility to draw lines, appreciated.
I have a scenario where I need to perform some actions upon clicking a label or path/line. Need to support events on path/line and labels.

**Comment by anseki** [comment]
Hi @Umer-Hayyat, thank you for your comment.

These may help you:
https://github.com/anseki/leader-line/issues?q=is%3Aissue+event+listener

**Comment by Umer-Hayyat** [comment]
> Hi @Umer-Hayyat, thank you for your comment.
> 
> These may help you:
> https://github.com/anseki/leader-line/issues?q=is%3Aissue+event+listener

Hi Aneski, 
thank you for replying. I have multiple lines then how to differentiate those if I add event by SVG DOM

**Comment by anseki** [comment]
A line is added to the end of the list of children of the `<body>` element.
For example:

```js
var line1 = new LeaderLine(elmStart1, elmEnd1),
  elmLine1 = document.querySelector('body>.leader-line:last-of-type'),
  line2 = new LeaderLine(elmStart2, elmEnd2),
  elmLine2 = document.querySelector('body>.leader-line:last-of-type');
```

Note that these are not supported as I said in past issues.

**Comment by Umer-Hayyat** [comment]
Hi Anseki, 

is it possible for you to provide support onclick event on label text?

**Comment by anseki** [comment]
No, that should never be supported as I said repeatedly.
If you really want that, you can use `SVGDOM#addEventListener` to add event listeners to the labels.

**Comment by anseki** [comment]
No reply came, then I close this abandoned issue.
