### ISSUE TITLE
Support needed to append SVG inside a div

### ISSUE THREAD

**Issue by Umer-Hayyat** [anseki/leader-line#60]
Hi, 

I have a scenario where I have a container with scroll enabled and inside that container, I am using LeaderLine. 
The Issue is that when I scroll container, Path/Line appears in the body and there is no way to hide line as content are hidden by scroll.

**Comment by anseki** [comment]
Hi @Umer-Hayyat, thank you for your comment.

These may help you:
https://github.com/anseki/leader-line/issues?q=is%3Aissue+scroll

**Comment by anseki** [comment]
No reply came, then I close this abandoned issue.
