### ISSUE TITLE
showEffectName draw not working

### ISSUE THREAD

**Issue by signaturesteve** [anseki/leader-line#61]
Hi I have the following set:

```js
var tLine = new LeaderLine(tPreviousElement, tThisElement, {
                        endPlug: 'behind',
                        color: '#fff',
                        dash: {
                            len: 12,
                            gap: 8
                        },
                        showEffectName: 'draw',
                        hide: true
                    });
```

However the draw animation will not work,  it just fades in.   Any ideas? thanks

**Comment by anseki** [comment]
Hi @signaturesteve, thank you for the comment.
What do you want?
Could you explain about your expected result?
I couldn't understand your code.

**Comment by signaturesteve** [comment]
Sorry thats just a snippet, basically I have a 'line' that goes between various points (previous element, this element etc),  that works great its just the animation (the show effect) that isnt working, it does not perform the draw animation but it just fades in when I call show

**Comment by anseki** [comment]
The `showEffectName` does not exist in the constructor options. Therefore the `showEffectName` option is of course ignored when you specified that. This is correct behavior.
Maybe you mistook that for `showEffectName` **argument** of [`show`/`hide`](https://github.com/anseki/leader-line#show-hide) method.
For example:
https://jsfiddle.net/cj5fd1pn/

**Comment by anseki** [comment]
No reply came, then I close this abandoned issue.
