### ISSUE TITLE
Smooth out lines

### ISSUE THREAD

**Issue by signaturesteve** [anseki/leader-line#63]
Hi I have multiple points with lines between them, for the most part they curve nicely but at some points they will become quite sharp at the 'joints' .  is there a way to force the lines to curve all the way?

What we sometimes get...
<img width="440" alt="Screenshot 2019-08-15 at 14 19 23" src="https://user-images.githubusercontent.com/43985865/63097191-b6262280-bf67-11e9-81c1-4440ba0183a6.png">

What we want all the time...
<img width="388" alt="Screenshot 2019-08-15 at 14 19 26" src="https://user-images.githubusercontent.com/43985865/63097193-b6262280-bf67-11e9-87fa-58adbb416dfa.png">

**Comment by anseki** [comment]
You should finish your another issue that you ignored.
https://github.com/anseki/leader-line/issues/61
Also, you should not ignore anyone who tried to help you.

**Comment by signaturesteve** [comment]
Good job keyboard warrior.

**Comment by anseki** [comment]
Sorry, my English is poor, and I couldn't understand you well.
Are you batting me?

**Comment by anseki** [comment]
Ah, I see...
Sorry, bye. :smile:
