### ISSUE TITLE
Leader-line displays outside of viewbox

### ISSUE THREAD

**Issue by crackityjones666** [anseki/leader-line#64]
Hi,

Thank you very much for this wonderful library!  We are using LeaderLines inside a custom SVG designer tool to simulate connections between devices.

Our designer implement some features to drag and move devices.  Connections follows very well through the "position" function...

My main issue is that, when devices gets moved outside of an SVG viewbox, I wished that the LeaderLine would be hidden.

![LeaderLine outside Viewbox](https://user-images.githubusercontent.com/54278727/63274726-4b7a2d00-c26e-11e9-9c1f-efe3712cddb6.png)

Is it possible to achieve such behavior?

Thank you very much for your collaboration!

**Comment by anseki** [comment]
Hi @crackityjones666, thank you for your comment.
These may help you:
https://github.com/anseki/leader-line/issues/13
https://github.com/anseki/leader-line/issues/54

**Comment by slx2005** [comment]
Hi @anseki,

It seems like more and more people are asking for this feature, to be able to set the container in which the SVG's are rendered, I know the library doesn't support this, and you recommend to append the lines to the container, but is there a reason this could not be implemented? Is there and underlying issue?

**Comment by anseki** [comment]
Hi @slx2005, thank you for your comment.
Unfortunately, the appending the lines does not work well or it makes problems in many cases.
Therefore, I never recommend that, also the library can't support that. (See past issues that are linked above)
You should move the elements only when you understand structure of your page well and you can adjust style if it wants.
When more users request that, I might try to find a way to implement that.

**Comment by anseki** [comment]
No reply came, then I close this abandoned issue.
