### ISSUE TITLE
Draw effect animation

### ISSUE THREAD

**Issue by RodrigoMtz10** [anseki/leader-line#65]
Hello, I'm using this libary and let me tell you it's awesome, thank you so much.

I'm trying to use the showEffectName method and the 'draw' keyword so that whenever I create the line, it has that effect, but I'm struggling to do that.

```js
let line = new LeaderLine(
            button,
            point,
            {
              startPlug: 'behind',
              endPlug: 'disc',
              startPlugColor: '#00B7F1',
              endPlugColor: '#007AFF',
              gradient: true,
              size: 4.5,
              startSocketGravity: 0,
              endSocketGravity: 0,
              dash: {animation: true},
              path: 'fluid',
              animOptions: {duration: 500, timing: [0.58, 0, 0.42, 1]}
            }
          );
```

This is how I tried to do it, but it's not working, could someone explain me how to do it?

**Comment by anseki** [comment]
Hi @RodrigoMtz10, thank you for the comment.

The `showEffectName` method doesn't exist.
https://anseki.github.io/leader-line/#show-hide
I consider that this issue was already solved.
