### ISSUE TITLE
Leaderline library is not working 

### ISSUE THREAD

**Issue by naveencs1992** [anseki/leader-line#66]
First I downloaded leader-line.min.js and placed in my project, then i have applied <script src="leader-line.min.js"></script> in html page. 

I tried whatever given in example on leader-line website ,its not working

**Comment by anseki** [comment]
Hi @naveencs1992, thank you for the comment.
Do the "leader-line website" mean https://anseki.github.io/leader-line/ ?
Also, which example didn't work? E.g. Did the first example not work?

**Comment by swarupe** [comment]
Yes its not working. Line is not getting drawed. Tried first example also it was not getting added. Do we need to add any other css files or other js files to html?

**Comment by anseki** [comment]
Hi @swarupe, thank you for the comment.
So, are you @naveencs1992?

**Comment by swarupe** [comment]
No

**Comment by anseki** [comment]
I see.
Could you make new issue?
This is an issue for @naveencs1992.

**Comment by anseki** [comment]
No reply came, then I close this abandoned issue.
