### ISSUE TITLE
Missing dependency?

### ISSUE THREAD

**Issue by UKMonkey** [anseki/leader-line#67]
When I imported this project into my webservice, I found the following error was reported:

Uncaught TypeError: Cannot read property 'add' of undefined
    at leader-line.js:5165
    at leader-line.js:5187

the given line reads `window.addEventListener('resize', AnimEvent.add(function(/* event */) {`
Looking around, it seems like "AnimEvent" is something from another library?

**Comment by anseki** [comment]
Hi @UKMonkey, thank you for the comment.
LeaderLine has no dependency, only one file `leader-line.min.js` is required.
See document: https://anseki.github.io/leader-line/
If you want to use this in development mode (However, that is not recommended), you have to install `devDependencies` modules (not `dependencies`) by `npm install` command.

**Comment by anseki** [comment]
BTW, which file did you try to import?
In other words, the error and you have read, which file?

**Comment by anseki** [comment]
No reply came, then I close this abandoned issue.
