### ISSUE TITLE
Help with Angular implementation?

### ISSUE THREAD

**Issue by 949mac** [anseki/leader-line#68]
Hello, 

I have a simple component defined as follows:

```
import {Component, Inject, OnInit} from '@angular/core';
import {DOCUMENT} from '@angular/common';

import 'leader-line';
declare let LeaderLine: any;

@Component({
    selector: 'app-show-me',
    templateUrl: './show-me.page.html',
    styleUrls: ['./show-me.page.scss'],
})
export class ShowMePage implements OnInit {

    constructor(@Inject(DOCUMENT) private document) {
    }

    ngOnInit() {
        const line = new LeaderLine(
            this.document.getElementById('remainder'),
            this.document.getElementById('button0')
        );
    }
}
```
I already ran `npm i leader-line --save` and added the following to my angular.json script array:
```
            "scripts": [
              "./node_modules/leader-line/leader-line.min.js"
            ]
```

I'm getting an error in the console that says:

`ERROR Error: Uncaught (in promise): ReferenceError: LeaderLine is not defined`
![image](https://user-images.githubusercontent.com/23151962/64914122-9407f780-d701-11e9-8b14-31f86fc5f6bd.png)

I couldn't find much on an Angular implementation. I did find this: https://stackoverflow.com/questions/54908009/angular-library-for-drawing-lines-between-objects and I also found a few typescript projects on Github that appeared to implement in a similar manor but no luck on my side.

Any tips for Angular implementation?

Thank you.

**Comment by 949mac** [comment]
If I add `export` to the function in leader-line.min.js and import via
`import { LeaderLine } from '../../../../node_modules/leader-line';`  it looks like the library loads.

However, using  `this.document.getElementById('xxx')` in ngOnInit doesn't seem be attaching the line properly.

Is there a better approach to load the lib in Angular?

**Comment by anseki** [comment]
Hi @949mac, thank you for the comment.
For example, an easy way uses `@angular-builders/custom-webpack` and `skeleton-loader`.
https://github.com/anseki/leader-line/issues/8#issuecomment-370147614

**Comment by 949mac** [comment]
I'll give it a try. Thank you.

**Comment by anseki** [comment]
:smile:
