### ISSUE TITLE
StartPlug and EndPlug is not displaying on sufari browser

### ISSUE THREAD

**Issue by akashb5432** [anseki/leader-line#69]
Hi,
As i have integrated  leader line in my web application.
It is working fine for all browser except safari.
After drawing all lines, in safari startPlug and endPlug is not displaying.

Looking forward your response.

**Comment by anseki** [comment]
Hi @akashb5432, thank you for the comment.

Do you mean that the `startPlug`/`endPlug` options didn't work? (i.e. The plugs (symbols that are shown at the end of the leader line) were not changed)
Or, both plugs were not shown? (i.e. That was shown like `behind` for the `startPlug`/`endPlug` options.)

Also, could you tell me a version of the Safari?

**Comment by akashb5432** [comment]
yes, both start and end points are not showing in safari Version 13.0 (14608.1.49).

**Comment by anseki** [comment]
This is screen shot of example (https://anseki.github.io/leader-line/#startplug-endplug) in my environment.
![ss01](https://user-images.githubusercontent.com/4763469/65686120-97569800-e09e-11e9-8c38-077b86a58911.png)
Could you show me a screen shot of the example above in your environment?

**Comment by akashb5432** [comment]
Yes, it's working in my environment. Might be issue with the integration.

**Comment by anseki** [comment]
Maybe your code has problem.
So, did you close this issue because it was solved?
