### ISSUE TITLE
EventListener via SVGDOM

### ISSUE THREAD

**Issue by spgonejoker** [anseki/leader-line#70]
Hello, 
i want to add an event listener to the SVG, which is created by your library. 

My task is: 
Delete a line with a double click directly instead of searching for the element. 

I added successfully an id to identify the svg directly, but now i have problems to add event listener. 
I have read all issues regarding event listeners, but in my case they didn't help much.

So it would be great to show me a way to implement an event listener directly to the line :)

Greetings

**Comment by anseki** [comment]
Hi @spgonejoker, thank you for the comment.
Could you explain about the problems to add event listener to the SVG elements that were given ID?
Or, could you show me your code?

**Comment by anseki** [comment]
I don't know what is problem in your code because I didn't read your code.
So, does this example help you?
https://jsfiddle.net/g4ksLh9v/
Note that this is not supported, and removing by double-click is not good idea for usability.

**Comment by spgonejoker** [comment]
Oh, that looks helpful. Thank you :)

**Comment by anseki** [comment]
I'm glad if I could help you. :smile: 
Could you close this issue if it was solved?

**Comment by spgonejoker** [comment]
It works like intended! Thank you very much :)
