### ISSUE TITLE
How to import/require/src?

### ISSUE THREAD

**Issue by xeroxstar** [anseki/leader-line#74]
I am not able to start going with this module, i tried everything to import it but nothing works:
i run `npm install leader-line`
After i try to import it and getting errors from every angle, i am using Vue framework and not sure what i am missing here:

`import LeaderLine from '../../node_modules/leader-line/leader-line.min.js'`
Error: **_node_modules_leader_line_leader_line_min_js__WEBPACK_IMPORTED_MODULE_1__.LeaderLine is not a constructor**
`import { LeaderLine } from '../../node_modules/leader-line/leader-line.min.js';`
Error: **Uncaught TypeError: LeaderLine is not a constructor**
<script src="'../../node_modules/leader-line/leader-line.min.js"></script>
Error:**Uncaught ReferenceError: LeaderLine is not defined**

**Comment by xeroxstar** [comment]
So i got this boy up and running with Vue, you just have to add at the `leader-line.min.js` a line at the bottom of the file: 
 `module.exports = LeaderLine`; 

then run:
let LeaderLine = require('LeaderLine');
new LeaderLine (this.$refs.pointA,this.$refs.pointB) :)

**Comment by anseki** [comment]
Hi @xeroxstar, thank you for the comment.

The best and easy way to import it is using Webpack and `skeleton-loader`.
https://github.com/anseki/leader-line/issues/8#issuecomment-370147614

At least, you should use `export default` instead of `module.exports` in your code because that is CommonJS that might be not supported in some environment.

**Comment by anseki** [comment]
Also, if you added the `<script>` element, you don't have to import that because it was already loaded.
This is the JavaScript specification.

**Comment by xeroxstar** [comment]
Thanks, by the way, this is an amazing module.

**Comment by anseki** [comment]
:smile:
