### ISSUE TITLE
Ability to set thinner outline on endplug

### ISSUE THREAD

**Issue by sashabeep** [anseki/leader-line#75]
End connector scales with its outline causing very thick border.
How to maintain border to be exact size?

```js
endPlugSize: 7,
endPlugOutlineSize: 1,
```
![Снимок экрана 2019-10-22 в 17 49 56](https://user-images.githubusercontent.com/5689796/67298816-742fd480-f4f4-11e9-912c-dd3adf63cb76.png)

```js
endPlugSize: 2,
endPlugOutlineSize: 1,
```
![Снимок экрана 2019-10-22 в 17 52 31](https://user-images.githubusercontent.com/5689796/67298978-bd802400-f4f4-11e9-886b-270f267ff385.png)

There is no unminified version in repository to find out how to do it by myself
Also values less than 1 is not supported at all. Sometimes the line is too thick.

BTW, this is the only one plugin that does what it does - connecting any elements on the page. Very helpful thing

**Comment by sashabeep** [comment]
```css
.leader-line-plug-outline-mask-shape{
    stroke-width: 1px !important; 
}
```
solves the issue in my case

**Comment by anseki** [comment]
Hi @sashabeep, thank you for the comment.

The size of outline is calculated by following mathematical expression.
```js
size * [default-plug-scale] * OPT.endPlugSize * [default-plug-outline-scale] * OPT.endPlugOutlineSize
```
The `endPlugSize` is greater than or equal to `1` and is less than or equal to `outlineMax`.
See: https://anseki.github.io/leader-line/#startplugoutlinesize-endplugoutlinesize

If you want another, you can hack that by CSS as you said, but it is of course not supported.

**Comment by anseki** [comment]
BTW, I don't know a line that you want, but the `endPlug` seems to be not adequate for your purpose.
The [`areaAnchor`](https://anseki.github.io/leader-line/#areaanchor) might help you.

**Comment by sashabeep** [comment]
@anseki at the first sight endPlug was easier to implement because of changing endpoint size on-the fly in my script. Some of my elements is IMGs, and some is just invisible DIVs with coordinates which uses small circle for endpoint. Using simple condition i was able to set the "radius" of endpoint
```js
...
//check if endpoint is icon
                    if ($endpoint.tagName.toLowerCase() == "img") {
                        defopts.endPlugSize = 6;
                    }
var line = new LeaderLine(start, end, defopts);
...
```
Setting stroke width in CSS works for me in this particular case.
I've used areaAnchor in text description and now i find out that it can be used on both sides of line with almost the same condition about circle size. 

Thanks. If it will be possible please publish unminified version in future releases too.

**Comment by anseki** [comment]
I'm glad if I could help you. :smile: 
The unminified version as source code is already being published in this repository.
