### ISSUE TITLE
Remove( ) options returns error when svg is appended to Div

### ISSUE THREAD

**Issue by sebasttti** [anseki/leader-line#76]
Hello, basically I wanted to tell you that I did the example you gave in past issues about appending svg to div, so when can hide lines on scrolling divs.

https://jsfiddle.net/heuj7mso/

The problem is that, when using this method, it returns an error on using the remove() method of the instaces object by LeaderLine, so what I do now is deleting the svg and deletind the variable of the name.

I trully believe that drwing the lines insde a div could be a great advantage for the repository. I have read that it is a difficult process, but doing what you showed in the example, but inside the class so the user dont notice could work.

Thanks a lot in advance for your repository, it has helped me a lot.

**Comment by anseki** [comment]
Hi @sebasttti, thank you for the comment.
Sorry, my English is poor.
Do you mean that you want to avoid an error?
However, the example that you indicated did not throw an error, also it doesn't seem to append SVG to `div` element.
Also, `remove` is method, it is not option. Do you mean that you tried to use the `remove` as an option?

**Comment by sebasttti** [comment]
Let me explain it to you.
In the example in the link, the solution you gave us for putting the lines inside a div, so they don't overlapse on scrolling that div was to append those lines to a wrapper div, and position it at the top corner on the page so it can maintain the original coordinates.

So far I'm just describing what I found on the link.

The problem is. What happens if I want to remove one leader-line? Well, we use method remove of leader-line right?

Well, if we use method remove() js throws an error because it can't find the Node. That is basically the issue.

**Comment by anseki** [comment]
I re-tried the example that [you indicated](https://github.com/anseki/leader-line/issues/76#issue-512177681).
However, it doesn't append SVG to div element, it uses "clip", also it did not throw an error. The line can be removed without an error.
Also, you said "Remove( ) options", is this your wrong?

**Comment by vatsalpande** [comment]
Sorry, if its a wrong question to ask here, but is there an option that can tell me if the line is already removed?

**Comment by anseki** [comment]
Hi @vatsalpande, thank you for the comment.
Could you make new issue for your question?

**Comment by sebasttti** [comment]
I'm sorry, I put the wrong link. The link I used is this one
https://jsfiddle.net/op2gnk0t/

Here, in JS lines 13 and 14 you do the appending. 

Using this same example, if I try to remove a line using line.remove() it throws an error.

**Comment by anseki** [comment]
I see.
Maybe you didn't read that issue until the end because that is long.
See this comment, and try this example.
https://github.com/anseki/leader-line/issues/54#issuecomment-521137273
You can remove lines without an error very easily. The example removes lines after 3secs.

**Comment by sebasttti** [comment]
Ohhhhhhh. Basically you return the lines to the body, so they can be found, and after Removed. (I haven't thought about that).

What I did was deleting the object with the class ".leader-line" and after delete the variables that holds the line.

Well, it seems this issue is solved. Just wanted to thank you again for this repo, I can't use enough words to tell how it has helped me in may work. Thanks for PlainDraggable too. If you ever consider opening a donation account on paypal, count with my contribution. Best regards and greetings form Colombia.

**Comment by anseki** [comment]
I'm glad if I could help you. :smile:
