### ISSUE TITLE
Programming method of Leader-line

### ISSUE THREAD

**Issue by sebasttti** [anseki/leader-line#77]
I'm sorry I'm asking you about this, but, could you please tell us what frameworks or tools did you use to create this repository, like eslint or something like that. If we want to do our apports, what tool do we have to use?

I'm asking you because I read the minified version, but, because it is transpiled I guess, I couldn't understand it

**Comment by sebasttti** [comment]
Did you write the code using any template or framework, or just vanilla JS? 

I notice it is a little bit complex, but I'd want to understand how it works from the inside.

What tool you used to transpile it?

**Comment by sebasttti** [comment]
OK man, it is still a great code. Thanks again. I'm gonna close this issue. I'm really gratefull with you

**Comment by anseki** [comment]
:smile: 
Anyway, the code and mechanism are simple. It's a bit long.
