### ISSUE TITLE
Extra space added to site when library is used on Internet Explorer & Edge

### ISSUE THREAD

**Issue by 10P** [anseki/leader-line#78]
Hi, 

I noticed an issue when the leader-lines are being used on a site when displayed on Internet Explorer or Edge. It seems like extra space is being added to the right and the bottom of the web page. I included a screenshot below which shows how much scrollable space has been added to the Leader-Line demo site when viewed on Internet Explorer. You can see that this is the bottom of the site when viewed on other browsers, but there is a lot of space to the bottom and to the right.
This issue doesn't show up on Chrome or Firefox.  

![ieExtraSpaces](https://user-images.githubusercontent.com/3535483/68325464-7454d600-0097-11ea-9150-2ff6fe044f7c.png)

**Comment by anseki** [comment]
Hi @10P, thank you for the comment.

Yes, I know this issue...
As you said, it occurs only in IE and Edge, then it seems a bug of IE and Edge.
I tried to avoid the issue so much, but I couldn't find the way to avoid that. Curious to say, the extra space was removed by pressing "F5" key on rare occasions. I gave up when I saw it... This is too strange bug.

I welcome a way to avoid the issue or information about it.

Temporary solution, the extra space might be removed by adding this line in your HTML code.
```html
<style>svg.leader-line { overflow: hidden !important; }</style>
```
Note that this might not remove the extra space, and this might break layout of your page. Anyway, you have to check that.

**Comment by anseki** [comment]
No reply came, then I close this abandoned issue.
