### ISSUE TITLE
Using with Webpack

### ISSUE THREAD

**Issue by confidence68** [anseki/leader-line#8]
您好，看了之前的Issues,#2，但是还是不是很清楚如何引用，你说的用skeleton-loader这个的作用是什么？不是很明白，我是直接npm安装，然后直接import,这样在vue created中使用是不可以的。还望指点，谢谢！

**Comment by anseki** [comment]
Hi @confidence68, thank you for the comment.
Sorry, I can't read Chinese.
Do you mean that you want to know about the skeleton-loader?

**Comment by confidence68** [comment]
Thanks for the  reply, @anseki.
 I'm very sorry, I thought you were Chinese.
After see the Issues #2 ,But i still not clear how to use the project in  Vue or React。In fact, I have a similar problem with #6。
In my project i also use vue-loader .I want to know ,If I want to use leader-line,I must install skeleton-loader?

My current practice is that I install leader-line by NPM ,and then import it in my project .but this is not possible.

Thinks!

**Comment by anseki** [comment]
I see.
The `import` statement in ECMAScript needs just a `export` statement. The LeaderLine now is provided as ES5, not ES2015.
Therefore, you can import that into your script easily by using the skeleton-loader that inserts the `export` statement.
For example, simplest case:

(Of course you already installed the skeleton-loader and leader-line.)

`src/index.js`

```js
import LeaderLine from 'leader-line';

var line1 = new LeaderLine(
  document.getElementById('start'),
  document.getElementById('end')
);
```

`webpack.config.js` (for Webpack v3)

```js
module.exports = {
  entry: './src/index.js',
  output: {
    path: __dirname,
    filename: 'bundle.js'
  },
  module: {
    rules: [
      {
        test: require('path').resolve(__dirname, 'node_modules/leader-line/'),
        use: [{
          loader: 'skeleton-loader',
          options: {procedure: content => `${content}export default LeaderLine`}
        }]
      }
    ]
  }
};
```

Run `webpack`.
And open this HTML file by web browser.

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    div {
      background-color: blue;
      color: white;
      width: 80px;
    }
  </style>
</head>
<body>

  <div id="start">start</div>
  <div id="end" style="margin: 160px 0 0 240px;">end</div>

  <script src="bundle.js"></script>

</body>
</html>
```

**Comment by anseki** [comment]
Or, more easy way without using the skeleton-loader:

```js
window.LeaderLine
```

 Also, you can access to `LeaderLine` after a statement:
```js
const LeaderLine = window.LeaderLine;
```

**Comment by confidence68** [comment]
Thank you very much. It has solved my problem！

**Comment by anseki** [comment]
:smile:

**Comment by logesh-freshworks** [comment]
try this solution #6

**Comment by Zvax** [comment]
I really do not understand the thumbs down here.

The skeleton loader fix is concise and, most importantly, works.

**Comment by anseki** [comment]
Hi @Zvax, thank you for the comment.
Yes, as you said, the skeleton-loader is good solution for legacy libraries. But user who doesn't understand Webpack and can't write config will be dissatisfied. Therefore, I think that the thumbs down doesn't really mean much. That is, the issue is solved very easily by user who knows Webpack, and the user never click the thumbs down button.
I hope that they who clicked the button learn Webpack and that solution. :smile:
