### ISSUE TITLE
Size property does not change "thickness" of line

### ISSUE THREAD

**Issue by wolfhog** [anseki/leader-line#80]
Hello, I am trying to draw a dashed line between two elements, however no matter what the size property is set to it's always the same thickness, the only thing that changes is the length and number of the dashes, my code is:
```
new LeaderLine(
	document.getElementById('icon2'),
	document.getElementById('icon3'),
	{
		dash: true,
		color: '#e3e3e3',
		size: 20,
		startPlug: 'behind',
		endPlug: 'behind',
	}
);
```

And this is what I see:
![image](https://user-images.githubusercontent.com/770255/68988491-9a504800-0806-11ea-9e28-fde29ef29b2d.png)

Thank you

**Comment by wolfhog** [comment]
Realized what was wrong right after I submitted the issue, it was a problem on my end, sorry.

**Comment by anseki** [comment]
Ok :smile:
