### ISSUE TITLE
Integrations of four more sides

### ISSUE THREAD

**Issue by narendersaini32** [anseki/leader-line#81]
Hi Sir Thanks for this wonderful library.
Actually we are using this library in our project and want to extend it. Currently the library provides
five options 'top', 'right', 'bottom', 'left' or 'auto'. and we want to include four more sides i.e the corners of the rectangles
![image](https://user-images.githubusercontent.com/50134025/69027219-21164800-09f4-11ea-8e04-613d509e21b2.png)
The brown one are those these library providing and green one are those that we want can you suggest/guide which functions/code we modify/update in source code to achieve that.

**Comment by anseki** [comment]
Hi @narendersaini32, thank you for the comment.
You can point anywhere in the element or the document by using [`pointAnchor`](https://anseki.github.io/leader-line/#pointanchor) attachment.

**Comment by narendersaini32** [comment]
Thanks Sir

**Comment by anseki** [comment]
:smile:

**Comment by narendersaini32** [comment]
Hi Sir
I tried with pointAnchor which is good but not fulfill my requirements we can change the x,y positons of starting and end of a connection but we need diagonally direction for connection

![image](https://user-images.githubusercontent.com/50134025/69034201-a30f6c80-0a06-11ea-8214-f09df0b053e9.png)

![image](https://user-images.githubusercontent.com/50134025/69034297-e8339e80-0a06-11ea-96b0-5533ff345f9f.png)

**Comment by narendersaini32** [comment]
Something between bottom and right direction

**Comment by narendersaini32** [comment]
![image](https://user-images.githubusercontent.com/50134025/69034444-3ea0dd00-0a07-11ea-9923-e8f678d83cc0.png)
Something like shown in the above pic pointAnchor only change the x,y but we required direction also do you have some suggestions

**Comment by anseki** [comment]
Sorry, your English is difficult for me...
Could you add period and commas?

**Comment by narendersaini32** [comment]
Sir I can change the location of the connection's start and end point on element using pointAnchor.  
But I also need to rotate the starting and end of connection. For example:- I can create socketEnd, socketStart direction using right, left, top, bottom values but i need to create something middle of right and bottom which is not possible using pointAnchor.

**Comment by narendersaini32** [comment]
how i create socketEnd and socketStart with green arrow directions as shown in image

![image](https://user-images.githubusercontent.com/50134025/69039768-95f87a80-0a12-11ea-8c1f-9dc327b14a69.png)

**Comment by anseki** [comment]
Do you mean that you want to specify the direction of line (not only point)?

**Comment by narendersaini32** [comment]
yes

**Comment by narendersaini32** [comment]
![image](https://user-images.githubusercontent.com/50134025/69042254-ea9df480-0a16-11ea-9bb7-095da74f77c4.png)
Something like this

**Comment by anseki** [comment]
I see.
For example: https://jsfiddle.net/psum8veb/

**Comment by narendersaini32** [comment]
yes thanks Sir :+1

**Comment by anseki** [comment]
:smile:
