### ISSUE TITLE
mouseHoverAnchor styling ?

### ISSUE THREAD

**Issue by varunistar** [anseki/leader-line#82]
Is there any way to remove the pre made styling for the mouseHoverAnchor  parent element (background etc)

**Comment by anseki** [comment]
Hi @varunistar, thank you for the comment.
You can remove background properties by this:
```js
element.style.background = ''
```
This is unrelated to the library.

**Comment by varunistar** [comment]
Ha got it ,
I thought there would be some option to remove the styling when i draw the line
Anyways thank u

**Comment by anseki** [comment]
Of course you can also do that by [`style`](https://anseki.github.io/leader-line/#style) option.
