### ISSUE TITLE
Position of the line is not correct when i try to draw a line in an overflow container

### ISSUE THREAD

**Issue by varunistar** [anseki/leader-line#84]
When i try to draw a line from a container which has overflow property the line is not positioned correctly

**Comment by varunistar** [comment]
I tried line.position that didnt work

**Comment by anseki** [comment]
Could you show me an example by using e.g. https://jsfiddle.net/ ?

**Comment by narendersaini32** [comment]
Same with my case maybe we need to modify the top and left values of svgs

**Comment by narendersaini32** [comment]
@varunistar hey found any solution buddy?

**Comment by anseki** [comment]
No reply came, then I close this abandoned issue.
@narendersaini32, this issue is unclear. If you have an issue, please create new issue.
