### ISSUE TITLE
不用使用import xxx from xxx 的方式引入

### ISSUE THREAD

**Issue by 826327700** [anseki/leader-line#85]
不用使用import xxx from xxx 的方式引入

**Comment by anseki** [comment]
Hi @826327700, thank you for the comment.
Sorry, I can't understand your language, but you may see the [document](https://anseki.github.io/leader-line/#usage) to solve that.

**Comment by 826327700** [comment]
> Hi @826327700, thank you for the comment.
> Sorry, I can't understand your language, but you may see the [document](https://anseki.github.io/leader-line/#usage) to solve that.

Sorry,I thought you were Chinese。
Well, This package can't use like this "import xxx from xxx " in vue or react ?

**Comment by anseki** [comment]
You can import it by using Webpack and `skeleton-loader`.
https://github.com/anseki/leader-line/issues/74

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
