### ISSUE TITLE
Is it possible to draw a line from static element to the cursor position?

### ISSUE THREAD

**Issue by rokmesojedec** [anseki/leader-line#86]
First of all, I'd like to give big thanks to @anseki  for this library. It's really well done and is helping my project immensely.  Thank you :+1: :smiley:

Now, I'd like to ask if the following is possible with **leader-line**: 

On mouse down on target element draw a line from the clicked element to cursor's position, the line should be redrawn to and when the cursor is moved. The line would disappear once the user releases the mouse button.

I need this for a tool I'm building where users can connect elements with lines, and I would like to mimic  functionality of Visio where you can drag and pull the line to the target element.

**Comment by anseki** [comment]
Hi @rokmesojedec, thank you for the comment. :smile: 
Does this example help you?
https://anseki.github.io/leader-line/#startsocket-endsocket
If you want to draw a line from the element to mouse pointer that no-element is there, you can do that by using [`pointAnchor`](https://anseki.github.io/leader-line/#pointanchor). That allows a line to be positioned anywhere in the document.
Or, you might use a transparent element.

**Comment by rokmesojedec** [comment]
The [draggable example](https://anseki.github.io/leader-line/#startsocket-endsocket) did the trick! Thanks a lot.
