### ISSUE TITLE
repositioning not working when more than one lines are drawn

### ISSUE THREAD

**Issue by adityapareek18** [anseki/leader-line#88]
Hi,

It's a strange one.
When there are multiple lines drawn to a scrollable element, It doesn't reposition on the scroll event. However if there is only one line then it does.

The error shown on console is:

A disconnected element was passed.
core.js:1673 ERROR TypeError: Cannot read property 'right' of null

Here is a stackblitz [demo](https://stackblitz.com/edit/angular-khfrwr).
Your response will be greatly appreciated.

Thanks,
Aditya

**Comment by anseki** [comment]
Hi @adityapareek18, thank you for the comment.
To reproduce that, could you show me an example by using e.g. https://jsfiddle.net/ ?
The your demo didn't reproduce that.

**Comment by adityapareek18** [comment]
Hi @anseki Thanks for your quick response. The demo is working on my end, Please follow this gif for steps to reproduce. Meanwhile I work on jsfiddle also.
![leader-line](https://user-images.githubusercontent.com/13797829/70221671-c9efd180-176e-11ea-9428-7ff5800d7a6c.gif)

**Comment by anseki** [comment]
The `core.js` that threw the error is not LeaderLine. Maybe your code has a problem.
Anyway, if you show an example by using https://jsfiddle.net/, I or someone might be able to help you.

**Comment by adityapareek18** [comment]
Tried making a demo in jsfiddle, it's working fine there. May be issue is because of the framework (angular 6) and how it works with the DOM.

**Comment by anseki** [comment]
I see.
Thank you for your report :smile:
