### ISSUE TITLE
import LeaderLine

### ISSUE THREAD

**Issue by userliuyi** [anseki/leader-line#89]
Hello, I need to use leader-line, to use import LeaderLine from "leader-line" in webpack4, but reporting that LeaderLine is not a constructor

**Comment by anseki** [comment]
Hi @userliuyi, thank you for the comment.
You can import it by using Webpack and `skeleton-loader`.
https://github.com/anseki/leader-line/issues/8#issuecomment-370147614

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
