### ISSUE TITLE
Arrows don't respond to page scroll when pointed at static/sticky object

### ISSUE THREAD

**Issue by James-Curran** [anseki/leader-line#9]
If you have something like a sticky footer and have an arrow pointing from element X on the page to element Y in the sticky footer, when the user scrolls down the page the arrow will stay bound to element X however the length will not change to accommodate the now greater distance between X and Y, therefore resulting in the arrow moving further and further away from Y the more you scroll.

**Comment by anseki** [comment]
Hi @James-Curran, thank you for the comment.
You should call [`position`](https://anseki.github.io/leader-line/#position) method when the layout was changed without resizing the window.
Maybe, your case likes the example in the link above. Please scroll a small frame, then you will see that the leader-line follows an element that is moved by scrolling.

**Comment by James-Curran** [comment]
Thanks for the prompt reply, I should of read the (excellent) documentation more thoroughly. The library is amazing, you've done a really great job with it, thanks again!

**Comment by anseki** [comment]
I am happy that I can help you. And thank you for your comment about the library. :smile: 
So, can you close this issue because it was solved?
