### ISSUE TITLE
The <svg>  is appended to <body>

### ISSUE THREAD

**Issue by NidusP** [anseki/leader-line#90]
Hello, I notice that  the line,  SVG is always added under the body,  Can i append it to other div elements? Because when the 'start' and 'end' Elements have an absolute position,  scrolling would have an impact on <SVG>. 
Do you have  any method ?  Thanks.

**Comment by anseki** [comment]
Hi @NidusP, thank you for the comment.
This may help you: https://github.com/anseki/leader-line/issues/54#issuecomment-498528407
Note that it is not supported.

**Comment by rich-poole** [comment]
Just wanted to say thanks for this awesome library, it's saved me a heap of work! I had to use the hack above as well, the main downside being the remove() method throws an error but I've coded around that. It's worth it for me as I can benefit from proper overflow controls in the parent container.

**Comment by anseki** [comment]
Hi @rich-poole, thank you for the comment.
Sorry, my English is poor.
Do you mean that the `remove` method threw an error because this library has problem?
Please give details about that error and your code that didn't work.

**Comment by rich-poole** [comment]
No problem at all with the standard library, but if you use the code to
move the lines into a different element (instead of the body) then the
remove method will throw an error.

**Comment by anseki** [comment]
This comment, and this example may help you:
https://github.com/anseki/leader-line/issues/54#issuecomment-521137273
You can remove lines without an error very easily. The example removes lines after 3secs.
Note that those are not supported.
