### ISSUE TITLE
Line Color Change Transition

### ISSUE THREAD

**Issue by AaronAtkinson** [anseki/leader-line#91]
Is there anyway to have the line color transition when it's changed?

I tried adding a CSS transition attribute to the leader-line class, but it doesn't seem to apply to color changes.

Super simple example of the transition effect I'm looking for. 
https://jsfiddle.net/airatkinson/p71dxr8g/

**Comment by AaronAtkinson** [comment]
I was able to add a transition to the line element by adding a stroke style it's <use> tag.

<style>
.leader-line use{
  transition: stroke 1s;
  -webkit-transition: stroke 1s;
}
</style>

Thanks for the fantastic library!

**Comment by anseki** [comment]
:smile:
