### ISSUE TITLE
lines hidden if target elements have non-zero z-index 

### ISSUE THREAD

**Issue by zoranpopovic** [anseki/leader-line#92]
Thanks for a great tool.  quite comprehensive.  There is one issue that seems to be a showstopper for us, however:

Tooltips and overlays are often drawn at different depth (z-index).  Currently there is no way for leader-line to appear in tooltips or overlays -- they end up  being hidden behind.

can we add a parameter to  specify the z-index of the drawn svg elements?  or at least, internally make svg elements have the same z-index value as the target elements they are connecting?

**Comment by anseki** [comment]
Hi @zoranpopovic, thank you for the comment.
This may help you: https://github.com/anseki/leader-line/issues/26

**Comment by zoranpopovic** [comment]
Thanks @anseki.  That works in general, but not when lines are both in background and in overlay (at different z-index values).  given a `let line = LeaderLine(...)` is there a way to get the svg element produced by that call, so that i can set the z-index to just that line, rather than all lines in the document?

**Comment by anseki** [comment]
Try this:
```js
const
  line1 = new LeaderLine(elmA, elmB),
  elmLine1 = document.querySelector('.leader-line:last-of-type'),

  line2 = new LeaderLine(elmC, elmD),
  elmLine2 = document.querySelector('.leader-line:last-of-type');
```

For your information, default of `z-index` is `auto`, it is not zero.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.

**Comment by SalkiDixit** [comment]
@anseki I am trying to give z-index to the line while hovering, not working.

**Comment by anseki** [comment]
Hi @SalkiDixit, thank you for the comment.
Could you make new issue for the different topic? And explain details.

**Comment by zoranpopovic** [comment]
it worked well, thanks!

**Comment by anseki** [comment]
@zoranpopovic :smile:
