### ISSUE TITLE
Change pointAnchor depending on direction of drag

### ISSUE THREAD

**Issue by yepecece** [anseki/leader-line#93]
Hi,
I have a draggable element that returns to its origine on _onDragEnd_. 
This item is connected by a line to the origin position.
I would like to move the _pointAnchor_ when I drag the element to the right of the origin (in order for it to be on the left of the draggable element element).

What would be the way to change _pointAnchor_ on _onMove_?
Here is the code
https://jsfiddle.net/0asrxjmL/9/

Thanks for your help.

**Comment by anseki** [comment]
Hi @yepecece, thank you for the comment.
You can change the `start` or `end` option to another one.
For example:
```js
line.end = LeaderLine.pointAnchor(target2, {x: '100%', y: 260});
```

**Comment by yepecece** [comment]
Perfect. Thanks for your help.

**Comment by anseki** [comment]
:smile:
