### ISSUE TITLE
Use drag item in combinaison with Flickity handle

### ISSUE THREAD

**Issue by yepecece** [anseki/leader-line#94]
Hi, I am trying to use a drag item with Flickity (https://flickity.metafizzy.co). Do you have an idea as how I could bind the drag of the item with the drag of the slider?

Here is a basic slider with a custom handle and the draggable item.
https://jsfiddle.net/1unbwmja/10/

**Comment by anseki** [comment]
Hi @yepecece, thank you for the comment.
Sorry, do you mean that you want to draw a line between a cell of Flickity and something?

**Comment by yepecece** [comment]
Basically I want the custom handle in Flickity to be the draggable element setup with PlainDraggable. If you see in the JSFiddle the gray square is the custom handle that is used to switch slides in Flickty on drag.

**Comment by anseki** [comment]
Is this an issue about LeaderLine?

**Comment by yepecece** [comment]
Sorry, you are right. I will go ahead and ask this in the PlainDraggable git.
Thanks.
