### ISSUE TITLE
Is there a plan to support “typescript”？

### ISSUE THREAD

**Issue by Ryqsky** [anseki/leader-line#95]
First , leader-line library has helped me a lot and thank @anseki  very much.
And i want to ask that Is there a plan to support “typescript” ?
Because typescript is becoming more and more popular now.

**Comment by anseki** [comment]
Hi @Ryqsky, thank you for the comment.
What does “support TypeScript” mean?
If you mean that you want a TypeScript type definition for LeaderLine, you can write that to `@types` and publish it on [`DefinitelyTyped`](https://github.com/DefinitelyTyped/DefinitelyTyped).

**Comment by cc189** [comment]
One easy solution is to add `noImplicitAny: false` in your `tsconfig.json`, but you will lose the type-safety feature.

```json
// tsconfig.json
{
        "compilerOptions": {
                "noImplicitAny": false
        }
}
``` 

> note:
> "noImplicitAny" raise error on expressions and declarations with an implied any type

**Comment by anseki** [comment]
Hi @cc189, thank you for the comment.
In general, that is a workaround for a package that has no type definition file.
Could you write a type definition?

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.

**Comment by brickolicious** [comment]
You could always grab the types file from the [new-leader-line ](https://github.com/II-alex-II/leader-line-new/blob/master/types/index.d.ts) if he doesn't object.

**Comment by anseki** [comment]
Hi @brickolicious, thank you for the information.
However, the package seems to have problem.
To avoid confusion, I hid the information.
Thank you.
