### ISSUE TITLE
Question: Curved grid paths during .show('draw')

### ISSUE THREAD

**Issue by joespiteri** [anseki/leader-line#97]
Not an issue but more of an implementation question.

In this comment: https://github.com/anseki/leader-line/issues/28#issuecomment-425339319_

You posted a solution for rounded corners when using grid paths:
https://jsfiddle.net/m4p5zvsg/

This is exactly what I needed, thank you. But is there a way to retain this style when animating the lines with the line.show('draw') method?

**Comment by anseki** [comment]
Hi @joespiteri, thank you for the comment.

LeaderLine has own `pathList` as path data, then the changed path data is restored by original path data.
Therefore, there is no way to run the `draw` effect with keeping the path data.
You can emulate that by using CSS animation.
For example:
https://jsfiddle.net/xhdr2puy/
You may have to customize the code for cross browsers.

**Comment by joespiteri** [comment]
Hi @anseki,
Thank you soo much for such a quick and useful reply.
This is exactly what I need.
Thanks.

**Comment by anseki** [comment]
:smile:
