### ISSUE TITLE
Line popping out of div

### ISSUE THREAD

**Issue by SalkiDixit** [anseki/leader-line#98]
@anseki Hi, I have a scrollable div, in that div elements are connected with leader-lines, when elements increase horizontally , lines goes out of div, elements are position absolute.
i checked ticket no 79 and 83, tried both but couldn't resolve my issue.

**Comment by anseki** [comment]
Hi @SalkiDixit, thank you for the comment.
Could you show me an example by using e.g. https://jsfiddle.net/ ?

**Comment by SalkiDixit** [comment]
@anseki updated, kindly look into it

**Comment by anseki** [comment]
Tell me an URL of JSFiddle page that contains your example.
That is made by "Save" button on top left.

**Comment by SalkiDixit** [comment]
@anseki https://jsfiddle.net/6Ly90mbc/ check this

**Comment by anseki** [comment]
I tried your example, but that didn't work. That seems to contain `require` etc.

**Comment by SalkiDixit** [comment]
I am using angular 8, there is some typescript error showing.

**Comment by SalkiDixit** [comment]
Can you check the code once...What am I doing wrong.

**Comment by anseki** [comment]
I don't know what is problem that you think.
Could you customize this example to show the issue?
https://jsfiddle.net/qp45vd2k/

**Comment by SalkiDixit** [comment]
@anseki  check this , i have added on stackblitz :  https://stackblitz.com/edit/angular-hrfx8a?file=src%2Fapp%2Fapp.component.ts

**Comment by anseki** [comment]
I tried your example on stackblitz.com, but that didn't work.
Could you customize this example to show the issue?
https://jsfiddle.net/qp45vd2k/

**Comment by SalkiDixit** [comment]
I tried on fiddle...not working there.
![aaa](https://user-images.githubusercontent.com/51451253/72661507-ee42fd00-3a00-11ea-97c4-1f7bf52d1666.png)

**Comment by SalkiDixit** [comment]
check this...its going out from my div

**Comment by anseki** [comment]
Could you tell me the URL that should be checked?

**Comment by SalkiDixit** [comment]
https://stackblitz.com/edit/angular-hrfx8a?file=src%2Fapp%2Fapp.component.ts here

**Comment by anseki** [comment]
Is this what you want to do?
https://jsfiddle.net/9Lt7yeuh/

**Comment by SalkiDixit** [comment]
not with iframe.

**Comment by anseki** [comment]
Is this what you want to do?
https://jsfiddle.net/op2gnk0t/

**Comment by SalkiDixit** [comment]
This example I already checked and tried.. this is not working with my code...as working here...
we need to wrap the lines in that "getBoundingClientRect" and need to do document.querySelector('.leader-line:last-of-type'), for every line...
I did..but this is not happening with my code...i have (n) elements and connections in between them so I am creating elements one by one with (x, y cords) and once this is done than I am making line based on conncetions one by one. not working... it is poping out of the div. i checked and tried what you shown there....nothing worked.

**Comment by SalkiDixit** [comment]
what exactly are we supposed to do to stop lines to pop out of div? I can see they are svg. Would help me with the chronology...how are you wrapping the svg inside the div.

**Comment by SalkiDixit** [comment]
https://jsfiddle.net/op2gnk0t/ check this..i have rearrange the connections...it stop working

**Comment by anseki** [comment]
Sorry, my English is poor.
What did you rearrange? Can I try that?
Also, Is not the example what you want to do?
Or, the example is what you want to do but it didn't work in your code.

**Comment by SalkiDixit** [comment]
var elmWrapper = document.getElementById('wrapper'),
  rectWrapper = elmWrapper.getBoundingClientRect(),
	 line1 = new LeaderLine(document.getElementById('terminal-1'),
    document.getElementById('terminal-2')),
  elmLine1 = document.querySelector('.leader-line:last-of-type'),
  line2 = new LeaderLine(document.getElementById('terminal-3'), line1.end),
  elmLine2 = document.querySelector('.leader-line:last-of-type');

above code : this was your js code.

After I rearrange
var elmWrapper = document.getElementById('wrapper'),
  rectWrapper = elmWrapper.getBoundingClientRect(),

  line2 = new LeaderLine(document.getElementById('terminal-3'), line1.end),
  elmLine2 = document.querySelector('.leader-line:last-of-type'),
    line1 = new LeaderLine(document.getElementById('terminal-1'),
    document.getElementById('terminal-2')),
  elmLine1 = document.querySelector('.leader-line:last-of-type');

it stopped working

please check once.

**Comment by anseki** [comment]
Could you show me the rearranged code in JSFiddle?

**Comment by SalkiDixit** [comment]
https://jsfiddle.net/965oy3js/ see this

**Comment by anseki** [comment]
See console (Push F12 key), and you can see a bug in your code:
```
TypeError: line1 is undefined
```

**Comment by anseki** [comment]
See this:
https://jsfiddle.net/ztfr4woq/

**Comment by SalkiDixit** [comment]
please check this.
https://jsfiddle.net/y56w3z0k/

**Comment by anseki** [comment]
Ok, I looked at that.
So, what is that?

**Comment by anseki** [comment]
Do you mean that you don't want to use the wrapper?

**Comment by SalkiDixit** [comment]
I want to use the wrapper no worries, but my objective is " I have a div with some width and height and position relative and I have elements with x, y cords and position absolute and connection between them". Elements are created dynamically and after that i am making line by giving x, y of start and end elements.
so it shouldn't go out of div, 
since elements are absolute and parent div is relative, elements wont go out but connections going out.
so I modified the fiddle as per my requirement, because elements count is not fixed so their connections.
how to keep connection lines inside my parent div like my elements are lying inside?

**Comment by anseki** [comment]
Try this:
https://jsfiddle.net/q4fsvj0c/

**Comment by SalkiDixit** [comment]
@anseki  Check this.
https://jsfiddle.net/a8n9s6vh/

**Comment by SalkiDixit** [comment]
first line is not showing but last is.

**Comment by anseki** [comment]
Ok, I looked at that.
So, what is that?
Do you mean that the example that I showed is not what you want to do?
Please explain why you changed that.

**Comment by SalkiDixit** [comment]
So how is it rendering? first any 2 elements than their connection,than next 2 elements and their connection?
What i did is... I created elements first and than based on elements list I made connections later, so only last line is visible others aren't...why is it?
Can't I do this way?

**Comment by anseki** [comment]
Do you mean that you want to use two loops?

**Comment by anseki** [comment]
I don't know why you want to use two loops, anyways I fixed your code.
https://jsfiddle.net/bhgspvL4/

**Comment by SalkiDixit** [comment]
Alright.. so means we need 'elmWrapper.appendChild(document.querySelector('body>.leader-line:last-of-type'));' after making line, that is a wrapper with 0 width, 0 height, position relative.
Cool.
Thanks a lot 👍 .

**Comment by anseki** [comment]
Uhmm... Sorry, I couldn't understand your words.
Anyways, the issue was solved? Then could you close this issue?

**Comment by anseki** [comment]
BTW, I suggest reading the example code again:
https://jsfiddle.net/op2gnk0t/
Then you should find which element should be added to the wrapper, and understand why.

**Comment by SalkiDixit** [comment]
Alright, I ll check this out, meanwhile 
Thank you,

**Comment by anseki** [comment]
:smile:

**Comment by jacky-cmd** [comment]
@SalkiDixit I am facing same issue while implementing leader lines in angular. Lines are going out of scroll div. How did you implemented this in angular. Could you please help me out?
